### ISSUE TITLE
Inspectieput riolering: vierkant symbool ipv ovaal

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#1]
Wij willen u vragen om in de symbolenbestanden een symbool toe te voegen voor de inspectieputranden van de riolering.
In Nederland zijn alle putranden voor inspectieputten in de riolering vierkant of rond met afmetingen van minimaal 80x80cm (zgn. ‘man-toegankelijk’).
Bij de conversie van de BGT naar AutoCad  wordt nu een ovaal symbool gebruikt, dat normaal gesproken wordt gebruikt voor brandkranen of afsluiters van de waterleiding.
Zo’n (gietijzeren) controledeksel is veel kleiner dan een inspectieput van de riolering (ca. 30x15 cm ovaal).
Zie onderstaande foto:

   

U zult begrijpen, dat bij de conversie van de BGT een ovaal symbool de gebruikers van de BGT op het verkeerde been gaat zetten.
Mag ik u vragen om voor riolering een vierkant symbool te blijven gebruiken, zoals voorheen in de riolering en wegenbouw gebruikelijk was?
En waar nodig de ovale symbolen te gebruiken voor de controleputjes/brandkranen van de waterleidingmaatschappijen?

**Comment by ElisabethKloren** [comment]
![inspectieputriool2](https://github.com/bimloket/NLCS/assets/48585720/0de87287-ae21-4da9-8855-6b395cb52947)
![inspectieputriool](https://github.com/bimloket/NLCS/assets/48585720/3dda12d3-bb8f-499e-8e20-81d86e4f48a1)

**Comment by MvanderHulst** [comment]
Ik kan hier symbolen voor aanleveren. Hoofdstuk RI is te summier en heb ik zelf aanvullingen voor gedaan.

**Comment by ElisabethKloren** [comment]
@MvanderHulst fijn dat je het symbool kan aanleveren; @NielsNederpel wordt het onderscheid tussen de ontroleputjes/brandkranen van de waterleidingmaatschappijen en de vierkante inspectieputranden ook gemaakt qua lagen?

**Comment by MvanderHulst** [comment]
Dat onderscheid wordt gemaakt, is verschil tussen hoofdgroep KL en RI.
Hoofdgroep RI bevat nu alleen de ondergronde onderdelen. alle putdeksels zijn daar helemaal verdwenen.
RI is op GWSW afgestemd, wat een 'inspectieput' vanuit beheer als 1 ding ziet. Engineering zit dit echter als 2 onderdelen. de daadwerkelijke put aangevuld met een putdeksel met putrand. Deze kan weer rond en vierkant zijn... ik heb een voorstel.

**Comment by SanderNijhof** [comment]
Het betreft hier symbolen uit de bibliotheek SIE (InrichtingsElementen) en dat zijn vooral leuke figuurtjes en labels: een cirkel, vierkant of ovaal met 2-3 letters erin. Prima voor een stadskaart, maar minder geschikt voor technische tekeningen. Misschien moeten we hier iets mee... In de zin van dat we ons met de NLCS richten op technische tekeningen en niet op kaarten zoals stadsplattegronden. Alternatieve weergaven zijn te regelen via thema's/externe tooling(?)

**Comment by MvanderHulst** [comment]
Voorstel staat in de mail.

**Comment by ElisabethKloren** [comment]
@MvanderHulst Waarvoor dank, het bestand staat hier: https://github.com/bimloket/NLCS/blob/main/ontwikkeling/riolering/SRI-AANVULLINGEN.dwg

**Comment by SanderNijhof** [comment]
> @MvanderHulst Waarvoor dank, het bestand staat hier: https://github.com/bimloket/NLCS/blob/main/ontwikkeling/riolering/SRI-AANVULLINGEN.dwg

Kun je hier ook een pdf versie van publiceren? Omdat ik niet zeker weet of de dwg in Microstation er hetzelfde uitziet.

**Comment by MvanderHulst** [comment]
[SRI-AANVULLINGEN.PDF](https://github.com/bimloket/NLCS/files/12616977/SRI-AANVULLINGEN.PDF)

PDF als bijlage.

**Comment by KristiaanH** [comment]
Voorkeur heeft het wel om voor algemeen symbool een afmeting te zoeken die overeenkomt met de meest gebruikelijke externe afmeting.
In feite zijn er drie gebruikelijke maten voor vierkante putafdekkingen: 
dagmaat 520 (extern 640x640)
dagmaat 600 (extern 745x745)
dagmaat 700 (extern 906x906)

Als de keuze voor een putdeksel afm 800x800 krijgt als algemeen symbool is het onderscheid met de onderliggende put (ook standaard weergegeven als 800x800) wel minder duidelijk.

**Comment by SanderNijhof** [comment]
Ik geef er wel de voorkeur aan dat het symbool voor een put(deksel) duidelijk groter is dat het symbool voor bijv. een kolk.
Vraag: moeten put en putdeksel apart in de tekening opgenomen worden als 2 symbolen die op elkaar liggen? Waarom?

**Comment by MvanderHulst** [comment]
Standaard toepassing is:
- één symbool die inspectieput met putdeksel beschrijft
- een apart symbool voor de putdeksel, onderliggende inspectieput hoeft niet zichtbaar te zijn.

**Comment by KristiaanH** [comment]
dat verschil is wenselijk om twee redenen:
Een put(onderbouw) wordt vaak al tijdens bouwrijpmaken aangebracht, en wordt dan meestal voorzien van een dekplaat (bij bouwweg puin) of van een putrand (als deze tijdelijk bestraat wordt). Het kan regelmatig gebeuren dat de put op sommige plaatsen met putdeksel en andere locaties zonder putdeksel weergegeven kan worden.
Omgekeerd kan het voorkomen dat bij een rioolvernieuwing ergens een volledig nieuwe put geplaatst wordt en elders de putrand opnieuw gesteld / vervangen.

daarnaast valt de putrand eigenlijk onder de weginrichting, deze moet passen langs bijvoorbeeld een molgoot of trottoirband.
Omgekeerd zijn je putten vaak fors groter. Het symbool voor put als XREF gebruiken voor je weginrichting kan dan betekenen dat je put veel te groot als putdeksel wordt gerepresenteerd.

Put en putrand als twee verschillende objecten behandelen komt m.i. het meest dicht bij de ontwerp- en uitvoeringspraktijk.

**Comment by MvanderHulst** [comment]
Put en putrand wordt bij ons inderdaad zo behandeld.
In bovenstaande aanvullingen heb ik dan ook de 'inspectieput' en 'deksel' als aanvullende objecten gedefinieerd.
Ze moeten beide in de bieb komen om e.e.a. werkbaar te krijgen.
Hoofdgroep RI is nu volledig gemaakt op basis van GWSW en dus een beheer standaard, helaas ontbreken hierdoor veel elementen die voor engineering nodig zijn.

**Comment by SanderNijhof** [comment]
> [SRI-AANVULLINGEN.PDF](https://github.com/bimloket/NLCS/files/12616977/SRI-AANVULLINGEN.PDF)
> 
> PDF als bijlage.

@MvanderHulst Ik had hier nog niet op gereageerd maar de symbolen in jouw voorstel doen het prima in Microstation.

**Comment by MvanderHulst** [comment]
Putranden komen op dit moment niet voor in de NLCS biblitoheek.
Hiervoor dienen aanvullende OBJECTEN aangemaakt te worden welke zijn voorzien van diverse symbolen.
Voorstel is om de volgende aanvullingen te doen in de objecten:
RI-DRAINAGE_RIOOLPUT_DEKSEL-S
RI-DWA_RIOOLPUT_DEKSEL-S
RI-GWA_RIOOLPUT_DEKSEL-S
RI-HWA_RIOOLPUT_DEKSEL-S
RI-ITR_RIOOLPUT_DEKSEL-S
RI-OVERIG_RIOOLPUT_DEKSEL-S

En de volgende symbolen toe te voegen:
SRI-PUT_DEKSEL-SO
SRI-PUT_DEKSEL_01-SO
SRI-PUT_DEKSEL_OVERIG-SO
SRI-PUT_DEKSEL_OVERIG_01-SO
SRI-PUT_DEKSEL_DWA-SO
SRI-PUT_DEKSEL_DWA_01-SO
SRI-PUT_DEKSEL_HWA-SO
SRI-PUT_DEKSEL_HWA_01-SO
SRI-PUT_DEKSEL_GWA-SO
SRI-PUT_DEKSEL_GWA_01-SO
SRI-PUT_DEKSEL_ITR-SO
SRI-PUT_DEKSEL_ITR_01-SO
SRI-PUT_DEKSEL_OVERIG-SO
SRI-PUT_DEKSEL_OVERIG_01-SO

V-SRI-PUT_DEKSEL-SO
V-SRI-PUT_DEKSEL_01-SO
V-SRI-PUT_DEKSEL_OVERIG-SO
V-SRI-PUT_DEKSEL_OVERIG_01-SO
V-SRI-PUT_DEKSEL_DWA-SO
V-SRI-PUT_DEKSEL_DWA_01-SO
V-SRI-PUT_DEKSEL_HWA-SO
V-SRI-PUT_DEKSEL_HWA_01-SO
V-SRI-PUT_DEKSEL_GWA-SO
V-SRI-PUT_DEKSEL_GWA_01-SO
V-SRI-PUT_DEKSEL_ITR-SO
V-SRI-PUT_DEKSEL_ITR_01-SO
V-SRI-PUT_DEKSEL_OVERIG-SO
V-SRI-PUT_DEKSEL_OVERIG_01-SO

Hierbij zijn de ‘standaard’ deksels een reguliere putrand met deksel en de _01 variant een ronde putrand met deksel. Hiermee zijn alle scenario’s weer uit te werken.

Aanvullend met de BGT-mapping nagelopen worden om te verwijzen naar de juiste ID.
![image](https://github.com/nl-digigo/NLCS/assets/144665595/c699881b-dac3-4139-b198-ed3859a3f57e)

**Comment by SanderNijhof** [comment]
Is het echt wenselijk/noodzakelijk dat er voor elk stelseltype een apart putsymbool is?

**Comment by ElisabethKloren** [comment]
> Is het echt wenselijk/noodzakelijk dat er voor elk stelseltype een apart putsymbool is?

voor iemand die een pdf in handen heeft is het wel handig om dit te kunnen zien

**Comment by MvanderHulst** [comment]
> Is het echt wenselijk/noodzakelijk dat er voor elk stelseltype een apart putsymbool is?

Absoluut, onmisbaar voor een duidelijke tekening.
Maar daarom ook de 'algemene' symbolen.
Kan je alle combinaties maken die je wilt, iedereen weer blij. :-)

**Comment by ElisabethDeVries** [comment]
[[Release note]] De symbolen voor putdeksels van rioleringen zijn aangevuld: er zijn nu putdeksels met een reguliere putrand en de _01 variant een ronde putrand met deksel. In de hoofdgroep KL zijn ovale symbolen beschikbaar voor de controleputjes/brandkranen van de waterleidingmaatschappijen.
