### ISSUE TITLE
#1683  Het object GW-DIJK_TALUD komt 2 keer voor. 

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#10]
Het object GW-DIJK_TALUD komt 2 keer voor. Eén keer op nr. 4087 en één keer op 4097. Welke is de juiste?

**Comment by ElisabethKloren** [comment]
Reactie expertcommissie: opmerking is terecht. Object 4097 laten vervallen. E.e.a. geldt ook voor GW-DIJK_KNIKLIJN object 4098

**Comment by ElisabethKloren** [comment]
op vervallen zetten in database, invloed op mapping?

**Comment by ElisabethDeVries** [comment]
[[Release note]] Objecten GW-DIJK_TALUD en GW-DIJK_KNIKLIJN kwamen dubbel voor, dubbeling is verwijderd.

**Comment by ElisabethDeVries** [comment]
REOPEN VOOR HERBEOORDELING 5.2
