### ISSUE TITLE
#1704 KG-GRONDVERWERVING_OPSTALLEN

### ISSUE THREAD

**Issue by NielsNederpel** [nl-digigo/NLCS#103]
KG-GRONDVERWERVING_OPSTALLEN, object is onlogisch op deze positie. Betreft een object uit hoofdgroep OG, of zou als onderdeel van KG in het object KADASTRAAL thuishoren.

**Comment by ElisabethDeVries** [comment]
re-open voor 6.0

**Comment by ElisabethDeVries** [comment]
[[release note]] In hoofdgroep Kadastrale Grenzen is het object KG-GRONDVERWERVING_OPSTALLEN vervallen, een nieuw object KADASTRAAL_OPSTAL is opgenomen. Dit is een logischere indeling.
