### ISSUE TITLE
#1705 KG-BENOGRENS en KG-ONDERHOUDSGRENS

### ISSUE THREAD

**Issue by NielsNederpel** [nl-digigo/NLCS#104]
KG-BENOGRENS en KG-ONDERHOUDSGRENS, een BENO grens is een onderhoudsgrens, waarom staat ONDERHOUSGRENS er nog als los object bij? Alle subobjecten zijn identiek.

**Comment by MvanderHulst** [comment]
BEHEERGRENS is aanwezig en ONDERHOUDSGRENS
BENO = BeheerENOnderhoudsgrens.

Kan inividueel voorkomen, maar ook als combinatie.

Is dat de oorsprong? Dan behouden.

**Comment by MvanderHulst** [comment]
Geen actie, combinaties kunnen voorkomen.

**Comment by ElisabethKloren** [comment]
Check, de drie grenzen blijven in de database staan
