### ISSUE TITLE
#1706 Naamgeving inritblokken

### ISSUE THREAD

**Issue by NielsNederpel** [nl-digigo/NLCS#105]
Naamgeving van inritbanden is onjuist.
Standaard format is diepte, hoogte, breedte.
Huidige opgenomen format is een andere volgorde aangehouden.

**Comment by MvanderHulst** [comment]
Algemeen:
Er bestaat:
VH-KANTOPSLUITING_ELEMENT_INRIT_PERRONBAND
VH-KANTOPSLUITING_ELEMENT_INRITBAND
VH-KANTOPSLUITING_INRITBAND

Zeer inconsequent.
Opties:
- inritbanden onderbrengen onder de bijbehorende kantopsluitingen
- het OBJECT INRITBAND vullen.

Het OBJECT ELEMENT is zeer onlogisch en niet toepasbaar. alle varianten zijn altijd onderdeel van een hogere noemene.
Het OBJECT ELEMENT kan niet als OBJECT bestaan, maar zal altijd minimaal een SUBOBJECT moeten zijn.

Voorstel inritbanden (volgens huidige bibliotheek)
[inritbanden.xlsx](https://github.com/nl-digigo/NLCS/files/14979681/inritbanden.xlsx)

Hiervoor geldt wel weer...
willen we dit beheren? Of stoppen we bij het beschikbaarstellen van het OBJECT?
