### ISSUE TITLE
#1707 fout in de tag bij het symbool STROOMRICHTING_RECHTS

### ISSUE THREAD

**Issue by NielsNederpel** [nl-digigo/NLCS#106]
Bij InfraCAD zit er een fout in de tag bij het symbool STROOMRICHTING_RECHTS. Tag PUTNR-L wordt twee keer gebruikt voor zowel PUTNUMMER LINKS als PUTNUMMER RECHTS.
Echter is dit een symbool uit de standaar NLCS-bibliotheek en wordt de standaard bibliotheek beheerd door digiGO BIM Loket.
Kunnen jullie hier iets mee?

**Comment by MvanderHulst** [comment]
Symbool gecorrigeerd:
![image](https://github.com/nl-digigo/NLCS/assets/144665595/4ff3e0ab-b661-4f15-8e2e-66e4260276d7)

**Comment by ElisabethDeVries** [comment]
[[Release note]] Symbool SRI-STROOMRICHTING_RECHTS is aangepast, deze gebruikte de verkeerde tag putnummer-links.
