### ISSUE TITLE
#1708 Tekstgrootte chemische stoffen

### ISSUE THREAD

**Issue by NielsNederpel** [nl-digigo/NLCS#107]
4.6.3 aanduiding chemische stoffen zoals PVC, met een lettergrootte van 3.5 mm?
Buiten het feit dat deze specifieke regel volgens mij overbodig is en valt onder 'bijschriften', is 3.5 aan de grote kant, zou dit niet 2.5 moeten zijn?

Aanvulling EK: dit staat hier in de documentatie: https://nl-digigo.github.io/NLCS/requirementscadmodels/#aanbevelingen-voor-tekstgebruik-en-hoogte

**Comment by ElisabethKloren** [comment]
sander zegt: Controleren in FB, voorstel voor aanpassing maken en bespreken in EC

**Comment by ElisabethKloren** [comment]
Vraag aan EC:
- Op welke soort tekeningen hebben we aanduiding van stoffen?
- Is het op deze tekeningen van belang deze stoffen zo groot te maken? Dan behouden we huidige grootte
- Zo niet, dan verwijderen we deze specifieke aanduiding

**Comment by MvanderHulst** [comment]
@ElisabethKloren zoals eerder besproken:
e.e.a. kan sterk vereenvoudigd worden. diverse grotere teksten onnodig, ongewenst en wordt niet gedaan.
![image](https://github.com/nl-digigo/NLCS/assets/144665595/15840f93-44a7-44b6-999d-ac2ea77fe31e)

**Comment by ElisabethKloren** [comment]
Heb er nu dit van gemaakt:

<table class="tabel3">
  <tr>
    <th>Aard van de tekst</th>
    <th>Hoogte (mm)</th>
    <th>Hoofdletters of kleine letters</th>
    <th>Opmerking</th>
    <th>Voorbeeld (niet op schaal)</th>
  </tr>
  <tr>
    <td>Onderschriften en titels</td>
    <td>5.0</td>
    <td>Hoofd- of kleine letters</td>
    <td>Onderstreept</td>
    <td><head>
    <style>
        /* CSS-stijl om tekst te onderstrepen en een hoogte van 5 in te stellen */
        .onderstreept-tekst {
            text-decoration: underline; /* Hiermee wordt de tekst onderstreept */
            line-height: 5; /* Hiermee wordt de hoogte van de tekst ingesteld op 5 (kan ook in pixels of andere eenheden zijn) */
        }
    </style>
</head>
<body>
    
    <p class="onderstreept-tekst">DOORSNEDE A-A</p>
</body></td>
  </tr>
  <tr>
    <td>Schaalaanduiding</td>
    <td>2.5</td>
    <td>Hoofd- of kleine letters</td>
    <td>Direct onder of naast de modeltitel</td>
    <td><head>
    <style>
        /* CSS-stijl om tekst te onderstrepen en een hoogte van 5 in te stellen */
        .schaalaanduiding {
            line-height: 2,5; /* Hiermee wordt de hoogte van de tekst ingesteld op 5 (kan ook in pixels of andere eenheden zijn) */
        }
    </style>
</head>
<body>
    
    <p class="schaalaanduiding">SCHAAL 1:100</p>
</body></td>
  </tr>
  <tr>
    <td>Geografische aanduidingen (plaatsnamen, wijknamen, poldernamen, riviernamen etc.)</td>
    <td>Vrij te bepalen op basis van leesbaarheid tekening</td>
    <td>Kleine letters, beginnend met een hoofdletter</td>
    <td></td>
    <td>Nootdorp</td>
  </tr>
  <tr>
    <td>N.A.P.-aanduiding</td>
    <td>Vrij te bepalen op basis van leesbaarheid tekening</td>
    <td>Hoofdletters</td>
    <td></td>
    <td><head>
    <style>
        /* CSS-stijl om tekst te onderstrepen en een hoogte van 5 in te stellen */
        .drieeneenhalf {
            line-height: 3,5; /* Hiermee wordt de hoogte van de tekst ingesteld op 5 (kan ook in pixels of andere eenheden zijn) */
        }
    </style>
</head>
<body>
    
    <p class="schaalaanduiding">N.A.P.</p>
</body></td>
  </tr>
  <tr>
    <td>Aanduiding chemische stoffen</td>
    <td>Vrij te bepalen op basis van leesbaarheid tekening</td>
    <td>Hoofdletters zonder puntjes</td>
    <td></td>
    <td> <p class="drieeneenhalf">PVC</p></td>
  </tr>
  <tr>
    <td>Asnamen</td>
    <td>2.5</td>
    <td>Hoofdletters</td>
    <td></td>
    <td> <p class="schaalaanduiding">ALM A6</p></td>
  </tr>
  <tr>
    <td>rd-coördinaten</td>
    <td>2.5</td>
    <td>Cijfers</td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Bijschriften t.a.v. nieuwe situatie</td>
    <td>2.5</td>
    <td>Kleine letters, eventueel beginnend met een hoofdletter</td>
    <td></td>
    <td><p class="schaalaanduiding">Asfaltverharding</p></td>
  </tr>
  <tr>
    <td>Bijschriften t.a.v. bestaande situatie</td>
    <td>1.8</td>
    <td>Kleine letters, cursief</td>
    <td></td>
    <td><head>
    <style>
        /* CSS-stijl om tekst te onderstrepen en een hoogte van 5 in te stellen */
        .eenpuntacht {
            line-height: 1,8; /* Hiermee wordt de hoogte van de tekst ingesteld op 5 (kan ook in pixels of andere eenheden zijn) */
        }
    </style>
</head>
<body>
    
    <p class="eenpuntacht">Bestaande band</p>
</body></td>
  </tr>
</table>

**Comment by ElisabethKloren** [comment]
beetje dûh niveau allemaal, wat mij betreft zou die hele paragraaf ook weg kunnen
