### ISSUE TITLE
#1709 Hoogtemaatvoering cursief of niet.

### ISSUE THREAD

**Issue by NielsNederpel** [nl-digigo/NLCS#108]
4.5.8 Hoogtematen
a. Hoogtematen boven een referentiepeil moeten worden aangeven met een plusteken (+) en beneden een referentiepeil met een minteken (-) voor de getalswaarde. Hoogtematen moeten worden aangeven in meters of in millimeters ten opzichte van N.A.P. of ten opzichte van een afgesproken peil. De vorm van de hoogteaanduiding is vrij, mits deze vorm consequent wordt gebruikt. In de onderstaande figuur zijn verschillende voorbeelden gegeven. De verwijzingslijn met tekst wordt getekend d.m.v. een lijn met een lengte afhankelijk van de bijgeplaatste tekst met de tekst boven de verwijzingslijn. Het lettertype voor bemating heeft een (geplotte) teksthoogte van 1,8 mm. Bestaande maten moeten in cursief lettertype worden weergegeven, nieuwe maten moeten in recht lettertype worden weergegeven.

Op de letter gelezen: wordt hier alleen een dwarsprofiel bedoeld of ook het bovenaanzicht? Geldt dit enkel voor hoogte maatvoering of ook voor BOB aanduidingen?

Veel 'hoogte' objecten binnen de NLCS zitten verwerkt in blocks. deze hanteren allemaal de standaard recht op staande tekststijlen. Wanneer hier verschil in zit, zouden voor alle hoogte symbolen een variant moeten zijn tussen bestaand en nieuw, waarin de cursief factor is verwerkt in het attribute....

Kan dit artikel toegelicht en beter omschreven worden? Is m.i. niet duidelijk.

EK: het betreft dit artikel: https://nl-digigo.github.io/NLCS/requirementscadmodels/#hoogtematen

**Comment by ElisabethKloren** [comment]
sander zegt: Controleren in FB, voorstel voor aanpassing maken en bespreken in EC

**Comment by ElisabethKloren** [comment]
Vraag aan de EC: 
Geldt de FB altijd voor alle soorten tekeningen, bovenaanzichten, dwars- en zijprofielen?
Geldt dat hier dan ook? 
Geldt dit enkel voor hoogte maatvoering of ook voor BOB (EK: wat is dat?) aanduidingen?

**Comment by SanderNijhof** [comment]
> * toevoeging, gezien 'bestaand' onder nieuw altijd grijs wordt getoond.

Dit is een afwijkende keuze, niet standaard. Standaard wordt 'Bestaand' afgedrukt in zwart in een dunnere lijnstijl. Als is bepaald dat de letterhoogte voor nieuwe en bestaande hoogtematen beide 1.8mm is dan is het onderscheid middels cursief duidelijk. 

> Alle teksten standaard ‘normaal’ weergeven. Onderscheid tussen ‘cursief’ en ‘normaal’ bij regulier tekenwerk niet relevant.

Juist zeer relevant!! Tekst i.r.t. bestaande objecten moet cursief zijn. Elke tekening die hierin afwijkt voldoet niet aan de NLCS-standaard.

> Bijvoorbeeld een bestaande rioolstreng. Moet alle bijbehorende informatie dan ook cursief, of alleen de bestaande bobs?

Kristal helder: Alle tekst i.r.t. bestaande objecten cursief. Dit was al zo toen er nog met de hand getekend werd. Zal vast ergens in een NEN norm staan, die we niet tot onze beschikking hebben :-/

**Comment by MvanderHulst** [comment]
@SanderNijhof 
Punt 1 ben ik neutraal in, afhankelijk van het tekenwerk kan dit inzicht geven.
Punt 2 neem je ene stelling in dat het op dit moment inderdaad MOET, maar we hebben het nu de doorontwikkeling en over de vraag of dat echt zo MOET zijn, of een optie KAN zijn.
punt 3. idem, ik praat niet over het verleden of de huidige situatie, maar of die situatie nog houdbaar is en niet gedateerd.

**Comment by MvanderHulst** [comment]
zie ook issue #53

**Comment by NielsNederpel** [comment]
ai...als je ook cursief wilt doorvoeren in alle symbolen met tekst komen er heel veel symbolen bij...bijna alle verhardingssymbolen hebben tekst (attributen) namelijk.
op dit moment hebben we namelijk veel symbolen die voor alle statussen (behalve V ivm het kruis erdoor) van toepassing zijn...
als we voor status B afwijkende (cursieve) teksten willen in de symbolen worden dit allemaal nieuwe symbolen voor status B!

hier zou ik dus, net als we doen voor de "nieuwe teksten moeten teksthoogte 2.5 zijn" regel ook een uitzondering maken voor wat betreft de symbolen

**Comment by MvanderHulst** [comment]
@NielsNederpel vandaag dit even kort met Elisabeth en Sander besproken.
De hele omgang met 'teksten' in de FB is totaal niet logisch en consequent.
Hiervoor gaan we een nieuwe issue aanmaken.

Wel waren we het er over eens dat het zeker niet gewenst is om alle symbolen dubbel uit te gaan voeren. daarvoor moet inderdaad een uitzonder komen.
