### ISSUE TITLE
#1682 SKL-Waterpomp terug bij de BGT import,

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#11]
Ook komt in InfraCAD SKL-Waterpomp terug bij de BGT import, welke schijnbaar wel in de data zit, maar niet in de BGT mapping

**Comment by SanderNijhof** [comment]
Dan houdt InfraCAD zich niet aan de NLCS-BGT mapping. Is dit dan niet een issue voor InfraCAD en niet voor de NLCS?

**Comment by ElisabethKloren** [comment]
check of er een object uit de BGT ontbreekt in de mapping

**Comment by MvanderHulst** [comment]
Komt inderdaad bekend voor als import van de BGT, staat niet in de mapping.
Voorstel symbool opgenomen in issue #16

**Comment by ElisabethDeVries** [comment]
Checken bij opstellen nieuwe BGT-mapping dat SIE-WATERPOMP gemapt wordt; tevens checken op mapping naar  geleideconstructie
