### ISSUE TITLE
Review objectentabel stedelijk spoor: Check op decompositie

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#114]
@NielsNederpel  zegt: •	check goed of de nieuwe subobjecten wel allemaal een bovenliggen bestaand of nieuw object heeft zodat de decompositie goed gaat. aantal heb ik al aangegeven die ontbreken.

Actie Marco & Erwin & Paul

**Comment by ElisabethKloren** [comment]
[Reactie HTM 20230619 - NLCS-OBJECTEN doorgenomen via Teams_opm_NN.xlsx](https://github.com/bimloket/NLCS/files/12534573/Reactie.HTM.20230619.-.NLCS-OBJECTEN.doorgenomen.via.Teams_opm_NN.xlsx)

**Comment by ElisabethKloren** [comment]
Bestand geplaatst op https://github.com/bimloket/NLCS/blob/main/ontwikkeling/stedelijk%20spoor/Reactie%20HTM%2020230619%20-%20NLCS-OBJECTEN%20doorgenomen%20via%20Teams_opm_NN.xlsx

**Comment by HarmdHerripon** [comment]
Besproken 12-12-2023: Aanvulling vanuit Marco en Erwin is gereed en er zijn 3 Excell bestanden naar Paul gestuurd. Paul maakt hier een Optimize-bestand van om daarna te laten testen door Marco&Erwin&Romano&Gerben.
Actie Paul -> na samenvoegen en controle excelllijst, delen en laten vaststellen door Expertcommissie. -> Bentley
Actie Romano en Gerbert -> Autodesk, CADAC en Arkance Systems.

**Comment by ehensing** [comment]
22-01-2024: navraag gedaan er was is niet helemaal goed gedaan met het maken van 1 tabel, actie loopt nog.

**Comment by HarmdHerripon** [comment]
Besproken 29-01-2024: actie loopt nog (Paul/Erwin/Marco)

**Comment by HarmdHerripon** [comment]
Besproken 11-3-2024: Controle op de decompositie heeft plaatsgevonden door Corné en Niels.
De lijsten nu samenvoegen. Paul is hier nog mee bezig. Eind deze maand gereed en dan check door werkgroepleden.
