### ISSUE TITLE
Stedelijk Spoor, lagen met alleen tekst

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#115]
Toetsen uitgangspunt bij expertcommissie: er zijn lagen met alleen tekst. Beschrijven waarom, toets of dit voldoet aan de uitgangspunten van NLCS

Actie: Marco & Erwin & Paul

@NielsNederpel  zegt: •	er zijn veel lagen als alleen tekst (-T) aangegeven in de database geven we dit niet aan en moeten dit dus wel objectenlagen worden (-G). Begrijp ik het goed dat je deze nooit zult tekenen als zijnde lijn/vlak/symbool? kunnen de teksten dan niet op een hoger of algemeen object gemaakt worden? Moet deze een herkenbare eigenlaag hebben?

**Comment by HarmdHerripon** [comment]
Besproken 12-12-2023: Erwin bespreekt dit met Marco. Normaal gesproken geen teksten in geometrielaag, Geen symbolen. Teksten apart in laag_label.

**Comment by ehensing** [comment]
22-01-2024: teksten komen op lagen die eindigen op: -T te staan

**Comment by HarmdHerripon** [comment]
Besproken 29-01-2024: Akkoord & issue afsluiten
