### ISSUE TITLE
We nemen geen status op in de laagnaam bij Stedelijk spoor, ook niet als het altijd meetgegevens zijn

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#119]
Toets nodig door expertcommissie op uitgangspunt We nemen geen status op in de laagnaam bij Stedelijk spoor, ook niet als het altijd meetgegevens zijn

Actie Marco & Erwin & Paul

Uitgangspunt beschrijven, en toetsen of dit past binnen de uitgangspunten van NLCS

**Comment by HarmdHerripon** [comment]
Besproken 12-12-2023: Akkoord, de lagen kunnen alle statussen krijgen.

**Comment by ElisabethDeVries** [comment]
[[Release note]] De werkgroep stedelijk spoor heeft NLCS-objecten waren aangeboden waarin statussen verwerkt waren, terwijl in de NLCS standaard het veld status gebruikt wordt. Herkomst was aansluiting op een bedrijfseigen kaart waarin alignement van sporen en meetgegevens in de gebruiksfase werden bijgehouden. Dit is een specifieke beheerwens, waarvan de statussen niet aansluiten op die van de NLCS. Besluit: er worden geen beheerobjecten met fasen opgenomen in NLCS stedelijk spoor, tram.
