### ISSUE TITLE
Uitbreiden NLCS met Stedelijk Spoor: tabellen vaststellen in werkgroep

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#120]
De werkgroep Stedelijk spoor gaat de tabellen vaststellen voor Stedelijk Spoor, om in te dienen bij de Expertcommissie. Doel is een concept-versie vaststellen voor het uitvoeren van eerste tests in software. 
Baan, bovenbouw, beveiliging, bovenleiding

Actiehouders Marco & Erwin & Paul

**Comment by ElisabethKloren** [comment]
80% versie Stedelijk Spoor: https://github.com/bimloket/NLCS/blob/main/ontwikkeling/stedelijk%20spoor/Reactie%20HTM%2020230619%20-%20NLCS-OBJECTEN%20doorgenomen%20via%20Teams_opm_NN.xlsx

**Comment by HarmdHerripon** [comment]
@ehensing @PHaffmans **test** Beste heren, hoe ver zijn jullie met dit issue?

**Comment by HarmdHerripon** [comment]
Besproken 12-12-2023: Eerst beproeven (zie #114), daarna vaststellen in Expertcommissie

**Comment by HarmdHerripon** [comment]
Besproken 29-01-2024: Eind feb 2024 gereed (Erwin en Marco)

**Comment by HarmdHerripon** [comment]
Besproken 11-3-2024: Dit wordt eind maart/begin april.

**Comment by HarmdHerripon** [comment]
Besproken 15-4-2024: De lijst wordt 24-4 besproken, samen met de de blocks/DWG's

**Comment by ElisabethKloren** [comment]
De laatste versie kan op dit moment worden gereviewed in #190, daarom sluit ik deze issue af
