### ISSUE TITLE
Concept publicatie & documentatie Stedelijk Spoor

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#121]
Na vaststellen tabellen en symbolen Stedelijk Spoor in Expertcommissie de Concept publicatie (in database) & documentatie Stedelijk Spoor klaarzetten voor test door softwareleveranciers

**Comment by HarmdHerripon** [comment]
Besproken 12-12-2023: Actie hoort bij Paul

**Comment by HarmdHerripon** [comment]
Besproken 29-01-2024: Status, Paul stemt lijst af met Erwin en Marco (symbolen). De lijst met objecten is goed nog koppelen met symboliek (oa kleur, lijndikte, etc).
actie 1: lagenlijst met symboliek afmaken (Paul-Marco/Erwin) : gereed eind feb.
actie 2: vaststellen in werkgroep : gereed eind feb.
actie 3: lijst gereed dan aanleveren aan Expertcommissie tbv aanleveren aan softwareleveranciers (Paul) : 
actie 4: verwerken feedback leveranciers (Paul-Marco/Erwin+expertcom)
actie 5: vaststellen in expertcommissie en positief advies aan beheercommissie
actie 6: Release

**Comment by HarmdHerripon** [comment]
Besproken 15-4-2024: na 24-4 wordt lijst toegevoegd (actie Paul)

**Comment by ElisabethKloren** [comment]
de tabellen en symbolen zijn opgenomen in release 5.1 van de standaard
