### ISSUE TITLE
Afstemmen beschrijving SD in Formele beschrijving NLCS

### ISSUE THREAD

**Issue by HenkArkance** [nl-digigo/NLCS#122]
Bij 3.5.6 en 3.5.9 wijken de beschrijvingen van SD symbolen af:

3.5.6 f.
Symbolen (S en SD) hebben in de regel een vaste lijndikte, kleuren volgens de objectentabellen en een vast lijntype:
 o lijndikte: Status Bestaand 0.18, overige statussen 0.25;

3.5.9 Tabel, bij SD:
o lijndikte: objectentabellen

**Comment by SanderNijhof** [comment]
Wat mij betreft is 3.5.9 juist en 3.5.6 f niet. Blocks/Cellen -S en -SD hebben beide default lijndikte en kleuren en de eigenschappen worden geregeld net als voor alle andere objecten via de laageigenschappen, tenzij...

**Comment by ElisabethKloren** [comment]
sander zegt: Controleren in FB, voorstel voor aanpassing maken en bespreken in EC

**Comment by SanderNijhof** [comment]
Nog even gekeken naar tabel 3.5.9 Daarin zitten meer onduidelijkheden.
Wat betreft SD: tabel 3.5.9 verwijst voor de lijndikte naar de objectentabellen, maar 'SD' komt niet voor de in de objectentabellen, dus is dat wel juist? Beter zou zijn 'als aangegeven bij element S'.
De beschrijving 3.5.6f: Bestaand lijndikte 0.18mm en Nieuw lijndikte 0.25mm is nieuw per NLCS 5.0. Bij element SV staat nog voor alle statussen lijndikte 0.25mm, moet dat dan ook niet gelijk aan element S zijn?
Bij element 'O' wordt in de tabel ook verwezen voor Kleur naar de objectentabellen, maar 'O' komt niet voor in de objectentabellen. Beter zou zijn 'als aangegeven bij element G'.
Bij element 'GV' wordt voor Kleur en Lijndikte verwezen naar de objectentabellen, maar 'GV' komt niet in de objectentabellen voor. Bij Lijntype staat 'CONTINUOUS'. Kan dit in alle 3 de gevallen niet beter zijn 'als aangegeven bij element G'?

**Comment by ElisabethKloren** [comment]
1. SD: Ik volg de uitleg in deze paragraaf: https://nl-digigo.github.io/NLCS/requirementscadmodels/#symbolen en pas de tabel aan met o lijndikte: Status Bestaand 0.18, overige statussen 0.25;
2. Wat betreft SD: tabel 3.5.9 verwijzing voor de lijndikte: objectentabellen als aangegeven bij element S' 
3. Bij element SV komt in deze tabel ook te staan 'objectentabellen als aangegeven bij element S'
4. Bij element 'O' komt 'objectentabellen als aangegeven bij element G'.
5. Bij element 'GV' komt in alle 3 de gevallen te staan 'als aangegeven bij element G'?

**Comment by MvanderHulst** [comment]
FB nalopen op basis van wijzigingen, omgang 'DOORSNEDE' elementen.

**Comment by NielsNederpel** [comment]
> Wat betreft SD: tabel 3.5.9 verwijzing voor de lijndikte: objectentabellen als aangegeven bij element S'
Bij element SV komt in deze tabel ook te staan 'objectentabellen als aangegeven bij element S'

klopt dat?
voor wat betreft de **lijntype** maken we alleen onderscheid in in statussen (B, N, V, T) er wordt voor de verschillende elementen (-G, -S, -A, -T**, -O etc) geen onderscheid gemaakt in de tabellen. als ik dus voor -SD/SV lees "zie objectentabellen bij element S" klopt dat niet. want er is geen lijntype voor element S. of gaat dit in de toekomst wel in de Linkedatabase versie ingevoerd worden? maar is dat dan al voor komende wijziging? voor nu moet in ieder geval de (2) paragrafen met elkaar matchen

**Comment by SanderNijhof** [comment]
> > als aangegeven bij element S'
> 
> klopt dat?

Ik had aangegeven  'als aangegeven bij element S' en daarmee bedoelde ik 'als aangegeven bij element S in de tabel bij 3.5.9' 
De tabel bij 3.5.9 kan in ieder geval nog wat verduidelijking gebruiken.

**Comment by MvanderHulst** [comment]
@ElisabethKloren deze is voor jou

**Comment by ElisabethKloren** [comment]
Check 1: In de objectentabellen in de database staan de volgende zaken:

[status] color
[status] color A
[status] color GD
[status] color GN
[status] color V
[status] linetype
[status] lineweight

Als ik daar aan refereer in de tabel kom ik uit op dit:

<table class="tabel3" title="representatie van ELEMENTEN">
  <thead>
    <tr>
      <th>ELEMENT</th>
      <th>LIJNDIKTE</th>
      <th>KLEUR</th>
      <th>LIJNTYPE</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>G</td>
      <td>objectentabellen: [status] lineweight</td>
      <td>objectentabellen: [status] color</td>
      <td>objectentabellen: [status] linetype</td>
    </tr>
    <tr>
      <td>GN</td>
      <td>één pendikte dunner dan aangegeven in objectentabellen: [status] lineweight</td>
      <td>objectentabellen: [status] color GN</td>
      <td>ZZ-HIDDEN-SO</td>
    </tr>
    <tr>
      <td>GD</td>
      <td>één pendikte dikker dan aangegeven objectentabellen: [status] lineweight<a href="#footnote-3">[3]</a></td>
      <td>objectentabellenobjectentabellen: [status] color GD</td>
      <td>continuous <a href="footnote-4">[4</a>]</td>
    </tr>
    <tr>
      <td>GV</td>
      <td>objectentabellen: [status] lineweight</td>
      <td>objectentabellen: [status] color</td>
      <td>objectentabellen: [status] linetype</td>
    </tr>
    <tr>
      <td>A</td>
      <td>0.18</td>
      <td>objectentabellen: [status] color A</td>
      <td>continuous</td>
    </tr>
    <tr>
      <td>AD</td>
      <td>0.18</td>
      <td>objectentabellen: [status] color A</td>
      <td>continuous</td>
    </tr>
    <tr>
      <td>S</td>
      <td>Status bestaand 0.18, overige statussen 0.25</td>
      <td>objectentabellen: [status] color</td>
      <td>continuous</td>
    </tr>
    <tr>
      <td>SN</td>
      <td>Status bestaand 0.13, overige statussen 0.18</td>
      <td>objectentabellen: [status] color</td>
      <td>ZZ-HIDDEN-SO</td>
    </tr>
    <tr>
      <td>SD</td>
      <td>Status bestaand 0.18, overige statussen 0.25</td>
      <td>objectentabellen: [status] color</td>
      <td>continuous</td>
    </tr>
    <tr>
      <td>SV</td>
      <td>Status bestaand 0.18, overige statussen 0.25</td>
      <td>objectentabellen: [status] color</td>
      <td>continuous</td>
    </tr>
    <tr>
      <td>O</td>
      <td>0.18</td>
      <td>objectentabellen: [status] color</td>
      <td>continuous</td>
    </tr>
    <tr>
      <td>T**/L**/M**/T**V </td>
      <td>object in ZZ: [status] lineweight</td>
      <td>object in ZZ: [status] color</td>
      <td>object in ZZ: [status] linetype</td>    </tr>
    <tr>
      <td>V</td>
      <td>objectentabellen: [status] lineweight</td>
      <td>objectentabellen: [status] color V</td>
      <td>continuous</td>
    </tr>
  </tbody>
</table>

**Comment by SanderNijhof** [comment]
1. wat zijn de footnotes [3] en [4]?
2. Waarom zijn SD en AD niet één pendikte dikker net als GD? 
3. Waarom zijn GN en SN één pendikte dunner en SD, AD en GD één pendikte dikker. Dat strookt niet met onderscheid bestaand/nieuw dus die pas ik daarom nooit toe! GN en SN onderscheiden zich sowieso al via ZZ-HIDDEN.
4. Waarom zijn de lijndikten van A, AD, S, SN, SD, SV en O niet gewoon de bylayer lijndikten volgens de objecttabellen en zijn die hard gespecificeerd? Uitgangspunt is tekenen bylayer volgens objecttabellen.
5. Waarom zijn juist de color voor element -A anders dan de color voor element -G?

T**V krijgt dezelfde kleur als 'color' (net als GV en SV), **NIET** de kleur 'color V'! Color V is alleen voor -V vlakvullingen.

**Comment by ElisabethKloren** [comment]
Ok, eerst plaats ik hier even de tabel uit versie 5 die alle verwarring heeft veroorzaakt:

![image](https://github.com/nl-digigo/NLCS/assets/48585720/6d5a9ea4-02c0-477a-b250-f2684400cf8e)

**Comment by ElisabethKloren** [comment]
> 1. wat zijn de footnotes [3] en [4]?

<p id="footnote-3">[3] Uitzondering op de lijndikte van GD is dat daar waar lijnen dichtvloeien bij het afdrukken (bijvoorbeeld bij doorsneden van damwanden en staalprofielen) juist een pendikte dunner mag worden gebruikt. Ook voor wapeningstaven geldt een uitzondering: deze kunnen worden getekend met zowel pendikte 0.5 als pendikte 0.7, ongeacht of het een staaf in aanzicht of in doorsnede betreft.</p>
<p id="footnote-4">[4] Als in GD het lijntype continuous niet logisch is, omdat het geen fysiek object betreft maar bijvoorbeeld een afbreeklijn, NAP lijn of 'bestaand' maaiveld, mag een ander lijntype worden toegepast.</p>

**Comment by ElisabethKloren** [comment]
> 2. Waarom zijn SD en AD niet één pendikte dikker net als GD?

In versie 5.0: 

- bij AD stond 0.18, dat heb ik gehandhaafd, dikker is vast onwenselijk voor de presentatie, ik handhaaf het oude uitgangspunt
- bij SD stond als in objectentabellen, alleen is er geen lineweight gespecificeerd voor S of SD  in de objectentabellen; dus ik ging ervan uit dat dit de gewone pendikte moest zijn, maar je hebt gelijk, logischer is hetzelfde doen en dan ook footnote 3 erbij zetten

> 3. Waarom zijn GN en SN één pendikte dunner en SD, AD en GD één pendikte dikker. Dat strookt niet met onderscheid bestaand/nieuw dus die pas ik daarom nooit toe! GN en SN onderscheiden zich sowieso al via ZZ-HIDDEN.

In versie 5.0: 

- Bij GN stond één pendikte dunner, heb ik gehandhaafd
- bij SN stond bestaand 0.13, overig 0.18, heb ik gehandhaafd > stond ook beschreven bij de symbolen

> 4. Waarom zijn de lijndikten van A, AD, S, SN, SD, SV en O niet gewoon de bylayer lijndikten volgens de objecttabellen en zijn die hard gespecificeerd? Uitgangspunt is tekenen bylayer volgens objecttabellen.

de lijndikten zijn in de objectendatabase niet per elementtype gespecificeerd; ik heb hier gewoon de oude uitgangspunten uit 5.0 gehandhaafd. 

> 5. Waarom zijn juist de color voor element -A anders dan de color voor element -G?

Geen idee, maar in de database wordt zowel een gewone color gegeven als een color A, dat was in versie 5.0 ook al zo. 

> T**V krijgt dezelfde kleur als 'color' (net als GV en SV), **NIET** de kleur 'color V'! Color V is alleen voor -V vlakvullingen.

Dat heb ik dan verkeerd geinterpreteerd, zal ik corrigeren

**Comment by ElisabethKloren** [comment]
Nieuwe tabel:

<table class="tabel3" title="representatie van ELEMENTEN">
  <thead>
    <tr>
      <th>ELEMENT</th>
      <th>LIJNDIKTE</th>
      <th>KLEUR</th>
      <th>LIJNTYPE</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>G</td>
      <td>objectentabellen: [status] lineweight</td>
      <td>objectentabellen: [status] color</td>
      <td>objectentabellen: [status] linetype</td>
    </tr>
    <tr>
      <td>GN</td>
      <td>één pendikte dunner dan aangegeven in objectentabellen: [status] lineweight</td>
      <td>objectentabellen: [status] color GN</td>
      <td>ZZ-HIDDEN-SO</td>
    </tr>
    <tr>
      <td>GD</td>
      <td>één pendikte dikker dan aangegeven objectentabellen: [status] lineweight<a href="#footnote-3">[3]</a></td>
      <td>objectentabellenobjectentabellen: [status] color GD</td>
      <td>continuous <a href="footnote-4">[4</a>]</td>
    </tr>
    <tr>
      <td>GV</td>
      <td>objectentabellen: [status] lineweight</td>
      <td>objectentabellen: [status] color</td>
      <td>objectentabellen: [status] linetype</td>
    </tr>
    <tr>
      <td>A</td>
      <td>0.18</td>
      <td>objectentabellen: [status] color A</td>
      <td>continuous</td>
    </tr>
    <tr>
      <td>AD</td>
      <td>0.18</td>
      <td>objectentabellen: [status] color A</td>
      <td>continuous</td>
    </tr>
    <tr>
      <td>S</td>
      <td>Status bestaand 0.18, overige statussen 0.25</td>
      <td>objectentabellen: [status] color</td>
      <td>continuous</td>
    </tr>
    <tr>
      <td>SN</td>
      <td>Status bestaand 0.13, overige statussen 0.18</td>
      <td>objectentabellen: [status] color</td>
      <td>ZZ-HIDDEN-SO</td>
    </tr>
    <tr>
      <td>SD</td>
      <td>één pendikte dikker dan aangegeven objectentabellen: [status] lineweight<a href="#footnote-3">[3]</a></td>
      <td>objectentabellen: [status] color</td>
      <td>continuous</td>
    </tr>
    <tr>
      <td>SV</td>
      <td>Status bestaand 0.18, overige statussen 0.25</td>
      <td>objectentabellen: [status] color</td>
      <td>continuous</td>
    </tr>
    <tr>
      <td>O</td>
      <td>0.18</td>
      <td>objectentabellen: [status] color</td>
      <td>continuous</td>
    </tr>
    <tr>
      <td>T**V </td>
      <td>als T** object in ZZ: [status] lineweight</td>
      <td>als T** object in ZZ: [status] color</td>
      <td>als T** object in ZZ: [status] linetype</td>    </tr>
    <tr>
      <td>T**V </td>
      <td>object in ZZ: [status] lineweight</td>
      <td>object in ZZ: [status] color</td>
      <td>object in ZZ: [status] linetype</td>    </tr>
    <tr>
      <td>V</td>
      <td>objectentabellen: [status] lineweight</td>
      <td>objectentabellen: [status] color V</td>
      <td>continuous</td>
    </tr>
  </tbody>
</table>

<p id="footnote-3">[3] Uitzondering op de lijndikte van GD is dat daar waar lijnen dichtvloeien bij het afdrukken (bijvoorbeeld bij doorsneden van damwanden en staalprofielen) juist een pendikte dunner mag worden gebruikt. Ook voor wapeningstaven geldt een uitzondering: deze kunnen worden getekend met zowel pendikte 0.5 als pendikte 0.7, ongeacht of het een staaf in aanzicht of in doorsnede betreft.</p>
<p id="footnote-4">[4] Als in GD het lijntype continuous niet logisch is, omdat het geen fysiek object betreft maar bijvoorbeeld een afbreeklijn, NAP lijn of 'bestaand' maaiveld, mag een ander lijntype worden toegepast.</p>

**Comment by SanderNijhof** [comment]
> , dat was in versie 5.0 ook al zo

Ja dat klopt, meeste heb je ook goed overgenomen uit de oude/huidige NLCS. Weet alleen niet waarom dat zo is opgenomen en of alle leveranciers/tekenaars zich hier ook aan houden. Misschien goed om dat te controleren.
Als ik in een tekening een bestaand vlak en nieuw vlak beide arceer met lijndikte 0.18mm dan is het verschil niet zichtbaar op papier, dus daar houd ik me sowieso standaard niet aan. Vind het niet logisch dat bij alle objecten er **standaard** verschil is in pendikte per status behalve bij arceringen en oppervlakken. Ik wijk daar **standaard** van af ten gunste van de leesbaarheid van de tekening.

**Comment by ElisabethKloren** [comment]
Ik heb issue #459 aangemaakt zodat we dit in de expertcommissie goed kunnen bespreken in de aanloop naar een volgende publicatie.
