### ISSUE TITLE
VWA symbolen bij DWA

### ISSUE THREAD

**Issue by HenkArkance** [nl-digigo/NLCS#123]
Onder DWA worden bij de volgende NLCS-objecten nog VWA symbolen toegepast:

DWA > RIOOLPUT > INSPECTIEPUT
DWA > RIOOLPUT > INSPECTIEPUT > REINIGENDEPUT

**Comment by MvanderHulst** [comment]
Hernoemen volgende symbolen:
V-SRI-PUT_VWA_KUNSTSTOF-SO
V-SRI-PUT_VWA-SO
SRI-PUT_VWA_KUNSTSTOF-SO
SRI-PUT_VWA-SO
B-SRI-PUT_VWA_KUNSTSTOF-SO
B-SRI-PUT_VWA-SO

naar:
V-SRI-PUT_DWA_KUNSTSTOF-SO
V-SRI-PUT_DWA-SO
SRI-PUT_DWA_KUNSTSTOF-SO
SRI-PUT_DWA-SO
B-SRI-PUT_DWA_KUNSTSTOF-SO
B-SRI-PUT_DWA-SO

**Comment by ElisabethDeVries** [comment]
[[Release note]] Symbolen met naam VWA zijn hernoemd naar DWA om te matchen met de keuze om naamgeving van rioleringsstelsels overeen te laten komen met het Gemeentelijk Woordenboek Stedelijk Water (GWSW).
