### ISSUE TITLE
Toevoegen VRI aan NLCS

### ISSUE THREAD

**Issue by NielsNederpel** [nl-digigo/NLCS#125]
Vorig jaar hebben we deze bestanden betreffende Verkeersregelinstallaties ontvangen om toe te voegen aan de NLCS. 
Graag jullie review op de documenten zodat we deze in een volgende release mee kunnen nemen

[NLCS-OBJECTEN-IW-VRI_LAAGOPBOUW-5.1.xls](https://github.com/bimloket/NLCS/files/12558765/NLCS-OBJECTEN-IW-VRI_LAAGOPBOUW-5.1.xls)
[NLCS-OBJECTEN-VRI lijntypes-5.1.xls](https://github.com/bimloket/NLCS/files/12558766/NLCS-OBJECTEN-VRI.lijntypes-5.1.xls)
[NLCS-OBJECTENVRI nieuwe symbolen-5.1.xlsx](https://github.com/bimloket/NLCS/files/12558768/NLCS-OBJECTENVRI.nieuwe.symbolen-5.1.xlsx)

[Symbolen status V.zip](https://github.com/bimloket/NLCS/files/12558816/Symbolen.status.V.zip)
[Symbolen statusloos.zip](https://github.com/bimloket/NLCS/files/12558817/Symbolen.statusloos.zip)
[Symbolen status B.zip](https://github.com/bimloket/NLCS/files/12558818/Symbolen.status.B.zip)

**Comment by MvanderHulst** [comment]
Hoi allen, inhoudelijk geen verstand van VRI, maar de Objecten zien er logisch uit in de opbouw.
De naamgeving van de linetypes is echter onjuist. dit zou V-...... moeten zijn. Nu staat de V aan de achterkant van de naam van het lijntype.

**Comment by SanderNijhof** [comment]
De kolommen met kleuren voor ‘V’ zijn niet correct ingevuld. Dat moeten grijswaarden of RGB kleuren zijn.
Ik heb problemen met de laag ‘IW-VRI_OVERIG-G/S’. Dit moet zijn ‘IW-VRI-G/S’ in de lijn van het harmonicamodel.
Zoals Michel terecht opmerkt kloppen de lijnstijlnamen voor status V- niet, maar ook de overige lijnstijlnamen kloppen niet bijv. ‘HIDDEN’ moet zijn ‘XX-HIDDEN’ en ‘KABELTRACE’ wordt dan ‘IW-KABELTRACE’ enzovoorts.
Verder valt me op dat de lijnstijlen en symbolen gelukkig niet-SO zijn.
De A-Kleuren moeten steeds de waarde+2 van de G-kleuren hebben. Uitzondering is kleur 7 daarbij hoort de kleur 252, dus:
Als ‘B color’ = 200 (kolom AC) dan is ‘B color A’ = 202 (kolom AD)
Als ‘B color’ = 150 (kolom AC) dan is ‘B color A’ = 152 (kolom AD)
Als ‘B color’ = 7 (kolom AC) dan is ‘B color A’ = 252 (kolom AD)
Enz.
De kleuren voor de kolommen van status V zijn nu allemaal '20' ofwel rood op het scherm en zwart op de afdruk. Dat is conform NLCS niet juist. Deze moeten identiek aan de kolommen voor status N zijn.

**Comment by ElisabethKloren** [comment]
werd ook nog gemaild met deze vraag: We zijn wel benieuwd of de expertcommissie ,waar VRI-objecten, symbolen en lijnstijlen onder vallen, ook weer van start is gegaan en wie hier eventueel vanuit de wegbeheerders is aangesloten. Zo kunnen we zorgen dat opgedane ervaring door verschillende wegbeheerders weer goed terecht komt in de expertcommissie.

**Comment by DimitryDekker** [comment]
Wij hebben indertijd samen met Arkance Systems bijgaande NLCS invulling samengesteld tbv de gemeente Den Haag voor het uitwisselen van VRI's. Negeer in deze bijlage de manier waarop de detectielussen zijn gemodelleerd, dat kunnen beter vlakobjecten zijn dan symbolen (dan kun je immers elke vorm tekenen). 

De overlap met de voorgestelde opzet is vrij groot, dus bovenstaand voorstel dekt een groot deel van de behoefte. Ik kan mij voorstellen dat bijgaande tekening nog wat nuttige symbolen toevoegt. Daarnaast zijn de verschillende soorten detectielussen in de bijgesloten tekening uitgewerkt. 

Overige relevante ervaringen die we hebben opgedaan: uitleggers van masten/portalen kunnen het beste als lijnobject worden gemodelleerd, omdat die in de praktijk een groot aantal varianten laten zien. 
[VRI-NLCS_FavorietenOverzicht.zip](https://github.com/nl-digigo/NLCS/files/13334958/VRI-NLCS_FavorietenOverzicht.zip)

**Comment by ElisabethKloren** [comment]
deze issue ligt al zo lang dat ik het meeneem in de concept-release van 5.1; ik heb zo goed en zo kwaad als het kan wijzigingen aangebracht nav de comments, wel de symbolen allemaal gebruikt, er is niemand die je tegenhoudt om lijnen te gebruiken ipv symbolen.

Ik kan zelf geen symbolen uit een tekening halen, ik ben bereid ze toe te voegen als er individuele dwg bestandjes geleverd worden

**Comment by ElisabethKloren** [comment]
Ik kijk naar de parallel met OV en stop de kabels en lussen in de hoofdgroep IW, en niet in KL. Eens, of niet?

**Comment by ElisabethKloren** [comment]
en dat doe ik dan ook met de DRIP kabel

**Comment by DimitryDekker** [comment]
> Ik kijk naar de parallel met OV en stop de kabels en lussen in de hoofdgroep IW, en niet in KL. Eens, of niet?

Dat klinkt mij ook logisch in de oren.

**Comment by MvanderHulst** [comment]
@ElisabethKloren 
Eens.
De hoofdgroep KL is voor 'Netbeheer' bedoeld.
Ook wel uit te leggen als 'Gas/water/licht' voor woningbouw.

OV en VRI en detectielussen e.d. zijn hier geen onderdeel van en behoren in de eigen hoofdgroepen/objectenstructuren.

**Comment by ElisabethKloren** [comment]
Heb dit met alle comments verwerkt. Verwacht nog wel wat feedback op de concept-publicatie, maar zo kunnen we goed vooruit.

**Comment by ElisabethDeVries** [comment]
[[Release note]] de VRI-werkgroep heeft extra objecten toegevoegd aan de hoofdgroep IW (Installaties wegen) voor de VRI's, waaronder een automaat, camera, detectie en bekabeling.
