### ISSUE TITLE
Release notes 5.0 toevoegen aan formele documentatie

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#126]
Release notes 5.0  en 5.1 toevoegen aan formele documentatie

**Comment by SanderNijhof** [comment]
Ook de afgeleide documenten controleren. In de [Uitgangspunten NLCS controles (PDF)](https://www.bimloket.nl//documents/Uitgangspunten-NLCS-controles.pdf). Staat bijvoorbeeld vermeld dat 'De huidig vigerende versie is NLCS 4.2.'

**Comment by ElisabethKloren** [comment]
Beide heb ik aangepast en verwerkt
