### ISSUE TITLE
Analyse oneigenlijk gebruik van X in de laagnaam

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#128]
[NLCS-OBJECTEN-RI-5.0.xls](https://github.com/bimloket/NLCS/files/12587782/NLCS-OBJECTEN-RI-5.0.xls)
[NLCS-OBJECTEN-RI-5.1_VOORSTEL.xls](https://github.com/bimloket/NLCS/files/12587784/NLCS-OBJECTEN-RI-5.1_VOORSTEL.xls)
[NLCS-OBJECTEN-VH-5.0.xls](https://github.com/bimloket/NLCS/files/12587785/NLCS-OBJECTEN-VH-5.0.xls)
[NLCS-OBJECTEN-VH-5.1_VOORSTEL.xls](https://github.com/bimloket/NLCS/files/12587786/NLCS-OBJECTEN-VH-5.1_VOORSTEL.xls)
[NLCS-OBJECTEN-VW-5.0.xls](https://github.com/bimloket/NLCS/files/12587787/NLCS-OBJECTEN-VW-5.0.xls)
[NLCS-OBJECTEN-VW-5.1_VOORSTEL.xls](https://github.com/bimloket/NLCS/files/12587788/NLCS-OBJECTEN-VW-5.1_VOORSTEL.xls)

Hierbij mijn (Michels) analyse van alle hoofdgroepen waarin de ‘x’ oneigenlijk is gebruikt in de laagnaam en eigenlijk een ‘/’ zou moeten zijn.
Omdat dit niet is toegestaan in laagnamen, moeten we dit als een ‘spatie’ aangeven.
Tevens heb ik alle hoofdgroepen even nagelopen op de controle of een spatie soms een gewenste aanvulling kant zijn.
Concluderend kwam ik tegen:
-	De ‘EI-buizen’ zouden aangepast moeten worden
-	De wegmarkeringen zijn inconsequent (het lijkt alsof mijn aanpassingen van 4.2 naar 5.0 niet zijn meegekomen?)
-	Tevens een aantal namen gevonden die m.i. niet nodig zijn en zouden kunnen vervallen.
-	In de verhardingen bij de kantopsluitingen de nodige bijzonderheden gevonden.
 
Ik heb ook alle symbolen nagelopen, enkel in de Verhardingen staan daar wat bijzonderheden in.
Bij het nalopen hiervan kwam ik er achter dat er zeer veel doorsnedes van materialen in de NLCS staan, welke niet eens meer geleverd worden door leverancier.
M.i. zou er best een flinke bezem door deze bibliotheek mogen. Willen we alle doorsnedes tot in den treure aanbieden? Zoja.. hebben we een aantal ‘standaard’ leverancier?
Persoonlijk denk ik dat je met de catalogus van ‘Struyk Verwo’ zo goed als alles toch wel te pakken hebt???
In ben dan ook even gestopt met deze bibliotheek omdat dit gevoelsmatig totaal nutteloos werk werd.

**Comment by MvanderHulst** [comment]
Ook benoemd ben in issue #33 ben ik voorstander om de doorsnedes van banden in zijn geheel te laten vervallen.
ZEER verouderde informatie, veel symbolen kloppen niet en maten bestaan niet.

Dat de doorsnede dikker is, gaat opgelost worden. Zie ook issue #17 

Geleideband hoogte kan toegevoegd worden.

Moeten we 1 leverancier 'beschrijven' in de standaard? Nu een chaos aan soorten.

Conform Struyk is een rijwielpadband een andere categorie. valt ter discussie te trekken.

Een 'plakband' bestaat en is vaak een 'stootband' of een lage 'trottoirband'.
Plakband is een spreekterm en geen te bestellen product.

Inritblokken bestaan niet en moeten inritbanden zijn. deze staat nog in de lijst.

**Comment by ElisabethKloren** [comment]
voorgenomen wijziging: conform bijgevoegde exceltabellen, corrigeren spaties en x-jes. 

De andere discussie over soorten banden bestaan andere discussies voor.

**Comment by ElisabethKloren** [comment]
voor inritblokken bestaat nu issue #440

**Comment by ElisabethDeVries** [comment]
dit wordt opgepakt in release 6.0
