### ISSUE TITLE
Voorstel hekwerken 'terreinafscheidingen'

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#129]
Zoals besproken, hierbij mijn (michels) idee over een logische indeling voor het object ‘terreinafscheiding’.
Op dit moment vind ik de logica niet echt logisch. Zie bijlage.

[NLCS-OBJECTEN-IE-5.0.xls](https://github.com/bimloket/NLCS/files/12587812/NLCS-OBJECTEN-IE-5.0.xls)
[NLCS-OBJECTEN-IE-5.1_VOORSTEL.xls](https://github.com/bimloket/NLCS/files/12587813/NLCS-OBJECTEN-IE-5.1_VOORSTEL.xls)

**Comment by MvanderHulst** [comment]
Graag het voorstel voor terreinafscheiding bespreken in EC.

**Comment by ElisabethDeVries** [comment]
[[Release note]] De laagnamen voor hekwerken, muren, doorgangen en andere constructieve afscheidingen in de hoofdgroep IE (InrichtingsElementen) zijn flink uitgebreid. Omdat de wens is om de naam te wijzigingen van "TERREINAFSCHEIDING_KUNSTMATIG" naar "CONSTRUCTIEVE AFSCHEIDING" vervallen de bestaande 8 laagnamen. Daarnaast vervallen alle objecten "TERREINAFSCHEIDING_NATUURLIJK" omdat hagen en houtwallen thuishoren in de hoofdgroep GR (Groen).

**Comment by ElisabethDeVries** [comment]
[[Release note]] De laagnamen voor hekwerken, muren, doorgangen en andere constructieve afscheidingen in de hoofdgroep IE (InrichtingsElementen) zijn flink uitgebreid. Omdat de wens is om de naam te wijzigingen van "TERREINAFSCHEIDING_KUNSTMATIG" naar "CONSTRUCTIEVE AFSCHEIDING" wijzigen 8 namen. Daarnaast vervallen alle objecten "TERREINAFSCHEIDING_NATUURLIJK" omdat hagen en houtwallen thuishoren in de hoofdgroep GR (Groen).

**Comment by ElisabethDeVries** [comment]
Technische commissie 2 juli 2026: De wijziging van TERREINAFSCHEIDING_KUNSTMATIG naar CONSTRUCTIEVE AFSCHEIDING is besproken: 
Ingrijpende wijziging op de grens, dit wordt door de toevoeging van ontbrekende soorten hekwerken wel een echte inhoudelijke verbetering voor gebruikers.
Dilemma: “Terreinafscheiding_kunstmatig” als naam gebruiken en dan in 6.0 alle nieuwe objecten weer van naam laten wijzigen > wordt niet als goed idee beschouwd
Dilemma: Oude objecten van naam laten wijzigen > het is makkelijker om te kunnen zoeken naar “vervallen” objecten, dus inderdaad oude objecten laten vervallen en nieuwe aanmaken
Dilemma: Dit heeft invloed op een paar objetcen in de BGT mapping. 
Overall advies: deze wijziging wel meenemen in de 5.2 release.
