### ISSUE TITLE
Voorstel hoofdgroep beplanting

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#130]
[NLCS-OBJECTEN-GR-5.1 VOORSTEL.xls](https://github.com/bimloket/NLCS/files/12587815/NLCS-OBJECTEN-GR-5.1.VOORSTEL.xls)

In het noodstuk beplanting zitten ook de nodige dubbelingen.
In de bijlage e.e.a. herzien (puur even op OBJECTEN niveau.

**Comment by ElisabethDeVries** [comment]
HEROPENEN, TE VERWERKEN IN 6.0
