### ISSUE TITLE
lijntypes riolering

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#131]
Zoals besproken in het NLCS-overleg, hierbij de. LIN file met een DWG van de riolering zoals wij deze bij HB al jaren toepassen.
voor het herzien van de lijntypes, dit kan mogelijk input en inspiratie hiervoor zijn.

[riolering-Model.pdf](https://github.com/bimloket/NLCS/files/12587856/riolering-Model.pdf)

**Comment by ElisabethKloren** [comment]
en deze bestanden kan ik niet in een issue gooien  dus maar hier geplaatst: https://github.com/bimloket/NLCS/tree/main/ontwikkeling/riolering

**Comment by MvanderHulst** [comment]
Zie ook issue #58

**Comment by MvanderHulst** [comment]
Gesloten ivm dubbel 58
