### ISSUE TITLE
mapping BGT, finetuning

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#132]
[BGT_NLCS_MODEL.pdf](https://github.com/bimloket/NLCS/files/12587897/BGT_NLCS_MODEL.pdf)
[BGT_HB_MODEL.pdf](https://github.com/bimloket/NLCS/files/12587898/BGT_HB_MODEL.pdf)

Michel zegt: In aanvulling op onderstaande heb ik e.e.a. nog even verder uitgewerkt.
Op verzoek van Frank neem ik hem even niet meer mee in de mail, hij wil zich enkel nog focussen op de overdracht van zijn werkzaamheden.
 
Bijgevoegd:
-	BGT symbolen NLCS.dwg
o	Alle symbolen zoals deze nu in de mapping zitten
-	BGT_NLCS_MODEL.pdf
o	De presentatie zoals deze op de PDF komt, met te kleine symbolen.
-	BGT Symbolen HB (block replaced).dwg
o	Aangepaste blocks met de juiste schalen, namen conform de huidige tabellen.
-	BGT Symbolen HB voorstel.dwg
o	Zelfde bestand als bovenstaande, maar met herziene namen van blocks om e.e.a. logischer te maken in de structuren.
-	BGT_HB_MODEL.pdf
o	Presentatie van de tekening met de aangepaste symbolen, waarbij alles goed leesbaar is.

**Comment by ElisabethKloren** [comment]
[Bevindingen BGT-symbolen.pdf](https://github.com/bimloket/NLCS/files/12587917/Bevindingen.BGT-symbolen.pdf)
[BGT symbolen-Model.pdf](https://github.com/bimloket/NLCS/files/12587918/BGT.symbolen-Model.pdf)

**Comment by ElisabethKloren** [comment]
En de dwg files staan hier: https://github.com/bimloket/NLCS/tree/main/ontwikkeling/bgt

**Comment by MvanderHulst** [comment]
Zie ook issue #16 , deze is ondertussen doorontwikkeld en actueel, inclusief aanvullende issues.
