### ISSUE TITLE
Symbolen NLCS publiceren via Github

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#133]
Symbolen NLCS publicdren via Github; werkwijze is versioning per afbeelding, niet per release van NLCS; dit ook opnemen in de documentatie

**Comment by MvanderHulst** [comment]
Ik snap op basis van bovenstaande niet goed wat precies bedoeld wordt?

**Comment by MvanderHulst** [comment]
@ElisabethKloren geen actie voor mij denk ik? anders hoor ik het graag.

**Comment by ElisabethKloren** [comment]
Idd geen actie, documentatie is gemaakt: 

in de [beheerhandleiding](https://nl-digigo.github.io/NLCS/managementmanual/#symbolen)
En de link naar de actuele symbolen staat in de [Readme](https://github.com/nl-digigo/NLCS/blob/main/README.md)
