### ISSUE TITLE
.lin kunnen genereren uit de database

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#135]
.lin kunnen genereren uit de database voor lijnen in de softwarepakketten & dit documenteren

Was dit een script in de oude database?

**Comment by ElisabethKloren** [comment]
Input Niels: Dat we het .lin bestand uit de database genereren is echt een database dingetje (en pas sinds de laatste versie van NLCS 5.0 mogelijk)
Hoe dat achter de schermen werkt weet ik niet, maar het is inderdaad "een druk op de knop" om de diverse zips te genereren.

In de documentatie die Luuk gestuurd heeft (met jou in cc ) op 20 juli 2023 staat wel het e.e.a. maar zelf kan ik hier niet echt wijs uit, maar mocht je meer over het achter de schermen verhaal weten verwacht ik dat Luuk je hier uiteraard wel mee kan helpen.

De overige bestandjes bij de lijntypes zijn benodigd om "complexe lijntypes te maken. Normale lijntypes met punt, streep principe, gaat in getallen waarbij de lengte van t streepje dan met een getal wordt aangegeven, dan een getal voor het "blanco" gedeelte" dan weer getal voor het streepje etc...echter voor complexe lijntypes (bijvoorbeeld met tekst of symbolen) zijn die andere bestanden benodigd. Hiernaar wordt dan een soort verwijzing gemaakt vnauit het lin bestand.

Met betrekking tot de arceringen is dat ook sinds NLCS 5.0 mogelijk en voor mij ook een druk op de knop.
Hieruit ontstonden dan meerdere arceringsbestanden 1 met losse arceringen in "tekst" bestandjes en 1 "tekst"bestand met alle arceringen.

Al deze zipjes (lin + arceringen) worden uiteraard als download aangeboden 
1 voor gebruikers zonder tooling, je kunt deze lijnstylen en arceringen namelijk op je computer opslaan zodat AutoCAD/Microstation deze lijn en arceringen kan gebruiken
2 worden ze uiteraard gebruikt door de leveranciers voor het vullen van hun tooling. (al gaat dat in theorie hetzelfde als het plaatsen op je computer zodat de tooling dit kan gebruiken binnen AutoCAD)

Vanuit TPG weet ik dat zij behoefte hadden aan alle arceringen in 1 bestand om e.e.a. goed te laten werken. ( vandaar 2 verschillende arceringen zips.) 

Dus in mijn idee moeten we inderdaad ook weer deze zipjes kunnen genereren uit de nieuwe database.

**Comment by ElisabethKloren** [comment]
EC 2023-11-09: Er was een script in de SQL database. Actie Elisabeth om dat script te achterhalen en te transformeren.

**Comment by gerritversteegh** [comment]
@ElisabethKloren momenteel staan de IDs in het .lin bestand verwerkt, e.g. de 3 in het onderstaande: 

```
*AL-DETAILS-SO,3
A,2,-1.2,2
```
Wil je dat behouden (indien het linetype een ID heeft) of wil je dit vervangen door de URIs?

**Comment by ElisabethKloren** [comment]
Oef, dat is een vraag voor de expertcommissie. Doe voor nu maar de id, ik weet niet of de CAD pakketen met uri's kunnen omgaan. Auch

**Comment by gerritversteegh** [comment]
Ter review: de gegenereerd linetypes staan hier in een .lin bestand:
https://github.com/nl-digigo/NLCS/tree/main/lijntypes/concept/5.1

**Comment by ElisabethKloren** [comment]
dit is helemaal top
