### ISSUE TITLE
#1681	geleideconstructie opnemen in BGT mapping

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#14]
Bij de InfraCAD BGT import komt een geleideconstructie mee in de import. Deze staat echter niet in de mapping. Omdat deze data wel in de BGT download zit, zou deze aan de mapping toegevoegd moeten worden,

**Comment by MvanderHulst** [comment]
In aanvulling op issue: #16 de symbolen voor een geleideconstructie:
![image](https://github.com/nl-digigo/NLCS/assets/144665595/b6957b6f-1363-498f-8bb2-c59076abd8dc)

tevens opnemen in mapping!

**Comment by ElisabethDeVries** [comment]
in issue #11 wordt de bgt mapping geadreseerd

**Comment by ElisabethDeVries** [comment]
[[Release note]] In hoofdgroep IE (InrichtingsElementen) is een object en zijn symbolen toegevoegd voor een geleideconstructie.
