### ISSUE TITLE
Hoe actueel is de BGT achtergondinformatie op de website?

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#140]
[Koppeling BGT IMGeo – NLCS](https://www.bimloket.nl//documents/Koppeling-BGT-IMGeo-en-NLCS-incl-bijlagen.zip) (zip)

**Comment by MvanderHulst** [comment]
Het korte antwoord is: totaal niet actueel. al jaren niet bijgewerkt. en achterhaald.

**Comment by ElisabethKloren** [comment]
Dan laat ik dit in het archief, en verwerk dit niet in de documentatie
