### ISSUE TITLE
Straatnamen en huisnummers uit BGT?

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#141]
Wij gebruiken regelmatig de ‘tool’ van Arkance, InfraCAD Map, om de BGT binnen te halen als ondergrond voor onze tekeningen.
We zouden hier graag een eigen toepassing voor ontwikkelen en hebben al een eerste versie. We zien daarin wel veel afwijkingen met de downloads van InfraCAD.
We zijn hierin op zoek naar wat handvaten. Bestaat er iets van een bibliotheek van de BGT van alle lagen en items?
 
En we missen in de huidige download met ons prototype dat de straatnamen en huisnummers ontbreken. Zijn deze überhaupt onderdeel van de BGT, of moeten we die separaat uit de BAG ophalen?

**Comment by ElisabethKloren** [comment]
Eerste deel van de vraag per mail beantwoord: In de huidige versie van NLCS 5.0 zit een tabel waarin wordt aangegeven, hoe BGT informatie moet worden weergegeven in CAD, volgens de NLCS. Dit is anders dan hoe de BGT in GIS wordt weergegeven. De softwareleveranciers kunnen de BGT gegevens als het goed is allemaal op dezelfde manier weergeven in NLCS stijl in CAD; overigens heb ik gemerkt, dat gebruikers hier nog wel wijzigingsverzoeken voor indienen zoals deze: https://github.com/bimloket/NLCS/issues/97

Over straatnamen en huisnummers: dat moet ik navragen, hoe dat in de conversie naar NLCS wordt meegenomen; ik weet dat straatnamen en huisnummers wel via de BAG worden gepubliceerd in de BGT 

De huidige versie van de NLCS wordt gepubliceerd in een SQL database; wij zitten midden in de transformatie naar publicatie als linked data. Als jullie iets gaan ontwikkelen zou het zonde zijn om nog functionaliteit te maken die de sql database nodig heeft. Echter, de mapping naar BGT is nog niet opgenomen in linked data (work in progress). Deze valt wel terug te vinden in de tabellen die te downloaden zijn op de website: https://www.bimloket.nl/p/429/Documentatie  (“tabellen sql database” en dan in de zip file kijken in de folder “mappingen”)
Als je iets wilt ontwikkelen op basis van de in CAD ingelezen ondergronden maak je gebruik van de standaard.

**Comment by ElisabethKloren** [comment]
Blijft openstaan: straatnamen en huisnummers uit de BGT, worden die weergegeven? Gaat dat goed?

**Comment by MvanderHulst** [comment]
hier kan ik geen uitspraak over doen. Dit moeten één van de software levernaciers antwoord op geven.
Maar.... van GIS naar CAD is een leveranciersoplossing.... is het aan de NLCS om hier antwoord op te geven?

**Comment by ElisabethKloren** [comment]
Herstel wat eerder geschreven is: er is een mapping tussen BGT en NLCS; de CAD leveranciers zijn op dit moment niet verplicht die te gebruiken; restactie: check of straatnamen en huisnummers in de mapping zijn opgenomen

**Comment by ElisabethKloren** [comment]
Straatnamen en huisnummers zijn niet in de mapping opgenomen, dit zijn ook geen geo-objecten maar teksten die niet te mappen zijn, omdat ze in de bgt geen label hebben > zouden allemaal op een algemene tekstlaag kunnen komen maardat hoeft niet in de mappingstabel geregeld. Ik sluit deze issue af.
