### ISSUE TITLE
Substatus uitbreiden

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#144]
Netbeheer wil extra statussen kunnen toevoegen in de substatus, in elk geval "buiten bedrijf"; "reserve" en eventueel "in bedrijf" (maar dat kan ook bestaand zijn)

Nu wordt als "noodoplossing" Tijdelijk gebruikt voor "buiten bedrijf" dat klopt natuurlijk niet

**Comment by SanderNijhof** [comment]
De status in de NLCS-laag is ervoor bedoeld dat software kan herkennen of een object gewijzigd of verwijderd is. De status in de NLCS-laag zegt niets over de toestand van het object zelf. Of een object ‘in bedrijf’ of ‘buiten bedrijf’ is staat los van die status. Dat zijn eigenschappen van die objecten! zie ook issue #145

**Comment by ElisabethKloren** [comment]
gesloten wegens dubbel met #327
