### ISSUE TITLE
NLCS bewerkingen toepassen op alle NLCS statussen

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#145]
NLCS bewerkingen toepassen op alle NLCS statussen

Huidig: status Nieuw en Tijdelijk

Bewerkingen zijn: opvullen, verplaatsen ed

**Comment by ElisabethKloren** [comment]
EC 2023-10-03  eigenlijk heb je dan over een status die valt onder beheer? de statussen in de NLCS zijn projectstatussen? > Inderdaad 'voorbereidend' voor beheer 

Nee, het gaat om bestaande objecten waarbij je een bewerking uitvoert zoals reinigen, het is niet een nieuw object maar een bewerkt object

NLCS zegt: bestaande situatie staat in een eigen model, de nulsituatie; de status 

![MicrosoftTeams-image (1)](https://github.com/bimloket/NLCS/assets/48585720/62ad02d4-810f-4a43-989f-5887b9d8c5e1)

**Comment by ElisabethKloren** [comment]
Michel zegt:

B = Bestaand
BBB = Bestaand, buiten bedrijf (aanvulling netbeheer)
BIB = Bestaand, in bedrijf (aanvulling netbeheer)
BRS = Bestaand, reserve
V = Te verwijderen/Verwijderd
T = Tijdelijk aanbrengen
N = Nieuw aanbrengen
R = Revisie

Workflow:
GIS -> CAD: status B, BIB, BBB, of BRS
Te verwijderen leidingen krijgen de status V, VIB, VBB of VRS.
Nieuwe leidingen krijgen de status: NIB, NRS.

Revisie tekening kan bevatten:
B, BIB, BBB of BRS
V, VIB, VBB of VRS
R
Waarbij B wordt gelezen als ongewijzigd
V wordt gelezen als verwijderd.
R wordt gelezen als gereviseerd ontwerp.

De aanvullende substatus specifiek voor de hoofdgroep KL en OV van toepassing is.


Met een aanvulling ‘M’ van mutatie of ‘A’ van aangepast’, of ‘G’ van gewijzigd’.
Lijkt het mij logisch om een B object te kunnen kenmerken als ‘voorzien van aangepaste eigenschappen’.
Zoals volschuimen, buiten bedrijf stellen, relinen o.i.d.
Dit zijn handelingen die je op een bestaand object doet, maar wel een ‘nieuwe’ werkzaamheid zijn.

Zo critisch als ik altijd ben, ben ik blij met de voorgestelde workflow.
Het enige ‘nadeel’ dat ik zie, is dat de substatus 01/99 wordt aangepast naar BB, IB en RS.
Hierdoor is de toepassing van een fasenummer voor netbeheer niet meer mogelijk.
Gaat dit geen problemen opleveren?

**Comment by ElisabethKloren** [comment]
Dimitry zegt; Ik weet niet of de statussen VIB, VBB of VRS veel toevoegen, het object wordt immers verwijderd. Voor NIB, NRS moeten we ook even kijken of we die nodig hebben: mogelijk heeft dat wel zin. 

Een status M of A lijkt mij zeker van toegevoegde waarde, omdat je die ook in een ontwerptekening kunt toepassen. 

De substatus 01/99 gebruikten we nu al in sommige gevallen om onderscheid te kunnen maken tussen de substatussen die we nu (veel leesbaarder) met letters kunnen/willen gaan vormgeven. Het gebruik van een numerieke substatus voor projectfasering was mij niet bekend. Die zullen we wel meenemen in overleg met de netbeheerders om te kijken of dat een issue zou kunnen zijn.

**Comment by ElisabethKloren** [comment]
Frank vraagt: kan jij inschatten hoe vaak de substatussen 01/99 worden gebruikt? Naar mijn idee is dat namelijk niet heel veel, veel gebruikers weten vaak niet eens het bestaan ervan.

**Comment by ElisabethKloren** [comment]
Michel zegt: Wij gebruiken de substatus enkel in combinatie met de status B.
Dit om een BGT in delen uit te kunnen schakelen bij gefaseerd werk.
Nieuwe situatie’s delen wij op in XREF’s, waardoor het gebruik van de substatus niet nodig is en wordt ondervangen in de naam van de DWG’s.

In het proces gebruiken wij dus:
B, B01, B02, B03 etc.
V (met per op te breken fase een andere DWG).
T (met per op te breken fase een andere DWG).
N (met per op te breken fase een andere DWG).
X

Soms houden we ook alles op B en doen we de V in faseringen… net een beetje afhankelijk van de aan te leveren producten.

Hoe andere bureau’s dit doen durf ik echt niet te zeggen.
Op basis van mijn kennis van de bureaus hier in de buurt wordt het helemaal niet gebruikt.

**Comment by ElisabethKloren** [comment]
en Michel zegt ook: Als een object van BIB of BBB wordt verplaatst naar vervallen, wil je dit ook bij gewijzigde inzichten kunnen herstellen het in CAD-model.
Zodoende zullen de statussen van B en V altijd synchroon moeten lopen.
Anders zou bij het verplaatsten van een BBB object naar V, dit nooit meer kunnen herstellen bij een wijziging in de scope.
NIB en NRS lijken mij dan ook voor het ontwerp gewenste statussen. Maargoed, dat is mijn invulling. 😉

**Comment by SanderNijhof** [comment]
B- is altijd een bestaand object in zijn laatst geregistreerde toestand.

N- is een object dat een nieuwe status krijgt, dus een bestaand object waarvan de oude status wijzigt (met het AssetID van het B-object), of een nieuw object dat nog geen status had, omdat het nog niet bestond.

R- is een ‘as built’ N-ieuw object. Een verwijdert object staat nooit op een R-laag. Als bijvoorbeeld van een leiding van 40m, de eerste 10 meter fysiek wordt verwijderd en de resterende 30m wordt volgeschuimd, dan komt de 10m op een V- laag en de 30m die volgeschuimd blijft liggen op een R- laag (met het originele AssetID).

T- Zijn objecten na gereedkomen van de werkzaamheden dezelfde asseteigenschappen hebben als voor aanvang van de werkzaamheden, waarvan de asseteigenschappen dus niet wijzigen. Bijvoorbeeld tijdelijke markeringen, hulpconstructies, of een paal die tijdelijk wordt verplaatst en daarna op exact dezelfde plek en toestand wordt teruggeplaatst en waarvan dus de asset-eigenschappen niet wijzigen. Een tijdelijke damwand of leiding die nadien geen functie meer heeft maar wel blijft bestaan komt op een N- laag.

V- Alleen objecten die fysiek worden verwijdert komen op een V-laag. D.w.z. na afronding van de werkzaamheden bestaat het object niet meer in de openbare ruimte. In geval een object deels verwijderd wordt en het verwijderde object blijft geregistreerd als Asset, dan krijgt het verwijderde deel een nieuw AssetID.
Aan de status kan een numerieke waarde worden voor om objecten te groeperen voor bijvoorbeeld fases van uitvoering.

De status in de NLCS heeft niet betrekking op de toestand van het object, maar de op het werkproces waarvoor de tekening gemaakt is. **Of een object ‘in bedrijf’ of ‘buiten bedrijf’ is staat los van die status. Dat zijn eigenschappen van die objecten!**
