### ISSUE TITLE
#1666 Niet alle rioolleidingen hebben de optie tot volschuimen, volzanden en relining

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#15]
Niet alle rioolleidingen hebben de optie tot volschuimen, volzanden en relining. Onderscheid is onnodig aanwezig. Kopieerfoutje?

**Comment by ElisabethKloren** [comment]
Reactie Expertcommissie: jij bedoelt dus dat we voor alle stelsel alle VOLZANDEN/VOLSCHUIMEN en RELINEN voor laten komen?

want in de tabellen ontbreekt alleen volzanden/volschuimen bij DRAINAGE en VACUUMLEIDING

in

DWA, GWA, HWA, ITR, OVERIG, PERSLEIDING
zitten ze wel degelijk.

relinen ontbreekt echter bij alle stelsels behalve OVERIG

**Comment by ElisabethKloren** [comment]
check met expert / GWSW of deze combi's inderdaad voor moeten komen?

**Comment by ElisabethKloren** [comment]
@MvanderHulst waarom is ophoogte brengen niet de bedoeling? gebeurt dit niet bij alle leidingen?

**Comment by ElisabethKloren** [comment]
Dus voorstel zoals hierboven en op hoogte brengen alleen bij de juiste objecten.

**Comment by MvanderHulst** [comment]
Op hoogte brengen hoeft alleen voor te komen bij het OBJECT 'putrand', welke op dit moment nog geen onderdeel van de NLCS is, hiervoor is een andere issue met het voorstel beschikbaar.

**Comment by ElisabethDeVries** [comment]
[[Release note]] Bij alle soorten stelsel zijn de opties voor bewerkingen van rioolleidingen toegevoegd (volschuimen, volzanden en relinen). Op hoogte brengen vervalt voor alle rioolleidingen, dit is geen realistische activiteit.

**Comment by MvanderHulst** [comment]
@ElisabethDeVries dit is onvoldoende,
deze bewerkingen moeten álle leidingen krijgen op het laagste subobjectniveau.

Je moet weten wélke diameter en materiaal de leiding is dit je gaat volschuimen.
De bewerking heeft betrekking op het object en is geen op zichzelfstaand object.

**Comment by ElisabethDeVries** [comment]
O-ooo dat worden veel extra laagnamen. Dat is tot nu toe niet gedaan in de database. Wellicht is dit een onderwerp voor de discussie over NLCS objectgericht? In elk geval is dit vrij controversieel dus ik label dit als bespreken met EC
