### ISSUE TITLE
Tekeningen checken op voldoen aan NLCS

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#151]
Check of dit goed beschreven staat in de documentatie:

Op pdf is het zeer lastig om te beoordelen of iets aan de NLCS voldoet of niet.
Visueel zie ik echter niet dat de tekening "in zijn geheel niet zou voldoen" aan de NLCS, want ik zie best wat bekende elementen. 
De vraag is echter ook of de lagen, arceringen en symbolen wel zijn opgebouwd volgens de NLCS (en dat is eigenlijk nog veel belangrijker!)

De NLCS biedt weliswaar standaard lijnstylen, arceringen en symbolen echter mag er van de visualisatie van de NLCS worden afgeweken/eigen lijnstylen, arceringen en symbolen worden toegevoegd, mits wordt voldaan aan "de spelregels" van de NLCS.

Zie hiervoor de formele beschrijving en dan met name: 
paragraaf 5.2.2. punt d
paragraaf 5.2.3. punt i
paragraaf 5.2.4. punt d
[Formele_beschrijving_NLCS_versie_5_0_V1_0.pdf (bimloket.nl)](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.bimloket.nl%2Fdocuments%2FFormele_beschrijving_NLCS_versie_5_0_V1_0.pdf&data=05%7C01%7Celisabeth.devries%40crow.nl%7C74e3772c2b1c4f6b7f7508dbd3d1d87d%7C1e0440a2a638433189c766de8119b255%7C0%7C0%7C638336670793888484%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jazr1xVjAekw4Ctu8vJnW4%2FKRUzt0cFtNp8JPh8aXEw%3D&reserved=0)

Juist doordat e.e.a. "digitaal goed in elkaar zit" kan de ene gebruiker het er it laten zien zoals hij wil, terwijl een andere tekenaar zijn eigen visualisatie voor zich ziet. 

Het is dus met name ook van belang dat jullie bij jullie uitvraag aangeven wat er wel en niet is toegestaan.

Daarnaast is het waarschijnlijk zo dat de tekeningen gemaakt zijn met behulp van tooling, die helpen met het bovenstaande maar daarnaast moet alle tooling, die u kunt vinden op onze website, voldoen aan een rapport/controle/herstel  functie.
U kunt de aannemer dus vragen om een rapport met de tekening mee te leveren waarin duidelijk wordt waar zij hebben afgeweken van de NLCS
[digiGO BIM Loket - Overzicht leveranciers](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.bimloket.nl%2Fp%2F505%2FOverzicht-leveranciers&data=05%7C01%7Celisabeth.devries%40crow.nl%7C74e3772c2b1c4f6b7f7508dbd3d1d87d%7C1e0440a2a638433189c766de8119b255%7C0%7C0%7C638336670793888484%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7bQsgfjCN9OeMn2goCDT8lAeC9K6cVrSxG6qagGA7N0%3D&reserved=0)
[digiGO BIM Loket - Minimale kwaliteitseisen](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.bimloket.nl%2Fp%2F506%2FMinimale-kwaliteitseisen&data=05%7C01%7Celisabeth.devries%40crow.nl%7C74e3772c2b1c4f6b7f7508dbd3d1d87d%7C1e0440a2a638433189c766de8119b255%7C0%7C0%7C638336670793888484%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0cpkpUKSwGn1cotzyaxHLR8vigFBrVDfmXhIjKgPSsI%3D&reserved=0)

Ik hoop dat u hier wat aan heeft.
Mochten er nog andere vragen zijn dan hoor ik het graag.

**Comment by MvanderHulst** [comment]
Bovenstaand lijkt mij een concrete samenvatting. Wat is nu de vraagactie?

**Comment by ElisabethKloren** [comment]
Toevoeging uitleg over het controleren van tekeningen in de FB:

Om te controleren of een tekening voldoet aan NLCS, hebben NLCS-leveranciers tooling beschikbaar. Die controleert op het gebruik van de juiste laagnamen, kleuren, lijnstijlen, lijndiktes, arceringen en symbolen. En geeft waarschuwingen als er afwijkingen of aanvullingen op de standaard zijn ontstaan. Als een opdrachtnemer een tekening conform NLCS aanlevert, kun u daarbij vragen om deze controle. Dan kunt u zien in hoeverre en voldaan wordt aan de standaard. 

NLCS biedt wel vrijheid om objecten anders te tekenen, vooral als dit de leesbaarheid van de tekening ten goede komt. Een afwijking is daarom niet altijd erg. 

NLCS regelt niet wat er op specifieke tekeningen moet komen. Een schetsontwerp vraagt een heel ander detailniveau dan een uitvoeringsontwerp. Als u wilt, dat specifieke objecten op de tekening staan of u bepaalde details wilt zien, dan moet u hier zelf om vragen.
