### ISSUE TITLE
#1664	Zeer veel BGT symbolen zijn een factor 5 te klein.

### ISSUE THREAD

**Issue by ElisabethDeVries** [nl-digigo/NLCS#16]
#1664	Zeer veel BGT symbolen zijn een factor 5 te klein. Tevens ontbreekt het 'vervallen' symbool voor bijna alle objecten. Ik heb reeds een uitgebreid voorstel aangeleverd voor BGT symbolen.

**Comment by MvanderHulst** [comment]
Symbolen kan ik aanleveren. Heb een hele bieb gemaakt met werkbare symbolen.

**Comment by ElisabethKloren** [comment]
@MvanderHulst fijn! ik heb het issue op je naam gezet, en label gewijzigd naar "minor fix" want volgens mij kan dit dan met de 5.1 versie mee?volgens mij kan jij de symbolen aanleveren en moet dan iemand anders nog een conversie naar microstation maken?

**Comment by MvanderHulst** [comment]
Ik heb reeds een voorstel gemaakt van alle BGT symbolen welke prima toepasbaar zijn.
![image](https://github.com/nl-digigo/NLCS/assets/144665595/5be35da8-6ac4-4628-9470-2051307a31fb)

Aandachtspunten zijn:
Naam van het boomsymbool aangepast van:
SGR-BOOM_GBKN-SO naar SGR-BOOM-SO
V-SGR-BOOM_GBKN-SO naar V-SGR-BOOM-SO
Aanvullingen zijn de SIE-WATERPOMP-SO en V-SIE_WATERPOMP-SO

**Comment by ElisabethDeVries** [comment]
[[Release note]] BGT-symbolen hadden soms een te kleine schaal, dit is verbeterd in meerdere hoofdgroepen. In hoofdgroep GRoen zijn de symbolen (V-)SGR-BOOM_GBKN-SO naar (V-)SGR-BOOM-SO aangepast, in de hoofdgroep InrichtingsElementen
