### ISSUE TITLE
Review op afbeelding: functionaliteit NLCS

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#162]
![NLCS architectuur](https://github.com/nl-digigo/NLCS/assets/48585720/23e956f1-f63d-472f-ab16-f15c515413fb)

Review dit op volledigheid functionaliteit NLCS

**Comment by ElisabethKloren** [comment]
toe te voegen: de plotinstellingen CTB, bij lijntypen de  soorten: voor autocad lin, SHX, SHP en voor microstation: rsc.

**Comment by MvanderHulst** [comment]
en ik mis de algemene 'OBJECTEN' nog. dus de lagenstructuur

**Comment by MvanderHulst** [comment]
@ElisabethKloren geen actie voor mij t.b.v. 5.1

**Comment by ElisabethKloren** [comment]
> Member



> toe te voegen: de plotinstellingen CTB, bij lijntypen de soorten: voor autocad lin, SHX, SHP en voor microstation: rsc.

dit is te veel detailniveau, heb ik weggelaten

**Comment by ElisabethKloren** [comment]
![NLCS architectuur](https://github.com/nl-digigo/NLCS/assets/48585720/9edca967-c0eb-4b3d-a10c-a4adc2acf902)
