### ISSUE TITLE
Foutjes Mapping BGT NLCS 5.0

### ISSUE THREAD

**Issue by NielsNederpel** [nl-digigo/NLCS#163]
In de bgt mapping zijn paar foutjes gevonden, mogelijk zijn deze al doorgegeven.

het is GRAS- EN KRUIDACHTIGEN
Geometrie typen kloppen niet
INSTALLATIE 1616 BGT-Geometrytype S, BIM-Geometrytype G
INSTALLATIE 4036 BGT-Geometrytype S, BIM-Geometrytype G
INSTALLATIE 4037 BGT-Geometrytype S, BIM-Geometrytype G

**Comment by MvanderHulst** [comment]
Het is mij niet duidelijk wat niet eventueel voor aangepast moet worden. Kan dit verhelderd worden, of is dit database werk?

**Comment by MvanderHulst** [comment]
@ElisabethKloren betreft een database aanpassing in de bgt mapping, deze is voor jou. ;-)

**Comment by ElisabethKloren** [comment]
@NielsNederpel ik snap het niet, in de bgt mapping staan geen geometriën, deze installaties hebben wel alleen een verwijzing naar laagnamen niet naar symbolen, dus dan klopt de mapping toch?

**Comment by ElisabethKloren** [comment]
spelfout wel aangepast
