### ISSUE TITLE
NLCS 5.0 namen

### ISSUE THREAD

**Issue by NielsNederpel** [nl-digigo/NLCS#164]
Ten aanzien van de hoofdgroep IE in NLCS 5.0 vragen/opmerkingen over deze laagnamen:
*-**-IE-MEUBILAIR_CAMERA-G/S
*-**-IE-MEUBILAIR_WEGMEUBILAIR_CAMERA-G/S
Wat is het verschil?
En ook:
*-**-IE-MEUBILAIR_FONTEIN-G/S
*-**-IE-MEUBILAIR_WEGMEUBILAIR_FONTEIN-G/S
En:
*-**-IE-KUNSTOBJECT-G/S
*-**-IE-MEUBILAIR_WEGMEUBILAIR_KUNSTWERK-G/S
Worden hier een beeld en een miniatuurbrug bedoeld of zijn deze voor identiek type objecten? Wellicht meubilair op een kunstwerk?

Wat is algemeen het belang/verschil tussen de lagen
*-**-IE-MEUBILAIR-*****-G/S
En
*-**-IE-MEUBILAIR_WEGMEUBILAIR_*****-G/S
?

Is onderscheid in
*-**-IE-MEUBILAIR_WEGMEUBILAIR_*****-G/S
En
*-**-IE-MEUBILAIR_WATERWEGMEUBILAIR_*****-G/S
noodzakelijk en niet vanzelfsprekend?

De laag *-**-IE-MEUBILAIR_WEGMEUBILAIR_PARKEERMAATREGEL-G/S omvat symbolen als een parkeerbeugel, poef, betonbol. Dit zijn ANTI-parkeermaatregelen. Met een parkeermaatregel faciliteer je juist (tijdelijk) parkeren bij bijv. een evenement, of t.b.v. invaliden.

*-**-IE-BORD-G/S
*-**-IE-MEUBILAIR_WEGMEUBILAIR_VERKEERSTEKEN-G/S
*-**-IE-MEUBILAIR_WEGMEUBILAIR_VERKEERBORD-G/S
Zijn deze lagen alle 3 nodig of kunnen deze vervangen worden door bijv. *-**-IE-VERKEERSTEKEN-G/S

En in lijn met deze:
*-**-VV-VERKEERSTEKEN-G/S
*-**-VV-VERKEERSTEKEN_BORD-G/S
NB.: geen *-**-VV-BEWEGWIJZERING -G/S
*-**-VW-BEWEGWIJZERING_BORD-G/S
*-**-VW-VERKEERSTEKEN_BORD-G/S

Zijn aparte lagen voor bewegwijzering nodig? Zijn bewegwijzering niet ook verkeerstekens? Kent VV geen bewegwijzering?

**Comment by ElisabethKloren** [comment]
uitwerken tot concreet voorstel

**Comment by MvanderHulst** [comment]
In overeenstemming met issue #94 , lijkt het mij verstandig om de verdeling van het meubilair te herzien.
OF alles op 1 hoop, of 2 verdelingen tussen WEG en WATER meubilair...
Een aantal zaken zijn beide toepasbaar, deze zijn destijds een niveua hoger geplaatst.

Volgens de oude gedachten zou het zo moeten zijn dat:
*--IE-MEUBILAIR_WEGMEUBILAIR_CAMERA-G/S kan komen te vervallen.
*--IE-MEUBILAIR_WEGMEUBILAIR_FONTEIN-G/S kan komen te vervallen.

*--IE-MEUBILAIR_WEGMEUBILAIR_KUNSTWERK-G/S kan komen te vervallen.
tevens zou dit KUNSTOBJECT moeten heten. als in, een standbeeld o.i.d.

Het onderscheid van mij inderdaad zou mogen vervallen. je weet tenslotte wat je tekent.
Wanner ik kijk naar de objecten in de lijst van ‘parkeermaatregel’, is dit een heel vreemd hoofdstuk.
 
PARKEERMAATREGELEN:
SIE-WEG_PARKEERMAATREGEL_GENIEBLOK
SIE-WEG_PARKEERMAATREGEL_HUNNENBED
SIE-WEG_PARKEERMAATREGEL_SCHAMPBLOK_650X450X400
SIE-WEG_PARKEERMAATREGEL_SCHAMPBLOK_650X500X400

Uitgaande van ‘mijn waarheid’ vallen onderstaande elementen onder ‘inrichtingselement’/’straatmeubilair’
 
![image](https://github.com/nl-digigo/NLCS/assets/144665595/c02136ba-4a43-474c-9fd5-b265a63f4d1d)

SIE-WEG_PARKEERMAATREGEL_POEF_VIERKANT
SIE-WEG_PARKEERMAATREGEL_POEF_ROND
SIE-WEG_PARKEERMAATREGEL_BETONBOL
SIE-WEG_PARKEERMAATREGEL_BETONBOL_VIERKANTENVOET
SIE-WEG_PARKEERMAATREGEL_BETONCARRE_300X300
SIE-WEG_PARKEERMAATREGEL_PARKEERBEUGEL

Vervolgens:
 
![image](https://github.com/nl-digigo/NLCS/assets/144665595/60652080-7f75-4876-bb38-dc4ba47461ab)

GENIEBLOK		=> exoot van Giverbo, vervallen? Anders onder antiparkeer.
HUNNENBED		=> bestaat niet		=> JUMBOBLOKKEN
SCHAMPBLOK_650X450X400
SCHAMPBLOK_650X500X400
BETONBOL_PYRAMIDE	=> naam herzien, is geen betonbol.

**Comment by MvanderHulst** [comment]
Tot slot voor de borden.
Verdelingen die je volgens mij nodig hebt:
- verkeersbord
- straatnaambord
- bewegwijzering
- verkeersbordpaal

aanvullend:
- reclamebord
- informatiebord

Verkeersborden zijn losse borden.
Daarbij moet je kunnen kenmerken of er een verkeersbordpaal bij geplaatst moet worden.
Zoniet, dan zou er een lichtmast bij moeten staan.

Verkeersbord is een bord t.b.v. de verkeersveiligheid
bewegwijzering is een bord welke bestuurders aangeeft welke kan op wat is.
straatnaambord is welbekend.

**Comment by NielsNederpel** [comment]
> Het onderscheid van mij inderdaad zou mogen vervallen. je weet tenslotte wat je tekent.
Wanner ik kijk naar de objecten in de lijst van ‘parkeermaatregel’, is dit een heel vreemd hoofdstuk.

ja in principe akkoord...echter...uiteraard kun je dan alleen nog maar alle meubilair op óf MEUBILAIR-S  óf het speciefieke object (bijvoorbeeld MEUBILAIR_CAMERA-S) tekenen en dus filteren,...een scheiding/filtering tussen MEUBILAIR_WATER en MEUBILAIR_WEG is dan niet meer mogelijk.

**Comment by MvanderHulst** [comment]
@NielsNederpel wat mij betreft is dat ook helemaal niet nodig.
Er staat of hangt 'iets'... of het nu voor een water of weggebruiker is bedoeld vindt ik niet heel relevant om in de laagnaam terug te vinden.

**Comment by ElisabethDeVries** [comment]
#867 neemt de resterende punten over voor NLCS 6.0, die nog niet in 5.2 verwerkt zijn

**Comment by ElisabethDeVries** [comment]
[[Release note]]  In hoofdgroep IE zijn de volgende aanpassingen gedaan, waarbij nieuwe objecten rechtstreeks onder MEUBILAIR geplaatst worden en niet meer met subobjecten WATERMEUBILAIR/WEGMEUBILAIR omdat deze indeling in NLCS 6.0 komt te vervallen in het kader van vereenvoudiging van de standaard.
Dubbele objecten vervallen: MEUBILAIR_WEGMEUBILAIR_CAMERA; MEUBILAIR_WEGMEUBILAIR_FONTEIN; MEUBILAIR_WEGMEUBILAIR_DRINKBAK.
Het object MEUBILAIR_WEGMEUBILAIR_PARKEERMAATREGEL vervalt; hiervoor in de plaats komt het object MEUBILAIR_ANTIPARKEERVOORZIENING. De symbolen voor de antiparkeervoorziening zijn in naamgeving en uiterlijk aangepast om overeen te komen met gangbare vormen en naamgeving.

In hoofdgroep VW zijn de volgende aanpassingen gedaan
Het object VERKEERSTEKEN_BORD_STRAATNAAM is toegevoegd.
