### ISSUE TITLE
Linetype tekenbladgrens

### ISSUE THREAD

**Issue by NielsNederpel** [nl-digigo/NLCS#165]
De linetype van 'tekenbladgrens' is onlogisch opgezet, waardoor deze niet symetrisch getoond wordt in AutoCAD.
Juiste definitie zou moeten zijn:
*AL-TEKENBLADGRENS-SO,8
A,5,-1.5,1,-1.5,1,-1.5

**Comment by MvanderHulst** [comment]
Controle en correct bevonden:

*AL-TEKENBLADGRENS-SO,8
A,5,-1.5,1,-1.5,1,-1.5

**Comment by ElisabethDeVries** [comment]
omdat dit issue geen inhoudelijke gevolgen heeft gehad, geef ik dit milestone gebruikersvragen

**Comment by MvanderHulst** [comment]
@ElisabethDeVries 
Dit is wel degelijk een wijziging met inhoudelijke gevolgen.
Nieuwe lijntype:
A,5,-1.5,1,-1.5,1,-1.5

**Comment by ElisabethDeVries** [comment]
@MvanderHulst deze wijziging was niet opgenomen in het 5.1 voorstel, daarom gemist. Ik voeg hem toe bij de lijst van wijzigingen in ALgemeen.

**Comment by ElisabethDeVries** [comment]
[[Release note]] Lijntype AL-TEKENBLADGRENS-SO is aangepast, omdat hij niet goed symmetrisch werd weergegeven.
