### ISSUE TITLE
Arceerpatronen grondwerk, onjuiste benamingen

### ISSUE THREAD

**Issue by NielsNederpel** [nl-digigo/NLCS#166]
NLCS bevat: CUNETZAND en FUNDERINGDZAND als arceerpatroon. Beide bestaand niet. 'zand voor zandbed' is de enigste juiste benaming.
Regulier 'grond' aanvullen is niet aanwezig als betroon. Teelaarde moet aan eisen voldoen en is meestal overkill.
Graag aanvullen en afstemmen aan vaktermen. e.e.a. in relatie tot de RAW

**Comment by ElisabethKloren** [comment]
akkoord, uitzoeken naar concreet voorstel voor aanpassing

**Comment by MvanderHulst** [comment]
zie ook issue #71 voor uitwerking van omgang met 'grond'

**Comment by ElisabethDeVries** [comment]
omdat bij release 5.2 het uitgangspunt is, zo weinig mogelijk laagnamen wijzigen, wordt dit issue onderdeel van release 6.0

**Comment by ElisabethDeVries** [comment]
[[Release note]] Hoofdgroep GW: De term TEELAARDE bestaat niet en wordt vervangen door de bij de RAW gebruikte term TEELGROND. De term ZANDBED wordt vervangen door ZAND omdat in deze hoofdgroep steeds het soort grond of zand wordt genoemd in de laagnaam.

**Comment by ElisabethDeVries** [comment]
zie issue #864 voor de toevoeging van GROND aan de objecten in 5.2
