### ISSUE TITLE
Arceerpatronen grond

### ISSUE THREAD

**Issue by NielsNederpel** [nl-digigo/NLCS#167]
*AGW-WERK_ONTGRAVEN-SOD,grondontgraven
Waarom heet het patroon 'WERK', als bij de toelichting GROND wordt bedoeld?
Graag naar van het pattern aanpassen naar 'GROND_ONTGRAVEN' en idem voor de WERK_AANVULLEN arcering.

**Comment by ElisabethKloren** [comment]
akkoord, verwerken naar concreet voorstel voor aanpassing database

**Comment by MvanderHulst** [comment]
zie ook issue #71 voor uitwerking van omgang met 'grond'

**Comment by ElisabethDeVries** [comment]
dubbel met #71, vandaar op backlog, duplicate label en afgesloten
