### ISSUE TITLE
Arceerpatronen grond versus groen

### ISSUE THREAD

**Issue by NielsNederpel** [nl-digigo/NLCS#168]
Waarom zijn de grondsoorten 'bomengrond' en 'bomenzand' enkel onderdeel van GR. Deze horen in GW thuis.
Tevens staat TEELGROND dubbel in de biebliotheken, zowel bij GR als GW. Beide met een afwijkende presentatie.

**Comment by ElisabethKloren** [comment]
Akkoord, te verwerken naar voorstel voor aanpassing

**Comment by MvanderHulst** [comment]
zie ook issue #71 voor uitwerking van omgang met 'grond'
Voorstel is om ook BOMENZAND en BOMENGROND naar hoofdgroep GW te verplaatsen, waar het thuis hoort.

**Comment by ElisabethDeVries** [comment]
[[Release note]]  In de hoofdgroep GR (groen) zijn nieuwe objecten toegevoegd onder PLANTGATVERBETERING. 
TEELGROND, GROND, BOMENGROND EN BOMENZAND komen te vervallen in hoofdgroep GR, en toegevoegd in hoofdgroep GW (Grondwerken). 
Wel zijn de objecten PLANTGATVERBETERING_BOMENGROND en PLANTGATVERBETERING_BOMENZAND toegevoegd onder GR.

**Comment by ElisabethDeVries** [comment]
reopen voor herbeoordeling 5.2
