### ISSUE TITLE
Arcering funderingen dubbele definities?

### ISSUE THREAD

**Issue by NielsNederpel** [nl-digigo/NLCS#169]
AVH-FUNDERING_GRAN_* en AVH-FUNDERING_GRANULAAT_* staat volledig dubbel in de bibliotheek, waarbij de ene serie GRAN in de naam heeft en de andere volledig GRANULAAT. Presentatie is identiek.
Verschil is dat de ene serie een SOD en de andere een SO is. Niet consequent met de hele bieb en ook niet nodig lijkt mij.

**Comment by MvanderHulst** [comment]
De standaard NLCS kent enkel de SOD arceringen.
Alle arceringen SO zijn extra aanvullingen vanuit Arkance in InfraCAD.
Wel is binnen NLCS dit verschil te zien in naamgeving:
![image](https://github.com/nl-digigo/NLCS/assets/144665595/00be7ec5-47e9-4367-85f6-563a8e8f9aa5)

Voorstel is om dit aan te passen naar GRANULAAT, dat is tenslotte ook waar een gebruiker naar gaat zoeken en niet naar 'GRAN'.
Ongeacht de keuze, moet ARKANCE zijn extra bibliotheek hier op controleren.

Aanvullend:
De arceringen GRAN_MENG_01 en GRAN_MENG_02 zijn zeer slecht zichtbaar.
Hiervoor graag de bestaande patronen van FUNDERING_01 en FUNDERING_02  voor toepassen en de deze 2 algemene arceringen laten vervallen.

**Comment by ElisabethDeVries** [comment]
[[Release note]] In de hoofdgroep VH zijn de namen va alle arceringen AVH -FUNDERING_GRANULAAT ingekort naar GRAN om te passen bij de maximale padnaam voor arceringen #651; arceringen GRAN_MENG_01 en GRAN_MENG_02 vervallen omdat deze niet goed leesbaar zijn.
