### ISSUE TITLE
#1663 lijnen van het ELEMENT GD  moeten worden getekend met één pen dikker (binnen dezelfde lijngroep) 

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#17]
#1663	"3.5.2.f. Algemeen geldt dat lijnen van het ELEMENT GD (Geometrie in doorsnede) moeten worden getekend
met één pen dikker (binnen dezelfde lijngroep) dan in de NLCS objectentabellen is aangegeven voor
het ELEMENT G (Geometrie in aanzicht).
Op deze regel mag een uitzondering worden gemaakt daar waar lijnen dichtvloeien bij het afdrukken
(bijvoorbeeld bij damwanden en staalprofielen). In dergelijke gevallen mag juist een pendikte dunner
worden gebruikt. Ook voor het tekenen van wapeningstaven geldt een uitzondering: hiervoor kan
zowel pendikte 0.5 als 0.7 worden toegepast, ongeacht of het gaat om een aanzicht of een doorsnede
van een wapeningstaaf

Vraag: Na de invoer van NLCS hier enorm veel klachten/vragen over gekregen. Bijna alles binnen wegontwerp vloeit dicht.
Dus de algemene vraag: ""waarom?"""

**Comment by ElisabethKloren** [comment]
NN: dit is geen wijzing m.b.t 5.0 neem ik aan?
dit is toch altijd zo geweest?
ik zet t in ieder geval op de lijst om te bespreken

MH: Bij navraag bij verschillende organisaties is gebleken dat iedereen doorsnedes ‘gewoon’ als ‘Standaard’ geometrie tekent, omdat de ‘Doorsnede’ presentaties niet werkbaar zijn.

**Comment by ElisabethKloren** [comment]
michel zegt: Graag aanpassen, onwerkbare aanvulling

**Comment by ElisabethKloren** [comment]
Te besluiten EC 2023-11-09 
Element GD wel of niet andere lijndikte geven ten opzichte van G
Moet dan dit hele element "weg" uit de tabellen / laagnamen? Een doorsnede is gewoon een ander soort tekening, of moet dat wel in de laagnaam worden gezet? (dit snap ik even nog niet helemaal, mijn fout waarschijnlijk)
Gaat het hier om "variant lijnstijlen" en moeten we dat documenteren?
Wat wordt verwacht van een software-implementatie?

**Comment by ElisabethKloren** [comment]
EC 2023-11-09
besluiten:
Lineweight G en GD hetzelfde maken > documentatatie aanpassen

**Comment by ElisabethKloren** [comment]
De tekst is nu: *  Lijnen van het ELEMENT GD (Geometrie in doorsnede) mogen een lijndikte -GD mag 1 factor dikker of dunner dan -G hebben. De keuzevrijheid moet zorgen voor goed leesbare tekeningen: daar waar lijnen dichtvloeien bij het afdrukken (bijvoorbeeld bij damwanden en staalprofielen) teken je bijvoorbeel dunner. Aanzichten of doorsnedes van Wapeningsstaven teken je zo, dat deze goed zichbaar zijn, bijvoorbeeld met pendikte 0.5 of 0.7.
* lijntype -GD mag continuous voor gebruikt worden, maar is niet verplicht als dit de tekening onduidelijker maakt.


Het staat hier in de documentatie: https://nl-digigo.github.io/NLCS/requirementscadmodels/#lijndikte

**Comment by SanderNijhof** [comment]
Staat het nu niet te specifiek/uitsluitend in de Formele Beschrijving? Nu is o.a. de tekst _"Ook voor het tekenen van wapeningstaven geldt een uitzondering: "_ opgenomen. Is dat altijd zo of indien het de leesbaarheid van de tekening ten goede komt?

Kan het niet beter algemener omschreven worden? Bijv. "**In de regel geldt dat lijnen van het ELEMENT GD (Geometrie in doorsnede) moeten worden getekend met één pen dikker (binnen dezelfde lijngroep) dan in de NLCS objectentabellen is aangegeven voor het ELEMENT G (Geometrie in aanzicht). Ook hier geldt dat een andere lijndikte binnen dezelfde lijngroep gekozen mag worden als dit de leesbaarheid van de tekening ten goede komt.**"

**Comment by MvanderHulst** [comment]
Ook controleeren: 3.5.1.e en 3.5.9

**Comment by MvanderHulst** [comment]
@ElisabethKloren wil jij deze verwerken in de documentatie

**Comment by ElisabethKloren** [comment]
> In de regel geldt dat lijnen van het ELEMENT GD (Geometrie in doorsnede) moeten worden getekend met één pen dikker (binnen dezelfde lijngroep) dan in de NLCS objectentabellen is aangegeven voor het ELEMENT G (Geometrie in aanzicht). Ook hier geldt dat een andere lijndikte binnen dezelfde lijngroep gekozen mag worden als dit de leesbaarheid van de tekening ten goede komt.

ik heb dit voorstel overgenomen

**Comment by MvanderHulst** [comment]
@ElisabethKloren en @SanderNijhof het overgenomen voorstel is weer de oude situatie.
In de EC is juist besproken dat we dit anders willen

EC 2023-11-09
besluiten:
Lineweight G en GD hetzelfde maken > documentatatie aanpassen

Tekst zou moeten zijn:

In de regel geldt dat lijnen van het ELEMENT GD worden getekend met de pen die in de NLCS objectentabellen is aangegeven voor het ELEMENT G (Geometrie). Een andere lijndikte binnen dezelfde lijngroep gekozen mag worden als dit de leesbaarheid van de tekening ten goede komt.

**Comment by ElisabethKloren** [comment]
check, ik pas de documentatie aan.

**Comment by ElisabethDeVries** [comment]
discussie gaat voort voor 6.0 release

Sander: Met de tabel met lijndikten voor NLCS 5.2 stappen we bewust af van het huidige NLCS principe:
Lijndikte 0,25mm mag conform NLCS 5.0 namelijk niet altijd 0.18 of 0,35 zijn:
a.	Lijndikte 0,25mm mag 0,13mm of 0,18mm zijn als 0,25mm oorspronkelijk uitlijngroep 0,50 komt
b.	Lijndikte 0,25mm mag 0,35mm of 0,50mm zijn als 0,25mm oorspronkelijk uitlijngroep 0,25 komt
En lijndikte 0,50mm mag conform NLCS 5.0 ook niet altijd 0,35 of 0,70 zijn:
a.	Lijndikte 0,50mm mag 0,25mm of 0,35mm zijn als 0,50mm oorspronkelijk uitlijngroep 0,50 komt
b.	Lijndikte 0,50mm mag 0,70mm of 1,00mm zijn als 0,25mm oorspronkelijk uitlijngroep 1,00 komt

Dat is nu onduidelijk en een ommissie in de NLCS. Wat mij betreft is nieuwe tabel een vereenvoudiging en daarmee een verbetering 😊

De voorgestelde aanpassingen in de tabel voor NLCS 5.2 vragen dan om aanpassing van de Formele Beschrijving 3.5.2 c,f en g plus aanpassing van de (controle)software. 

Michel: Ik heb die toelichtingentabellen voor lijntypes nooit echt goed begrepen.
De nieuwe tabel roept echter ook wel een paar vragen op.

Wat is nu het ‘uitgangspunt’ wanneer nieuwe objecten worden toegevoegd?
Bestaand 0.13, 0.18 of 0.25?
Nieuw 0.25, 0.35 of 0.50?

Zou bij ID.6, de 1 mm, niet 1.00 moeten staan én de kolom voor dunner op 0.70 moeten staan?
Wat is de toegevoegde waarde van de kolom met ‘lijngroep 35’?


“Zou bij ID.6, de 1 mm, niet 1.00 moeten staan én de kolom voor dunner op 0.70 moeten staan?
Wat is de toegevoegde waarde van de kolom met ‘lijngroep 35’?”

Sander:
Ja mee eens, en bij ID5 dunner “0.50” ipv 0.5 en bij dikker “1.00” ipv 1, om het uniform te maken.
En de kolom ‘id’ en ‘microstation’ zijn ook identiek. 

De verwijzing naar lijngroep 35 kan dan beter vervallen, is niet meer van toepassing en vooral verwarrend. 
Lijngroep 35 was alleen relevant en duidelijk geweest als in de objecttabellen alleen lijndikten uit lijngroep35 waren opgenomen, maar daar wordt in de objecttabellen volop van afgeweken zonder vermelding uit welke lijngroep ze komen en welke dikten ze mogen hebben.

Voorstel: Uitgangspunt is dan de opgegeven basiswaarde in de objecttabellen. Dus er mag een lijndikte 1 stap dunner of 1 stap dikker gekozen worden t.o.v. de waarde in de objecttabellen. 

Dit wijkt af van de huidige Formele Beschrijving, maar dat doen de objecttabellen toch al jaren. De Formele Beschrijving kan dan verduidelijkt worden en sluit aan op NEN-ISO 128-2 (dacht ik).
Lijkt mij wel dat als je de pendikte van een object wijzigt, je dit dan voor alle statussen van dat object moet doen. Dus als status B- één pendikte groter wordt, dan moet status N- ook één pendikte groter worden, anders is het verschil te klein of krijgen beide mogelijk dezelfde lijndikte. Daar zou de Formele Beschrijving ook duidelijk in moeten zijn.
