### ISSUE TITLE
 Arceringen GW versus VH-fundering

### ISSUE THREAD

**Issue by NielsNederpel** [nl-digigo/NLCS#170]
Waarom bestaat er een arcering voor ZAND/CUNETZAND en FUNDERINGSZAND in hoofdgroep GW en is er ooknog een definitie voor ZAND in VH-Funderingen? allemaal erg dubbelop.

**Comment by ElisabethKloren** [comment]
<img width="318" alt="GW zand" src="https://github.com/nl-digigo/NLCS/assets/48585720/e8d1f018-4099-4986-896d-197851afc28c">
<img width="340" alt="verharding-zand" src="https://github.com/nl-digigo/NLCS/assets/48585720/a144912a-9a17-4f56-aeec-3f7a2d8346c9">

**Comment by ElisabethKloren** [comment]
is er een ander werkproces dan dat van het ontwerpen van de fundering van een weg, waarbij ook funderingszand gebruikt wordt? Want ik kan me voorstellen dat een wegontwerper het zand in zijn lijstje met funderingen wil hebben staan;

Ik zie dat bij NLCS de neiging bestaat om een hoofdgroep te maken voor een specifiek specialisme, waarbij objecten die in meer specialismen voorkomen dubbel zijn. Dat hoeft niet erg te zijn > als informatiekundig maar duidelijk is dat het om hetzelfde object gaat.

**Comment by MvanderHulst** [comment]
Voor deze discussie schaar ik mij zeer sterk achter alle wettelijke verplichtingen binnen de 'Milieu/Bodem' wereld en aanvullend de RAW systematiek.
Binnen de GWW is het ZEER gebruikelijk dat ZAND wordt bestempeld als 'GRONDWERK' en niet als FUNDERING.

voor bodembemonstering is zand/klei/grond allemaal dezelfde behandeling.
Voor FUNDERINGSMATERIAAL, lees: potentieel asbestverdacht gelden andere normen.

Ook in een bestek staat het leveren, aanbrengen en verwerken van ZAND onder grondwerk, waarbij zand-voor-zandbed de functie 'grondverbetering' krijgt, wat vaak wordt beschreven als 'fundering'.

Aanbrengen van funderingsmateriaal is ook in de RAW-systematiek een hele andere opgave met andere regels.

dus ja.
ZAND hoort in de hoofdgroep GRONDWERK
Fudneringen staat prima onder verhardingen.

Als we kijken naar de smaken in ZAND, kloppen deze ook niet.
De soorten die bestaan zijn: zie ook issue #166 

- ZAND
- ZAND voor ZANDBED
- DRAINEERZAND (drain of drainagezand bestaat formeel ook niet)

**Comment by ElisabethDeVries** [comment]
in issue #166 staan de voorstellen voor wijzigingen van hoofdgroep GW.
Deze issue is voor verwerking van wijzigingen in VH
