### ISSUE TITLE
Kleurgebruik arceringen

### ISSUE THREAD

**Issue by NielsNederpel** [nl-digigo/NLCS#171]
Alle arceringen worden 'zwart' afgedrukt.
Enkel de arceringen in 'verhardingen' worden grijs geplot.
Waarom dit onderscheid? Toont heel vreemd in een dwarsprofiel.

**Comment by MvanderHulst** [comment]
Bekend probleem, hebben wij lokaal opgelost.
Probleem zit in de volgende objecten;
FUNDERING
FUNDERING_BIMS
FUNDERING_EPS
FUNDERING_GRANULAAT
FUNDERING_GRANULAAT_BETON
FUNDERING_GRANULAAT_MENG
FUNDERING_GRANULAAT_MENG_HYDRAULISCH
FUNDERING_SCHUIMBETON
FUNDERING_SLAKKEN
FUNDERING_SLAKKEN_AVI
FUNDERING_SLAKKEN_HOOGOVEN
FUNDERING_ZAND
FUNDERING_ZANDCEMENTSTABILISATIE
HERSTRATEN
KANTOPSLUITING
KANTOPSLUITING_LEICONBLOK
OPENVERHARDING_TEGEL_ZINLOOS GEWELD TEGEL
VERHARDING
VERHARDING_GLAS
VERHARDING_HALFOPEN
VERHARDING_OVERIG
KNIPLIJN

Aanvullend heeft Arkance dit ook in de Extra bibliotheek zitten bij een aantal OBJECTEN
Arkance, graag even nalopen!
