### ISSUE TITLE
Hondentoilet in 'GR'

### ISSUE THREAD

**Issue by NielsNederpel** [nl-digigo/NLCS#172]
In de hoofdgroep GROEN staat 'hondentoilet'. Dit is niet groen maar een functie. Pas meer onder 'OG'.

**Comment by ElisabethKloren** [comment]
is wel logisch vanuit degene die tekent, toch? Je ontwerpt het groen en daar hoort dan een hondentoilet bij?

**Comment by MvanderHulst** [comment]
Neen, niet logisch.
Je ontwerp GROEN, als bomen, struik, gras e.d. zaken die je kan bestellen.
HONDENTOILET is een resultantie, een functie van een gebied. dat mag in OG geplaatst worden.

Vaak is een 'hondentoilet' een samenstelling uit verschillende kantopsluitingen, met daartussen zand.

OBJECTEN en FUNCTIES niet door elkaar laten lopen.

**Comment by ElisabethDeVries** [comment]
heropenen, deze is voor 6.0
