### ISSUE TITLE
Maaiveld in Groen

### ISSUE THREAD

**Issue by NielsNederpel** [nl-digigo/NLCS#173]
Maaiveld is een 'Grondwerk' term, welke gelukkig ook in GW terug komt. Ook staat deze in groen waar hij m.i. niet thuis hoort.
Voelt een beetje als een 'pan' indelen bij servies.

**Comment by MvanderHulst** [comment]
Voorstel:
De lijn MAAIVELD wordt enkel gebruikt bij het tekenen van dwarsprofielen.
Hierbij is het een tekentechnisch onderdeel van het grondwerk.
Indelen in GW en verwijderen uit GR.

Let op!
Presentatie van MAAIVELD heeft een conflict met de tot nu toe afgedwongen presentatie van GD lagen.
dit goed controleren bij alle aanpassingen.
Zie ook issue. #18

**Comment by ElisabethDeVries** [comment]
[[Release note]] Het object MAAIVELD is verwijderd uit de hoofdgroep GRoen, dit object was dubbel met het object in GrondWerken waar het thuis hoort.
