### ISSUE TITLE
Voorstel: lijntypes haag

### ISSUE THREAD

**Issue by NielsNederpel** [nl-digigo/NLCS#174]
Graag zou ik het standaard lijntype voor de haag als continuous zien met variant 01 02 en 03 met de afwijkende lijntypes.
Veel gebruikers tekeken de haag als 'continuous' lijn met een global width in plaats van de hartlijn. Huidige lijntype voldoet hiervoor voor vele niet.

**Comment by MvanderHulst** [comment]
![image](https://github.com/nl-digigo/NLCS/assets/144665595/d970882a-2eed-4a32-8d52-c639b0e12d06)

**Comment by ElisabethDeVries** [comment]
[[Release note]] Het lijntype voor HAAG is veranderd naar CONTINUOUS; daarnaast blijven de drie bestaande varianten HAAG1, -,2 en -3 bestaan om verschillende soorten hagen te kunnen onderscheiden op de tekening.

**Comment by MvanderHulst** [comment]
@ElisabethDeVries 
In het voorstel GR is het vervallen lijntype voor HAAG niet goed toegekend.

**Comment by ElisabethDeVries** [comment]
> [@ElisabethDeVries](https://github.com/ElisabethDeVries) In het voorstel GR is het vervallen lijntype voor HAAG niet goed toegekend.

heb ik aangepast
