### ISSUE TITLE
Arcering bomengranulaat

### ISSUE THREAD

**Issue by NielsNederpel** [nl-digigo/NLCS#175]
Arcering en objectdefinitie bomengranulaat ontbreekt.

**Comment by MvanderHulst** [comment]
Voorstel:
![image](https://github.com/nl-digigo/NLCS/assets/144665595/2c0bfe4a-b323-4ca5-a56d-9596d708cd09)

Is een funderingssoort. dus onder VH-Fundering onderbrengen.

*AGR-BOMENGRANULAAT-SO,bomengranulaat
000.00000,0.25,0.75,4.00000,2.00000,1.00000,-9.00000
018.43495,0.75,-1.25,4.42719,0.63246,1.58114,-30.04164
071.56505,0.25,0.75,0.00000,-3.16228,1.58114,-1.58114
090.00000,0.75,-1.25,4.00000,2.00000,1.00000,-9.00000
108.43495,1.25,0.75,4.42719,0.63246,1.58114,-30.04164
161.56505,-0.75,0.25,0.00000,-3.16228,1.58114,-1.58114
180.00000,-0.25,-0.75,4.00000,2.00000,1.00000,-9.00000
198.43495,-0.75,1.25,4.42719,0.63246,1.58114,-30.04164
270.00000,-0.75,1.25,4.00000,2.00000,1.00000,-9.00000
288.43495,-1.25,-0.75,4.42719,0.63246,1.58114,-30.04164

**Comment by ElisabethDeVries** [comment]
[[Release note]] In de hoofdgroep GR (groen) zijn de ontbrekende objecten PLANTGATVERBETERING._BOMENGRANULAAT en PLANTGATVERBETERING._SANDWICHCONSTRUCTIE toegevoegd.
