### ISSUE TITLE
kaderrand

### ISSUE THREAD

**Issue by NielsNederpel** [nl-digigo/NLCS#183]
In het kader A3.0 (A3 hoog A0 lang) wordt de binnenkaderrand heeel breed als deze op de sheet/layout komt. Er zit een rare schaal, breedte van een lijn in. Dit is allemaal niet nodig. Gewoon de dikte van een lijn regelen met de Width van een level/laag?
Wellicht de andere kaders ook herstellen?

**Comment by NielsNederpel** [comment]
Als ik de bronsymbolen na kijk zie ik niks geks/anders tov van andere kaders
Degene die ik gecontroleerd heb hebben allen een harde lijndikte van 0.50

Volgens de formele beschrijving moet dit echter zelfs 0.70 zijn! 
Er lijkt dus sowieso iets niet te kloppen (of de omschrijving of het symbool)

**Comment by NielsNederpel** [comment]
toevoeging vanuit melder bij oorspronkelijke ticket:

Ik maak me niet heel druk om de dikte. Een glitch ook niet. Maar als ik en een collega het tegelijk ervaren dan is dat geen toeval. Het lukte ons alleen bij dat kader en niet bij een ander.

In de bijlage de bibliotheek (dgn) met de cell: SAL-TEKENBLAD_A3.0-SO
[Optimize_Plot.zip](https://github.com/nl-digigo/NLCS/files/13266085/Optimize_Plot.zip)


Ik heb het voorbeeld VANDAAG niet meer en kan het niet reproduceren. Wel weet ik dat zowel ik als mijn collega er op hetzelfde moment last van hadden.
De binnenkaderrand (licht roze hierboven) was ineens zo breed dat er een smalle zichtbare strook in het kader over bleef.


![kaderrand](https://github.com/nl-digigo/NLCS/assets/143591987/75e9a849-a742-4ae2-a77d-010f9ded980a)

De Scale, Start Width Constant Width waren een factor 200 groter. Dat was toevallig ook de schaal van de tekening.
Als gebruiker snap ik niet dat er een dikte en schaal en aparte dikte aan dit element hangt. Het is allemaal geregeld bylevel/bylayer. Zelfs in AutoCAD is dat niet nodig.

**Comment by SanderNijhof** [comment]
@NielsNederpel Ik weet wel dat er in eerdere Optimize versies meerdere lijnstijlen zaten met de naam 'CONTINUOUS' waarvan enkele verschillende vaste breedten hadden (waarschijnlijk bij conversie gebeurd). Sommige zo breed dat je hele scherm zwart wordt. In de éne tekening gaat het goed met de lijndikte, in een andere tekening niet. Het is maar net welke versie van de lijnstijl 'CONTINUOUS' als eerste in de dgn toegepast en opgeslagen wordt. 
De beste oplossing daarvoor is om in alle lagen de lijnstijl 'CONTINUOUS' te vervangen door lijnstijl '0'. In het bestand  [Optimize_Plot.zip](https://github.com/nl-digigo/NLCS/files/13266085/Optimize_Plot.zip) van de melder heeft de melder dat al gedaan.

**Comment by MvanderHulst** [comment]
Als ik de kaders bekijk, is de algemene conclusie dat deze lijnen niet 'ByLayer' staan, maar een override met een LineWeight van 0.50 mm.
![image](https://github.com/nl-digigo/NLCS/assets/144665595/c32ec070-36f8-43b5-9fc9-a925a9572665)

Het OBJECT:
X-XX-AL-TEKENBLAD_KADER_CENTERMARKERING-G
Heeft een lineweight van 0.25, dit zou dus zonder gevolgen aangepast kunnen worden naar 0.50
Er is geen andere plek waar dit object gebruikt wordt.

Het OBJECT:
X-XX-AL-TEKENBLAD_KADER-G
heeft ook een lineweight van 0.25, maar wordt WEL op verschillende plekken toegepast.
Om de buitenrand naar 0.50 te corrigeren, zou dus een nieuw OBJECT gemaakt moeten worden met een lineweight van 0.50.
Als de Formele beschijving wordt gevolgd, moet dit zelf een rand van 0.70 zijn.

De afmetingen komen uit de NEN-EN-ISO 5457:1999. Deze is nog WEL actueel.
Heeft iemand deze, zodat de maat gecontroleerd kan worden?
Het zou natuurlijk kunnen dan de 0.70 een typfout is?

Acties:
NEN controleren
Spoor 1: FB aanpassen en nieuw OBJECT maken met lineweight 0.50 en alle kaders nalopen, zodat alles BYLAYER komt te staan.
Spoor 2: Nieuw OBJECT maken met lineweight 0.70 en alle kaders nalopen, zodat alles BYLAYER komt te staan.
e.e.a. afhankelijk van de NEN-Norm.

**Comment by ElisabethKloren** [comment]
NEN-EN-ISO 5457:1999 blijft actueel, maar is aangevuld met NEN-EN-ISO 5457:1999/A1:2010

ik heb 'm aangevraagd, even geduld

**Comment by ElisabethKloren** [comment]
Cf. NEN-EN-ISO 5457:1999: Het kader voor de tekenruimte wordt gevormd door doorlopende lijnen met een dikte van 0,7 mm .

**Comment by ElisabethDeVries** [comment]
Release note verplaatst naar onderliggende issue #845

**Comment by ElisabethDeVries** [comment]
reopen voor acceptatie 5.2

**Comment by MvanderHulst** [comment]
@ElisabethDeVries conclusie is onjuist.

Aanvullend op de centermarkering moet ook X-XX-AL-TEKENBLAD_KADER-G opgelost worden.
Deze beide randen staan op deze layer:
<img width="656" height="473" alt="Image" src="https://github.com/user-attachments/assets/9dd4195a-67c9-4a4e-8919-999d19de5621" />

De binnenrand heeft een lineweight override naar 0.50.
De buitenrand is ByLayer, wat resulteerd in een lineweight van 0.25.
Voor de binnenrand dient dus een nieuw object aangemaakt te worden met een lineweight van 0.50

Vervolgens dienen álle kadersymbolen bijgewerkt te worden naar een nieuwe versie.

**Comment by ElisabethDeVries** [comment]
> Voor de binnenrand dient dus een nieuw object aangemaakt te worden met een lineweight van 0.50
> 
> Vervolgens dienen álle kadersymbolen bijgewerkt te worden naar een nieuwe versie.

@MvanderHulst is dat niet gebeurd in 5.1? Ik dacht dat jij nieuwe symbolen had aangeleverd? Of moeten we deze actie oppakken bij 6.0?

**Comment by MvanderHulst** [comment]
@ElisabethDeVries de nieuwe symbolen hebben enkel een herziene naam en de 'ByLayer' eigenschap aangepast zodat de overrides eruit zijn. Deze issue is hierin nog niet verwerkt.
