### ISSUE TITLE
Opstellen toelichting bij huidige versie Stedelijk Spoor, focus op tram

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#188]
Opstellen toelichting bij huidige versie Stedelijk Spoor, focus op tram 

actie: Marco & Erwin & Paul

**Comment by HarmdHerripon** [comment]
Besproken 12-12-2023: Nog geen voortgang. De bedoeling om een korte alinea te schrijven voor de release-notes.

**Comment by ehensing** [comment]
22-01-2024:  hieronder een concept tekst voor de release-notes

NLCS stedelijke spoor lagen betreft een 1e release. De lagen zijn opgezet voor spoorse infra in stedelijke omgeving met name gericht op tram. De lagen voor metro en lightrail zullen in later stadium toegevoegd.
De lagen zijn onderverdeeld in 3 disciplines spoor , bovenleiding en wisselaansturing.
De lagen voor discipline spoor komen voor namelijk in hoofdgroep SB terecht. De lagen voor bovenleiding en wisselaansturing zullen voor namelijk in hoofdgroep IS terecht komen. Tevens is gekeken waar lagen eventueel in de huidige NLCS structuur passen en daar geplaatst.

**Comment by HarmdHerripon** [comment]
Besproken 29-01-2024: Wat vindt de groep van de tekst van Erwin?

Tekst aangepast naar:
NLCS stedelijke spoor lagen betreft een 1e release. De lagen zijn opgezet voor spoorse infra in stedelijke omgeving met name gericht op tram. De lagen voor metro/lightrail zullen in later stadium worden toegevoegd.
De lagen zijn onderverdeeld in 4 hoofdgroepen Spoorbouw (SB), Energievoorziening (EV)=Nieuw, Installatie Spoor (IS) (=wisselaansturing en -verwarming), Verkeersmaatregelen Spoorweg (VS) (=seinen, etc)
Tevens is gekeken waar lagen eventueel in de huidige NLCS structuur passen en zijn daar geplaatst.

Discussie om hoofdgroep EV Energievoorziening te maken -> bespreken met Elisabeth

**Comment by HarmdHerripon** [comment]
Besproken 11-03-2024: Erwin bespreekt met Elisabeth om hoofdgroep EV Energievoorziening te maken.

**Comment by HarmdHerripon** [comment]
Besproken 15-04-2024:

Tekst aangepast naar:
NLCS stedelijke spoor lagen betreft een 1e release. De lagen zijn opgezet voor spoorse infra in stedelijke omgeving met name gericht op tram. De lagen voor metro/lightrail zullen in later stadium worden toegevoegd.
De lagen zijn onderverdeeld in 4 hoofdgroepen Spoorbouw (SB), **Energievoorziening Spoor (ES)**=Nieuw, Installatie Spoor (IS) (=wisselaansturing en -verwarming), Verkeersmaatregelen Spoorweg (VS) (=seinen, etc)
Tevens is gekeken waar lagen eventueel in de huidige NLCS structuur passen en zijn daar geplaatst.

**Comment by ElisabethKloren** [comment]
ik heb dit opgenomen in de documentatie
