### ISSUE TITLE
#1638	"Zaagsnede heeft alleen een NIEUW blok gedefinieerd,

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#19]
#1638	"Zaagsnede heeft alleen een NIEUW blok gedefinieerd, geen BESTAAND, TIJDELIJK of VERVALLEN.
Mogen de andere statussen wel door een klant uitbreiding worden toegevoegd of zijn andere statussen helemaal niet toegestaan binnen NLCS 5.0."

**Comment by ElisabethKloren** [comment]
Reactie Expertcommissie: ASFALT_ZAAGSNEDE heeft inderdaad al sinds, in ieder geval, versie 3.1 alleen een status  "nieuw"

In principe mogen er altijd objecten worden toegevoegd, mits er wordt volstaan de de afgesproken regels.
In principe denk ik dus ook dat er statussen aan een object mogen toegevoegd, maar misschien wordt dit toch anders gezien.

**Comment by SanderNijhof** [comment]
kort door de bocht zou ik zeggen dat een object dat in de NLCS-database is opgenomen voor alle statussen moet voorzien. Een zaagsnede kan prima status bestaand hebben. Bijv. als ik aannemer A asfalt laat zagen dan is dit voor de opdrachtnemer B een bestaande zaagsnede op de tekening bij zijn opdracht.

**Comment by ElisabethKloren** [comment]
Sander zegt: Uitkomst is principieel voor de standaard. Het komt vaker voor dat niet alle statussen van een object gedefinieerd zijn.

**Comment by ElisabethKloren** [comment]
EC 2023-11-09 
Besluit: Zaagsnede als object, bij asfalt > die heeft nu alleen status nieuw. We vinden dat dit alle statussen moet kunnen krijgen.

Principieel besluit, een object kan altijd alle statussen krijgen: opnemen in de "tabellen". Als status niet gedefinieerd is, lijnstijl van andere status overnemen. Vervallen > daarvoor is een standaard lijntype

Actie: Overzicht maken van welke objecten extra statussen moeten krijgen

**Comment by SanderNijhof** [comment]
In bijgaande Excel alle lagen waarbij informatie ontbreekt (status, lijnstijl e.d.) . “TERREIN_MILIEUBESCHERMINGSGEBIED” is geel gemarkeerd omdat daar een waarde -1 is ingevuld i.p.v. geldige waarden. 
[NLCS-5.0-OBJECTEN WAARBIJ GEGEVENS ONTBREKEN.xls](https://github.com/nl-digigo/NLCS/files/13307531/NLCS-5.0-OBJECTEN.WAARBIJ.GEGEVENS.ONTBREKEN.xls)

**Comment by MvanderHulst** [comment]
Nalopen volgens voorstel Sander.
Valt mij op dat veel lege velden een BEWERKING zijn, een bewerking zou m.i. geen VERVALLEN status kunnen hebben?

Volgens mij zijn er geen aanvullingen nodig qua bibliotheken, enkel aanpassingen in de database.

**Comment by ElisabethDeVries** [comment]
[[Release note]] Alle NLCS-Objecten krijgen voortaan voor alle statussen visualisaties mee in de database. Een tekenaar kan heel goed zelf besluiten of de status zinvol is. Een voorbeeld is het object ASFALT_ZAAGSNEDE; dit had alleen de status nieuw, en dat lijkt logisch, behalve als werkzaamheden verdeeld worden: als bijvoorbeeld opdrachtnemer A asfalt zaagt dan is dit voor de opdrachtnemer B een bestaande zaagsnede op de tekening bij zijn opdracht.
