### ISSUE TITLE
Stedelijk Spoor: SAP en GIS versus NLCS en CAD

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#192]
Beschrijven wat het probleem is voor de gebruiker, de integratie van GIS en SAP, de relatie met NLCS tekeningen, wat hebben we nodig van de standaard

Gerben, geholpen door Aydemir, Marco, Erwin, Romano zoekt GIS specialist >

**Comment by HarmdHerripon** [comment]
Besproken 12-12-2023: Objectinformatie uit NLCS tekeningen naar GIS en AM-systeem (bijv SAP, Maximo) uitwisselbaar maken (eerste versie)

**Comment by HarmdHerripon** [comment]
Besproken 29-01-2024:  Gerben is nog niet gestart. Issue samenvoegen met #189. Gerben stemt dit af met Elisabeth.

**Comment by ElisabethKloren** [comment]
dan sluit ik dit issue af omdat het probleem  in #189 wordt uitgewerkt
