### ISSUE TITLE
#1637 Naamgeving lijnstijlen

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#20]
#1637	Voor NLCS 5.0 zijn er aanpassingen doorgevoerd voor wat betreft het toestaan van naamgeving van lijnstijlen, deze staan echter tegenstijdig in de standaard. Artikel 3.5.3 Lijntype (linetype) staat de status N toe in de naam van de lijnstijl, Artikel 5.2.4 Naamgeving van lijnstijlen staat deze niet meer toe. Dit is een hiaat in de standaard. Wij en onze klanten maken voor NLCS 4,2 gebruik van N-hoofdgroep-Lijntypenaam namen. Ook in NLCS zijn deze dus meegekomen. Graag een duidelijk aanpassing in de standaard. en dergelijke aanpassingen helderder communiceren! Dit is namelijk alleen met lezen in stukken te achterhalen en nu dus zelfs niet eenduidig, maar is niet in een mechaniek als release notes terug te lezen.

**Comment by ElisabethKloren** [comment]
Reactie Expertcommissie: er zit inderdaad een tegenstrijdigheid in 3.5.3 en 5.2.4.
3.5.3 gelijktrekken met 5.2.4.

**Comment by MvanderHulst** [comment]
Net als symbolen behandelen: geen status is algemeen toepasbaar. bij afwijkende presentatie B V en T toegestaand. N = statusloos.

**Comment by ElisabethKloren** [comment]
Ik heb het artikel https://nl-digigo.github.io/NLCS/requirementscadmodels/#lijntype-linetype aangepast naar de nieuwe manier van werken. Dit komt in de Releasenotes van 5.1 naar voren.
