### ISSUE TITLE
Onderzoeken relatie CAD en GIS

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#206]
Waarom GIS?
1. Voor de beheerders gangbaar: GIS heeft in de Infra sector een prominente rol, vooral in de beheer- en gebruiksfase van objecten wordt GIS volop toegepast om objecten te representeren. 
2. Door de afstemming met GIS wordt het mogelijk om (data) analyses op basis van de NLCS-tekeningen te maken.  

Voor de doorontwikkeling van de NLCS is het wenselijk om inzicht te krijgen in hoe de link tussen CAD en GIS gelegd kan worden.

**Comment by lammerts** [comment]
Nogal een groot issue. Is het nieuws dat Gis en Cad in elkaars verlengde liggen? Ik begrijp ook niet waarom Autidesk en Ersi zo prominent genoemd zouden moeten worden.

**Comment by ElisabethKloren** [comment]
Goed punt, deze tekst zal ik aanpassen zodat het leveranciersonafhankelijk wordt

**Comment by ElisabethKloren** [comment]
Verwerk in een aanzet tot onderzoeksvragen naar een uitwisselformaat voor NLCS in: https://nl-digigo.github.io/NLCS/representations/
