### ISSUE TITLE
COORDINAATPUNT van AL naar ZZ

### ISSUE THREAD

**Issue by SanderNijhof** [nl-digigo/NLCS#208]
Is het logisch om in navolging van PEIL en HOOGTELABEL ook COORDINAATPUNT van hoofdgroep AL naar ZZ te verhuizen?

**Comment by MvanderHulst** [comment]
Helemaal mee eens.
zie ook #384

**Comment by ElisabethDeVries** [comment]
wegens issue #826 wordt dit voorstel meegenomen in NLCS 6.0 en niet in de 5.2 release.
