### ISSUE TITLE
#1632	"1. Kunt u aangeven wat de reden is dat deze verschillende haaientanden niet meer zijn opgenomen?

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#21]
#1632	"1. Kunt u aangeven wat de reden is dat deze verschillende haaientanden niet meer zijn opgenomen?

2. Is het mogelijk dat deze verschillende lagen alsnog worden opgenomen?

3. Deze vraag is iets algemener, maar wij vragen ons af wat de reden is van de nieuwe laagindeling. Zo zijn alle lagen/ objecten die betrekking hebben tot asfaltverhardingen, uitgebreid met de term ‘gesloten verharding’. Alle elementenverhardingen zijn uitgebreid met de term ‘open verharding’. Kunt u ons een korte toelichting geven wat de reden is van deze wijzigingen?"

**Comment by ElisabethKloren** [comment]
1. zie #1624
2. zie #1624
3. De toevoeging van open- en gesloten verharding heeft te maken om de mapping tussen BGT en NLCS tot stand te kunnen laten komen.

**Comment by ElisabethKloren** [comment]
EC 2023-11-09

1e overweging: linetypes verwijderen. haaientanden linetypes zijn slecht toepasbaar, maar dat wordt wel zo gebruikt.
haaientanden zijn "figuraties". Figuraties gaat in stuks, 'strepen' gaan in meters.
2e overweging: dit sluit aan op de RAW
3e overweging: alle markeringen ook haaietanden worden in Microstation wel als lijnstijlen getekend worden. Dit leidt er wel toe, dat ze niet automatisch geteld kunnen worden. Voor uitwisseling met GIS-achtige systemen is dit wel lastig.

Lijkt wel gek omdat langsmarkeringen wel lijnen zijn, maar ja, dat werkt anders.  

alternatief is ze als symbolen tekenen ook omdat de haaientanden in STUKS in bestek komen 

Besluit: figuraties alleen als symbolen opnemen. 
Check op figuraties in de standaard.

**Comment by ElisabethKloren** [comment]
Check op omgekeerd: langsmarkering bijvoorbeeld, alleen als lijnstijlen tekenen, niet als symbolen. Check op aansluiting RAW, opties voor wat een lijn is in RAW (per strekkende meter lijn)

EC 2023-11-09 Check op symbolen die verwijderd moeten worden voor éénduidig tekenen

**Comment by MvanderHulst** [comment]
Wanneer de NLCS standaard wordt gespiegeld aan de RAW-systematiek, welke onderscheid maakt in ‘stuks’ en in ‘meters’, zijn de volgende aanpassingen noodzakelijk:
Te vervallen symbolen:
SVW-MARKERING_STREEP_050050_010
SVW-MARKERING_STREEP_050050_020
SVW-MARKERING_STREEP_11_010
SVW-MARKERING_STREEP_11_015
SVW-MARKERING_STREEP_13_010
SVW-MARKERING_STREEP_13_015
SVW-MARKERING_STREEP_13_020
SVW-MARKERING_STREEP_13_030
SVW-MARKERING_STREEP_13_045
SVW-MARKERING_STREEP_270030_010
SVW-MARKERING_STREEP_270030_015
SVW-MARKERING_STREEP_30270_010
SVW-MARKERING_STREEP_30270_015
SVW-MARKERING_STREEP_31_010
SVW-MARKERING_STREEP_33_015
SVW-MARKERING_STREEP_39_010
SVW-MARKERING_STREEP_39_015
SVW-MARKERING_STREEP_39_030
SVW-MARKERING_STREEP_91_010
SVW-MARKERING_STREEP_91_030
SVW-MARKERING_STREEP_93_010
SVW-MARKERING_STREEP_93_030

Te herziene symbolen:
Waarom is er een verschil tussen ‘PICTOGRAM’ en ‘PIJL’?
Waarom is PICTOGRAM ‘leeg’/hol’ en ‘PIJL’ gevuld, zoals het hoort?

**Comment by ElisabethKloren** [comment]
@MvanderHulst moet er een aanpassing komen in de "objectententabellen" voor wat betreft haaietanden? Ik zie alleen voorstellen van jou over markeringen?

**Comment by MvanderHulst** [comment]
@ElisabethKloren terechte vraag.
In een eerder EC overleg is besproken dat alle lijntypes voor figuraties komen te vervallen én alleen de strepen als lijntype blijven.

Het lijntype voor haaientanden moet dus geheel komen te vervallen uit de database. Het OBJECT moet continuous worden met de juiste symbolen gekoppeld.
