### ISSUE TITLE
#1591 e kleur voor -GV is gelijk aan -G of hoort een -GV object de kleur te krijgen van een -V element (vlakvulling).

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#23]
#1591	In de database zijn kleuren gedefinieerd, nu is het zo dat een object bv element G ook vlakvormend kan zijn en dus de extensie -GV krijgt, welke kleur hoort officieel te worden aangehouden. De kleur voor -GV is gelijk aan -G of hoort een -GV object de kleur te krijgen van een -V element (vlakvulling).

**Comment by ElisabethKloren** [comment]
Reactie Expertcommissie: terechte opmerking, staat niks over in FB om e.e.a. uit te sluiten opnemen in FB

**Comment by ElisabethKloren** [comment]
aanpassen in FB, ook in de database?

**Comment by SanderNijhof** [comment]
Voor zover niet anders vermeld krijgt een object de symbologie van -G. Dus -GV krijgt dezelfde symbologie als element -G.

**Comment by MvanderHulst** [comment]
G is een engineeringslijk. GV is bedoeld voor GIS-mapping. De stelling dat een G element óók vlakvormend kan zijn, is hierbij onjuist. Echter voor de logica zou ik G en GV als gelijke presentatie behandelen. Als GV en V dezelfde kleur krijgen, is dit op het scherm slecht zichtbaar.

**Comment by SanderNijhof** [comment]
Ik kan me voorstellen dat gebruik van de 'V' voor vlakvorming en de tevens de 'V' voor Vlakvulling erg verwarrend is. Is de 'V' voor vlakvulling wel echt nodig? We kennen ook nog de 'O' voor oppervlak, kan die niet ook voor Vlakvulling gebruikt worden?

**Comment by MvanderHulst** [comment]
Dit principe aan mijn cursisten uitleggen is inderdaad een onmogelijke opgave. Ook de diverse leveranciers geven hier een verschillende interpretatie over.
Wanneer ik een BGT import maak, bevat deze bijvoorbeeld standaard allemaal -GV lagen, omdat de geometrie gesloten is. Wanneer ik de FB erop nasla, is dit eigenlijk onjuist en zouden het gewoon -G lagen moeten zijn.

In de FB zou het als volgt beschreven kunnen worden:

Beschrijft de grafische representatie van het getekende type object.
Inrichting openbare ruimte:
Element		Verklaring:		Toelichting:
-	G		Geometrie		Standaard lijnen;
-	A		Arcering			Arceringen van technische aard;
-	S		Symbool			Blocks;
-	O		Oppervlak		Hulplijnen voor hoeveelheden vlakbepaling;
-	M		Maatvoering		Dimensions;
-	T**		Tekst + hoogte		Teksten en aanpijlingen;
-	V		Vlakvulling		Solid arcering voor presentatie doeleinden;

Doorsnedes:
Element		Verklaring:		Toelichting:
-	GD		Geometrie in Doorsnede	Standaard lijnen voor doorsnede (doorgetrokken);
-	AD		Arcering in doorsnede	Standaard arceringen voor doorsnede (fijne schaal);
-	SD		Symbool in doorsnede	Standaard blocks van doorsneden van objecten;


Aanvullingen voor constructief tekenwerk:
Element		Verklaring:		Toelichting:
-	GN		Geometrie Niet zichtbaar	Standaard lijnobject, gestippeld/gestreept;
-	SN		Symbool Niet zichtbaar	Standaard symbool, gestippeld/gestreept;


Aanvullingen voor uitwisseling CAD naar GIS:
Element		Verklaring:
-	GV		Geometrie Vlakvormend
-	SV		Symbool Vlakvormend
-	T**V		Tekst + hoogte Vlakvormend

Snel is dan al duidelijk dat:
- de GV, SV en T**V elementen een speciale behandeling nodig hebben. en ook in tooling niet prominemt aanwezig hoeven te zijn
- Dat de GN en SN enkel voor 'Constructief' van toepassing zijn
- Ook is bekend dat de GD SD en AD zo goed als niet gebruikt worden, omdat de lijntypes te dik zijn en alle lijnen continuous zijn wat niet gewenst is.
- Dat het verschil tussen V en A prima uit te leggen is, als V als 'presentatielagen' worden gebeschouwd.
- Dat het element O eigenlijk enkel een extra hulpvlak is, welke niet geplot hoeft te worden.

**Comment by ElisabethKloren** [comment]
EC 2023-11-09 Beschrijving opnemen in documentatie

**Comment by ElisabethKloren** [comment]
Tekst over de elementen aangepast in https://nl-digigo.github.io/NLCS/requirementscadmodels/#element

GV = kleur van G, opgenomen in https://nl-digigo.github.io/NLCS/requirementscadmodels/#samenvatting-representatie-van-objecten-in-nlcs

**Comment by MvanderHulst** [comment]
FB goed nalopen op toelichtingen.
Elementen ontbreken nu!

**Comment by NielsNederpel** [comment]
> Aanvullingen voor constructief tekenwerk:
Element Verklaring: Toelichting:
GN Geometrie Niet zichtbaar Standaard lijnobject, gestippeld/gestreept;
SN Symbool Niet zichtbaar Standaard symbool, gestippeld/gestreept;

hoe wordt een tunnelbuis in een ondergrond (BGT)  dan aangegeven? is zeker voor buitenruimte inrichting óók interessant en valt voor mijn gevoel niet persé onder "constructies" of gaan we dat dan wel op deze manier communiceren?

**Comment by MvanderHulst** [comment]
Die zal denk ik als GEOMETRIE (continuous) als KUNSTWERK opgenomen zijn in de BGT?

GN niet zichtbaar is bedoeld voor doorsnedes constructief, om iets gestippeld aan te geven

**Comment by NielsNederpel** [comment]
is dat jouw interpretatie? want dit staat nu niet in de FB? 
daar wordt niet genoemd dat GN alleen voor doorsnedes constructief is...

is er geen enkele situatie in buitenruimte zodat we daar zonder -GN kunnen?
inderdaad is de mapping van de BGT nu continuous, maar binnen onze eigen ondergrond van Rotterdam worden bijvoorbeeld tunnels altijd wel als GN en dus gestippeld aangegeven.
dit maakt vaak wel duidelijk dat "er dus wat onder zit" en dat daarom daar in sommige situatie bijvoorbeeld geen boom geplaatst kan worden of ander zware belasting is toegestaan o.i.d.

en ja je hebt gelijk riool is ook niet zichtbaar maar dat vind ik toch anders denk ik... :)

daarbij heb ik het wel altijd al typisch gevonden dat er wel een onderscheid is tussen situatie en doorsnede doormiddel van G en GD, maar dan blijkbaar niet voor GN...
kun je die dan inderdaad alleen voor doorsneden gebruiken? of juist voor situaties? of voor beiden?

al met al zeker behoefte aan duidelijkheid op dit vlak

**Comment by MvanderHulst** [comment]
@NielsNederpel 
Klopt, staat inderdaad niet in de Formele Beschrijving. Dit is iets wat Corné mij ooit heeft verteld.
Dat de oorsprong inderdaad is dat G voor bovengrond is en GD voor doorsnede, maar dat vanuit constructie de behoefte was om ook 'aanzichten' met stippellijnen te kunnen tekenen, van sparingen en dergelijke.

Maar omdat het niet beschreven staat, is 'misbruik' voor een topo-tekening natuurlijk altijd slim om te doen. ;-)

**Comment by ElisabethKloren** [comment]
Conclusie: in de documentatie staat het nu correct, dat het veel te ingewikkeld is voor gebruikers, ja. Klopt.
