### ISSUE TITLE
Titelblok als S, niet G: overerven elementtypes? 

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#236]
Vraag softwareleverancier: We zijn bezig met het validatie proces te verbeteren en hiervoor heb ik een vraag:

In een tekening kwam ik volgende laag tegen:

-	X-XX-AL-TEKENBLAD_TITELBLOK-S

Als ik dit object opzoek in de NLCS 5.0 db, dan krijg ik deze match:

![image](https://github.com/nl-digigo/NLCS/assets/48585720/06aa6983-608d-400d-bb3f-f84a8e572fda)

Hiervoor worden enkel geometrie elementen toegelaten. De laag die wij valideren heeft een elementtype S, en past hier dus niet.

22 (TITELBLOK) is echter kind van 12 (TEKENBLAD), en deze kreeg in de database wel S als elementtype voorgeschreven.

Op zich lijkt het wel dat een titelblok als symbool zou moeten kunnen worden ingevoerd.

Daarom vraag ik me af of elementtypes van OBJECTEN overgeërfd moeten worden door SUBOBJECTEN? Dit heb ik nergens in documentatie kunnen terugvinden, maar door deze case stel ik mezelf de vraag.

**Comment by ElisabethKloren** [comment]
Deelvragen die ik hierbij heb:
- Is het toegestaan eigen symbolen toe te voegen aan NLCS? Zo ja, dan kan een laag ook een S-variant krijgen zoals bij dit titelblok
- Er zijn in elk geval wel meer voorbeelden van wijziging is G/S, ik vond bijvoorbeeld: 
- *-**-VW-BEWEGWIJZERING-G/S
- *-**-VW-BEWEGWIJZERING_DRAAGCONSTRUCTIE-G/S
- *-**-VW-BEWEGWIJZERING_DRAAGCONSTRUCTIE_PORTAAL-G
- *-**-VW-BEWEGWIJZERING_DRAAGCONSTRUCTIE_PORTAAL_POER-G
Dus ik denk dat het elementtype niet overerft; check door Expertcommissie nodig

Langere termijn vraag: moeten we van objecttypes niet eigenlijk aanduiden of dit als punt, lijn of vlak getekend wordt, of als symbool? Of kan dit variëren, en waarom is dat handig?

**Comment by ElisabethKloren** [comment]
oude regel in NLCS 4.1 was: blok wordt geplaatst één niveau hoger: X-XX-AL-TEKENBLAD-S

Nieuwe afspraak: vanaf 5.0 blok wordt geplaatst eigen niveau X-XX-AL-TEKENBLAD-TITELBLOK-S
O-o: die wijziging lijkt niet toegevoegd aan de database

Reden: gebruikers willen elk symbool individueel uit kunnen zetten.

Gewetensvraag: is dit in de tools geïmplementeerd? En in de database?

Het blok staat niet in de database; maar voldoet wel aan de formele beschrijving

Vraag 1: moeten we het aanpassen in de database?
Of... moeten we terugkomen op de formele beschrijving. 

Er moet dus gecheckt worden of er al een implementatie van is door de leveranciers. Als niemand dit goed heeft geïmplementeerd dan is het makkelijkste om de regel terug te draaien?

**Comment by SanderNijhof** [comment]
> Dit is VEEL WERK: namen van symbolen checken, laagnamen checken in de database

Ik denk dat de kolom 'ELEMENT' in de database helemaal doorlopen moet worden en ook duidelijk moet zijn wat de betekenis van die kolom is: Als er alleen 'G' in die kolom staat betekend dat dan dat alleen elementtype 'G' mag voorkomen? Of dat alleen elementtype 'G' is gedefinieerd in de database en in de bibliotheek wordt meegeleverd. Ik denk het 2e.

Wat mij betreft is X-XX-AL-TEKENBLAD_TITELBLOK-S correct als die laag een symbool bevat. Het is de gebruiker toegestaan zelf symbolen toe te voegen, onder voorwaarden zoals genoemd in de Formele Beschrijving 5.0.
Van belang is dat geometrie op G-lagen komen en symbolen op S-lagen.


> Langere termijn vraag: moeten we van objecttypes niet eigenlijk aanduiden of dit als punt, lijn of vlak getekend wordt, of als symbool? Of kan dit variëren, en waarom is dat handig?

Er zijn verschillende manieren om objecten te tekenen. In de laagnamen is opgenomen welk objecttype de laag moet bevatten. Als het objecttype niet overeenkomt met de laagnaam, dan is de laag+object ongeldig. Voor uitwisseling tussen verschillende standaarden kan ik me voorstellen dat maken van afspraken over objecttypen de uitwisseling vereenvoudigd.

**Comment by ElisabethKloren** [comment]
EC 2023-12-14: 
1. Het is voor softwareleveranciers niet duidelijk waar op gecontroleerd wordt; 
2. De leveranciers zorgen dat een symbool niet geplaatst kan worden op een G-laag, het symbool wordt dan een niveau hoger geplaatst conform de database. Er kan wel handmatig een afwijking worden gemaakt. 
3. Een block is een symbool, geen geometrie

Actie aanpassen database: Tekenblad-titelblok moet G/S zijn ; actie beheerder standaard = checken of als er symbolen voorkomen, de laagnaam wel op G/S staat

Check documentatie, daar moet staan: je MOET een symbool op een S-laag zetten, als die er niet is, maak je een laagnaam. 

Dan nog het grote vraagstuk: alle symbolen moeten in de database een stap lager komen in de database. of op beide locaties? Hier kom de discussie, wil je het object tekenen, en attributen aangeven, of wil je een laagnaam dieper en daar het attribuut toevoegen? In de tabel staan elementtypes genoemd die je mag toepassen?

**Comment by ElisabethKloren** [comment]
sander zei:
volgens mij moet geometrie op laag -G en symbool op laag -S, ongeacht hoe het in de database is opgenomen. Meer is het niet toch?

**Comment by MvanderHulst** [comment]
Samenvatting van alle vragen:
Is het toegestaan eigen symbolen toe te voegen aan NLCS? Zo ja, dan kan een laag ook een S-variant krijgen zoals bij dit titelblok
Ja het is toegestsaan om eigen symbolen (en objecten en arceringen) toe te voegen aan de NLCS.
Technisch moet het dus mogelijkzijn om op alle OBJECT alle varianten aan te kunnen maken.
TITELBLOK zal 99/100x een symbool zijn en niet als losse 'Geometrie' getekend worden.

Er zijn in elk geval wel meer voorbeelden van wijziging is G/S, ik vond bijvoorbeeld:
*-**-VW-BEWEGWIJZERING-G/S
*-**-VW-BEWEGWIJZERING_DRAAGCONSTRUCTIE-G/S
*-**-VW-BEWEGWIJZERING_DRAAGCONSTRUCTIE_PORTAAL-G
*-**-VW-BEWEGWIJZERING_DRAAGCONSTRUCTIE_PORTAAL_POER-G
Dus ik denk dat het elementtype niet overerft; check door Expertcommissie nodig
Dit is ook een vreemde situatie.
Als ik standaard PORTAAL_POER symbolen maak, moet ik deze gewoon op het OBJECT kwijt kunnen.

Langere termijn vraag: moeten we van objecttypes niet eigenlijk aanduiden of dit als punt, lijn of vlak getekend wordt, of als symbool? Of kan dit variëren, en waarom is dat handig?
Neen, dit is sterk afhankelijk van het doel van de tekening.
Bijvoorbeeld een MANTELBUIS of een DUIKER
De ene keer is het voldoende om een LIJN aan te geven waar deze komt te liggen, de andere keer wil je hem geheel in detail uitwerken (en dan maak je er meestal een symbool van, maar hoeft niet persee.

oude regel in NLCS 4.1 was: blok wordt geplaatst één niveau hoger: X-XX-AL-TEKENBLAD-S
Nieuwe afspraak: vanaf 5.0 blok wordt geplaatst eigen niveau X-XX-AL-TEKENBLAD-TITELBLOK-S
O-o: die wijziging lijkt niet toegevoegd aan de database
Reden: gebruikers willen elk symbool individueel uit kunnen zetten.
Gewetensvraag: is dit in de tools geïmplementeerd? En in de database?
Het blok staat niet in de database; maar voldoet wel aan de formele beschrijving
Vraag 1: moeten we het aanpassen in de database?
Of... moeten we terugkomen op de formele beschrijving.
Er moet dus gecheckt worden of er al een implementatie van is door de leveranciers. Als niemand dit goed heeft geïmplementeerd dan is het makkelijkste om de regel terug te draaien?
Dit is VEEL WERK: namen van symbolen checken, laagnamen checken in de database
Per versie 5.0 is het toegestaan dat symbolen op een eigen laag komen te staan (4.1 logica), of eventueel een niveau hoger, mits het harmonicamodel dit toestaat.
Bijvoorbeeld: Symbool N-SVW-VERKEERSTEKEN_BORD_E01-SO, mag geplaatst worden op het OBJECT N-WE-VW-VERKEERSTEKEN_BORD_E01-S, maar ook op N-WE-VW-VERKEERSTEKEN_BORD-S
Bijvoorbeeld: Symbool N-SIE-WEG_ABRI-SO, mag geplaatst worden op het OBJECT N-WE-IE-WEGMEUBILAIR-S, maar ook op N-WE-IE-WEGMEUBILAIR_ABRI-S
Dit wordt nog niet consequent door de leveranciers ondersteund.
Voor de Abri bijvoorbeeld wel:
 

Maar voor BORD nog niet.
 

De regel terugdraaien is m.i. absoluut geen optie.
Gebruikers hebben deze behoefte en noodzaak. Als het niet meer ‘mag’,  gaan ze het toch gewoon doen.

Ik denk dat de kolom 'ELEMENT' in de database helemaal doorlopen moet worden en ook duidelijk moet zijn wat de betekenis van die kolom is: Als er alleen 'G' in die kolom staat betekend dat dan dat alleen elementtype 'G' mag voorkomen? Of dat alleen elementtype 'G' is gedefinieerd in de database en in de bibliotheek wordt meegeleverd. Ik denk het 2e.
Wat is de toegevoegde waarde van deze kolom? Als gebruikers zelf op alle fronten mogen uitbreiden? Dan zou de 2e optie logisch zijn, maar voor wie doe je het dan? Zal de gebruiker een zorg zijn hoe het in de database staat, als het maar werkt.

Wat mij betreft is X-XX-AL-TEKENBLAD_TITELBLOK-S correct als die laag een symbool bevat. Het is de gebruiker toegestaan zelf symbolen toe te voegen, onder voorwaarden zoals genoemd in de Formele Beschrijving 5.0.
Van belang is dat geometrie op G-lagen komen en symbolen op S-lagen.
De standaard NLCS bevat 2 titelblok symbolen, dus moeten op een S-laag aangemaakt worden.
Als dit volgens de database nu niet kan, is dat een fout in de database.

Er zijn verschillende manieren om objecten te tekenen. In de laagnamen is opgenomen welk objecttype de laag moet bevatten. Als het objecttype niet overeenkomt met de laagnaam, dan is de laag+object ongeldig. Voor uitwisseling tussen verschillende standaarden kan ik me voorstellen dat maken van afspraken over objecttypen de uitwisseling vereenvoudigd.
Zie ook bovenstaand. Datatechnisch zou je hier afspraken over kunnnen maken, werkbaar is het niet. Een Duiker in bovenaanzicht is vaak een lijn of block, in doorsnede meestal losse lijnen, tenzij het standaard duikers zijn, dan maak je er weer gauw een block van. Dit is niet voor te schrijven. Idem voor ‘kantopsluitingen’ in doorsnede, moet de band een block zijn of mag het een polyline zijn? Lekker open houden.

EC 2023-12-14:
1.	Het is voor softwareleveranciers niet duidelijk waar op gecontroleerd wordt;
2.	De leveranciers zorgen dat een symbool niet geplaatst kan worden op een G-laag, het symbool wordt dan een niveau hoger geplaatst conform de database. Er kan wel handmatig een afwijking worden gemaakt.
3.	Een block is een symbool, geen geometrie
Actie aanpassen database: Tekenblad-titelblok moet G/S zijn ; actie beheerder standaard = checken of als er symbolen voorkomen, de laagnaam wel op G/S staat
M.i. logisch als G/S een standaard combinatie is, zie ook bovenstaande ‘optie 2’ van Sander eventueel.

Check documentatie, daar moet staan: je MOET een symbool op een S-laag zetten, als die er niet is, maak je een laagnaam.
Staat vermeld in 5.2.3

Dan nog het grote vraagstuk: alle symbolen moeten in de database een stap lager komen in de database. of op beide locaties? Hier kom de discussie, wil je het object tekenen, en attributen aangeven, of wil je een laagnaam dieper en daar het attribuut toevoegen? In de tabel staan elementtypes genoemd die je mag toepassen?
Zie het eerdere voorbeeld van de Abri. Hoe is dit in de tool geregeld?
Uiitgangspunt is dat een symbool op alle OBJECT en SUBOBJECT niveau’s geplaatst mag worden, welke ook in de SYMBOOLNAAM voorkomen.
Bijvoorbeeld een symbool als:
SVH-KANTOPSLUITING_TROTTOIRBAND_130 150_GRIJS
Mag geplaats worden op de lagen:
*-**-VH-KANTOPSLUITING-S
*-**-VH-KANTOPSLUITING_TROTTOIRBAND-S
*-**-VH-KANTOPSLUITING_TROTTOIRBAND_130 150-S
*-**-VH-KANTOPSLUITING_TROTTOIRBAND_130 150_GRIJS-S

Maar: als er tussenniveau's zijn, zoals fruitboom of xboom, dan vindt je de deze niet meer op een hoger niveau.
Actie voor beheerder: in database doorvoeren dat je symbool een niveau lager kan plaatsen; en zoekfuncties toevoegen voor tussenlagen"
Zie bovenstaand.
Bijvoorbeeld een symbool als:
SGR-BOOM_FRUITBOOM
Mag geplaats worden op de lagen:
*-**-GR-BOOM-S
*-**-GR-BOOM_FRUITBOOM-S
*-**-VH-KANTOPSLUITING_TROTTOIRBAND_130 150_GRIJS-S

Actie : intentie beschrijven voor hoe het voor gebruiker moet werken / onderzoeken hoe dat geïmplementeerd is bij de softwareleveranciers / actie voor databasebeheerder
Zie bovenstaand.

sander zei:
volgens mij moet geometrie op laag -G en symbool op laag -S, ongeacht hoe het in de database is opgenomen. Meer is het niet toch?
Eens, heeft de kolom in de database een toegevoegde waarde?
Combinatie BLOCK op een -S laag is voldoende.

**Comment by MvanderHulst** [comment]
@ElisabethKloren actie voor jou voor verwerking/controle database

**Comment by ElisabethKloren** [comment]
Definitie en eisen aan het element in de documentatie ingekort naar:

<dfn>ELEMENT</dfn>
<d>Een ELEMENT geeft weer wat er in de laag is getekend: een of meer [grafische representaties](#representatie-van-objecten) van een (SUB)OBJECT, zoals geometrie, arcering of symbool; of een hulpelement voor duiding van de tekening zoals een tekst of maatvoering.<br><br>

Indien binnen de NLCS een symbool beschikbaar is is dit in de database weergegeven met S, of in combinatie met andere elementen G/S of A/S of G/A/S<br>
Indien er geen symbool beschikbaar is binnen de NLCS mag een eigen symbool worden gebruikt, de afwezigheid van S in de database houdt geen verbod in maar geeft alleen weer dat er geen symbool beschikbaar is binnen de standaard. 


<ol><li>Aan ieder OBJECT of SUBOBJECT MOET het ELEMENT worden toegevoegd.
<li>Als in de laagnaam alleen de HOOFDGROEP voorkomt zonder een OBJECT uit deze hoofdgroep, mogen alleen MAATVOERING of TEKST gebruikt worden als element. De algemene objecten uit hoofdgroep ZZ (aanpijling, afbreeklijn, hulplijn et cetera) mogen ook in de laagnaam voorkomen zonder OBJECT uit de hoofdgroep. Een symbool of arcering MOET altijd gekoppeld zijn aan een OBJECT of SUBOBJECT. 
</ol>

**Comment by ElisabethKloren** [comment]
Als een symbool in de database is gekoppeld aan een object, erven de onderliggende objecten ook dit symbool. In die zin gaat het dus goed, als het symbool juist in een hogere laag is toegevoegd. 

Als het inderdaad zo is dat de toevoeging G, S of A in het informatieveld ELEMENT geen verbod inhoudt om de andere elementen te gebruiken dan heeft deze aanduiding in de database inderdaad geen toegevoegde waarde.  Dit wil ik wel checken voor ik het element volledig weghaal uit de database > even een aparte issue gemaakt #455
