### ISSUE TITLE
gebruikersvraag: Revit template

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#238]
Vraag per mail vanuit gebruiker: : staat er op jullie roadmap de ontwikkeling van een Revit template oid?

**Comment by ElisabethKloren** [comment]
deze  staat  al een tijdje op ons NLCS roadmap 
Er is hiervoor al een exercitie gedaan door een gebruikersgroep  maar dan gebaseerd op de oude 4.2 versie van de NLCS. Inmiddels is de nieuwe 5.0 versie van de NLCS in linked data beschikbaar waarmee de uitwisseling vanuit 3D modellen (Revit o.a.) naar NLCS kan worden geregeld

3.5 NLCS Afstemming 3D
NLCS wordt momenteel gebruikt als uitgangspunt voor 2D exports vanuit 3D CAD / BIM modellen. 
De implementatie is nog niet volledig en deels ook op een verouderde versie van de NLCS gebaseerd. 
In samenwerking met de gebruikersverenigingen worden de countrykits verder afgestemd met de vigerende versie van de NLCS.

**Comment by ElisabethKloren** [comment]
Ik vraag me hierbij af, wat wij als standaard kunnen rgelen zodat softwarepakketten die in 3D modelleren NLCS kunnen gebruiken. NLCS opnemen in de BSDD? Een ontology alignment naar IFC 4.3?
Of moet er per softwarepakket een specifieke oplossing worden gemaakt, en is dat dan opnze taak of moeten wij dat alleen functioneel beschrijven?

**Comment by SanderNijhof** [comment]
Wat mij betreft is het maken van templates zeker GEEN taak voor de NLCS. Templates zijn software gebonden. Aanpassingen aan de NLCS om werken met templates mogelijk te maken, ondersteunen of te verbeteren behoren, wat mij betreft, WEL tot de taken van de NLCS. Templates zijn (nog) geen onderdeel van de standaard en zijn ook niet als zodanig opgenomen in de database. Het verbaasd mij dat dit op de roadmap van de NLCS staat. 

> Inmiddels is de nieuwe 5.0 versie van de NLCS in linked data beschikbaar

Getest en goedgekeurd?

**Comment by ElisabethKloren** [comment]
dit wordt meegenomen in een poging om tot een digideal te komen, samen met de bim basis infra. Wordt vervolgd, maar niet in deze issue
