### ISSUE TITLE
NLCS object STATUS - versie 5.0 ophelderen documentatie

### ISSUE THREAD

**Issue by SanderNijhof** [nl-digigo/NLCS#239]
In de Formele Beschrijving 5.0 worden de statussen B, N, V en T in paragraaf 5.1.1 (https://nl-digigo.github.io/NLCS/requirementscadmodels/#status) uitgelegd als status van de 'Situatie' van een object.
- Bestaande situatie
- Nieuwe situatie
- Tijdelijke situatie
- te Verwijderen situatie

Dit is niet consequent doorgevoerd in de Formele Beschrijving 5.0. In de tabel bij 5.2.1 wordt status nog uitgelegd als de status van 'werk'. De betekenis is niet hetzelfde en zorgt daardoor mogelijk voor verwarring.

> red. E de Vries: ik zie dit niet in de laatste versie van de formele beschrijving: https://github.com/nl-digigo/NLCS/blob/main/docs/archive/Formele_beschrijving_NLCS_versie_5_0_V1_0.pdf

**Comment by SanderNijhof** [comment]
Hergebruik kan zijn op dezelfde locatie, of op een andere locatie en wordt wel degelijk gedekt door de STATUS/FASE **N**ieuw. Het object ondergaat nl. een bewerking en daarmee wijzigt de STATUS van dat object om aan te geven dat de software die mutaties verwerkt (mogelijk) iets met dat object moet doen.

**Comment by MvanderHulst** [comment]
Iets bestaands haal en weg en stel je als nieuwe situatie.
B en N zijn hiermee dekkend.

Een beheerder zal hier natuurlijk weer anders over denken...

**Comment by ElisabethKloren** [comment]
<table border="1">
  <tr>
    <th>Startsituatie</th>
    <th>Eindsituatie</th>
    <th>NLCS status</th>
    <th>NLCS netbeheer substatus</th>
    <th>voorbeeld NLCS laagnaam</th>
  </tr>
  <tr>
    <td>Bestaand, in Bedrijf</td>
    <td>Bestaand, verlaten</td>
    <td>B</td>
    <td></td>
    <td>B-OI-KL-ET_MS_DISTRIBUTIE_6 kV_3x95Cu-G</td>
  </tr>
  <tr>
    <td>Bestaand, in Bedrijf</td>
    <td>Bestaand, reserve</td>
    <td>B</td>
    <td></td>
    <td>B-OI-KL-ET_MS_DISTRIBUTIE_6 kV_3x95Cu-G</td>
  </tr>
  <tr>
    <td>Bestaand, in Bedrijf</td>
    <td>Verwijderd</td>
    <td>B</td>
    <td></td>
    <td>B-OI-KL-ET_MS_DISTRIBUTIE_6 kV_3x95Cu-G</td>
  </tr>
  
  <tr>
    <td>Bestaand, in Bedrijf</td>
    <td>Bestaand, opgevuld</td>
    <td>B</td>
    <td></td>
    <td>B-OI-KL-GAS_LD_DISTRIBUTIE_100 MBAR_NGIJ_118-G</td>
  </tr>
  <tr>
    <td>Bestaand, in Bedrijf</td>
    <td>Bestaand, gerelined</td>
    <td>B</td>
    <td></td>
    <td>B-OI-KL-GAS_LD_DISTRIBUTIE_100 MBAR_NGIJ_118-G</td>
  </tr>
</table>

**Comment by ElisabethKloren** [comment]
Ik snap status x niet?

Ik snap het verschil tussen nieuw en revisie niet?

**Comment by SanderNijhof** [comment]
> Ik snap status x niet?

Status X is bedoeld voor elementen zoals legenda, tekeninghoofd, noordpijl. Die zijn niet afhankelijk van een status/situatie.



> Ik snap het verschil tussen nieuw en revisie niet?

Is er functioneel bij mijn weten ook niet. Maar er is in het verleden een verzoek geweest om STATUS 'R' toe te voegen en dat hebben we toen gedaan.
He enige wat ik kan bedenken is het controle-idee: Als een laag een status R heeft dan is het object gecontroleerd/nagemeten met de nieuwe/uitgevoerde situatie. Of dat je op een niet-revisie-tekening R- lagen plaatst om de nauwkeurigheid aan te geven? Van mij mag status R vervallen, maar ik heb er ook geen probleem mee als die blijft. Voor mij zijn STATUS R en N gelijk.

**Comment by MvanderHulst** [comment]
De status R is van belang voor revisie tekeningen.
Hiermee wordt de status N (ontwerp) opgewaardeerd tot R (werkelijkheid).
De revisie is dus het ontwerp, zoals uitgevoerd.
Hiermee wordt vervolgens weer de hele mutatie systematiek in gang gezet.
Status T kan dan ook absoluut niet vervallen.
Niet van belang voor het ingenieursbureau, maar onmisbaar voor een aannemer/doorlevering naar beheer.

**Comment by SanderNijhof** [comment]
Een object met STATUS 'T' op een tekening wil eigenlijk zeggen dat het object voor aanvang van het werk en na gereedkomen van het werk niet aanwezig is. Bijv. tijdelijke markering en bebording, bekisting (die niet achterblijft), tijdelijke wal, tijdelijk brug.
Objecten die wel van belang zijn voor de werkzaamheden en tekening, maar die uiteindelijk niet verwerkt hoeven te worden in bijvoorbeeld het 'beheersysteem'.

Met vriendelijke groet,

Sander Nijhof
Team Projecten
***@***.***

T (0546) 54 11 11
M 06 55 42 99 16
I www.almelo.nl<http://www.almelo.nl/>
***@***.******@***.***<https://nl-nl.facebook.com/gemeentealmelo>
Postadres
Postbus 5100
7600 GC Almelo
Bezoekadres
Haven Zuidzijde 30
7607 EW Almelo

Disclaimer
De informatie opgenomen in dit bericht kan vertrouwelijk zijn en is uitsluitend bestemd voor de geadresseerde. Als u dit bericht ten onrechte ontvangt, wordt u vriendelijk verzocht dit aan de afzender te melden.

Van: Elisabeth de Vries ***@***.***>
Verzonden: maandag 18 maart 2024 11:10
Aan: nl-digigo/NLCS ***@***.***>
CC: Nijhof, Sander ***@***.***>; Author ***@***.***>
Onderwerp: Re: [nl-digigo/NLCS] NLCS object STATUS - versie 5.0 ophelderen documentatie (Issue #239)


LET OP: Deze e-mail is afkomstig van een afzender buiten de Gemeente Almelo. Klik niet op een link of bijlage(n) in deze e-mail, tenzij je de afzender vertrouwt en je zeker weet dat de inhoud veilig is. Neem in geval van twijfel contact op met de I&A servicedesk.

Is dit dan hoe de definities zouden moeten zijn van de huidige statussen:

De objecten krijgen in de laagnaam een status mee. Als de status tijdens het werken met de tekening wijzigt, is het object twee keer getekend: een keer (als ondergrond) met de status bij aanvang van het werk, één keer met de status op het einde van het werk.
De statussen in NLCS
Code
Verklaring
Omschrijving
N
Nieuwe situatie
Het object is na uitvoering van het werk op basis van de tekening nieuw, of heeft een bewerking ondergaan
B
Bestaande situatie
Het object in de (bestaande) situatie waarin men het aantreft bij het starten van het werk op basis van deze tekening.
V
Te verwijderen situatie
Het object is na uitvoering van het werk op basis van de tekening verwijderd
T
Tijdelijke situatie
Het object is na uitvoering van het werk op basis van de tekening tijdelijk geplaatst
X
Onafhankelijk van STATUS/fase
Status "X" MOET altijd worden gecombineerd met de discipline "XX".
R
Revisie
Het object is na uitvoering van het werk op basis van de tekening nieuw, of heeft een bewerking ondergaan, en wordt aangeboden ter revisie

-

**Comment by ElisabethKloren** [comment]
Uitgewerkt voor opname in documentatie van versie 5.0, toerlichting op de huidige werkwijze:

| Code | Verklaring | Bestaand | Ontwerp | as-built | Toelichting | Is de status relevant voor het bijwerken van de beheerdata |
|------|------------|----------|---------|----------|-------------|----------------------------------------------------------|
|      |            | X        | X       | X        | Object is een bestaand object dat tijdens de werkzaamheden ongewijzigd is | Nee |
|      |            |          | X       | (X)*2    | Object wordt tijdens de werkzaamheden gewijzigd. Dit betreft bijvoorbeeld een bestaand object dat aangepast, vervangen*1 of verplaatst wordt, maar ook nieuw toe te voegen objecten | Ja |
|      |            | X        |         | (X)*2    | Objecten die nog niet bestaan en nieuw worden toegevoegd. | Ja |
|      |            |          | X       | X        | Object is een bestaand object dat na gereedkomen van de werkzaamheden niet meer aanwezig is. Dus wordt (ontwerp) of is (asbuilt) verwijderd | Ja |
|      |            | X        |         | X        | Object is een bestaand object dat wordt verplaatst. (of snoeien) | Ja |
|      |            |          | X       |          | Object is alleen tijdens de werkzaamheden aanwezig. Dus bij start van het werk is het object niet aanwezig en na gereed komen van het werk is het object ook niet meer aanwezig. Voorbeelden zijn tijdelijke markeringen, rijplaten, bemaling | Nee |
|      |            | X        | X       | X        | Tijdelijke objecten die in de asbuilt nog aanwezig zijn. Dit zou je niet zo moeten gebruiken, als een tijdelijk object na het project in beheer wordt genomen, kun je het beter als N op je tekening hebben staan. | ? |
|      |            |          |         |          | Geen beheerbaar object. Voorbeelden zijn legenda, werkgrens, noordpijl. Zie hoofdgroep AL | Nee |
|      |            | X        |         |          | Object is tijdens de werkzaamheden gewijzigd, gecontroleerd en ingemeten. Dit betreft bijvoorbeeld een bestaand object dat aangepast of verplaatst is, maar ook nieuw toegevoegde objecten | Ja |
|      |            |          | X (niet doen)      | X        | Object is een bestaand object dat tijdens de werkzaamheden is gewijzigd | Ja |

**Comment by SanderNijhof** [comment]
> Uitgewerkt voor opname in documentatie van versie 5.0, toerlichting op de huidige werkwijze:

De tabel kan zo niet opgenomen worden in de documentatie. 
Ten 1e is dit een afwijkende bewerking van de tabel die we afgelopen dinsdag gedeeld hebben. Voor mij is bijv. nieuw dat we besproken hebben dat status revisie in een 'bestaande situatie' tekening opgenomen wordt.
Ten 2e geeft deze tabel ruimte aan verschillende interpretaties voor gebruik van de statussen.
Dit was een inventarisatie van hoe de statussen nu gebruikt worden. In de Documentatie moet juist eenduidig opgenomen worden hoe **wel** met de statussen omgegaan moet worden.

**Comment by MvanderHulst** [comment]
Bovenstaande tabel is onjuist, niet geschikt voor de documentatie.
M.i. de originele vraag:
5.2.1 moet aangepast worden op de kolom omschrijving
AB t/m AH
AI t/m AO
AP t/m AV
AW t/m BC

De woorden 'WERK' aanpassen naar 'situatie om consequent te maken met 5.1.1
Als dit op basis van de laatste overleggen wordt aangepast, dit op beide plekken consequent doorvoeren.

**Comment by ElisabethKloren** [comment]
Ik heb nu in [eisen aan tekeningen en modellen](https://nl-digigo.github.io/NLCS/requirementscadmodels/#status) de uitleg van statussen opgenomen zoals die nu gebruikt worden. 

<table class="tabel3">
    <caption>De statussen in NLCS</caption>
    <tr>
        <th>Afkorting</th>
        <th>Status</th>
        <th>Definitie</th>
        <th>Komt voor op tekening bestaande situatie</th>
        <th>Komt voor op ontwerptekening</th>
        <th>Komt voor op revisietekening</th>
    </tr>
        <tr>
        <td>B</td>
        <td>Bestaande situatie</td>
        <td>Het object in de (bestaande) situatie waarin men het aantreft bij het starten van het werk op basis van deze tekening.</td>
        <td>Ja</td>
        <td>Ja</td>
        <td>Ja</td>
    </tr>
    <tr>
        <td>N</td>
        <td>Nieuwe situatie</td>
        <td>Het object is in het ontwerp geheel nieuw toegevoegd, of een bestaand object moet een bewerking ondergaan, zoals verplaatsing, reiniging of onderhoud</td>
        <td>Nee</td>
        <td>Ja</td>
        <th>Nee</td>
    </tr>
        <tr>
        <td>R</td>
        <td>Revisie</td>
        <td>Het object is tijdens de uitvoering geheel nieuw toegevoegd, of een bestaand object heeft een bewerking ondergaan, zoals verplaatsing, reiniging of onderhoud</td>
        <td>Nee</td>
        <td>Nee</td>
        <td>Ja</td>
    </tr>
    <tr>
        <td>V</td>
        <td>Te verwijderen situatie</td>
        <td>Het object moet verwijderd worden tijdens het werk (ontwerptekening) of is verwijderd (revisietekening)</td>
        <td>Nee</td>
        <td>Ja</td>
        <td>Ja</td>
    </tr>
    <tr>
        <td>T</td>
        <td>Tijdelijke situatie</td>
        <td>Het object wordt nieuw geplaatst, maar tijdelijk, gaat tijdens het werk weer weg.</td>
        <td>Nee</td>
        <td>Ja</td>
        <td>Nee</td>
    </tr>
    <tr>
        <td>X</td>
        <td>Onafhankelijk van STATUS/fase</td>
        <td>Status X is bedoeld voor elementen zoals legenda, tekeninghoofd, noordpijl. Die zijn niet afhankelijk van een status/situatie. Status “X” MOET altijd worden gecombineerd met de discipline “XX”.</td>
        <td>Ja</td>
        <td>Ja</td>
        <td>Ja</td>
    </tr>
</table>

<aside class="note" title="Voorbeelden toepassing statussen">
Bij een werkvoorbereiding met de faseringen: voorbelasting, bouwrijp maken, woonrijp maken.
<br>Voorbelasting: status tijdelijk T = nieuw, maar tijdelijk, gaat in het werk weer weg.
<br>Bouwrijp maken: De bouwwegen en dergelijke krijgen de status T.
<br>Woonrijp maken: De riolering en nieuwe wegen krijgen de status N = nieuw op de ontwerptekening, en R op de revisietekening
</aside>

**Comment by SanderNijhof** [comment]
B : _Het object in de (bestaande) situatie waarin men het aantreft bij het starten van het werk_ (ontwerp)**en niet is gewijzigd aan het einde van het werk.(revisie)** 
N : Waarom mag status N niet voorkomen op een revisie tekening? Moeten dan alle namen hernoemd worden naar R? Dat vind ik niet zinvol. Status R was nodig omdat die tezamen met status N op een tekening kan voorkomen?
R : _Het object is tijdens de uitvoering geheel nieuw toegevoegd, of een bestaand object heeft een bewerking ondergaan, zoals verplaatsing, reiniging of onderhoud_ Het gaat erom dat dit object is gecontroleerd met de werkelijke situatie buiten. Dus **"Het object is nieuw of gewijzigd ten opzichte van de situatie voorafgaand aan de werkzaamheden en de gegevens van dit object zijn gecontroleerd en goedgekeurd op juistheid."**
T : extra?: Object is bij aanvang van het werk niet aanwezig en na afronden van het werk niet aanwezig.
X : is X ook onafhankelijk van fase? Dus X01-XX-AL-... kan niet?

**Comment by SanderNijhof** [comment]
> 4\. De betekenis van R ben ik niet met je eens: R is "het object is ingemeten na oplevering van de werk"  maar dat het de status R heeft betekent toch niet dat het werk goed is uitgevoerd?

Dat ben ik met je eens. R wil zeggen de ingemeten toestand van het object nadat het werk is uitgevoerd, dat blijkt niet uit de beschreven definite. 'R' zegt inderdaad niet direct iets over de overige attributen van het object.

**Comment by ElisabethKloren** [comment]
ik heb nu deze definitie opgenom,en bij R, dit lijkt me de meest heldere: Het object op de ingemeten locatie en met de afmetingen van het object nadat het werk is uitgevoerd

**Comment by MvanderHulst** [comment]
@ElisabethKloren de tekst is te specifiek gemaakt.
Voldoende is:
Het object op de ingemeten locatie nadat het werk is uitgevoerd.

Voor 'puntobjecten', bomen, palen, lichtmasten e.d. worden afmetingen allemaal niet vastgelegd in een R-meting.
