### ISSUE TITLE
#1589 riolering, oa wat het verschil is tussen een RIOOLLEIDING en TRANSPORTLEIDING?

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#24]
NLCS 5.0 heeft een goede verbetering voor riolering doorgevoerd. Echter is daarbij wel een onderdeel onduidelijker geworden. Kunt u aangeven wat het verschil is tussen een RIOOLLEIDING en TRANSPORTLEIDING?
Het type lijkt gelijk aan elkaar, ook leiding diameters komen hierin beide voor, maar de opbouw van deze hoofdstukken is niet gelijk aan elkaar. Daardoor is het verwarrend wat het precieze verschil tussen deze hoofdstukken is.
Voorbeeld: ITR>TRANSPORTLEIDING is niet ingevuld
Daarnaast is de opbouw van benaming voor deze hoofdstukken in DWA, GWA, HWA en ITR niet eenduidig opgebouwd.
Voorbeeld: 'OP HOOGTE BRENGEN' komt voor bij DWA in zowel RIOOLLEIDING als TRANSPORTLEIDING; bij GWA allen onder RIOOLLEIDING en onder TRANSPORTLEIDING niet; bij HWA is dit weer omgekeerd en komt bij RIOOLLEIDING niet voor en bij TRANSPORTLEIDING wel; bij ITR ontbreekt deze volledig.

**Comment by SanderNijhof** [comment]
De termen 'RIOOLLEIDING' en 'TRANSPORTLEIDING' komen uit het GWSW. Betekenis van beide staan daar ook toegelicht.
De ontbrekende lagen inventariseren en in overleg toevoegen?

**Comment by ElisabethKloren** [comment]
EC 2023-11-09 Opnemen in documentatie verwijzing naar GWSW

**Comment by MvanderHulst** [comment]
Even zonder controle op de GWSW en op basis van boeren verstand:
- TRANSPORTLEIDING is een enorme leiding die van A naar Z gaat op water over langere afstanden te vervoeren, eventueel onder druk?
- RIOOLLEIDING is de reguliere leiding zoals deze in woonwijken e.d. terug te vinden is.

Even een 'dump' waarin de verschillen tussen de 'stelsels' goed zichtbaar zijn.
![image](https://github.com/nl-digigo/NLCS/assets/144665595/412bbf9a-1559-4fce-bf60-473dc5600afb)

Bevindingen:
DRAINAGE_AANSLUITPUT		ontbreekt
DRAINAGE_DRAIN			komt alleen voor bij 'drainage', dat is opzich wel logisch.
OVERIG_AANSLUITPUNT		ontbreekt
DRAINAGE_ASFSCHEIDER		ontbreekt
GWA_ASFSCHEIDER			ontbreekt
HWA_ASFSCHEIDER			ontbreekt
ITR_ASFSCHEIDER			ontbreekt
OVERIG_ASFSCHEIDER		ontbreekt
DWA_IBA				overbodig, kan vervallen, is onderdeel van DWA_AFSCHEIDER
DRAINAGE_KOLKAANSLUITLEIDING	onvollidig gevuld
DWA_KOLKAANSLUITLEIDING		onvollidig gevuld
DRAINAGE_KOLKAANSLUITLEIDING	onvollidig gevuld
OVERIG_KOLKAANSLUITLEIDING	ontbreekt
DRAINAGE_LOZEPUT		onvollidig gevuld
HWA_LOZEPUT			onvollidig gevuld
OVERIG_LOZEPUT			onvollidig gevuld
DRAINAGE_LOZINGSPUNT		onvollidig gevuld
DWA_LOZINGSPUNT			ontbreekt
OVERIG_LOZINGSPUNT		ontbreekt
DRAINAGE_PERCEELAANSLUITPUNT	ontbreekt
GWA_PERCEELAANSLUITPUNT		ontbreekt
ITR_PERCEELAANSLUITPUNT		ontbreekt
OVERIG_PERCEELAANSLUITPUNT	ontbreekt
DRAINAGE_PUT			inconsequent, moet zijn: DRAINAGE_RIOOLPUT
DRAINAGE_RIOOLLEIDING		ontbreekt
OVERIG_SCHILDMUUR		ontbreekt
DRAINAGE_TALUDGOOT		geen idee wat dit is, is dit niet gewoon een 'hulpstuk' uitstroomvoorziening'?
DRAINAGE_TRANSPORTLEIDING	onvolledig gevuld
DRAINAGE_STROMINGSRICHTING	ontbreekt
DWA_SEPTICTANK			als IBA als symbool onder DWA_AFSCHEIDER is ondergebracht, mag deze daar ook bij en is DWA_SEPTICTANK overbodig.

Tot slot, de bijzonderheden in OVERIG
OVERIG_BERGBEZINKLEIDING	staat enkel onder OVERIG, zou onder alle stelsels terug mogen komen en is onderdeel van het hoofdriool, hernoemen naar RIOOLLEIDING_BERGBEZINKLEIDING
OVERIG_BERGINGSLEIDING		staat enkel onder OVERIG, zou onder alle stelsels terug mogen komem en is onderdeel van het hoofdriool, hernoemen naar RIOOLLEIDING_BERGINGSLEIDING
OVERIG_BLUSRIOOL		staat enkel onder OVERIG, zou onder alle stelsels terug mogen komen
OVERIG_DUIKER			een DUIKER is onderdeel van een HWA riool, die hoort OOK daar terug te komen, zou m.i. bij overige wegmoeten
OVERIG_GEBOORDELEIDING		een geboordeleiding is een uitvoeringsmethodiek, maar zegt niks over de leiding zelf. kan voor alle stelsels gelden... hoe willen we hiermee omgaan?
OVERIG_ONTLUCHTINGSLEIDING	is (denk ik) alleen onderdeel van een persriool en kan dus in alle stelsels voorkomen?
OVERIG_OVERSTORTLEIDING		staat enkel onder OVERIG, zou onder alle stelsels terug mogen komen en is onderdeel van het hoofdriool, hernoemen naar RIOOLLEIDING_OVERSTORTLEIDING
OVERIG_TANK			hieronder staan 'TANK_AARDGAS, TANK_PROPAAN, TANK_SEPTIC, TANK als symbolen. Septic kan naar AFSCHEIDER volgens bovenstaan. de overige zijn GEEN rioleringsonderdelen. Horen deze niet beter onder IE thuis?
OVERIG_TERREINKAST		staat enkel onder OVERIG, zou onder alle stelsels terug mogen komen
OVERIG_WEESLEIDING		Een leiding waarvan de eigenaar onbekend is.... maar zegt niks over het stelseltype. Zou m.i. dus ook onder alle andere stelselsoorten terug mogen komen.

OVERIG_ZINKER			DRAINAGE_ZINKER ontbreekt en HWA_ZINKER ontbreekt. een ZINKER is echter een functie maar nogsteeds een 'RIOOLLEIDING'. Is het gewenst om de FUNCTIE te benoemen? Dan zou je bij ZINKER ook de SUBOBJECTEN voor MATERIAAL en DIAMETER op moeten nemen.
				Dit geldt eigenlijk ook voor BERGBEZINKLEIDING, BERGINGSLEIDING en OVERSTORTLEIDING.

**Comment by SanderNijhof** [comment]
Volgens GWSW:
**Rioolleiding**
**definitie**: “Samenstel van buizen tussen twee putten bestemd voor de inzameling en/of het transport van afvalwater.”
**Synoniem**: “rioolleidingen”
**Transportrioolleiding** 
**definitie:** “Een gesloten rioolleiding waarop in principe geen aansluitleidingen zijn aangesloten.”
**Synoniem:** “transportrioolleidingen, hoofdriool, hoofdriolen, moerriool, moerriolen, transportriool, transportriolen”


> OVERIG_WEESLEIDING

Als 'OVERIG' wil zeggen niet GWA, DWA, HWA, ITR, DRAINAGE, PERSLEIDING of VACUUMLEIDING, is OVERIGE dan wel terecht gebruikt?
Van een weesleiding is niet bekend welk type leiding het is. 
Kan weesleiding daarom wel iets anders zijn dan B-..-..-WEESLEIDING-G ?

**Comment by ElisabethDeVries** [comment]
de hoofdgroep rioleringen krijgt een grote herziening in 6.0
