### ISSUE TITLE
Ophelderen: regels over kleurgebruik in de standaard

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#242]
- (Wanneer) mag je eigen kleuren gebruiken voor objecten in NLCS? Wanneer niet? 

Dit beter beschrijven in de documentatie en de FAQ's op de website

**Comment by MvanderHulst** [comment]
In de FB zou een artikel opgenomen worden welke dit beschrijft. Dit gaat verder dan de kleur, maar ook de lineweight en de linetype.

Omgang met eigen presentaties:
Het doel van de NLCS is om de digitale omgeving van het tekenwerk te standaardiseren. Door het uniform opstellen van een digitaal model, zijn alle getekende objecten herkenbaar, herleidbaar en kan dit bij uitwisseling snel hergebruikt worden. Het wordt dan ook aangeraden om de presentatie van de NLCS in het digitale model niet aan te passen.

Als het gewenst is om afwijkende kleuren, pendiktes of lijnstijlen toe te passen, wordt geadviseerd om dit in de ‘layout’ omgeving te regelen middels een Xref-Layer-Override/Reference-Level-Override of een Viewport-Overide. Hiermee kan de eindgebruiker zijn eigen presentatie toepassen voor op het eindproduct (PDF), maar blijven de ‘bronbestanden/ het digitale model’ intact volgens de NLCS.

**Comment by MvanderHulst** [comment]
@ElisabethKloren graag uitwerken in tekst in FB

**Comment by MvanderHulst** [comment]
@ElisabethKloren  Xref-Layer-Override is de AutoCAD term. Reference-Level-Override is de Microstation term.
Viewport kan in AutoCAD, maar zou bij nader inzien achter wegen mogen blijven gezien het een vervelende oplossing is. ;-)

**Comment by ElisabethKloren** [comment]
tekst opgenomen in de fb
