### ISSUE TITLE
ontbrekende objecten tbv grondscheiding

### ISSUE THREAD

**Issue by NielsNederpel** [nl-digigo/NLCS#246]
binnen de NLCS bibliotheek ontbreken er zaken aangaande grondscheiding en/of wortelschermen/folie.
er bestaat wel een object *-**-GW-GROND-SCHEIDINGLAAG-G
onduidelijk is echter of hier een doek/folie bedoeld wordt. en lijkt me meer een laag van grond die een scheiding vormt
volgens mij kunnen er diverse objecten toe worden gevoegd.
o.a.
*-**-GW-GROND_SCHEIDING-G
*-**-GW-GROND_SCHEIDING_SCHEIDINGSLAAG-G
*-**-GW-GROND_SCHEIDING_SCHERM_-G
*-**-GW-GROND_SCHEIDING_DOEK-G
*-**-GW-GROND_SCHEIDING_FOLIE-G
eventueel kan er gekozen worden om eerst aan te geven of het een verticale of horizontale scheiding betreft.
*-**-GW-GROND_SCHEIDING-G
*-**-GW-GROND_SCHEIDING_HORIZONTAAL-G
*-**-GW-GROND_SCHEIDING_HORIZONTAAL_SCHEIDINGSLAAG-G
*-**-GW-GROND_SCHEIDING_HORIZONTAAL_DOEK-G
*-**-GW-GROND_SCHEIDING_HORIZONTAAL_FOLIE-G
*-**-GW-GROND_SCHEIDING_VERTICAAL-G
*-**-GW-GROND_SCHEIDING_VERTICAAL_SCHERM-G
*-**-GW-GROND_SCHEIDING_VERTICAAL_DOEK-G
*-**-GW-GROND_SCHEIDING_VERTICAAL_FOLIE-G
er kan uiteraard ook gekozen worden om wortelschermen als apart object op te nemen

**Comment by MvanderHulst** [comment]
eens dat deze objecten ontbreken.
Verschil horizontaal en verticaal zou ik niet opnemen. meestal 'pak' je iets ook in, dan is het een combinatie.
Graag ook onderscheid tussen een aantal doeksoorten:
- waterdoorlatend of enkel grondscheidend. aanzienlijk verschil.
verder niet te veel subonderdelen van maken

**Comment by MvanderHulst** [comment]
Dit raakt behoorlijk issue #71 
Indien dat akkoord is, denk ik dat het logisch is om GROND_SCHEIDING te laten vervallen. Dit heeft niks met GRONDSOORTEN te maken, en een SCHEIDING is geen OBJECT.
Voorstel om in de hoofdgroep GW een nieuw OBJECT te maken:
GRONDSCHEIDINGEN
GRONDSCHEIDINGEN_GEOTEXTIEL
GRONDSCHEIDINGEN_GEOTEXTIEL_WATERDOORLATEND
GRONDSCHEIDINGEN_GEOGRID
GRONDSCHEIDINGEN_GEOMEMBRAAM
GRONDSCHEIDINGEN_ANTIWORTELDOEK
GRONDSCHEIDINGEN_ANTIWORTELDOEK_WOVEN
GRONDSCHEIDINGEN_ANTIWORTELDOEK_NONWOVEN

**Comment by NielsNederpel** [comment]
GROND_SCHEIDING bestaat nog niet als object (in 5.0) dit was slechts een voorstel.
als we hier het object GRONDSCHEIDINGEN van maken is mij dit ook prima.
mis ik in je lijstje de zogenaamde "antiwortelschermen/panelen" dus de wat stijvere variant van t antiworteldoek?
voorbeeldje:
https://www.intergrow.be/nl/store/openbaar-groen/wortelgeleiding--wortelwering/trg-wortelgeleiding-biologisch-afbreekbaar
en dan dus  in wel of niet biologisch afbreekbaar.

wilde je wel GROND_SCHEIDINGSLAAG laten staan?

**Comment by MvanderHulst** [comment]
@NielsNederpel 
GROND_SCHEIDINGSLAAG mag m.i. ook vervallen.
Het feit dat de grondlaag de functie 'scheiding' heeft, zegt nogsteeds niks over de soort van de grond.
Je zou de grondlaag moeten speciferen en documenteren dat het een scheidingslaag is.

Een wortelscherm is inderdaad ook een leuke.
grondscheidingen zijn primair bedoeld als grond wapening/versterking of scheiding.

Een wortelscherm heeft echt een wezelijk ander doel en zou ik persoonlijk weer niet onder grondscheidingen zetten.
In onze eigen bilibotheek staat deze als OBJECT in GR-WORTELSCHERM.

**Comment by NielsNederpel** [comment]
hmmm ok...kan ik in mee gaan, maar vind je dat dan niet ook voor het door jou genoemde antiworteldoek?...vind ik ook niet "alleen een grondscheiding" zeker niet indien deze in de "vertikale" positie wordt gebruikt....

**Comment by MvanderHulst** [comment]
@NielsNederpel daar heb je helemaal gelijk in.
antiworteldoek is meestal een onderdeel van een verhardingscontructie en niet van grondwerk/grondverbetering....
maar een 'geotextiel' tussen een straatlaag van split 4/6 en een menggranulaat 4/31 wordt ook veel toegepast...
dat is eigenlijk ook weer een onderdeel van de verhardingsconstructie en geen 'grondwerk' of 'groen'.....
idem voor asfaltwapeningen en membramen.

Je kent in de praktijk volgens mij 3 smaken...
- doeken/textielen/wapeningen voor grondwerkzaamheden
- idem voor verhardingsconstructies (funderingsopbouwen/asfaltconstructies
- voor groen ken je de 'wortelschermen' de massieve verticale panelen.
- 
hmm... hier ga ik nog even een nachtje over slapen...

**Comment by NielsNederpel** [comment]
hmm niet helemaal...wij brengen verticaal ook wel wortelschermen van folie aan...dan vind ik t niet echt onderdeel van je verhardingsconstructie al wordt deze vaak wel "met" deze werkzaamheden mee aangebracht in de sleuf...maar in iedergeval prima als er "iets" voor in de standaard komt want nu ontbreekt t geheel...:)

**Comment by ElisabethDeVries** [comment]
[[Release note]]  In hoofdgroep GW (GrondWerk) zijn extra objecten toegevoegd voor GRONSCHEIDINGEN: ANTIWORTELDOEK, ANTIWORTELSCHERM, GEOGRID, GEOMEMBRAAN, GEOTEXTIEL.
