### ISSUE TITLE
Presentatie 'perceelsgrensen'

### ISSUE THREAD

**Issue by MvanderHulst** [nl-digigo/NLCS#254]
Graag zou ik de presentatie van de perceelsgrenzen herzien.
De +-P-+-P-+ lijn wordt vaak aangezien als een 'persleiding'.

Na een kort onderzoek bij verschillende ingenieursbureau's is het algemene beeld dat deze altijd wordt aangepast naar een streeplijn en in true color wordt gepresenteerd.

Als bij alle bureau's deze standaard presentatie aanpassen, moet dit misschien in de bron eens worden hierzien?

**Comment by MvanderHulst** [comment]
Voorstel voor lijntype 'Perceelgrens'
De huidige grens lijkt te veel op de PERSLEIDING en deze worden vaak door de war gehaald.
Rustigere lijn is gewenst.

*KG-PERCEEL-SO,__ __ . __ __ . __ __ . __ __ . __ __ .
A, 3.00, -1.50, 3.00, -1.50, 0, -1.50

![image](https://github.com/nl-digigo/NLCS/assets/144665595/473db8fe-fb1e-4767-b95b-a02fd6988986)

Toepassingsvoorbeeld:
[23HB0521-WR-101-1-BO-240213-WOONRIJP MAKEN FASE 1.PDF](https://github.com/nl-digigo/NLCS/files/14996143/23HB0521-WR-101-1-BO-240213-WOONRIJP.MAKEN.FASE.1.PDF)

Aanvullend:
In de hoofdgroep staan de OBJECTEN:
KG-GRENS_KADASTRAAL
KG-GRENS_PERCEEL

Volgens het kadaster is dit 1 ding: een:
KG_GRENS_KADASTRALE PERCEELGRENS

Bovenstaande losse objecten bestaan niet in de termologie.
Voorstel om dit te herzien. en de samenvoegen, bovenstaande lijntype te geven.

**Comment by ElisabethDeVries** [comment]
[[Release note]] In de Hoofdgroep KG (Kadastrale Grenzen) vervalt het object GRENS_KADASTRAAL, omdat dit hetzelfde is als het object GRENS_PERCEEL, hiermee wordt de kadastrale perceelgrens bedoeld. Het lijntype van de kadastrale perceelgrens is nieuw om te zorgen dat het beter te onderscheiden valt van persleiding, en heet nu KG-KADASTRALEPERCEELGRENS-SO.
