### ISSUE TITLE
verwijzing naar 4.7e in par 3.5.6

### ISSUE THREAD

**Issue by SanderNijhof** [nl-digigo/NLCS#258]
In paragraaf 3.5.6 van de Formele Beschrijving wordt verwezen naar paragraaf 4.7e voor verduidelijking over 'Schaalbare Objecten'.
Paragraaf 4.7e bestaat niet meer in de huidige versie van de Formele Beschrijving.
In eerdere versies van de Formele Beschrijving bevatte paragraaf 4.7e de tekst die nu bij paragraaf 4.8 staat: _"De Noordpijl en ruitkruisjes in het bovenstaande voorbeeld zijn ‘schaalonafhankelijke symbolen’. Deze symbolen hebben op een afgedrukte tekening altijd dezelfde afmetingen, onafhankelijk van de voor de tekening gehanteerde schaal."_
Dat is ook de enige vermelding waar SO nog vertaalt wordt naar '**S**chaal**O**nafhankelijk', dat zou '**S**chaalbare **O**bjecten' moeten worden.
Ik zou graag zien dat de verwijzing bij 3.5.6 naar paragraaf 4.7e verdwijnt en er één duidelijke en werkbare beschrijving in de FB word opgenomen met de betekenis van de toevoeging -SO.

Zie ook issue #96

**Comment by MvanderHulst** [comment]
In dit voorbeeld zou de noordpijl juist géén SO symbool moeten zijn, dat deze altijd één afmeting heeft. Uitgaande dat deze natuurlijk in de layout van de tekening wordt geplaatst. Als iemand een noordpijl in de 'model' plaatst, zou deze wél een SO symbool willen toepassen om de juiste grootte op tekening te krijgen. :-)

**Comment by MvanderHulst** [comment]
Zie ook issue #96  m.b.t. 'SO symbolen.
Noordpijl is per definitie een slecht voorbeeld, omdat de verschillende softwarepakketten hier weer anders mee omgaan.
Dus deze verwijzing en toelichting moet sowiezo verdwijnen.

**Comment by SanderNijhof** [comment]
Is dan toch een goed voorbeeld, juist omdat softwarepakketten er verschillend mee omgaan. Dat zou niet moeten.
De vraag is waarom gaan ze er verschillend mee om en hoe voorkomen we dat.

**Comment by MvanderHulst** [comment]
Oplossen volgens #445
