### ISSUE TITLE
Diameter in millimeters

### ISSUE THREAD

**Issue by SanderNijhof** [nl-digigo/NLCS#259]
In de Formele Beschrijving paragraaf 3.3 is opgenomen dat op tekening de tekst "_Diameters in mm, tenzij anders vermeld_" wordt opgenomen. Om welke diameters gaat het dan? Buisdiameters bijv. zijn materiaalmaten en dat valt al onder 'Materiaalmaten in mm'.
Bij paragraaf 4.5.5 worden voorbeelden van maatvoering van diameters aangegeven met '33.16' en '18.42'. Dat lijken mij juist voorbeelden in meters ipv millimeters.

**Comment by MvanderHulst** [comment]
Graag **In de Formele Beschrijving paragraaf 3.3 is opgenomen dat op tekening de tekst "Diameters in mm, tenzij anders vermeld" wordt opgenomen. Om welke diameters gaat het dan? Buisdiameters bijv. zijn materiaalmaten en dat valt al onder 'Materiaalmaten in mm'.** als leidend houden.
Bij een buis/riooltekeningen wordt altijd de diameter in millimeters aangegeven.
Ook voor OVL wordt alles in mm verklaard.

Voorbeeld in meters zou m.i. aangepast moeten worden.

**Comment by MvanderHulst** [comment]
Zie issue #32 

Waarom MOET de diameter in MM? Radius is ook in meters
Heeft dit nut? Zonee, mag de toelichting in 3.3 van mij komen te vervallen.

**Comment by SanderNijhof** [comment]
> ik haal het voorbeeld van de diameters weg uit de FB

Het gaat niet zozeer om het voorbeeld. Ooit is aan de FB toegevoegd dat de tekst  "Diameters in mm, tenzij anders vermeld" op een tekening opgenomen moet worden. Maar die tekst voegt niets toe, in tegendeel. Tenzij iemand kan uitleggen waarom juist diameters in tegenstelling tot alle andere maten in mm moeten zou die tekst uit par 3.3 gehaald moeten worden.
Als de uitleg is "diameters van buizen" dan betreft het materiaalmaten en die vallen al onder "materiaalmaten in mm".
Als ik een gat graaf met een diameter van 5 meter, zie ik niet in waarom ik alleen die maat in mm moet schrijven (zonder mm erachter te moeten zetten) of een 'm' achter de maat moet toevoegen, terwijl alle andere afstandmaten standaard wel in meters zijn.

**Comment by ElisabethKloren** [comment]
Ik lees de tekst in de FB met letterlijke interpretatie zo: De tekst beschrijft, dat hoe op tekening moet aangeven welke eenheid je gebruikt hebt, en dat je bij afwijkingen op die eenheid de eenheid moet weergeven bij de maat.

De eenheden die in de voorbeelden worden gegeven zijn dus niet de verplichte eenheden, maar alleen voorbeelden

Gezien de verwarring die ontstaat heb ik gewoon een voorbeeld weggehaald. 

Als er nog steeds verwarring ontstaat, kan ik de voorbeelden aanpassen naar [eenheid]  in plaats van m of mm aan te duiden

**Comment by SanderNijhof** [comment]
De vraag blijft: "Waarom moeten diameters standaard en mm aangegeven worden." 
De verwarring is nietde beschrijving in de FB, maar de verwarring die het volgen van de FB veroorzaakt in tekeningen:
Zoals ik hierboven beschrijf: een lengtemaat is volgens de FB standaard in meters en dus noteer je 2 meter als "2,00" zonder toevoeging van eenheid. Een diameter-afstand van 2,00 meter moet je volgens de FB standaard noteren in millimeters als "2000" zonder eenheid of als "2,00m" met eenheid. Dat onderscheid vind ik slecht bedacht. Ik zie die tekst en par 3.3 graag verdwijnen!
Ik heb het dan dus niet over een diameter van een leiding of buis, want die valt onder "Materiaalmaten in mm".

**Comment by ElisabethKloren** [comment]
Ik open deze issue wegens de verwarring. 

Check 1: in [deze tekst over eenheden, paragraaf 3.3](https://nl-digigo.github.io/NLCS/requirementscadmodels/#eenheden) staat dat je zelf mag kiezen of je m of mm gebruikt, en dat je op tekening je eenheid moet aangeven in het opmerkinggedeelte van de strook voor de verklaring boven of links naast het stempel worden weergegeven. Daar dienen de bijbehorende voorbeelden voor. Dus er is GEEN verplichting om materialen of diameters in m of mm te doen. Toch?

Check 2: in [deze tekst over aanduiding van diameters](https://nl-digigo.github.io/NLCS/requirementscadmodels/#aanduiding-van-cirkels-bogen-diameter-straal) worden voorbeelden van maatvoering van diameters aangegeven met '33.16' en '18.42, dat zijn voorbeelden van meters, maar dat mag ook volgens paragraaf 3.3, toch?

**Comment by SanderNijhof** [comment]
> Check 2: in [deze tekst over aanduiding van diameters](https://nl-digigo.github.io/NLCS/requirementscadmodels/#aanduiding-van-cirkels-bogen-diameter-straal) worden voorbeelden van maatvoering van diameters aangegeven met '33.16' en '18.42, dat zijn voorbeelden van meters, maar dat mag ook volgens paragraaf 3.3, toch?

Dat mag ook, maar volgens paragraaf 3.3 zet je deze tekst op elke tekening:
_Maten in meters, tenzij anders vermeld  
Materiaalmaten in mm, tenzij anders vermeld 
Peilmaten in meters t.o.v. N.A.P., tenzij anders vermeld  
Diameters in mm, tenzij anders vermeld_ 
De combinatie van "Maten in meters" en "Diameters in mm" strookt wat mij betreft niet met elkaar. Een diameter kan ook een (afstand)maat zijn ipv een materiaalmaat.

**Comment by ElisabethKloren** [comment]
> Dat mag ook, maar volgens paragraaf 3.3 zet je deze tekst op elke tekening:

ik lees dit anders, de tekst zijn een voorbeeld (als staat ook "als in het voorbeeld", je hoeft deze teksten niet over te nemen

**Comment by SanderNijhof** [comment]
> ik lees dit anders,

Volgens mij heb jij het over https://nl-digigo.github.io/NLCS/requirementscadmodels/#eenheden. Ik heb het over de Formele beschrijving NLCS 5.0, daar staat "_De gebruikte eenheid voor maataanduidingen moeten als volgt in het opmerkinggedeelte van de strook voor de verklaring boven of links naast het stempel worden weergegeven:_ "

Die verplichting komt te vervallen in 5.1?

**Comment by ElisabethKloren** [comment]
sorry, ik had die tekst inderdaad al geredigeerd. Even een snapshot uit de FB 5.0:

![image](https://github.com/nl-digigo/NLCS/assets/48585720/f7276a8a-d472-43ad-bc5d-27d0dd2504f6)

Ik lees hier dus vier voorbeeldteksten in de bullets, maar niet dat je deze eenheden moet gebruiken of ze alle vier op je tekening moet zetten

**Comment by SanderNijhof** [comment]
> Ik lees hier dus vier voorbeeldteksten in de bullets,

Ik zie geen bullit bij elk voorbeeld.
Nee. Uitgelegd is dat deze tekst in z'n geheel op een tekening moet staan. 
De 4e regel "Diameters in mm, tenzij anders vermeld" is er als laatste aan toegevoegd, wat geen toegevoegde waarde voor de FB heeft als die optioneel zou zijn. Bovendien staat er duidelijk '_moeten als volgt_' en niet bijv. '_kunnen als volgt_'. Het gaat erom, dat wanneer aan een maat geen eenheid is toegevoegd, duidelijk is in welke eenheid die maat gelezen moet worden.

**Comment by ElisabethKloren** [comment]
ik blijf de tekst anders interpreteren, want 'moeten als volgt" betekent in mijn ogen "moeten op deze manier' maar er staan niet per sé dat die teksten altijd allemaal op tekening moeten staan of dat dit de gebruikte eenheden moeten zijn.

En er staat ook duidelijk dat maataanduidingen meters of milimeters kunnen zijn.

De experts die reageren hebben duidelijk een verschil in interpretatie van deze tekst. Ik verduidelijk bij deze dat het een voorbeeld is een geen verplichting.

**Comment by MvanderHulst** [comment]
@ElisabethKloren en @SanderNijhof
Deze eerste drie regels moeten altijd standaard op een tekening staan:
![image](https://github.com/user-attachments/assets/390099a3-5e44-4530-bf5e-7c8b8646172d)

Dit zijn standaard uitgangspunten welke al jaren op tekeningen worden vermeld, zelf al voor het bestaan van de NLCS. Er is 'ergens' een NEN-EN norm die hieraan ter grondslag ligt.

De reden hiervoor is om juridisch ingedekt te zijn bij samenwerking tussen 'bouw' en 'infra' bedrijven.

De vierde regel is later bijgevoegd, welke inderdaad overbodig is naar mijn idee omdat dit vaak materiaalbeschrijvingen zijn, welke al door de 2e bullet worden ondervangen.

**Comment by ElisabethKloren** [comment]
all right, dan beschrijf ik dit dus wel als verplichting, al blijft me onduidelijk of je de eenheid wel of niet mag wisselen.

**Comment by SanderNijhof** [comment]
> De vierde regel is later bijgevoegd, welke inderdaad overbodig is naar mijn idee omdat dit vaak materiaalbeschrijvingen zijn, welke al door de 2e bullet worden ondervangen.

Wat mij betreft is het niet uit te leggen dat je diameters die geen betrekking hebben op materiaalmaten in mm noteert, en hoogtes, lengtes, breedtes en stralen wel standaard in m. Vooral verwarrend. Kan alleen bedenken dat dit ten onrechte is toegevoegd voor bijv. kabel en buisdiameters, maar die vallen zoals gezegd onder de 2e regel materiaalmaten.

Voor de duidelijkheid dus alleen de 1e 3 regels behouden en regel 4 laten vervallen:
**Maten in meters, tenzij anders vermeld
Materiaalmaten in mm, tenzij anders vermeld
Peilmaten in meters t.o.v. N.A.P., tenzij anders vermeld**
D̷i̷a̷m̷e̷t̷e̷r̷s̷ ̷i̷n̷ ̷m̷m̷,̷ ̷t̷e̷n̷z̷i̷j̷ ̷a̷n̷d̷e̷r̷s̷ ̷v̷e̷r̷m̷e̷l̷d̷

**Comment by ElisabethKloren** [comment]
Dank, ik heb het inderdaad op deze manier overgenomen in de documentatie  https://nl-digigo.github.io/NLCS/requirementscadmodels/#eenheden
