### ISSUE TITLE
#1574 voor Nuts bedrijven is het belangrijk dat bewerkingen ook aan objecten met de status Bestaand kan worden toegevoegd. 

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#26]
#1574	"ZOals jullie wellicht weten is het mogelijk om Bewerkingen aan (sub)objecten in de laag toe te voegen, dit geldt echter alleen voor objecten in de status Nieuw/tijdelijk. Maar voor Nuts bedrijven is het belangrijk dat bewerkingen ook aan objecten met de status Bestaand kan worden toegevoegd. Denk bijvoorbeeld aan het omhoogbrengen van een leiding, of volschuimen van een leiding. Nu kunnen wij de bewerking officieel niet toekennen aan bestaande objecten. Graag hoor ik van jullie of dit kan worden toegevoegd aan de NLCS omschrijving.
"

**Comment by SanderNijhof** [comment]
De status betreft de situatie van het object. Als je een bestaand object wijzigt, dan krijgt dat object een andere status zoals bijvoorbeeld de status Nieuw, omdat deze afwijkt van de bestaande status. Heeft een bestaand object de status Nieuw gekregen, zonder dat het object eerst is verwijderd, dan betreft het een wijziging van het bestaande object.

**Comment by MvanderHulst** [comment]
Lastige discussie..... afhankelijk van het soort tekenwerk.
Als je puur naar 'DATA' kijkt, wordt de data van een object 'gereviseerd' naar 'buiten werking gesteld' Tekentechnisch zou R dan logisch zijn. Echter is het nogsteeds een B-object in het veld, welke een nieuwe bewerking krijgt.
Zodoende is een bewerking een 'nieuw' uit te voeren handeling en zou de status N logisch zijn. Echter is het object nogsteeds een B object.
Een object een bewerking meegeven is dan m.i. onlogisch, en volschuimen/relinen e.d. zou een extra getekend object moeten zijn.... een verplaatsing is de status R weer logisch... Teken je als engineer of als 'beheerder'

**Comment by SanderNijhof** [comment]
In mijn beleving is een object dat wijzigt geen B-object meer. De B-estaande status van dat object wijzigt nl. Dus wordt het een N-, V-, of T-object en uiteindelijk R-. Een B-estaand object is altijd een onbewerkt object, dat is de definitie van 'Bestaand'.

**Comment by MvanderHulst** [comment]
Ben ik helemaal met je eens. zodoende zou een 'bewerking' altijd een Extra laag zijn met de status N als zijnde uit te voeren werk, zonder dat de bron-lijn aangepast wordt. Dit blijft op B staan.
Bij geautomatiseerde beheer-aanpas-systemen is dat natuurlijk weer lastig. Maar dat is de lastige discussie. is het een engineeringsstandaard, of een standaard voor de uitwisseling tussen beheer-ontwerp-revisie.
Beide werelden samenbrengen gaat met de huidige NLCS niet lukken.
Dan zou er een extra status M voor mutatie bijgevoegd moeten worden. Wat dan de combinatie is van 'Bestaand' en een bewerking. :-)

**Comment by ElisabethKloren** [comment]
sander zegt: Niet logische interpretatie. Uitleggen in FB. Als je een object bewerkt, is dat vaak een bestaand object, maar het betreft dan een nieuwe status van dat bestaande object, dus N-

**Comment by ElisabethKloren** [comment]
ik sluit deze issue af wegens dubbel met #145
