### ISSUE TITLE
Molgoot in hoofdgroep riolering?

### ISSUE THREAD

**Issue by MvanderHulst** [nl-digigo/NLCS#268]
Molgoot staat in de hoofdgroep riolering, deze zou in de hoofdgroep verhardingen moeten staan.
In de hoofdgroep verhardingen ontbreekt de molgoot en schijngoot juist weer.

**Comment by ElisabethKloren** [comment]
in het gwsw wordt dit gedefinieerd, als onderdeel van stedelijk water (aka riolering) : https://data.gwsw.nl/Molgoot/
Het lijkt dus een willekeurige keuze waar deze geplaatst wordt qua hoofdgroep; begrijp ik goed, dat je redeneert dat je een molgoot intekent op het moment dat je de verharding ontwerpt, en je hem dus ook daar wilt vinden? Aan de andere kant wil een ander misschien alle rioleringsonderdelen kunnen selecteren en is het handig om dit onder hoofdgroep riolering te hebben. 

Schijngoot komt niet voor in GWSW en ook niet in NLCS?

**Comment by MvanderHulst** [comment]
Een molgoot en schijngoot zouden zowieso in 'VERHARDING' opgenomen moeten worden.
Vanuit engineering/RAW-Systematiek is het een verhardingsonderdeel.

Mogelijk is een molgoot ook in GWSW defefineerd, maar ik kan mij niet voorstellen dat er ook maar één civiel tekenaar is die een molgoot op 'RI' wilt zien.

**Comment by ElisabethKloren** [comment]
Zou het dan logisch zijn om de onderdelen HWA_GOOT allemaal te verplaatsen naar VH_GOOT en een schijngoot toe te voegen?

Ik vindt het moeilijk dan in de VH_GOOT een materialen indeling is opgenomen, en in HWA_GOOT meer een ontwerpoplossing?
Appels en peren?
<img width="153" alt="VH_GOOT" src="https://github.com/nl-digigo/NLCS/assets/48585720/8c2622e4-e151-4d55-ad99-903365847b8a">
<img width="184" alt="HWA_GOOT" src="https://github.com/nl-digigo/NLCS/assets/48585720/6eccf5e0-d88d-4c93-91df-eca2896ce28b">

**Comment by MvanderHulst** [comment]
naar mijn idee moet hier secuur naar de objecten gekeken worden:
een LIJNGOOT en en KOLK zijn funcitoneel 'hetzelfde' en passen prima in riolering.
een MOLGOOT en SCHIJNGOOT zijn verhardingen.
Hier is vanuit de techniek geen enkele discussie over.

De huidige indeling van 'GOOT' in de verhardingen is m.i. ook niet logisch opgenomen.
GOOT_ASFALT is een combinatie van een 'functie' en het 'materiaal'. De soort ontbreekt hier echter.
Logischer zou zijn:
MOLGOOT
MOLGOOT_BETONSTRAATSTENEN
MOLGOOT_STRAATBAKSTENEN
MOLGOOT_TEGELS

SCHIJNGOOT
SCHIJNGOOT_BETONSTRAATSTENEN
SCHIJNGOOT_STRAATBAKSTENEN
SCHIJNGOOT_TEGELS

MOLGOOT_ASFALT, vindt ik dubieus... ik ken geen goten van asfalt?
MOLGOOT_ZOAB, deze kan sowiezo weg, gezien ZOAB een asfaltsoort is en dus dubbel is met bovenstaande. anders zou je alle asfaltsoorten moeten toevoegen...

**Comment by ElisabethDeVries** [comment]
verplaatsing van objecten naar geheel andere hoofdgroepen worden wegens impact op gebruikers meegenomen in release 6.0
