### ISSUE TITLE
lijnkleuren tabel lijkt niet uit linked data versie te komen?

### ISSUE THREAD

**Issue by ElisabethDeVries** [nl-digigo/NLCS#269]
Tabel lijnkleuren lijkt te ontbreken in nieuwe database:
CREATE TABLE `lijnkleuren` (
  `id` int(6) NOT NULL AUTO_INCREMENT,
  `fase` char(2) NOT NULL DEFAULT '',
  `nummer` int(4) NOT NULL DEFAULT 0,
  `omschrijving` varchar(12) NOT NULL DEFAULT '',
  `hex` varchar(9) NOT NULL DEFAULT '',
  `R` int(3) NOT NULL DEFAULT 0,
  `G` int(3) NOT NULL DEFAULT 0,
  `B` int(3) NOT NULL DEFAULT 0,
  `opt` varchar(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=356 DEFAULT CHARSET=latin1;

INSERT INTO `lijnkleuren` VALUES('100','0','0','','#000000','0','0','0','');
INSERT INTO `lijnkleuren` VALUES('101','0','1','','#FF0000','255','0','0','');
INSERT INTO `lijnkleuren` VALUES('102','0','2','','#FFFF00','255','255','0','');
INSERT INTO `lijnkleuren` VALUES('103','0','3','','#00FF00','0','255','0','');
INSERT INTO `lijnkleuren` VALUES('104','0','4','','#00FFFF','0','255','255','');
INSERT INTO `lijnkleuren` VALUES('105','0','5','','#0000FF','0','0','255','');
INSERT INTO `lijnkleuren` VALUES('106','0','6','','#FF00FF','255','0','255','');
INSERT INTO `lijnkleuren` VALUES('107','0','7','','#FFFFFF','255','255','255','AZG');

Of is het wel aanwezig, hoe kan het dan gequeried worden?

**Comment by ElisabethKloren** [comment]
@gerritversteegh volgens mij is deze tabel nooit in de beheeromgeving opgenomen; bij de NLCS objecten wordt verwezen naar lijnkleuren met een bepaald nummer, in deze tabel worden daarbij de rgb nummers en nog wat attributen meegegeven. Zou je deze tabel alsnog willen opnemen in de beheeromgeving?

de bron is hier: https://github.com/nl-digigo/NLCS/tree/main/tabellen/Versie-5.0/NLCS-sql-5.0

wat mij betreft met deze attributen:

`id` int(6) NOT NULL AUTO_INCREMENT,
  `fase` char(2) NOT NULL DEFAULT '',
  `nummer` int(4) NOT NULL DEFAULT 0,

  `hex` varchar(9) NOT NULL DEFAULT '',
  `R` int(3) NOT NULL DEFAULT 0,
  `G` int(3) NOT NULL DEFAULT 0,
  `B` int(3) NOT NULL DEFAULT 0,
  `opt` varchar(4) NOT NULL,

**Comment by gerritversteegh** [comment]
@ElisabethKloren De data bestaat grotendeels uit getallen en heeft geen duidelijke naam zoals dat bij de NLCS objecten/arceringen/symbolen/lijntypes het geval was. Binnen Laces moeten we er wel een naam aan geven, wil je deze namen baseren op de IDs van de lijnkleuren? Of liever op basis van (een combinatie van) andere kolommen uit de tabel?

**Comment by ElisabethKloren** [comment]
Moeilijke vraag, ik zie in de objectentabellen een kleurnummer staan, even kijken of ik dat kan terugvinden welke van de drie cijferreeksen in de sql tabel met lijnkleuren dat is, echt slecht gedocumenteerd dit weer, maar even kijken -- bij beplanting staat B-color 90 in de tabel, de ID's beginnen bij honder, ik denk dat je dus als naam het "nummer" moet hebben uit de tabel:

 `id` int(6) NOT NULL AUTO_INCREMENT,
  `fase` char(2) NOT NULL DEFAULT '',
  `nummer` int(4) NOT NULL DEFAULT 0,
  `omschrijving` varchar(12) NOT NULL DEFAULT '',
  `hex` varchar(9) NOT NULL DEFAULT '',
  `R` int(3) NOT NULL DEFAULT 0,
  `G` int(3) NOT NULL DEFAULT 0,
  `B` int(3) NOT NULL DEFAULT 0,
  `opt` varchar(4) NOT NULL,
  PRIMARY KEY (`id`)

**Comment by ElisabethKloren** [comment]
bij de nieuwe publicatie komt deze er keurig uit rollen
