### ISSUE TITLE
200 missende lijntypes in nieuwe database

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#271]
200 lijntypes staan wel in de oude database, maar worden niet gevonden door de query in de nieuwe database; te onderzoeken waar de fout zit, in database, in publicatie of in query; of gaat dit om vervallen lijntypes? > dat lijkt het niet te zijn

https://github.com/nl-digigo/NLCS/blob/main/code/Query%20lijntypes.rq

**Comment by gerritversteegh** [comment]
Is er een lijst met de missende lijntypes beschikbaar? Ik heb de lijntypes uit de LDP publicatie vergeleken met de lijntypes uit het Excel bestand, en daaruit blijkt dat er 2 lijntypes missen in de LDP publicatie. Dit betreft de lijntypes met ID 349 en 350, en die zijn overgeslagen omdat er al andere lijntypes met identieke namen bestaan (zie screenshot). De namen van de lijntypes zijn gebaseerd op HOOFDGROEP, LIJNTYPE, FASE, en OPTIE.

![image](https://github.com/nl-digigo/NLCS/assets/157105462/4a1c1f07-6dc2-4102-97ec-fdf9b88a36cb)

Ik ben er dus nog niet achter gekomen waardoor er zoveel lijntypes missen, het zou kunnen dat er een verouderd Excel bestand is gebruikt voor de import. Het gebruikte bestand is echter van NLCS 5.0 dus dit zou moeten kloppen. Zie bijlage voor het gebruikte Excel bestand, is dit het juiste bestand en is deze up-to-date?

[NLCS-LIJNTYPES-5.0.xls](https://github.com/nl-digigo/NLCS/files/14167910/NLCS-LIJNTYPES-5.0.xls)

**Comment by ElisabethKloren** [comment]
@gerritversteegh ik vermoed dat het probleem is, dat je op twee manieren lijntypes kan vinden: de lijntypes die als attribuut aan een NLCS object hangen dat zijn er minder dan de lijst met lijntypes die je met die Excel importeert. Dus hopelijk is de oplossing een tweede query die de andere soort lijntypes oproept

**Comment by ElisabethKloren** [comment]
er is al een query naar de gemodelleerde lijntypes (in vervallen), deze geeft de "totale lijst", de andere query is de lijst met "gebruikte lijntypes"

**Comment by ElisabethKloren** [comment]
check op de verschillen, zie ook de issue van Michel over niet-gebruikte lijntypes

**Comment by ElisabethKloren** [comment]
deze query leidt tot 539 lintypes: https://github.com/nl-digigo/NLCS/blob/main/code/vervallen/QueryLijntypes.rq\

deze ook: https://github.com/nl-digigo/NLCS/blob/main/code/Query%20lijntypes.rq

mmmm ik heb query cursus nodig

**Comment by gerritversteegh** [comment]
Ik heb de [query](https://github.com/nl-digigo/NLCS/blob/main/code/Query%20lijntypes.rq) geupdated. Nu leidt de query tot 541 lijntypes, dat zijn alle lijntypes die in het Excel bestand stonden m.u.v. de lijntypes met dezelfde naam (zie ook [deze comment](https://github.com/nl-digigo/NLCS/issues/271#issuecomment-1927322417))

**Comment by ElisabethKloren** [comment]
in de sql database is een tabel met lijntypes, daar staan er 753 in (en iets wat ik niet snap, een nummering -1 en een -2)  https://github.com/nl-digigo/NLCS/tree/main/tabellen/Versie-5.0/NLCS-sql-5.0

in de objectentabellen is sprake van lijntypes in de attributen (in de sql database heten de kolommen lt_b, lt_n, lt-t) > daar wordt verwezen naar de nummering van de lijntypes en niet alle lijntypes uit de lijntypetabel worden gebruikt

als je dus alle lijntypes hebt overgenomen uit de objectentabellen, dan zijn het er minder dan de lijst met lijntypes uit de sql database. 

omdat we versie 5.0 ongewijzigd willen laten moeten we wel alle lijntypes hebben

even gecheckt qua ID's van lijntypes die uit de query komen, inderdaad worden niet alle opvolgende nummers gebruikt

**Comment by ElisabethKloren** [comment]
> Is er een lijst met de missende lijntypes beschikbaar? Ik heb de lijntypes uit de LDP publicatie vergeleken met de lijntypes uit het Excel bestand, en daaruit blijkt dat er 2 lijntypes missen in de LDP publicatie. Dit betreft de lijntypes met ID 349 en 350, en die zijn overgeslagen omdat er al andere lijntypes met identieke namen bestaan (zie screenshot). De namen van de lijntypes zijn gebaseerd op HOOFDGROEP, LIJNTYPE, FASE, en OPTIE.
> 
> ![image](https://private-user-images.githubusercontent.com/157105462/302346845-4a1c1f07-6dc2-4102-97ec-fdf9b88a36cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MjA4NTcsIm5iZiI6MTcwNzgyMDU1NywicGF0aCI6Ii8xNTcxMDU0NjIvMzAyMzQ2ODQ1LTRhMWMxZjA3LTZkYzItNDEwMi05N2VjLWZkZjliODhhMzZjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QxMDM1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjgzOTk5MTZiOGI3Zjg2NDA4NTJjMWRhZjlkMDA3OWJkYzgwOGZjYzkxMGNlOTMxYThhYmQyNGZkMzA0YTg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wtqlif9FvGDrzPiXFmW_XlJc_inci1lsdSTTKB7NWQA)
> 
> Ik ben er dus nog niet achter gekomen waardoor er zoveel lijntypes missen, het zou kunnen dat er een verouderd Excel bestand is gebruikt voor de import. Het gebruikte bestand is echter van NLCS 5.0 dus dit zou moeten kloppen. Zie bijlage voor het gebruikte Excel bestand, is dit het juiste bestand en is deze up-to-date?
> 
> [NLCS-LIJNTYPES-5.0.xls](https://github.com/nl-digigo/NLCS/files/14167910/NLCS-LIJNTYPES-5.0.xls)

De Excel tabel geeft de gebruikte lijntypes weer, niet de complete lijst.

**Comment by ElisabethKloren** [comment]
Dat leidt bij mij ook tot de vraag, wat wordt in het .lin bestand geëxporteerd? alle of alleen de gebruikte?

**Comment by ElisabethKloren** [comment]
@gerritversteegh  wil jij de lijntypes importeren zoals die opgesomd zijn in de tabel in de sql database: https://github.com/nl-digigo/NLCS/tree/main/tabellen/Versie-5.0/NLCS-sql-5.0

Als je goed is heb je er dus al een heleboel

Van deze tabel graag de volgende attributen opnemen: 

  `id` int(10) NOT NULL AUTO_INCREMENT,
  `hoofdgroep` varchar(2) NOT NULL,
  `lijntype` varchar(100) NOT NULL,
  `fase` varchar(2) NOT NULL,
  `optie` varchar(4) NOT NULL,
  `autocaddef` varchar(300) NOT NULL,
  `omschrijving` varchar(100) NOT NULL,

**Comment by ElisabethKloren** [comment]
dit is opgelost, er ontbreken alleen de vervallen lijntypes
