### ISSUE TITLE
Kleuren grondwerklijnen aanpassen van groen naar bruinisch

### ISSUE THREAD

**Issue by MvanderHulst** [nl-digigo/NLCS#275]
De kleuren van de grondwerklijnen zijn standaard 'groen'.
Dit is zeer verwarrend met het gezamelijk gebruik van lijnen voor groenobjecten.
Graag de kleuren van grondwerk aanpassen naar bruin-achtige tinten, of in ieder geval dat ze goed onderscheidbaar zijn van andere veelgebruikte objecten.

**Comment by MvanderHulst** [comment]
Zie ook isue #387 voor het voorstel.

**Comment by ElisabethDeVries** [comment]
[[Release note]] Hoofdgroep GW (GrondWerk): De kleur van de GRONDWERKLIJN was een groene lijn, visueel zeer onduidelijk i.r.t. groenobjecten. Dit is aangepast naar GRONDWERKLIJN, kleur 43; GRONDWERKLIJN_TEEN, kleur 33; GRONDWERKLIJN_KRUIN, kleur 53. Nieuwe objecten zijn toegevoegd: GRONDWERKLIJN_KNIKLIJN, kleur 63 en GRONDWERKLIJN_ONDERWATER rood, om duidelijk verschil tussen nat en droog grondwerk aan te kunnen geven.
