### ISSUE TITLE
FB 3.5.2, NEN-ISO 128- 23:1999, norm bestaat niet meer

### ISSUE THREAD

**Issue by MvanderHulst** [nl-digigo/NLCS#276]
Heel hoofdstuk 3.5.2 verwijst naar de NEN-ISO 128-23:1999, echter bestaat deze norm niet meer.
De uitleg van de linegroups ontbreekt volledig in de FB.
Wie bepaald voor welk object de lineweight?

mag een nieuwe situatie 0.18 lineweight hebben?

**Comment by MvanderHulst** [comment]
Hi Sander,

ik zie alleen 'lijndikte' groepen staan. Ik zie nergens de relatie met statussen o.i.d.
3.5.2.a en c is voor mij een shot hagel.

**Comment by SanderNijhof** [comment]
Hi Michel,

Ik keek naar '_Status bestaand 0.18, overige statussen 0.25_' maar dat staat inderdaad alleen vermeld bij Element 'S'. Voor 'G' geldt volgens 3.5.9d de waarde in de objecttabellen. En daar staan inderdaad lijndikten 0.18mm en zelfs 0.13mm in de kolom voor **N**ieuwe objecten. Om het consequent en duidelijk te houden...

**Comment by ElisabethKloren** [comment]
ok, in de nieuwe nen-norm staan ook gewoon deze waarden, ik zorg wel voor een verwijzing naar die norm.

Voorgestelde wijziging:

* In NLCS wordt bij elke laag en per status een van de standaard lijndiktes voorgeschreven. Deze lijndiktes voldoen aan de [[NEN_EN_ISO_128_2_2022]]
* Om de overzichtelijkheid of duidelijkheid van een tekening te verbeteren, mag een object ook een lijndikte dunner of dikker worden getekend. In onderstaande tabel staan de standaard lijndiktes met de bijbehorende dikkere of dunnere waarde.

<table class="tabel2">
  <tr>
    <td colspan="3">Standaard lijndikten en toegestane dunnere of dikkere lijnen voor leesbaarheid</td>
  </tr>
  <tr>
    <td width="150px">dunner</td>
    <td width="150px"><b>standaard</b></td>
    <td width="150px">dikker</td>
  </tr>
  <tr>
    <td>0.13</td>
    <td><b>0.18</b></td>
    <td>0.25</td>
  </tr>
  <tr>
    <td>0.25</td>
    <td><b>0.35</b></td>
    <td>0.50</td>
  </tr>
  <tr>
    <td>0.50</td>
    <td><b>0.70</b></td>
    <td>1.00</td>
  </tr>
</table>


* Uitzondering op de lijndikte van GD is dat daar waar lijnen dichtvloeien bij het afdrukken (bijvoorbeeld bij doorsneden van damwanden en staalprofielen) juist een pendikte dunner mag worden gebruikt.
Ook voor wapeningstaven geldt een uitzondering: deze kunnen worden getekend met zowel pendikte 0.5 als pendikte 0.7, ongeacht of het een staaf in aanzicht of in doorsnede betreft.
* Uitzondering op het lijntype continuous van -GD; Tenzij dit niet werkbaar is, bijvoorbeeld in het geval van een afbreeklijn, NAP lijn of bestaand maaiveld in doorsnede.
* Lijnen van het ELEMENT GN (Geometrie, niet zichtbaar) worden standaard met de dunnere lijndikte (binnen dezelfde lijngroep) getekend dan in de objectentabellen is aangegeven voor het ELEMENT G.

**Comment by ElisabethKloren** [comment]
Deze wijziging kan straks worden gereviewed als onderdeel van de documentatie. Apart aanbieden aan de Expertcommissie lijkt mij niet nodig daar er geen wijziging uit voortkomt, alleen tekstuele aanpassing. Ik sluit deze issue af.

**Comment by MvanderHulst** [comment]
@ElisabethKloren voorstel is tegenstrijdig met het besluit van issue #17 zodoende weer open.

Ook is de definitie van de toepqssing nogsteeds niet helder.

**Comment by ElisabethKloren** [comment]
> Ook is de definitie van de toepassing nog steeds niet helder.

klopt, er is in deze tekst nog niks bijgekomen, alleen ingekort en nieuwe norm

**Comment by ElisabethKloren** [comment]
en inderdaad, er wordt niet gezegd welke regels er gebruikt worden om een lijndikte te kiezen bij een laag in de standaard, stond ook niet in de oude documentatie
