### ISSUE TITLE
KG-GRENS_KADASTRAAL en KG-GRENS_PERCEEL

### ISSUE THREAD

**Issue by MvanderHulst** [nl-digigo/NLCS#277]
De NLCS bevat de objecten: KG-GRENS_KADASTRAAL en KG-GRENS_PERCEEL
De enigste correcte term is: 'kadastrale perceelgrens'.

Graag deze objecten samenvoegen tot één object zoals het kadaster dit hanteerd.

**Comment by MvanderHulst** [comment]
Zie ook issue #254

**Comment by ElisabethDeVries** [comment]
wegens dubbel op milestone backlog
