### ISSUE TITLE
Arceringen,  wat is VRKL_LANG?

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#279]
wat is VRKL_LANG? > daar staat een gek getal?

In deze attributen van arceringen: 

<img width="528" alt="attributenarceringen" src="https://github.com/nl-digigo/NLCS/assets/48585720/2fcd690c-a7c9-4f5b-8ede-e0b13704668d">

**Comment by SanderNijhof** [comment]
Volgens FB: VKLR_LANG: “VERKLARING LANG”: hierin kunnen teksten worden opgenomen voor het 
automatisch genereren van verklaringen op tekeningen (renvooi).

**Comment by ElisabethKloren** [comment]
> Volgens FB: VRKL_LANG: “VERKLARING LANG”: hierin kunnen teksten worden opgenomen voor het automatisch genereren van verklaringen op tekeningen (renvooi).

de reeksen getallen bij vklr-lang lijken niet overeen te komen met deze beschrijving? is geen tekst?

**Comment by SanderNijhof** [comment]
Volgens mij is het de definitie van het (AutoCAD)pattern. Één van de software leveranciers kan vast helderheid geven of die definitie in dat veld in de database hoort.

**Comment by ElisabethKloren** [comment]
Inderdaad gecheckt:  in AutoCAD kan een arceringspatroon (hatch pattern) worden gedefinieerd met een reeks parameters die de opmaak van de arcering bepalen.
