### ISSUE TITLE
#1547	"We zien dat er spaties staan in de objectnaam en/of subobjectnaam.

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#28]
#1547	"We zien dat er spaties staan in de objectnaam en/of subobjectnaam.

Binnen ons ontwikkelteam is er discussie of een spatie nu wel of niet toegestaan. Voorkeur is niet afdoende in is mijn mening. Dus mag het wel of niet.
En is dit schriftelijk vastgelegd? Zo ja graag aan geven waar dit is gedocumenteerd."

**Comment by MvanderHulst** [comment]
Er staat nergens dat dit niet mag in de FB. indien het op 'object' niveau logisch is, vooral doen lijkt mij.
blablabla_OP HOOGTE BRENGEN-S is logischer dan blabla_OPHOOGTEBRENGEN-S
De strepen zijn de object-scheidende tekens.. spaties zijn gewoon mogelijk. Database zit er vol mee.
Hier heb ik vorigjaar nog een analyse op gedaan en de conclusie is dat alle spaties op een logische plek zijn toegepast.

**Comment by ElisabethKloren** [comment]
wegens dubbeling sluit ik deze issue
