### ISSUE TITLE
Gebruikersvraag: geleideband en soorten geometrie

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#293]
Als ik in de NLCS kijk bij doorsneden → kantopsluitingen → geleideband, dan zie ik een hele rij soorten/maten staan (42 mogelijkheden).
Deze serie van onderscheid zie ik niet terug in de geometrie. Daar zijn de mogelijkheden beperkt tot 2 hoofdmaten.
Dat zou betekenen dat er in de geometrie beperkter getekend kan worden t.o.v. de doorsneden.
 
Aangezien ik samen met een paar collega’s druk ben met situatiemetingen (landmeter) kunnen we blijkbaar in een profielmeting meer informatie kwijt dan in het bovenaanzicht. Maar als er in het dwarsprofiel een geleideband 190-200 geprojecteerd staat, zou die in het bovenaanzicht ook als dusdanig gemeten moeten kunne worden.
Nu kunnen wij daar binnen de landmeetkundige apparatuur wel iets voor bedenken, maar als NLCS het lijnsoort niet beschikbaar heeft wordt het niet getekend.

**Comment by MvanderHulst** [comment]
De vraag klopt niet helemaal er zijn meerdere geometrie objecten beschikbaar in NLCS.
![image](https://github.com/nl-digigo/NLCS/assets/144665595/838ee761-95af-4f82-af68-b716e073964b)

Wel ben ik het ermee eens dat áls de afmetingen in de symbolenbiebliotheek zitten, je deze ook als object moet ontsluiten.
Of je moet de keuze maken om alle doorsnedes enkel op 'GELEIDEBAND' niveau aan te bieden.

InfraCAD heeft ook een zeer uitgebreide extra bibliotheek waarbij veel afmetingen worden toegevoegd.
Ook hierin kan wel een goede slag gemaakt worden.

Uiteraard kan de vraagsteller altijd zelf aanvullende objecten definiëren, maar ik snap de vraag wel.

**Comment by NielsNederpel** [comment]
klopt wat Michel aangeeft.
Verder zijn het geen 42 symbolen maar eigenlijk maar 21. Dit zit hem in het feit dat er voor alle banden een “bestaand” symbool en een “statusloos”symbool is (voor bijvoorbeeld nieuw).
Dan valt dus nog steeds wel op dat er meer doorsnede symbolen zijn dan dat er objecten/lagen zijn.

Hier moeten we denk ik dus wel ook het e.e.a. gaan rechttrekken.
Echter zie ik ook nog enigzins een dubbeling met PWS banden. Bij veel leveranciers staan PWS banden genoemd onder kopje geleidebanden.
Verder zie ik nog wel bij de symbolen een vreemde eend die me meer aan een soort van “havenband” doet denken.
 Maar al met al in mijn idee dus wel iets om op de lijst te zetten om eens meer eenheid in te brengen.

Waarbij we wel ook moeten bedenken dat of wel of niet “compleet willen zijn”. Er zijn namelijk nogal wat leveranciers met net weer een net iets ander type band. (en of andere benaming voor een band!)
Dit is namelijk wel ook de reden geweest om in NLCS 5.0 af te stappen van verschillende lijntypen per afmeting van de verschillende banden. Zodoende dat we nu alleen op “hoofd type band” een onderscheidend lijntype hebben en dan nog 1 of 2 variant lijntypen per hoofd type band zodat visueel er binnen een project toch onderscheid kan worden gemaakt bij gebruik van bijvoorbeeld 2 typen trottoirbanden binnen 1 werk.
![image](https://github.com/nl-digigo/NLCS/assets/143591987/9d08d0a4-d391-47ee-8e9f-27b167716b7c)

**Comment by ElisabethKloren** [comment]
Reactie gebreuiker per mail: Als ik het goed begrijp is er nog werk aan de winkel.
Voor nu kan ik me vinden in het antwoord. De conclusie voor het meten van dwarsprofielen is dat we moeten beperken tot en algemeen symbool voor een kantopsluiting.

En nu we toch hebben over lijnen / lagen / symbolen. Wij, als landmeters, zouden graag zien dat er onderscheid in een fysiek gemeten lijn of symbool mogelijk is t.o.v. nieuw. Daar bedoel ik mee een groter onderscheid dan alleen de kleur grijs en/of laagnaam. Is daar al eens over nagedacht?

**Comment by ElisabethKloren** [comment]
Niels antwoord per mail: Dan even over uw laatste opmerking.
Ik snap niet helemaal wat de meerwaarde is van een beter onderscheid.(zelf dan ook geen landmeter 😊)

Als iets ingemeten is, is dat de nieuwe situatie. Deze kan dan toch in de voorgeschreven NLCS kleuren worden gepresenteerd volgens de “nieuwe” lagen/objecten van de NLCS?
Indien gewenst kan dan onder de ingemeten situatie de “geplande” nieuwe situatie gehangen worden (als Xref) in een grijze kleur?

Of bedoelt u iets heel anders?

> hierover zal nog persoonlijk contact woprden opgenomen met de vraagsteller

**Comment by MvanderHulst** [comment]
Ik snap exact wat de gebruiker bedoeld.
Als een 'bestaande situatie' wordt ingemeten, is dit niet Nieuw, maar bestaand.

Als gebruiker wil je van een object graag duidelijk onderscheid zien tussen bestaande en nieuwe objeten.
enkel de lineweight is hierbij onvoldoende, pas bij het maken van een plot-bestand kan je eventueel iets op grijs zetten waardoor het onderscheid iets duidelijker wordt.

Concreet wilt de gebruiker:
een duidelijk ander symbool voor bestaand en nieuw, zodat onderscheid direct duidelijk is, zoals bij kolken wel (deels) het geval is.

Vanuit de standaard snap ik dat je niet alle symbolen op die manier wilt onderscheiden en dat er gekozen is voor de huidige oplossing.
Wel is het dan weer vreemd dat een aantal objecten wél dit onderscheid maken, nogmaals zoals de kolken.
Hier zo wel éénduidigheid in mogen komen.

**Comment by MvanderHulst** [comment]
Conclusie:
Zelfde als issue #61 en #33 
Gaan we alle doorsneden aanleveren vanuit de standaard?
Zoja: welke leverancier?

Algemeen: voor de OBJECTEN zou ik graag ook naar één leverancier willen als uitgangspunt.
Struyk Verwo is hierbij m.i. de meest logische.
