### ISSUE TITLE
Implementatie-eisen: kleuren en symbolen tewrugzetten naar NLCS vóór uitwisseling

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#296]
Mogelijk gewenste eis aan software-implementatie van NLCS is om eigen kleuren en symbolen op een tekening te kunnen gebruiken van nlcs objecten / symbolen, maar deze bij uitwisseling om te zetten naar standaard kleuren en symbolen van NLCS

open vraag moet dit een implementatie-eis worden?

**Comment by MvanderHulst** [comment]
Absoluut.
Veel standaard-NLCS objecten worden overruled naar andere kleurinstellingen omdat de bibliotheken hierin tekort schieten.
Dit lokaal aan te kunnen passen, maar terug te kunnen zetten naar de standaard is zeker gewenst.
'Controle en herstel' van InfraCAD is een perfect voorbeeld hiervan.
De eigen mogen m.i. uitgebreider naar óók het herstellen van het symbooluiterlijk en het herstellen van linetypes volgens de bron, omdat ook het overschijven van standaard objecten is toegestaan.

Het zou een verplichte optie moeten zijn om de mogelijkheid te hebben om het aangeleverde terug te zetten naar de basis, maar voor de gebruiker geen verplichting en naar behoefte toe te passen.

**Comment by SanderNijhof** [comment]
'Mogelijk gewenste eis' mooi verwoord :-)

> Het zou een verplichte optie moeten zijn om de mogelijkheid te hebben om het aangeleverde terug te zetten naar de basis, maar voor de gebruiker geen verplichting en naar behoefte toe te passen.

Met die gedachte dan ook geen harde eis, maar zoals je zegt wel 'gewenst',  voor de software om het mogelijk te maken om objecten in een andere presentatie weer te geven dan door de NLCS wordt geleverd. Wat mij betreft is de minimale eis het toepassen van de NLCS zoals die geleverd wordt. 

Daarbij WEL de harde eis dat ALS software de mogelijkheid biedt om objecten anders te presenteren dat de software ook de presentatie weer terug kan zetten naar de NLCS basis presentatie.

**Comment by ElisabethKloren** [comment]
op basis van expertadvies 12-04-2024 opgenomen als eis in de documentatie
