### ISSUE TITLE
Implementatieverseisten NLCS applicaties: presentatie (symbology) van objecten

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#299]
•	Wat doen we met presentatie (symbology) van objecten. Deze is nu min of meer vrij vanuit NLCS maar wordt tegelijkertijd wel voorgesteld en er wordt op getoetst
o	Wat ons betreft mag de symbology vastgelegd (voorgeschreven) worden en kan de gebruiker op basis van presentatiemogelijkheden zelf de weergave aanpassen. De onderliggende NLCS-definitie blijft daarbij dus in tact en kan getoetst worden terwijl de gebruiker meerder presentaties vanuit dezelfde basis kang even.
o	Er is eerder al discussie geweest dat deze presentaties uitwisselbaar zouden moeten zijn tussen applicaties zodat een aannemer die met Autocad werkt dezelfde presentatie kan gebruiken al seen Gemeente met MicroStation.

**Comment by SanderNijhof** [comment]
zie ook #296

**Comment by ElisabethKloren** [comment]
dit issue is blijkbaar dubbel met #296, ik sluit het af
