### ISSUE TITLE
NLCS kent geen FysiekeObjecten, alleen informatieobjecten. Objectclassificatie nodig?

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#3]
De hoofdgroepen lijken een representatie van een [nen2660:PhysicalObject](https://w3id.org/nen2660/def#PhysicalObject) te willen aanduiden, maar worden ook als informatieobject gerepresenteerd - dat klopt ook, de laag in een model is een informatieobject 

Te onderzoeken: moet NLCs om "objectgericht" te zijn eigen fysieke objecten definiëren? Of kan het volstaan om een relatie met een ontologie zoals imbor en/of gwsw te hebben om aan te duiden welk objecttype in een laag is getekend?

**Comment by MvanderHulst** [comment]
Persoonlijk zou het mijn voorkeur hebben als (bijna) alle name van de hoofdgroepen ‘object’ georiënteerd zijn en niet ‘functie’ gericht. De standaard is in de basis een ‘engineerings’ stuk gereedschap welke we in de toekomst willen kunnen relateren aan ook de RAW-systematiek voor bestekschrijven.
M.i. heeft een beheerder altijd een aantal fysieke objecten in zijn beheer en kan het dus zijn dat deze onderdeel zijn van verschillende hoofdgroepen binnen de NLCS. Aanvullend zijn er ook een aantal hoofdgroepen die prima onder ‘ZZ’ in te delen zijn, of juist onder te brengen onder de hoofdgroepen.
Zo heb ik bijvoorbeeld veel moeite met:

AM, assen en metrering = FUNCTIE
Alle onderliggende objecten zijn onder te brengen onder reeds bestaande hoofdgroepen.

BV, bermbeveiligingsvoorzieningen. = FUNCTIE omschrijving, geen object.
Wat is dit anders dan een ‘inrichtingselement’?
Vangrail, geleiderail, schrikhek allemaal ‘staal’ voor de inrichting.

FV, faunavoorziening = FUNCTIE
Idem, allemaal objecten welke onderdeel van IE en VH kunnen zijn. Wat is de toegevoegde waarde om deze separaat te zetten?

VW, verkeersmaatregelen weg = FUNCTIE
Allemaal objecten van een ‘wegbeheerder’, deze groep is overduidelijk bedacht om voor een beheerder alles in 1 groep te kunnen plaatsen. Zo is het toch niet uit te leggen dat alle verhardingen in VH staan, maar de ‘parkeervakmarkering’ in een hele andere hoofdgroep VW? Alleen de kleur van de steen is anders.
Idem voor asfaltverharding met thermoplast.
Wat is een ‘afzetpaal’ anders dan een ‘bord’, beide inrichtingselementen.

Verrkeeersmaatregelen is enkel logisch voor het toepassen van tekenwerk volgens CROW 96A/B.
Als dit seperaat wordt gemaakt van de technische tekening, is het weer een logisch geheel.

Kort antwoord:
In de basis NLCS objectgericht indelen.
Uitzonderingen beperken en zijn duidelijk opnoembaar.

**Comment by ElisabethKloren** [comment]
Dit wordt onderzocht in samenwerking met de BIM Basis Infra, dit issue sluit ik voor nu af.
