### ISSUE TITLE
Kaders als niet SO?

### ISSUE THREAD

**Issue by Han-Loermans** [nl-digigo/NLCS#309]
Alle Kaders zijn nu opgenomen als Schaalbaar Object (SO). Op een layout (AutoCAD) is de schaal altijd 1:1, dus een kader zou als een maatvast object toepasbaar zijn. Nu dient de schaal op 1:1000 te staan.
Ook is het een object dat in mm wordt getekend. Dient deze dus als een -MM symbool te worden opgenomen in de bibliotheek?

- [ ] Documenteren werking kaders én omgang met schaalbare objecten in de [Uitleg standaard](https://nl-digigo.github.io/NLCS/functionalspecification)
- [ ] Onderzoeken werking in AutoCAD en Microstation / interoperabiliteitsvraagstuk

**Comment by MvanderHulst** [comment]
Ik dénk dat dit voortkomt uit het feit dat het ook is toegestaan om kaders vanuit je model te tekenen.
Dat je dus het kader verschaalt in de model en geen gebruik maakt van Layouts.
Dat is in ieder geval de techniek die 'Microstation' wel een soort van toepast.

**Comment by SanderNijhof** [comment]
Dit is juist een typisch -SO symbool: op papier heeft dit symbool altijd dezelfde grootte.
> Op een layout (AutoCAD) is de schaal altijd 1:1

Dus in dat geval krijgt conform de FB het symbool een verschalingsfactor 1

> Nu dient de schaal op 1:1000 te staan.

Ik hoop niet dat hier wordt bedoeld in een layout model maar in een (design) modelspace(?) In een modelspace 1:1000 krijgt het SO-symbool conform FB inderdaad een verschalingsfactor 1000, zodat deze op papier dezelfde grootte heeft als bij plaatsing zonder verschaling in een 1:1 model. 
Deze verschalingen zou de NLCS-tooling automatisch moeten regelen zodat de gebruiker daar niets van merkt. Vandaar de toevoeging -SO aan het symbool zodat de NLCS-tooling kan herkennen wat de bedoeling is met het symbool.

**Comment by Han-Loermans** [comment]
Ik lees hierin dat kaders ook nog in de praktijk in de model space worden geplaatst. Dit is iets waar ik zelf niet aan gedacht heb, dit was altijd een doodzonde binnen de organisaties waar ik gewerkt heb. Nu adviseer ik dit ook niet, alleen plaatsen op de layout. En omdat binnen AutoCAD de layout geen schaal bevat/gebruikt zou het totaal geen toegevoegde waarde hebben om deze als -SO object aan te bieden. 
Maar als het gangbaar en regelmatig gebruikt wordt snap ik de redenatie om deze als -SO aan te bieden, zonder het daarmee eens te hoeven zijn.

**Comment by MvanderHulst** [comment]
Binnen de AutoCAD wereld is het inderdaad ondenkbaar om het in de model te plaatsen.
Binnen Microstation wordt het wel toegepast door de NLCS software leverancier.
Nu weet ik al dat al onze Microstationgebruikers de 'kader' module van Optimze totaal niet logisch vinden en ook graag de 'kaders' op de AutoCAD manier zouden willen tekenen, maar de softwaretool dwingt dit af.

**Comment by MvanderHulst** [comment]
Concreet voorstel:
AutoCAD uitgangspunt:
Kaders worden in de layout geplaatst.
De layout omgeving betreft inderdaad een omgeving in millimeters.
De namen van de kaders nalopen en voorzien van de MM aanvulling is dan ook logisch.
In de tooling gaat dit nu echter wel goed... units van het block en de tooling zouden dan ook goed gecontroleerd moeten worden.
Omdat de kaders in de layout staan en verschaling middels een viewport gebeurd, is het kader altijd op ware grootte en dus geen 'Schaalbaar Object' of 'Symbolisch Object', oftewel een '-SO' symbool.
Om de toevoeging -SO weg te halen is vanuit de AutoCAD gedachte volledig logisch.

Binnen Microstation wordt op dit moment de schaal van het kader aangepast naar de presentatie schaal.
Het kader zou in dit geval dus wél -SO moeten zijn, omdat deze anders niet verschaald kan worden.

Hier zit ook direct de eeuwige discussie tussen 'Sander' en 'Mijzelf'.
Microstation gaat heel anders om met het plotten dan AutoCAD dit doet... gaat nooit op 1 lijn komen.
Tenzij TPG dit anders gaat inrichten?

**Comment by SanderNijhof** [comment]
> Hier zit ook direct de eeuwige discussie tussen 'Sander' en 'Mijzelf'.

Volgens de huidige Formele Beschrijving worden symbolen 1:1 getekend en krijgen -SO symbolen een schaalfactor die gelijk is aan de plotschaal. Dus is volgens de huidige beschrijving de toevoeging -SO volledig terecht:
Een symbool KADER-SO wordt 1:1 getekend. Bij een layout op ware grootte, dus 1:1 krijgt de -SO cel een verschalingsfactor 1. Wordt de KADER-SO symbool geplaatst in een designmodel 1:200 dan krijgt het symbool een verschalingsfactor x200 en bij 1:500 een verschalingsfactor x500. Op de afdruk zijn de symbolen in alle 3 de gevallen even groot.
Althans letterlijk conform de Formele Beschrijving, maar dat moet anders. Daar zijn we het over eens toch?

> Microstation gaat heel anders om met het plotten dan AutoCAD dit doet... gaat nooit op 1 lijn komen.
> Tenzij TPG dit anders gaat inrichten?

Dat is toch ook de reden waarom Microstation en AutoCAD layoutmodellen kennen. Maar TPG ziet dat anders. Ik denk dat Optimize van TPG wereldwijd (nagenoeg) uniek is met hun werkwijze. 
Wij gebruiken de plottool van TPG daarom ook niet. En als ik jou zo hoor vraag ik me af wie wel?

**Comment by MvanderHulst** [comment]
@SanderNijhof 
Ik heb de vraag bij TPG terug gelegd, waarom dit is gedaan. Ik ken zelf ook geen enkele Microstation gebruiker die hier wel blij mee is. Lijkt mij iets moois om uniform te maken! :-)

**Comment by ElisabethDeVries** [comment]
Opgenomen tekst volgens issue #379 over hoe plots op te maken

De werkwijze met SO wordt beschreven in issue #445

de mm check wordt uitgevoerd door Michel in issue #183

**Comment by ElisabethDeVries** [comment]
[[Release note]] Alle symbolen SAL-TEKENBLAD zijn vervallen, omdat deze de optie SO hadden terwijl dit SOMM had moeten zijn. Er zijn nieuwe symbolen gemaakt met optie SOMM.

**Comment by ElisabethDeVries** [comment]
reopen voor acceptatie 5.2

**Comment by SanderNijhof** [comment]
> Alle symbolen SAL-TEKENBLAD zijn vervallen, omdat deze de optie SO hadden terwijl dit SOMM had moeten zijn. Er zijn nieuwe symbolen gemaakt met optie SOMM.

Oneens! Dit -SO symbolen houden. Met welke reden is bepaald dat dit SOMM symbolen moeten zijn?
SOMM is alleen relevant voor AutoCAD. Kaders zijn relevant voor ALLE cadpakketten. Daarom tekenkaders SO houden, dus in meters. Of beide opnemen: -SO en -SOMM.
Ik begrijp dit ook niet. Volgens NLCS teken je 1 op 1. Of dit nu meter, millimeters of kilometers zijn. 1m=1000mm. Dit is een AutoCAD technisch iets? Iets met instellen van units ofzo? Dan hebben het ontwerp model en plotmodel verschillende units? Wat mij betreft niet logisch en niet gewenst.

**Comment by MvanderHulst** [comment]
@SanderNijhof in de NLCS (zowel versie 4.2 als 5.0) zijn de kaders gemaakt en aangeboden in millimeters. Zodoende zou SOMM de juiste naamgeving moeten zijn.

**Comment by SanderNijhof** [comment]
@MvanderHulst 
Toevoegingen met MM, zoals -SOMM, zie je in de praktijk eigenlijk alleen bij CONSTRUCTIES en een paar keer bij BERMBEVEILIGINGSVOORZIENINGEN.
Voor CONSTRUCTIES is dat nog wel te verklaren omdat daar vaak met mm gewerkt wordt. Voor BERMBEVEILIGINGSVOORZIENINGEN zie ik de meerwaarde eerlijk gezegd niet zo.
Tekenkaders en de bijbehorende symbolen staan los van disciplines. Daarom zou ik die graag als -SO houden.
Dan blijft het gewoon duidelijk en voorkom je onnodige complexiteit.

**Comment by MvanderHulst** [comment]
@SanderNijhof
Als ik de tekst uit de FB erop nasla:

<img width="993" height="77" alt="Image" src="https://github.com/user-attachments/assets/c91e405c-d504-4765-b0fb-6eebe3b621bb" />

Is dit punt inderdaad wel dubieus. De 'eenheid' van de kaders blocks zijn nog 'Unitless' in de 5.0 versie. Maar hij is wel getekend op MM.
Dit afwijkend op de 'bermbeveiligingsvoorziening', waar de eenheid wel daadwerkelijk in millimeters gezet is.

In het 5.1 concept staan de kaders wel weer op METERS terwijl ze millimeters getekend zijn.
Al met al.... de kaders moeten nog kritisch bekeken worden voor 5.1/5.2

Hierbij direct de SOMM interpretatie scherper neerzetten en de doel bepalen.

@ElisabethDeVries 
Advies is om dit in versie 6.0 in 1x goed te verwerken en de kaders dan voor alsnog even niet aan te passen.
We weten dat er wat geks in zit, maar het hele land werkt er nu wel zo mee.
Noodzaak versus effect is dan niet in verhouding om dit nu allemaal mee te pakken.
