### ISSUE TITLE
#1525	"Basiskleur wit (RGB 255,255,255, de 'wisselkleur')  leveranciersspecifiek

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#31]
#1525	"Basiskleur wit (RGB 255,255,255, de 'wisselkleur') wordt in NLCS toebedeeld aan kleur 7, de standaard wit-kleur voor AutoCAD. In MicroStation wordt hier echter kleur 0 voor gebruikt. In de conversie tussen beide paketten worden deze kleuren netjes op de juiste wijze uitgewisseld.
Graag in de formele beschrijving (in algemene bewoording of specifiek bij artikel 3-5-4.b en ""Conversietabel CAD-kleuren – RGB-codes"") opnemen dat in MicroStation ook kleur 0 gebruikt mag worden voor RGB 255,255,255, de wisselkleur."

**Comment by ElisabethKloren** [comment]
To Do
aanpassen in FB, ook checken in de database

**Comment by MvanderHulst** [comment]
Aan te passen teksten voor de FB:
3.5.4.b
In de NLCS wordt gebruik gemaakt van het kleurenschema dat is weergegeven op pagina 25. Voor lijnen wordt gebruik gemaakt van de AutoCAD kleuren uit de “10-serie” (10, 20, 30, enzovoort), de ‘wisselkleur’ of de grijstinten (zwart in combinatie met transparantie) 250 t/m 254. De corresponderende RGB-waarden zijn weergegeven in de conversietabel. De wisselkleur is de kleur welke wit op een zwarte achtergrond en zwart op een witte achtergrond wordt afgedrukt. Voor AutoCAD is dit kleur 7 en voor Microstation kleur 0.

Pagina 25, convertietabel CAD-kleuren – RGB-codes
Wit/zwart en grijstinten:

Kleur 7 aanpassen naar ‘wisselkleur*’

Toelichting toevoegen:
*De wisselkleur is de kleur welke wit op een zwarte achtergrond en zwart op een witte achtergrond wordt afgedrukt. Voor AutoCAD is dit kleur 7 en voor Microstation kleur 0.

**Comment by MvanderHulst** [comment]
@ElisabethKloren  deze is voor jou.

**Comment by ElisabethKloren** [comment]
verwerkt in de documentatie
