### ISSUE TITLE
Ter besluit OG: in NLCS wel/niet overnemen van 10- en 100 borden op verkeersbordenoverzicht.nl

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#315]
![extraverkeersborden](https://github.com/nl-digigo/NLCS/assets/48585720/6517bda3-b42d-4b73-ad5d-cbc36f8f689e)

De op de website www.verkeersbordenoverzicht.nl genoemde borden met 10.. en 100.. codering maken geen deel uit van de oorspronkelijke uitvraag. 

Voorstel: deze borden nog niet opnemen in NLCS om te zorgen dat we zo snel mogelijk met de standaard borden het werkproces kunnen faciliteren; als uit de analyse van de verkeersbordendata blijkt dat deze extra borden veel gebruikt worden, kunnen ze alsnog worden toegevoegd.

**Comment by MvanderHulst** [comment]
Straatnaamborden zijn ook nogsteeds nergens te vinden! :-)
Idem voor de ANWB fietsroute borden. en de 'groene' borden voor recreatieroutes.

**Comment by ElisabethKloren** [comment]
> Straatnaamborden zijn ook nogsteeds nergens te vinden! :-) Idem voor de ANWB fietsroute borden. en de 'groene' borden voor recreatieroutes.

Inderdaad, helaas is dit buiten scope van het huidige project

**Comment by ElisabethKloren** [comment]
Besproken met OG 6-6-2024: akkoord met deze beperking van scope voor eerste publicatie

**Comment by MvanderHulst** [comment]
Ik gooi de issue nog even op.
Is zie dat verkeersbordenoverzicht.nl wordt gebruikt als referentie?
Deze bordencoderingen wijken af van de RVV-nummers volgens de VNVF.

Graag wel de officiele nummers aanhouden en niet de 'hobby' nummering van de genoemde website!

**Comment by ElisabethKloren** [comment]
we hebben helaas nog van de opdrachtgever, noch van de VNVF een lijst met de bordcodes uit hun boekje mogen ontvangen; dus ik ga het omkeren en aan hen vragen te bevestigen dat we de juiste codes gebruiken

**Comment by ElisabethKloren** [comment]
ik sluit wel deze issue, omdat dit gewoon een vraag was of we deze borden wel of niet meenemen, en deze vraag is beantwoord.

**Comment by ElisabethDeVries** [comment]
[[Release note]] zie #194
