### ISSUE TITLE
Ter besluit OG: in NLCS beperkt aantal borden opnemen, faciliteren van nieuwe codering VNVF via koppeling met informatiemodel

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#317]
Zie voor inhoud vnvf codering deze issue bij het informatiemodel: https://github.com/Stichting-CROW/verkeersborden/issues/239

De NLCS wegontwerpen met verkeersborden gebruikt kunnen/moeten worden door een aannemer/gemeente om borden te bestellen, dat vraagt om standaardisering door de hele keten.

Gewenste situatie lange termijn: opnemen van mogelijkheid om combiborden samen te stellen en teksten / symbolen van onderborden op te nemen volgens de voorgestelde codering. Hiermee kan gezorgd worden dat de verkeersborden op tekening hetzelfde eruit zien als de borden die besteld worden. 

Consequentie: mogelijk leidt dit tot extra kosten voor het opstellen van de werkinstructie en tot inspanningen bij de softwareleveranciers. 

**Voorstel korte termijn: NLCS gaat de meest voorkomende borden bevatten, via het informatiemodel is de VNVF codering van dit bord af te leiden. Het samenstellen van platen en gebruik van minder voorkomende borden wordt niet geregeld in de eerste publicatie van NLCS verkeersborden.**

**Comment by ElisabethKloren** [comment]
Dit voorstel is als aanname gebruikt voor de 5.1 release.

**Comment by ElisabethDeVries** [comment]
[[Release note]]: Zie #194
