### ISSUE TITLE
Ter besluit OG: Afwijking verkeersborden symbolen van NEN productienormen

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#318]
Bij de inhoudelijke controle van de NLCS-bibliotheken bleek ook dat de afmetingen (al dan niet verschaalt) niet overeenkomen met de NEN. 
Als de door de NEN voorgeschreven maatvoering als uitgangspunt aangehouden zou worden zijn de geleverde symbolen bibliotheken niet bruikbaar. 

**Voorstel: dit verschil negeren, de symbolen leesbaar houden in CAD / GIS. Deze worden niet gebruikt als bronbestand voor de productie van de borden.**

**Comment by SanderNijhof** [comment]
De NLCS levert toch helemaal (nog) geen verkeersbordsymbolen? Deze worden geleverd door de software leveranciers.
Hoe dan ook, symbolen zijn figuratief en hebben veelal een schaal zodat deze op tekening goed leesbaar zijn.

**Comment by ElisabethKloren** [comment]
@SanderNijhof we zijn de verkeersbordbibliotheken aan het samenvoegen en standaardiseren; de nen normen zijn normen voor de productie van borden met heel specifieke kleuren, reflectie en maatgeving; de afbeeldingen in CAD wijken daar iets van af voor leesbaarheid inderdaad

**Comment by ElisabethKloren** [comment]
Dit voorstel is  overgenomen in concept-publicatie van release 5.1

**Comment by ElisabethDeVries** [comment]
[[Release note]] Bij de verkeersbordenbibliotheek voor de NLCS standaard zijn CAD-symbolen en svg-afbeeldingen gemaakt van verkeersborden. De kleuren en maten van de symbolen wijken af van de NEN-productienormen. Dit is bewust gedaan, omdat de afbeelding van de borden op een tekening of op een beeldscherm veel kleiner is, en hierbij andere eisen gelden voor de leesbaarheid van het verkeersbord.
