### ISSUE TITLE
Continue updates NLCS

### ISSUE THREAD

**Issue by BTobben** [nl-digigo/NLCS#319]
Is de enige bron waar de actuele informatie van de NLCS te vinden is nu deze github pagina? Hoe kunnen opdrachtgever en opdrachtnemer hier mee up to date blijven als er continue updates doorgevoerd worden in de huidige versie (5.0)?  Als de github de enige actuele bron voor de standaard is, is het dan niet beter de ontwikkelingen in een zijspoor/aparte omgeving te laten lopen en bij release een nieuwe versie uit te brengen?

In de huidige situatie is het volgens mij niet haalbaar om aan de richtlijn te kunnen voldoen als versie 5.0 schijnbaar bijna dagelijks updates ontvangt.

**Comment by ElisabethKloren** [comment]
@BTobben je hebt gelijk; ik heb nu de 5.0 versie in de Readme toegevoegd, dit is de actuele versie; https://github.com/nl-digigo/NLCS/blob/main/docs/archive/Formele_beschrijving_NLCS_versie_5_0_V1_0.pdf

**Comment by BTobben** [comment]
Wat betekend dat voor de blockbibliotheek? Deze staat denk ik los van de formele werkbeschrijving en lijkt soms ook nog onderhevig te zijn aan wijzigingen tussendoor. Word dan aangeraden om alle relevante bestanden nog van de link genoemd in de formele werkbeschrijving (https://www.bimloket.nl/p/429/Documentatie) op te halen om de laatste definitieve 5.0 versie te hanteren?

**Comment by ElisabethKloren** [comment]
Van de blocks / symbolen is de versie op 5.0 vastgesteld en gepubliceerd op GitHub, deze veranderen niet voordat een nieuwe versie van de standaard wordt gepubliceerd https://github.com/nl-digigo/NLCS/tree/main/symbolen/5.0
