### ISSUE TITLE
#1513  De aanhaallijnen van de maatvoering  / De prefix van de radius en diameter aanduidingen.

### ISSUE THREAD

**Issue by ElisabethDeVries** [nl-digigo/NLCS#32]
#1513	"1. In de formele beschrijving staat bij 4.5.5 “De getalswaarde bij een straal moet worden voorzien van het symbool: “ R= “.” In Microstation (en volgens mij in AutoCAD ook?) kun je een straal wel een prefix ‘R’ geven maar ‘R=’ is niet mogelijk. In de formele beschrijving staat dat voor diameter “ø” moet worden toegepast en niet “ø=”, dus daar past ‘R’ ipv ‘R=’ dan ook beter bij.
 

2. Bij het expertcommissie overleg over de NLCS 5.0 release is gezegd, dat in tegenstelling t/m NLCS 4.2 , het opnemen van ‘_X’ in de naam van maatvoeringstijlen verplicht is voor stijlen zonder aanhaallijnen.
Maatvoeringstijlen met aanhaallijnen krijgen conform formele beschrijving NLCS een ‘_A’ in de maatvoeringstijlnaam.

Tot en met NLCS 4.2 was _X toepassen in de stijlnaam optioneel, maar vanaf NLCS 5.0 zou dat verplicht worden.

Ik vind niet terug in de formele beschrijving van NLCS 5.0 dat toepassen van ‘_X’ nu verplicht is:"

Acties die uit deze vraag volgen: 
- [ ] De aanhaallijnen van de maatvoering
- [ ] De prefix van de radius en diameter aanduidingen.

**Comment by ElisabethKloren** [comment]
Reactie Expertcommissie
"1: FB aanpassen zodat beide opties mogelijk worden
2: staat nog niet zo in is in 5.0 dus nog onjuist doorgevoerd in FB."

**Comment by ElisabethKloren** [comment]
To Do
"FB aanpassen: 

4.5.12 (let ook op voorbeelden)"

**Comment by MvanderHulst** [comment]
Bij een eerdere EC is aangegeven dat één van de varianten niet mogelijk was in Microstation.
Toen is besloten dat de 'beperking' van Microstation leidend wordt. Dit om wildgroei te voorkomen en uitwisselbaarheid te borgen.

**Comment by MvanderHulst** [comment]
Hierbij de aangepaste tekst voor hoofdstuk 4.5.5
_**4.5.5 Aanduiding van cirkels/bogen (diameter/straal)
_a. De maataanduiding van de straal van een cirkel moet worden aangegeven met een maatlijn vanuit het
middelpunt en een pijlpunt rakend aan de cirkel. De maataanduiding van de diameter van een cirkel
moet worden aangegeven met een maatlijn door het middelpunt en twee pijlpunten rakend aan de
cirkel. Indien, bij een kleine straal of diameter, de ruimte voor de pijlpunt(en) en de getalswaarde
ontbreekt, mogen deze ook aan buitenzijde van de cirkel of boog worden geplaatst. De getalswaarde
bij een diameter moet worden voorzien van het symbool “ Ø “. De getalswaarde bij een straal moet
worden voorzien van het voorvoegsel: “ R“._**_

Aangepaste bijlage voor FB
![Diameter en Radius](https://github.com/nl-digigo/NLCS/assets/144665595/51c98b13-c840-495a-944d-5cc102574acb)

**Comment by MvanderHulst** [comment]
Bovenstaand is ook 4.5.12 wederom besproken, met betrekking tot de aanhaallijnen van maatvoeringen.

De FB zegt nu dat de toepasbare waarden voor 'AANAALLIJNEN' A (met) of X (zonder) moet zijn.
Dit suggereerd dus dat het altijd één van de 2 is. Zie ook onderstaande afbeelding.
![image](https://github.com/nl-digigo/NLCS/assets/144665595/6d640cfe-4ff0-4c5e-a155-f41e59b15ae4)

De aanpassing die gedaan moet worden is dat 'AANHAALLIJNEN' niet tussen [ en ] moet staan, als zijnde optioneel.
![image](https://github.com/nl-digigo/NLCS/assets/144665595/5cb005cc-4a8b-4f97-bad0-f1a169fcab9a)

**Comment by MvanderHulst** [comment]
In het verleden is ook veel gesproken over de presentatie, grootte e.d.
Veelbesproken onderwerp in het verleden met diverse mailverkeer.
Verzoek om dit in werkgroep / klein comite af te tikken wat nu de status is.

**Comment by MvanderHulst** [comment]
Zie ook issue #75

**Comment by ElisabethKloren** [comment]
https://github.com/nl-digigo/NLCS/tree/main/ontwikkeling/bijlagen_bij_issues/32

**Comment by ElisabethKloren** [comment]
de vraag is, of de leveranciers denken dat dit technisch haalbaar is

**Comment by MvanderHulst** [comment]
@ElisabethKloren is de mail nu verstuurd?

**Comment by ElisabethKloren** [comment]
Beste Expertcommissie NLCS,

In de issues van 5.1 zitten een paar, die impact hebben op software implementatie of controle tooling. Dat zijn de issues waarvan ik graag zou willen, dat jullie die met extra aandacht reviewen. Ik weet dat de officiële reviewperiode van juni al voorbij is…. Maar denk dat het belangrijk is om voor deze meer tijd te geven, terwijl we al aan de slag zijn met de kleine verbeteringen. 

Ik zou jullie willen vragen om deze issues voor 1 september te reviewen en daarbij duidelijk aan te geven of het voorstel moet worden aangepast of uitgesteld naar een volgende release als deze te veel impact heeft.

**Comment by ElisabethKloren** [comment]
sander schreef in mail hierover nog dit: Moeten we issue #32 over uniforme vormgeving van maatvoering ook nog onder de aandacht brengen?
Ik kan de gemaakte afspraken niet terugvinden op GitHub.  Alsnog toevoegen?

Volgens mij hebben we o.a. dit afgesproken:
1.	Grootte van de pijlpunt: 2,5mm lang / 1,0mm breed (40% van de pijlbreedte = AutoCAD standaard) (=aanvulling FB)
2.	Lengte van schrap = 2,0mm onder hoek van 45 graden (=conform FB)
3.	(open)bol hebben een diameter van 1,0mm (=conform FB)
4.	Maatlijn niet 2,0mm doortrekken tot voorbij snijpunt met hulplijn (=wijziging FB)
5.	Hulplijnen 2mm doortrekken tot voorbij snijpunt met maatlijn (=conform FB)
6.	Alle maatlijnen hebben een lijndikte van 0.18mm (=conform FB)
7.	Bij maatvoeren stralen “R=” wijzigen naar of aanvullen met “R” (=wijziging FB)

Volgens de FB moet de getalswaarde van een bemating 1,0mm boven de maatlijn worden geplaatst. Dat houden we ook zo aan?

Aanvullend hierop: 
a.	Voor multileaders is niet aangegeven wat de lijndikte moet zijn.
b.	Voor multileaders is niet aangegeven wat de afstand van de tekst tot de lijn moet zijn. Dit vrij laten of gelijk maken aan die van maatvoeringen = 1,0mm ?
c.	Voor multileaders is aangegeven in de FB dat de tekst altijd in HOOFDLETTERS geplaatst moet worden. Is dat nodig: Bijschrijften in kleine letters, aanpijlingen in hoofdletters?

Ik weet niet of over a,b iets in NEN-ISO 128-22:1999 staat maar als we hier eisen aan gaan stellen dan wel handig om die in de FB op te nemen.

**Comment by ElisabethKloren** [comment]
[Maatvoeringen-Model.pdf](https://github.com/user-attachments/files/16927604/Maatvoeringen-Model.pdf)

**Comment by ElisabethKloren** [comment]
15-12-2022 mailt michel; Het valt me op dat naast verschillen in de vormgeving van de maatvoering er ook verschillende teksthoogten bij bematingen worden gebruikt.
Alleen hoogtematen hebben een teksthoogte van 1,8mm conform de Formele Beschrijving, maar ik zie ook tekeningen waarin alle maten met een teksthoogte van 1,8mm zijn geplaatst.

Is dat nog een aandachtspunt voor NLCS 5.1?


Achtergrond info:
NLCS versie	
t/m 4.0	Teksthoogtes voor alle bematingen gelijk: 2,5mm

4.1 (2016)	De teksthoogte voor hoogtematen aangepast naar 1.8mm. Alle overige maten houden een teksthoogte van 2,5mm
5.0 (2022)	Hoogtematen een teksthoogte van 1.8mm waarbij bestaande hoogten 1.8mm cursief. Overige bestaande maten 1.8mm cursief, nieuwe maten 2,5mm rechtop.


Overzicht teksthoogtes bemating Formele Beschrijving NLCS 5.0: 
paragraaf			Teksthoogte(n)
4.5.7	Plaatsing van bemating	Het lettertype voor de bemating heeft afhankelijk van de toegepaste STATUS een geplotte teksthoogte van 1,8mm (BESTAAND) of 2,5 mm (overige).	1,8mm
2,5mm
4.5.8	Hoogtematen	Het lettertype voor bemating heeft een (geplotte) teksthoogte van 1,8 mm. 
Bestaande maten moeten in cursief lettertype worden weergegeven, nieuwe maten moeten in recht lettertype worden weergegeven.	1,8mm
4.5.9	Metrering	Het lettertype voor de bemating heeft afhankelijk van de toegepaste STATUS een geplotte teksthoogte van 1,8mm (BESTAAND) of 2,5 mm (overige).	1,8mm
2,5mm
4.5.10a	Horizontale Alignementen	Het lettertype voor bemating heeft een geplotte teksthoogte van 2,5 mm.	2,5mm
4.5.10b	Verticale Alignementen	Het lettertype voor de bemating heeft afhankelijk van de toegepaste STATUS een geplotte teksthoogte van 1,8mm (BESTAAND) of 2,5 mm (overige).	1,8mm
2,5mm
4.5.11	Coördinaten	Hiervoor kunnen de symbolen uit de bibliotheek SAL gebruikt worden. 	2,5mm
(In deze cellen zijn alle teksthoogten 2,5mm.)

Klopt de tekst bij 4.5.10a of moet die eigenlijk zijn zoals bij 4.5.10b?

**Comment by ElisabethKloren** [comment]
7 dec 2022 mailt sander;

Ik denk dat ik jouw voorstel de voor maatvoeringstijlen voor NLCS 5.1 nu goed heb geïnterpreteerd en vertaald in Microstation: 
 
![maatvoeringvoorstel](https://github.com/user-attachments/assets/d15bb345-97f0-49d5-8372-6b9b622ffd37)


Voorbeelden van het resultaat heb ik in dgn, dwg en dxf-formaat aan deze mail geplakt. Zou mooi zijn als je kunt controleren of deze goed in AutoCAD zijn te openen en zo niet wat er niet goed gaat. Misschien dat ik dan nog wat kan aanpassen zodat het goed/beter gaat met uitwisseling.
Ik kon jouw voorbeeld DWG niet goed importeren in Microstation, daar ga ik nog mee stoeien om te kijken waarom dat niet lukt.

Mijn vragen bij jouw voorstel:
1.	Heb ik jouw voorstel zo goed vertaalt naar Microstation?
Jazeker, de aangeleverde DWG heb ik met een factor 0.2 verschaald naar 1:200. Dan komen de aangeleverde presentaties inderdaad 1 op 1 overeen met het voorstel.
2.	Kan de hoogte van de pijl niet beter 1,0mm worden ipv 0,83mm (=2,5mm/3)? (omdat hoogte bol=1,0mm, openbol=1,0mm, lengte/hoogte schrap=2 x 1,0mm).
In AutoCAD is de hoogte van de pijl een verhouding t.o.v. van de ‘schaal’ van de arrowhead. Oftewel, de lengte van de pijl kan ik instellen. De hoogte is altijd een factor 3 daarvan.
Ben het overigens helemaal met je eens, maar is technisch in AutoCAD simpelweg niet mogelijk.
3.	Is het verstandig de lengte van de schraplijn te wijzigen van 2,00mm naar 2,83mm? (omdat de maat 2,0mm is overgenomen uit de voormalige RTW (Richtlijnen Tekeningenverkeer Waterstaat ) die zijn gebaseerd op o.a. NEN 3870 en NEN-ISO 128-22:1999. Ik weet echter niet wat er in die NEN-normen staat).
Dan zou de schrap nog groter worden als ik het goed begrijp? In AutoCAD resulteert de ‘schaal’ van de schrap, in een ronde maat in de hoogte, de daadwerkelijke lengte van de schraplijn zelf is dan een rare resultante. Zelf gebruik ik deze schraps nooit, dus geen ervaring wat een prettige grootte is.
Met jou huidige vertaling is hij m.i. wel mooi in balans met de rest.

**Comment by ElisabethKloren** [comment]
Micherl zegt 8-12-2022: Als de lengte van de schrap op 2 mm moet staan, is de schaalfactor van 1.414 prima inderdaad.
Of het werken met deze ‘rare’ verschalingen onder de motorkap voor problemen kan zorgen bij InfraCAD e.d. is dan denk ik even het belangrijkste.
De huidige presentatie van InfraCAD is veel te groot, dus het wordt hoe dan ook beter. 😉

**Comment by ElisabethKloren** [comment]
sander zegt 2 sept 2024:Ter illustratie hoe het ter test voor NLCS 5.1 in Microstation eruit ziet:
![20240902voorbeeldaanhaallijnenmaatvoering](https://github.com/user-attachments/assets/8b75cfc7-824d-4ff7-9378-eb8130a59400)

Alle elementen in elk object staan op één laag, dus de tekst staat niet op aparte lagen.
Bij de aanpijlingen heb ik alleen de laagnamen aangegeven.
 
Plaatsen van hoogtematen vraagt nog wel wat verduidelijking: op welke laag komen die? Afhankelijk van type element -S -T -L of -M allen toegestaan? Voorheen in NLCS 4.2 plaatste ik hoogtematen bijv. op N-WE-GR-AANPIJLIJNG-G…
De hoogtematen heb ik in dit voorbeeld op M-lagen gezet, ondanks dat ze er als aanpijlingen uitzien: In Microstation zijn deze hoogtematen dimensionelements en de 5 aanpijlingen onderin zijn ‘Notes’ (=combi van text en dimension). Technisch is het wel mogelijk om de hoogtematen ook als ‘Notes’ te plaatsen.

**Comment by ElisabethKloren** [comment]
michel zegt 3 sept 2024: Ziet er goed uit volgens mij.
Paar kleine vraagjes:
Is de ‘gesloten bol’ nu net zo groot als de ‘open bol’? deze lijkt iets kleiner te zijn? Of is dat optisch bedrog?
De M18 elementen krijgen ook een kleur 7/wit neem ik aan?
 
Hoogtemaatvoering plaats in altijd als losse tekst en zal dus bij mij in een -T laag staan.
Als hij is getekend zoals jouw voorbeeld, is het Microstation object/entiteit een leader en zou dit dus een -L moeten worden.
 
Maatvoering zie ik echt als de ‘dimenions’. Ik relateer de elementen van NLCS daar echt aan en niet zozeer aan de ‘gebruiksfunctie’.

**Comment by ElisabethKloren** [comment]
zegt sander: Ja de ‘bol’ en ‘openbol’ zijn exact even groot. Is geen optisch bedrog maar een fout in onderstaande screencapture. Een dimstyle-reset loste dat op.

Nee M18 is nu niet 7/wit. Was het idee dat zowel M18 als M25 lagen kleur 7/wit krijgen? Dacht juist dat de wens is deze gelijk te laten lopen met de tekstlagen?
En de L-lagen ook allemaal wit of die wel gelijk met de kleuren van de overeenkomstige tekstlagen ?

De (aangepijlde) hoogtematen zijn dimension-elementen, dus hetzelfde type element als maatvoeringen, maar denk dat ik ze ondanks dat toch op -L lagen ga plaatsen…
![aangepijldehoogtematen](https://github.com/user-attachments/assets/710e525f-4000-411a-bff2-39166010fa8b)

De ‘aanpijlingen’ zijn Note-elementen.

**Comment by ElisabethKloren** [comment]
Bijgaand het dgn bestand en dwg-export vanuit Microstation.
Bij export naar dwg/dxf vervalt een deel van de ‘extentionlines’… Ik weet nog niet of ik dat kan oplossen. 
Verder heb ik bij de opbouw van de dimensionstyles zoveel mogelijk rekening gehouden met compatibiliteit met AutoCAD.

https://github.com/nl-digigo/NLCS/tree/main/ontwikkeling/bijlagen_bij_issues/32

**Comment by ElisabethKloren** [comment]
michel zegt: Het zou mijn voorkeur hebben dat lettergrootte inderdaad met de kleur te herkennen is en de logica van de teksten ook voor het element L en M wordt toegepast.



Een aantal zaken die mij opvallen in de DWG:

Naamgeving styling:
In AutoCAD komen de maatvoeringen Annotatief binnen, zie rechter lijst vanuit de properties.
De naamgeving van de style komt hier echter niet mee overeen, dit zou moeten zijn: NLCS-ANNOTATIEF-T25-OPENBOL_X
Of in de convertie gaat dit niet goed, of jou naamgeving van de styling klopt niet.

![styling1](https://github.com/user-attachments/assets/4f9cb353-bebb-4ecd-8a9a-9be5a7c2246e)
![styling2](https://github.com/user-attachments/assets/a7511607-03fc-4597-80ce-0ed9685a018b)

Afmetingen arrowheads:
Links AutoCAD en rechts Microstation
M25 komt overeen met elkaar:
![stijling3](https://github.com/user-attachments/assets/5833f3d4-47cd-45ee-bdea-0099292912a9)

M18 zit eeen verschil in:
In AutoCAD worden de arrowheads naar-ratio verscklein op basis van de schaal.
De M18 arrowhead is dan ook een factor 0.72 kleiner dan de M25 variant.
Dit is voor de leesbaarheid ook gewenst.
Een evengrootte arrowhead voor M18 en M25 wordt erg vol en lastiger leesbaar.
![styling4](https://github.com/user-attachments/assets/0a72d9c4-19dc-4d16-9e30-a7666b55c07a)

<img width="403" alt="stylingtm6 en tekst" src="https://github.com/user-attachments/assets/171ce3ac-6afe-4a3e-9c19-7318e9c45f09">

In Microstation wordt alles ten opzichte van de ‘basis 200x groter gemaakt.
In AutoCAD is alles een factor 0.20 ten opzichte van de basis.

Dit verschalingsprobleem zie ik dus ook in de model terug, bij het ‘doortekenen’ op de aangeleverde schalen.
![styling7](https://github.com/user-attachments/assets/e662ec92-42db-4386-bbd6-0888a46d4f21)

De leader (-L element:
Deze komt nu als losse tekst en losse ‘leader’ in AutoCAD, dit is verwacht gedrag. Maar herkenbaar door het element L, dus voor de uitwisseling prima.
 
![styling8](https://github.com/user-attachments/assets/1eb8bd29-9521-4a0b-a103-c9dbd0de07a6)

Bij het hoogtelabel gebeurd dit ook, deze waren echter met een M-element gemaakt, waardoor de tekst en de leader nu op M-lagen staan.
Dit is ongewenst en zou dus een L-element moeten zijn.

![styling9](https://github.com/user-attachments/assets/d518d98b-1712-4c81-a413-411281985325)

**Comment by ElisabethKloren** [comment]
<img width="418" alt="sander1" src="https://github.com/user-attachments/assets/aca5b26f-dbb5-4521-ae41-dfa21cdd42b5">

**Comment by ElisabethKloren** [comment]
Ter info
Boven: terminator groter/kleiner afhankelijk van tekstgrootte
Onder: terminator vaste grootte volgens FB
![tekst](https://github.com/user-attachments/assets/da5daa0e-a651-4f29-97f9-b92d7b18f0bf)
<img width="375" alt="sandermichel2" src="https://github.com/user-attachments/assets/676e3fb8-1186-4614-8a19-2063997e01f0">

**Comment by ElisabethKloren** [comment]
reply michel

Als ik het zo zie…. Heb je helemaal gelijk.
Ik neig er haast naar om de FB aan te houden, zeker voor de grotere teksten.
Mag ik dan mijn verzoek herzien:
-	Kan de afmeting van de ‘standaard’ afmeting van de terminator met 2,5 mm aangepast worden naar 1,8 mm? 😊
De 2,5 mm arrow vindt ik voor een 1.8 tekst aan de grote kant.


reply sander
Wij gebruiken de arrows niet voor maatvoeringen van breedtes en lengtes, alleen voor stralen en diameters ,c.q. waar de NLCS voorschrijft dat je arrows moet gebruiken.
Voor overige maten gebruiken we de schrappen. Dus voor ons de is pijlpuntgrootte geen probleem.
Misschien dat Niels 1.8mm ook beter vind?


reply michel:
Wij gebruiken zelf de ‘open bol’ variant en ook allee de arrow voor de radius en diameter.
Dus persoonlijk maakt het mij ook niet veel uit.

Ik weet alleen dat andere ingenieursbureaus in mijn regio wel van de pijlen gebruik maken en dit probleem ook ervaren.

In dit geval spreek ik dus vanuit ‘wat ik hoor en zie in mijn omgeving’, maar niet zozeer eigen belang. 😉

**Comment by ElisabethKloren** [comment]
en niels: Wij gebruiken in principe de schrap.

Met 2.5 op zich geen problemen, maar om dit naar 1.8 terug te brengen heb ik geen problemen mee…

Persoonlijk zoals in je voorbeeld wel mooier om 1 grootte aan te houden….

Weet alleen niet of dit in praktijk op een “echte” tekening ook zo is…maar dan zou ik bijna zeggen als ze mee vergroten dat je eerder kans hebt dat het iets anders afdekt waardoor je dit weer niet goed ziet…
Dus in die zin ook voorstander van “ de kleinere en even grootte” pijlpunt

**Comment by ElisabethKloren** [comment]
sander mailt: Ik denk dat we er toch niet onderuit komen om een naast -SO nieuw type -WG toe te voegen.
Ik ging er eerder vanuit, dat figuratieve symbolen en symbolen op ware grootte beide met factor x1 worden geplaatst, maar ik begrijp nu dat dat niet zo is(?).
Als het klopt, dat met de objecten van de originele NLCS-set, in een 1:200 ontwerpmodel, een markeringspijl met factor x1 geplaatst wordt en een lichtmastsymbool met factor 0.2 , denk ik toch dat we er goed aan doen om een -WG type te gaan toevoegen.
Alternatief is te doen wat The People Group heeft gedaan: alle symbolen en arceringen een factor 5 verschalen, maar dat vind ik zelf niet de beste optie. 

michel mailt:
<img width="400" alt="sodiscussie" src="https://github.com/user-attachments/assets/5ad4cd70-95bc-4250-b2ee-27a5125cb159">

**Comment by ElisabethKloren** [comment]
Expertcommissie 2024-09-19: 
Arrow staat altijd op 2.5 mm bij 1.8 tekst is te groot; voorstel arrowheads allemaal dezelfde grootte, 1.8, zodat dit niet te groot is
Of een dimension wel of geen aanhaallijnen heeft, moet duidelijk worden in de stijlnaam. Gebruik dus X of A, om dezelfde posities aan te houden.
Akkoord expertcommissie om dit door te voeren.

**Comment by ElisabethKloren** [comment]
Als volgt beschreven: *  De benaming van maatvoeringsstijlen in de NLCS isMOET als volgt zijn opgebouwd: NLCS-[EENHEID SCHAAL]-TEKSTHOOGTE_[CURSIEF]-MAATVOERINGSYMBOOL[_AANHAALLIJNEN][_BACKGROUNDMASK][_AANTAL DECIMALEN LINEAR][_AANTAL DECIMALEN HOEK]

| Ondrdeel naam                  | Toelichting                                                                                                           |
|----------------------------|-----------------------------------------------------------------------------------------------------------------------|
| NLCS-                      | Veld MOET voorkomen. Waarde alstijd NLCS-                                                                                                               |
| [EENHEID SCHAAL]-         | Veld MOET voorkomen. Waarde altijd meeteenheid en schaal  minus 1:                                                                                                   |
| TEKSTHOOGTE                | Veld MOET voorkomen. Waarde altijd Txx, waarbij xx de teksthoogte in mm is                                                                                |
| [_CURSIEF]                | Indien van toepassing MOET _CURSIEF zijn toegevoegd in de naam van de maatvoeringsstijl                                                                                |
| -MAATVOERINGSYMBOOL       | Veld MOET voorkomen. De waarde MOET een van de volgende zijn: PIJL (Arrow), SCHRAP (Oblique), BOL (Dot), OPENBOL (DotBlank).         |
| [_AANHAALLIJNEN]          | Veld MOET voorkomen: De waarde MOET een van de volgende zijn:  A (met) of X (zonder).                                                                             |
| [_BACKGROUNDMASK]         | Veld MOET voorkomen: De waarde MOET een van de volgende zijn:  BG of X                                                                                             |
| [_AANTAL DECIMALEN LINEAR] | Indien van toepassing MOET dit zijn toegevoegd in de naam van de maatvoeringsstijl  Lx  met x het aantal decimalen                                                                                      |
| [_AANTAL DECIMALEN HOEK]   | Indien van toepassing MOET dit zijn toegevoegd in de naam van de maatvoeringsstijl  Hx met x het aantal decimalen                                                                                           |






<table class="tabel3" title="voorbeelden benaming van maatvoeringsstijlen">
  <tr>
    <th>Stijl</th>
    <th>Beschrijving</th>
  </tr>
  <tr>
    <td>NLCS-M100-T25-PIJL-X-X</td>
    <td>NLCS maatvoeringstijl in meters, schaal 1:100, teksthoogte 2.5, pijl als symbool;</td>
  </tr>
   <tr>
    <td>NLCS-M100-T25-X-X-PIJL_BG</td>
    <td>NLCS maatvoeringstijl in meters, schaal 1:100, teksthoogte 2.5, pijl als symbool; met backgroundmask</td>
  </tr>
  <tr>
    <td>NLCS-MM20-T25_X-X-CURSIEF-BOL</td>
    <td>NLCS maatvoeringstijl in millimeters, schaal 1:20, teksthoogte 2.5, tekst cursief, bol als symbool;</td>
  </tr>
  <tr>
    <td>NLCS-M500-T25-OPENBOL</td>
    <td>NLCS maatvoeringstijl voor de toepassing van coördinaten: in meters, schaal 1:500, teksthoogte 2.5, open bol als symbool;</td>
  </tr>
  <tr>
    <td>NLCS-M500-T18-SCHRAP</td>
    <td>NLCS maatvoeringstijl in meters, schaal 1:500, teksthoogte 1.8, schrap als symbool;</td>
  </tr>
  <tr>
    <td>NLCS-ANNOTATIEF-T25-PIJL</td>
    <td>NLCS maatvoeringstijl met teksthoogte 2.5, pijl als symbool, annotatief; in dit geval is de eenheid in de naam niet van belang vanwege de annotatieve schaal;</td>
  </tr>
  <tr>
    <td>NLCS-M100-T25-PIJL_X_L2_H1</td>
    <td>NLCS maatvoeringstijl in meters, schaal 1:100, teksthoogte 2.5, pijl als symbool, zonder aanhaallijnen, 2 decimalen voor lineaire maten, 1 decimaal voor hoeken;</td>
  </tr>
  <tr>
    <td>NLCS-M500_T25-OPENBOL_X_L2_H1</td>
    <td>NLCS maatvoeringstijl voor de toepassing van coördinaten: in meters, schaal 1:500, teksthoogte 2.5, open bol als symbool, zonder aanhaallijnen, 2 decimalen voor lineaire maten, 1 decimaal voor hoeken;</td>
  </tr>
  <tr>
    <td>NLCS-MM20-T25_CURSIEF-BOL_A_L2_H2</td>
    <td>NLCS maatvoeringstijl in millimeters, schaal 1:20, teksthoogte 2.5, tekst cursief, bol als symbool, met aanhaallijnen, 2 decimalen voor lineaire maten, 2 decimalen voor hoeken.</td>
  </tr>
</table>

**Comment by ElisabethKloren** [comment]
en deze voorbeelden:
<table class="tabel3" title="voorbeelden benaming van maatvoeringsstijlen">
  <tr>
    <th>Stijl</th>
    <th>Beschrijving</th>
  </tr>
  <tr>
    <td>NLCS-M100-T25-PIJL_X_X</td>
    <td>NLCS maatvoeringstijl in meters, schaal 1:100, teksthoogte 2.5, pijl als symbool;</td>
  </tr>
   <tr>
    <td>NLCS-M100-T25-PIJL_X_BG</td>
    <td>NLCS maatvoeringstijl in meters, schaal 1:100, teksthoogte 2.5, pijl als symbool; met backgroundmask</td>
  </tr>
  <tr>
    <td>NLCS-MM20-T25_CURSIEF-BOL_X_X</td>
    <td>NLCS maatvoeringstijl in millimeters, schaal 1:20, teksthoogte 2.5, tekst cursief, bol als symbool;</td>
  </tr>
  <tr>
    <td>NLCS-M500-T25-OPENBOL_X_X</td>
    <td>NLCS maatvoeringstijl voor de toepassing van coördinaten: in meters, schaal 1:500, teksthoogte 2.5, open bol als symbool;</td>
  </tr>
  <tr>
    <td>NLCS-M500-T18-SCHRAP_X_X</td>
    <td>NLCS maatvoeringstijl in meters, schaal 1:500, teksthoogte 1.8, schrap als symbool;</td>
  </tr>
  <tr>
    <td>NLCS-ANNOTATIEF-T25-PIJL_X_X</td>
    <td>NLCS maatvoeringstijl met teksthoogte 2.5, pijl als symbool, annotatief; in dit geval is de eenheid in de naam niet van belang vanwege de annotatieve schaal;</td>
  </tr>
  <tr>
    <td>NLCS-M100-T25-PIJL_X_X-L2_H1</td>
    <td>NLCS maatvoeringstijl in meters, schaal 1:100, teksthoogte 2.5, pijl als symbool, zonder aanhaallijnen, 2 decimalen voor lineaire maten, 1 decimaal voor hoeken;</td>
  </tr>
  <tr>
    <td>NLCS-M500_T25-OPENBOL_X_X_L2_H1</td>
    <td>NLCS maatvoeringstijl voor de toepassing van coördinaten: in meters, schaal 1:500, teksthoogte 2.5, open bol als symbool, zonder aanhaallijnen, 2 decimalen voor lineaire maten, 1 decimaal voor hoeken;</td>
  </tr>
  <tr>
    <td>NLCS-MM20-T25_CURSIEF-BOL_A_X_L2_H2</td>
    <td>NLCS maatvoeringstijl in millimeters, schaal 1:20, teksthoogte 2.5, tekst cursief, bol als symbool, met aanhaallijnen, 2 decimalen voor lineaire maten, 2 decimalen voor hoeken.</td>
  </tr>
</table>
