### ISSUE TITLE
De huidige werkwijze voor disciplines moet worden opgehelderd in de uitleg standaard

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#320]
Ophelderen dat het gebruik van disciplines vrij is en op verschillende manieren wordt ingevuld, waardoor het per organisatie verschilt hoe dit werkt

**Comment by MvanderHulst** [comment]
Beschouwend 5.1.2 van de FB:
5.1.2.b verwijst naar de NEN3610, hierin valt echter niks te herleiden wat ook maar iets te maken heeft met de 'disciplines'.
5.1.2.c geeft aan dat er een verdeling is voor hoofdgroepen per discipline. Volgens mij is dit niet het geval.
5.1.2.c. geeft tot slot aan dat iedere organisatie per discipline kan aangegeven welke hoofdgroepen daarop thuis horen. Dit zou dus een EIS moeten zijn voor de software leveranciers. Dat deze indeling gemaakt kan worden.
Algemene vraag: 'WAAROM'? Werkt alleen maar beperkend en lastig.

Conclusie:
Het is een eerste filtering op de afkomst van lagen. Wat het risico van fouten bij samenvoeging alleen maar groter maakt.

Voorstel volgens issue #310 wat mij betreft nogsteeds logischere toepassing van de positie van discipline.

**Comment by ElisabethKloren** [comment]
voorstel is hier, huidige werkwijze beter beschrijven in 5.1, #310 staat op de backlog voor een volgende grotere wijziging aan NLCS

**Comment by ElisabethKloren** [comment]
Ik heb de tekst aangepast naar:
1. De DISCIPLINE geeft het vakgebied aan waarop het model betrekking heeft en vormt voor de gebruiker een mogelijkheid voor de ordening of filtering van informatie in een CAD model.
2. NLCS schrijft niet voor welke objecten of hoofdgroepen binnen een discipline vallen. 
3. De DISCIPLINES die in NLCS zijn opgenomen, zijn weergegeven in onderstaande tabel.
4. De DISCIPLINE “XX” mag alleen worden toegepast in combinatie met de hoofdgroep “AL”.

Dit als voorbeeld meegegeven:
<aside class="note" title="Gebruik disciplines afhankelijk van organisatie-specifieke afspraken">
De disciplines worden door verschillende organisaties op verschillende wijze gebruikt: 
<ol><li>Een interpretatie is aanduiding van de herkomst van de getekende objecten. De discipline is dan de afdeling waar de tekening is opgesteld. 
<li>De ander ziet het als een indeling van soorten objecten en vult dan in bij welke hoofdgroepen welke discipline thuishoort. 
</ol>
</aside>
