### ISSUE TITLE
Outdated link in eisen aan tekeningen en modellen

### ISSUE THREAD

**Issue by BTobben** [nl-digigo/NLCS#321]
In het document Eisen aan tekeningen en modellen staat helemaal bovenaan ook nog een oude link naar de bimloket github. Overigens is hier ook nog het logo van BIMLoket in opgenomen. Laatste is natuurlijk niet persee bezwaarlijk maar wellicht dat dit over het hoofd gezien is?
![Schermafbeelding 2024-02-28 163126](https://github.com/nl-digigo/NLCS/assets/46655663/95317daa-bfa8-44f0-8ce8-ff1225e01bf2)

**Comment by ElisabethKloren** [comment]
@BTobben dank voor je input, beide problemen zijn inmiddels verholpen
