### ISSUE TITLE
[NLCS NBH] NLCS Netbeheer gebundelde wijziging 2024Q1

### ISSUE THREAD

**Issue by theokolman** [nl-digigo/NLCS#322]
Het digiGO versnellingsproject NLCS++ Netbeheer heeft de NLCS doorgenomen en de gewenste wijzigingen om het bruikbaar te maken voor Netbeheerders vastgelegd in bijlage. 

[NLCSNetbeheer_VoorstelAanpassingenNLCS.pdf](https://github.com/nl-digigo/NLCS/files/14521320/NLCSNetbeheer_VoorstelAanpassingenNLCS.pdf)

De daarin voorgestelde wijzigingen worden in github als afzonderlijke issues vastgelegd met verwijzing naar dit document, zodat afzonderlijke discussie en besluitvorming kan worden gedaan en geregistreerd.

Als alle voorstellen zijn behandeld, wordt dit overkoepelende issue gesloten.

- [x] #323 
- [x] #324 
- [x] #325 
- [x] #326 
- [x] #327 
- [x] #461 
- [x] #328

**Comment by theokolman** [comment]
Deze issues worden met prefix [NLCS NBH] geregistreerd.

**Comment by theokolman** [comment]
[NLCSNetbeheer_VoorstelAanpassingenNLCS.docx](https://github.com/nl-digigo/NLCS/files/14511326/NLCSNetbeheer_VoorstelAanpassingenNLCS.docx)

**Comment by ElisabethKloren** [comment]
de voorstellen zijn allemaal opgenomen in afzonderlijke issues, deze overzichtsissue sluit ik af
