### ISSUE TITLE
[NLCS NBH] 2.	NLCS subobject02 (Subnettype)

### ISSUE THREAD

**Issue by theokolman** [nl-digigo/NLCS#324]
Voor NLCS netbeheer wordt Subobject02 gebruikt voor de aanduiding van het subnettype. Hierbij wordt gebruik gemaakt van de terminologie TRANSPORT, DISTRIBUTIE en AANSLUITNET en is voor de verschillende NLCS netbeheer thema’s gelijk. 

Mogelijke waarden die kunnen voorkomen voor Subobject02:
•	TRANSPORT = Hoofdnet
•	DISTRIBUTIE = Distributie netwerk
•	AANSLUITNET = Aansluiting/aansluitnetwerk

**Consequenties ACTIE | DIGIGO**
-	Bespreken in NLCS Netbeheer Expertcommissie
-	Vastleggen in Formele Beschrijving NLCS
-	Aanpassen NLCS database 

Huidige naam van NLCS ID 1054 en 1143 aanpassen van HOOFDLEIDING naar DISTRIBUTIE. Idem voor NLCS ID 1000 en 1113 naar AANSLUITNET
<Object nummer="1054" hoofdgroep="11" omschrijving="DISTRIBUTIE"
<Object nummer="1143" hoofdgroep="11" omschrijving="DISTRIBUTIE" 
<Object nummer="1000" hoofdgroep="11" omschrijving="AANSLUITNET"
<Object nummer="1113" hoofdgroep="11" omschrijving="AANSLUITNET"

Voor de huidige (NLCS 5.0) hoofdgroep Riolering geldt dat termen als “TRANSPORTLEIDING” worden gebruikt. Bespreken / afstemmen.

**Consequenties ACTIE | DIGIGO**
-	Bespreken in NLCS Netbeheer Expertcommissie
-	Vastleggen in Formele Beschrijving NLCS
-	Aanpassen NLCS database 

Huidige naam van NLCS ID 1054 en 1143 aanpassen van HOOFDLEIDING naar DISTRIBUTIE. Idem voor NLCS ID 1000 en 1113 naar AANSLUITNET
<Object nummer="1054" hoofdgroep="11" omschrijving="DISTRIBUTIE"
<Object nummer="1143" hoofdgroep="11" omschrijving="DISTRIBUTIE" 
<Object nummer="1000" hoofdgroep="11" omschrijving="AANSLUITNET"
<Object nummer="1113" hoofdgroep="11" omschrijving="AANSLUITNET"

Voor de huidige (NLCS 5.0) hoofdgroep Riolering geldt dat termen als “TRANSPORTLEIDING” worden gebruikt. Bespreken / afstemmen.

**Comment by NielsNederpel** [comment]
TRANSPORTLEIDING bij riool komt vanuit GWSW. behoorlijk wat tijd in gestoken om de NLCS en GWSW op elkaar te laten aansluiten. lijkt me niet wenselijk dit nu weer terug te draaien? daarbij zit TRANSPORTLEIDING niet op subobject02 maar op Subobject 01

**Comment by ElisabethKloren** [comment]
EC 2024-03-14 Akkoord voor gebruik in netbeheer; voor riolering/GWSW gelden andere termen voor gebruikers, dus niet doorvoeren in andere hoofdgroepen.

Toevoegen "OVERIG" en "ONBEKEND"
Overig gebruiken, omdat dit bij GWSW ook gebeurt

Discussie: 
liever 'SPECIAL' o.i.d. dan 'OVERIGE'. Bij overige is nog steeds onbekend wat het wel is een 'detectielus' is ook iets typisch 'OVERIGE' onderdeel. maar is zeker geen SPECIAL
dan liever 'ANDERS' of 'ONBENOEMD' overige' is een te vage term; vanuit de oorsprong van de NLCS, vul je nies in als je niet weet wat het is, dus geen 'overige' en geen 'onbekend'
Dit wordt op zo hoog mogelijk niveau ingevuld 

> er wordt geen Controle tooling gevraagd van de softwareleveranciers, er worden enkele opties toegevoegd hoog in de boom

![image](https://github.com/nl-digigo/NLCS/assets/48585720/2e5dad7f-fc83-4ffa-aae4-aad87e391bb9)
'overige' uit de GWSW mapping is volgende stap

**Comment by ElisabethKloren** [comment]
Beschreven en verwerkt
