### ISSUE TITLE
[NLCS NBH] 4. Hoofdlettergebruik

### ISSUE THREAD

**Issue by theokolman** [nl-digigo/NLCS#326]
Hoewel tot en met versie 5.0 van de NLCS niets is opgenomen in de NLCS Formele Beschrijving ten aanzien van het gebruik van hoofdletters is het wenselijk dit te gaan opnemen. 
Voor NLCS netbeheer is het wenselijk het gebruik van kleine letters voor bepaalde onderdelen toe te passen. Zo is de aanduiding “kV” of de naamgeving van chemische elementen “Al of Cu” standaard bepaald en gebruikelijk.

**Consequenties ACTIE | DIGIGO**
-	Bespreken in NLCS Netbeheer Expertcommissie
-	Vastleggen in Formele Beschrijving NLCS
-	Aanpassen NLCS database 

**Consequenties Software ontwikkelaars**
-	Aanpassen software
Gewenste functionaliteit in software tooling

Uitgangspunt blijft dat in de basis gebruikt wordt gemaakt van hoofdletters met uitzondering van de specifieke onderdelen waarvoor geldt dat kleine letters “verplicht” zijn.
•	Automatisch aanpassen naar hoofdlettergebruik bij wijzigingen in Objectenlijst uitschakelen
•	Optioneel maken van hoofdlettergebruik bij controle mogelijkheden in instellingen van software

Optioneel zou het mogelijk kunnen zijn heel specifiek posities in de objectenlijst uit te sluiten van het hoofdlettergebruik. Dit heeft meer impact op de implementatie hiervan bij NLCS tooling.

**Comment by ElisabethKloren** [comment]
Expertcommissie 2024-03-14: Algemene regel van de standaard kleine letters zijn toegestaan indien nodig voor bijvoorbeeld eenheden en de elementen uit het periodiek systeem. 

Controle tools voor individuele bibliotheken worden gevraagd om wel een waarschuwing te geven "in heeft in de laagnaam kleine letters gebruikt, is dit nodig om eenheden of periodieke elementen te verduidelijken?"

**Comment by ElisabethKloren** [comment]
Teksten opgenomen in formele beschrijving; we eisen niet van leveranciers dat het maken van individuele bibliotheken wordt ondersteund, er gaat technisch ook niets mis als er kleine letters worden gebruikt. Dus ik formuleer hier geen nieuwe eis aan de applicaties.
