### ISSUE TITLE
Overbodige symbolen aarding

### ISSUE THREAD

**Issue by BTobben** [nl-digigo/NLCS#329]
Het is me opgevallen dat er 2 symbolen voor Aarding/Aardelectrodes zijn. Ik heb op mijn afdeling gepeild of iemand wist welk symbool voor welke toepassing is en wat de verschillen zijn tussen de aarding en de aardelectrode maar hier kon niemand uitsluitsel geven. Is het misschien overbodig om hier 2 symbolen te hebben of is hier een toepassing voor die aan ons voorbij gaat?
![Schermafbeelding 2024-03-07 163614](https://github.com/nl-digigo/NLCS/assets/46655663/418bd5c0-9db6-4e8b-a3a2-bc32b565eb58)

**Comment by ElisabethKloren** [comment]
To do definitie van deze twee objecten publiceren in versie 5.1

**Comment by MvanderHulst** [comment]
Geen actie noodzakelijk.
Als OV je vak is, dan weet je dit.

**Comment by B-Tobben** [comment]
Bedankt voor de reacties, het is voor ons nu redelijk duidelijk hoe deze symbolen gebruikt dienen te worden. De stelling 'Als OV je vak is, dan weet je dit.' lijkt mij iets te kort door de bocht, ik modelleer nu zelf slechts een jaar in de lijninfra maar heb collega modelleurs en engineers met tientallen jaren ervaring bij verschillende bedrijven gevraagd en kon hier geen uitsluitsel krijgen. Naar mijn weten wordt ook wel eens een aardpen gebruikt die niet direct wordt aangesloten op de hoofdaardrail, bijvoorbeeld bij bepaalde armaturen en portalen. De bovengenoemde definitie van aardelektrode in acht nemende (een staaf die de grond in gaat) zou ik deze als elektrode verwachten maar met de stelling dat de aardelektrode op de hoofdaardrail zit zou zo'n aardpen/elektrode eerder bij het aarding symbool behoren?

Deze overwegingen in acht nemende concludeer ik dat de toepassingen van deze twee symbolen nog niet volledig genoeg zijn afgebakend en nog teveel ruimte voor interpretatie over laten.

Ik probeer enkel mee te denken omdat het me regelmatig opvalt dat de eisen en richtlijnen nog niet waterdicht zijn en nog veel aspecten tegenkomen die onlogisch of ondoordacht lijken.

OV, DVM en VRIs is mijn vak, niemand binnen de afdeling kon hier een eenduidige antwoord geven, ik denk dat je laatste stelling misschien heroverwogen zou kunnen worden.

**Comment by ElisabethDeVries** [comment]
reopen om dit issue te adresseren in een volgende herziening van hoofdgroep OV
