### ISSUE TITLE
#1502	"o.a. “KANTOPSLUITING_TROTTOIRBAND_130 150-G

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#33]
#1502	"o.a. “KANTOPSLUITING_TROTTOIRBAND_130 150-G” is gewijzigd naar “KANTOPSLUITING_TROTTOIRBAND_130X150-G” = spatie vervangen door ‘X’

Dat voorstel was (tot mijn grote geruststelling) toch teruggedraaid? Spaties in laagnamen zouden blijven staan!

 

“130x150” voor “130/150x….” is eigenlijk niet goed, zeker als je dit vergelijkt met andere laagnamen zoals voor opsluitband 100x200. Op z’n minst verwarrend.

Als er geen spatie tussen 130 en 150 mag (zou niet weten waarom niet, komt in meerdere lagen nog voor), dan moet er een ander teken voor terugkomen dan ‘X’ of geen teken, dan wordt het “130150”, net als bij markeringen.

 

Dan zijn er nog deze kantopsluitingen waarin de spatie wel is blijven staan:

                ROTONDEBLOK_500 200

                TROTTOIRBAND_RWS_110 220"

**Comment by ElisabethKloren** [comment]
Reactie Expertcommissie
spatie vanwege leesbaarheid en ivm geen slash

**Comment by MvanderHulst** [comment]
Te herziene objecten in VH-KANTOPSLUITING
ASFALTBAND_50x200x150			=>	ASFALTBAND_50 200x150
ASFALTBAND_50x200x200			=>	ASFALTBAND_50 200x200
ASFALTBAND_50x200x250			=>	ASFALTBAND_50 200x250
GELEIDEBAND_50X150				=>	GELEIDEBAND_50 150
GELEIDEBAND_50X200				=>	GELEIDEBAND_50 200
GELEIDEBAND_60X120				=>	GELEIDEBAND_60 120
GELEIDEBAND_70X150				=>	GELEIDEBAND_70 150
GELEIDEBAND_70X200				=>	GELEIDEBAND_70 200
GELEIDEBAND_80X160				=>	GELEIDEBAND_80 160
PLATEAUBAND_60X120				=>	PLATEAUBAND_60 120
PWSBAND_250x130				=>	PWSBAND_250x130 200
RIJWIELPADBAND_380x200			=>	RIJWIELPADBAND_380 200
RIJWIELPADBAND_410x250			=>	RIJWIELPADBAND_410 250
SCHEIDINGSBAND_100x300			=>	SCHEIDINGSBAND_100 300
SCHEIDINGSBAND_110x250			=>	SCHEIDINGSBAND_110 250
SCHEIDINGSBAND_120X350			=>	SCHEIDINGSBAND_120 350
SCHEIDINGSBAND_150X390			=>	SCHEIDINGSBAND_150 390
SCHEIDINGSBAND_160X200			=>	SCHEIDINGSBAND_160 200
SCHEIDINGSBAND_200X400			=>	SCHEIDINGSBAND_200 400
SCHEIDINGSBAND_220X440			=>	SCHEIDINGSBAND_220 440
SCHEIDINGSBAND_360X400			=>	SCHEIDINGSBAND_360 400
SCHEIDINGSBAND_470X500			=>	SCHEIDINGSBAND_470 500
TROTTOIRBAND_130X150			=>	TROTTOIIRBAND_130 150
TROTTOIRBAND_180X200			=>	TROTTOIIRBAND_180 200
TROTTOIRBAND_280X300			=>	TROTTOIIRBAND_280 300

**Comment by MvanderHulst** [comment]
Nagenoeg alle SVH-KANTOPSLUITING symbolen moeten aangepast worden.

Algemeen:
Zeer veel exoten in de bibliotheek van allerlei leveranciers.
Moeten we dit niet uitdunnen/beperken?

Standaard StruykVerwo als 'leidend' aanhouden?

**Comment by MvanderHulst** [comment]
Zie ook issue #128

**Comment by MvanderHulst** [comment]
zie ook #369 zelfde vraag

**Comment by MvanderHulst** [comment]
Concreet voorstel: bibliotheek uitdunnen tot 'Struyk Verwo' als standaard.

**Comment by ElisabethKloren** [comment]
spatie terugzetten = voorgenomen wijziging; struykverwo = bespreken, want; willen we niet van "bestaand" allerlei situaties kunnen tekenen, maar voor "nieuw" als eerte standaard maten suggereren in de software, dan pas exoten? Dan moet je standaard kunnen taggen oid in de database.

Of zijn de experts het over eens dat uitdunnen database op dit gebied handig is?

**Comment by ElisabethKloren** [comment]
Toelichting op voorgenomen wijziging: we gaan objecten met dezelfde maten die met meerdere namen voorkomen, samenvoegen met zo leveran ciersneutraal mogelijke naam:

troittoirband 130/150 x 250 is hetzelfde ding als een asfaltband bij een andere leverancier > hier gebruiken we dus de naam trottoirband

@MvanderHulst maakt een lijst met ook synoniemen die we kunnen opnemen in de termen.

**Comment by MvanderHulst** [comment]
Onderstaand mogen m.i. komen te vervallen:
- ASFALTBAND
- PLAKBAND
- SIGNALERINGSBAND <- is een standaard band, aangevuld met ogen/lampen. Zonder afmeting niet als zelfstandig toepasbaar.
- TALUDBAND

**Comment by ElisabethDeVries** [comment]
herziening laagnamen vh pas meenemen in 6.0
