### ISSUE TITLE
nieuwe hoofdgroep Energievoorziening Spoor (ES) 

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#331]
Voorstel om voor stedelijk spoor een tweede hoofdgroep beschikbaar te stellen: Energievoorziening Spoor (ES) 

als verzamelgroep voor alle assets die daaronder vallen, dus: bovenleiding, tractie, aarding, etc.

**Comment by ElisabethKloren** [comment]
Dit om betere onderscheid te kunnen maken en scheelt ook in decompositie van de laagnamen:
 
 
 
![energievoorzieningspoor](https://github.com/nl-digigo/NLCS/assets/48585720/4c872eed-dc25-4b0f-8d6f-6865486ae176)

In de huidige decompositie kan dan bij 165 objecten SB-BOVENLEIDING worden voor vervangen door EV wat decompositie overzichtelijker en beheersbaarder maakt.

**Comment by HarmdHerripon** [comment]
Besluit werkgroep: Energievoorziening Spoor (ES) is akkoord.
Bespreken in expertcommissie

**Comment by ElisabethDeVries** [comment]
[[Release note]] In NLCS 5.2 is een nieuwe hoofdgroep toegevoegd: Energievoorziening Spoor (ES).
