### ISSUE TITLE
Motie voor mijden van 'OVERIG' in NLCS-laagnamen

### ISSUE THREAD

**Issue by SanderNijhof** [nl-digigo/NLCS#332]
Met de komst van NLCS 5.0 zijn een heleboel laagnamen met de tekst ‘OVERIG’ erin vervallen. Daar ben ik blij om.
Bij deze 4 laagnamen is ‘_OVERIG’ blijven staan:

- *-**-KL-DATA_DEFENSIE_HULPSTUK_OVERIG-G
- *-**-KL-OLIE_OVERIG-G
- *-**-KL-WARMTENET_HULPSTUK_OVERIG-G
- *-**-OG-BEBOUWING_OVERIG-G

Zijn deze laagnamen vergeten?

Daarnaast zijn in de hoofdgroep RI in de serie #-##-RI-G veel lagen vervallen en is #-##-RI-OVERIG-G uitgebreid. Ik mis daardoor lagen zoals #-##-RI-PUTNUMMER-S om alle putnummers op 1 laag te plaatsen en bijv. #-##-RI-TROTTOIRKOLK-S voor bestaande kolken waarvan het stelseltype niet bekend of relevant is.

Omdat ‘OVERIG’ te weinig zegt over het object en omdat de laagnaam door '_luie_' tekenaars te pas en onpas gebruikt kan worden zou ik graag zien dat ‘OVERIG’ in alle NLCS-laagnamen gemeden wordt.

Zie ook deze pdf: [motie overige.pdf](https://github.com/nl-digigo/NLCS/files/14605061/motie.overige.pdf)

**Comment by MvanderHulst** [comment]
DATA_DEFENSIE_HULPSTUK_AANSLUITPUNT
DATA_DEFENSIE_HULPSTUK_MOF
DATA_DEFENSIE_HULPSTUK_OVERIG

Wat is het nut van deze OBJECTEN, als je ook DATA_DEFENSIE_HULPSTUK kan toepassen?
In INFRACAD kan ik de symbolen niet eens plaatsen op het diepere SUBOBJECT niveau.
![image](https://github.com/nl-digigo/NLCS/assets/144665595/199d711f-daa1-4837-ae13-44e3cb38c988)

idem voor:
WARMTENET_HULPSTUK_OVERIG
WARMTENET_HULPSTUK_AANSLUITPUNT
WARMTENET_HULPSTUK_AFSLUITER
![image](https://github.com/nl-digigo/NLCS/assets/144665595/cdcf21f4-0119-450f-9ceb-67f3efd33ff8)

Bovenstaande 6 objecten kunnen m.i. vervallen.

OLIE-OVERIG is inconsequent met alle OBJECTEN en kan vervallen.

Onder BEBOUWING_ staan zo veel soorten subobjecten. Daar zal je je keuze altijd wel in kwijt kunnen.
BEBOUWING_OVERIG zou zodoende mogen vervallen.

@SanderNijhof 
Onderstaande tabel lijkt het voorstel hetzelfde als de naam? Ik snap niet goed wat hierbij het voorstel is:
![image](https://github.com/nl-digigo/NLCS/assets/144665595/41fb3296-58d1-4616-864e-02ca50cc8e38)


RI-MATERIAAL en RI-BOB worden toegepast om labels te plaatsen om het soort leiding en de BOB als tekst weer te geven.
Noodzaak is er dus wel, maar op deze positie is het vreemd.
Dit zou ALTIJD een onderdeel van een stelsel moeten zijn, waarbij OVERIG ook een stelsel is.
BOB staat al onder alle stelsels. Materiaal moet daaraan toegevoegd worden.
MATERIAAL dus aan alle stelsels toevoegen
RI-BOB en RI-MATERIAAL moeten vervolgens vervallen.

Vervolgens:
![image](https://github.com/nl-digigo/NLCS/assets/144665595/634b64e1-91d6-40c4-9a17-1e6087351aeb)
OVERIGE is inderdaad een stelsel, anders dan de standaard gespecificeerde.
Een algemene laag voor PUTNUMMER is er inderdaad niet meer. Persoonlijk vindt ik het vreemd dat je één laag zou willen met alle putnummers, zonder dat je deze aan een stelsel koppelt. maar dat is weer een ander gesprek.

Als als je dat wel zou willen faciliteren, zou er inderdaad een 'algemeen' stelsel moeten komen die je als vergaarbak kan gebruiken
Is toevoeging RI-ALGEMEEN dan een optie? alle Algemene symbolen hebben we eigenlijk ook al.
'ongespecificeerd' heb je dan, alle 'stelsels' heb je dan en 'overig' heb je dan. Ben je wel compleet.
Symbolen relaties moeten dan wel goed gecontroleerd worden.

Tot slot:
![image](https://github.com/nl-digigo/NLCS/assets/144665595/b859d337-7f7a-4b0a-a9e3-c323a2c8f46e)
In het voorstel worden deze 'gelijk' getrokken in de beschouwing met RI-MATERIAAL.
Zoals bovenstaand benoemd is het doel van RI-MATERIAAL anders dan het OVERIGMATERIAAL zoals beschreven in de constructie hoofdgroepen.
Deze OBJECTEN zouden wel mogen vervallen.
Als je constructief tekent, wil je alle materialen benoemd en omschreven hebben.
Met de verplichting dat iedereen eigen objecten mag aanmaken, zou je moeten stimuleren dat gebruikers aanvullingen gaan maken en niet deze vergaarbak gebruiken.

**Comment by SanderNijhof** [comment]
@MvanderHulst 
> Onderstaande tabel lijkt het voorstel hetzelfde als de naam? Ik snap niet goed wat hierbij het voorstel is:

(Inderdaad het onduidelijke) Punt hierbij was dat in de hoofdgroep RI de laag RI-OVERIG_MATERIAAL niet bestaat en het voorstel is/was om dat zo te houden, maar die mening is aan het wankelen.



> RI-BOB en RI-MATERIAAL moeten vervolgens vervallen.

Zouden dit bijvoorbeeld ook RI-LEIDING_BOB en RI-LEIDING_MATERIAAL, RI-PUT_MATERIAAL kunnen worden?
En dan ook RI-OVERIG_MATERIAAL? Of RI-OVERIG_LEIDING_MATERIAAL ect.
Ik vind 'MATERIAAL' niet een object, maar een SUBOBJECT. En dat geld ook voor 'OVERIGMATERIAAL' en 'OVERIG MATERIAAL'.

> OVERIGE is inderdaad een stelsel, anders dan de standaard gespecificeerde.

Ik ben blij dat je dat ook zo ziet, maar ik vraag me af of gebruikers en leveranciers dat ook zo zien en blijven zien.

> Persoonlijk vindt ik het vreemd dat je één laag zou willen met alle putnummers, zonder dat je deze aan een stelsel koppelt.

Niet zozeer dat ik dat zou willen, maar vooral noodzaak: in het verleden hebben we bij putten geen onderscheid per stelsel gemaakt, omdat het stelseltype al blijkt uit de leidingen die op de put zijn aangesloten. Dus niet van alle putten is geregistreerd tot welk stelsel ze behoren. Het gaat me er vooral om dat voor die putnummers niet een 'OVERIG' laag wordt gebruikt en in het algemeen dat uit alle laagnamen die we in de NLCS ter beschikking stellen duidelijk blijkt dat OVERIG een specifiek stelsel betreft en niet een vergaarbak wordt.
Zo zijn er ook leidingen in ons beheersysteem van het type 'onbekend'. Slecht, ik weet het, maar ze staan er nu eenmaal zo in. Als we de enige in Nederland zijn dan lossen we het zelf op, maar ik vraag het me af.

> Met de verplichting dat iedereen eigen objecten mag aanmaken, zou je moeten stimuleren dat gebruikers aanvullingen gaan maken en niet deze vergaarbak gebruiken.

Precies dat! Als 'OVERIG' in een laagnaam is opgenomen dan moet wel duidelijk zijn waarvoor die laag wel en niet gebruikt kan worden. Bij hoofdgroep RI is dat goed uit te leggen.

**Comment by MvanderHulst** [comment]
@SanderNijhof 
Het gros van de motie heb ik verwerkt in het voorstel voor 5.1

Er is nog 1 puntje waar ik even mee zit....

Straks is de OBJECTENboom van RI:
![image](https://github.com/nl-digigo/NLCS/assets/144665595/ac47b9d2-99c8-4bab-ae3b-dcfc6e105d1a)

Waarbij alle stelselsoorten bevatten:
- rioolleiding_bob
- rioolleiding_materiaal
- rioolput_putnummer
- rioolput_putrandhoogte
- en uiteraard de rest.

Je wilt graag deze 'labels' ook stelselloos kunnen toepassen, wat ik volledig begrijp.
De objectenboom zou dan worden:
(DIVERSE)
BOB
DRAINAGE
DWA
GWA
HWA
ITR
MATERIAAL
OVERIG
PERSLEIDING
PUTNUMMER
PUTRANDHOOGTE
RWZI
VACUUMLEIDING

Hier staan de stelsels en 'losse' onderdelen dan door elkaar heen. Dit vindt ik niet fraai.
Graag zou ik dit toch in een hoofdstukje (OBJECT)  zetten...

OVERIG is voor een ander soort stelsel, dan één voor de standaard systemen.
Dit voldoet niet als 'ongedefineerd'....

ALGEMEEN als 'stelsel' toevoegen was ook niet gewenst....

ONBEKEND is hierbij denk ik ook niet het juiste alternatief....

is er een acceptabele 'algemene' term voor te bedenken?
Als ik alles als OBJECT ga toevoegen, ben ik bang dat daar straks ook tussenstaat:
TRANSPORTLEIDING
OVERSTORTLEIDING
BERGINGSLEIDING
BRANDLEIDING e.d.

waar stopt het dan...

**Comment by ElisabethKloren** [comment]
Ik zou er voor zijn om de logica van netbeheer te volgen > er wordt in NLCS altijd getekend met een stelsel & deze staat altijd vooraan in de laagnaam; 

dan zou je voor deze gebruikerswens wel een STELSEL-XX kunnen toevoegen. Dan is duidelijk dat het stelsel niet altijd gespecificeerd is.

Ik heb even gekeken naar de mapping naar PDOK Thema Stedelijk Water > daarin komen ook de laagnamen voor met "overig" dus we moeten wel een onbekend stelsel toevoegen.

**Comment by SanderNijhof** [comment]
Ik blijf erbij 'OVERIG' is geen stelseltype, maar een verzamelnaam voor het niet gedefinieerde. Gewoon weglaten dus. 
Dan komen objecten inderdaad niet gegroepeerd te staan, maar dat komt omdat een stelseltype door de GWSW als een object wordt gezien maar in werkelijkheid geen (fysiek) object is.
Lastig, ik weet geen betere oplossing.
