### ISSUE TITLE
NLCS-IMBOR projectie: AL

### ISSUE THREAD

**Issue by wjtmollema** [nl-digigo/NLCS#333]
In dit issue wordt de voortgang van het opstellen van een projectie van de NLCS-laagnamen naar IMBOR-objecttypes voor de hoofdgroep AL weergegeven. Relevante notulen of discussiepunten van de NLCS-IMBOR commissie kunnen ter raadpleging worden bijgevoegd.

**Projectiedocument**
[20240304_NLCS-OBJECTEN-SKOS-Mapping.IMBOR.2022_AL.xlsx](https://github.com/nl-digigo/NLCS/files/14615671/20240304_NLCS-OBJECTEN-SKOS-Mapping.IMBOR.2022_AL.xlsx)

**Status**
Vastgesteld: Buiten scope.

**Comment by ElisabethKloren** [comment]
Eens, buiten scope en daarmee sluit ik deze issue af
