### ISSUE TITLE
NLCS-IMBOR projectie: BC

### ISSUE THREAD

**Issue by wjtmollema** [nl-digigo/NLCS#335]
In dit issue wordt de voortgang van het opstellen van een projectie van de NLCS-laagnamen naar IMBOR-objecttypes voor de hoofdgroep BC weergegeven. Relevante notulen of discussiepunten van de NLCS-IMBOR commissie kunnen ter raadpleging worden bijgevoegd.

**Projectiedocument**
[20240304_NLCS-OBJECTEN-SKOS-Mapping.IMBOR.2022_BC.xlsx](https://github.com/nl-digigo/NLCS/files/14615744/20240304_NLCS-OBJECTEN-SKOS-Mapping.IMBOR.2022_BC.xlsx)

**Status**
Buiten scope. Opgesteld.

**Comment by ElisabethKloren** [comment]
akkoord, buiten scope, daarmee sluit ik deze issue
