### ISSUE TITLE
#1501	"NLCS 5 kent de lagen: OG-BEBOUWING_HOOFDGEBOUW OG-BEBOUWING_ENTREE_HOOFDGEBOUW

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#34]
#1501	"NLCS 5 kent de lagen:
OG-BEBOUWING_HOOFDGEBOUW
OG-BEBOUWING_ENTREE_HOOFDGEBOUW

Is niet logischer:
OG-BEBOUWING_HOOFDGEBOUW
OG-BEBOUWING_HOOFDGEBOUW_ENTREE

En:
OG-BEBOUWING_BIJGEBOUW
OG-BEBOUWING_BIJGEBOUW_OPTIE
OG-BEBOUWING_ENTREE_BIJGEBOUW

Wordt dan:
OG-BEBOUWING_BIJGEBOUW
OG-BEBOUWING_BIJGEBOUW_OPTIE
OG-BEBOUWING_BIJGEBOUW_ENTREE

Waarom straatnaam onder ‘bebouwing’ en niet onder ‘weg’?
Waarom bestaan beide lagen OG-TOPOGRAFIE_WATER én OG-WATER, kan de laag ‘topografie’ weg?
in de bijlage nog een aantal lagen m.b.t. ‘overig’ in de laagnaam. Ik meende dat we dat niet willen in laagnamen.
Overig komt wellicht bij het GWSW vandaag? Moeten we dat dan volgen?
En er staan ook lagen zonder ‘overig’ in de groep RI, moeten we die dan niet gelijktrekken met de ander RI-lagen?"

**Comment by NielsNederpel** [comment]
en worden ook de voorgestelde decompositie voorstellen over genomen?

**Comment by MvanderHulst** [comment]
@NielsNederpel ik zie dat is een IE voorstel in de verkeerde issue heb gezet.
Jou voorstel moet inderdaad worden overgenomen.

**Comment by MvanderHulst** [comment]
@ElisabethKloren ik kan bovenstaande scenario niet vinden in de database.
kan je dit toelichten, of is dit achterhaald?

**Comment by ElisabethKloren** [comment]
1. BEBOUWING_ENTREE bestaat nu alleen maar; het onderscheid naar wat voor soort gebouw is niet nodig, het gebouwtype wordt al aangegeven in de laagnaam waar het gebouw zelf op getekend is. In de NLCS 5.0 zat alleen nog maar EENTREE_GARAGE; die laat ik vervallen om het geheel logisch opgebouwd te houden
2. BEBOUWING_STRAATNAAM gewijzigd naar WEG_STRAATNAAM
3. TOPOGRAFIE_WATER bestaat niet in versie 5.0, probleem is dus al opgelost
4. overig wordt in andere issues aangepakt.

**Comment by MvanderHulst** [comment]
@ElisabethKloren punt 2 ook even goed controleren met eventuele BGT mapping.

**Comment by ElisabethKloren** [comment]
BGT mapping is inderdaad actie als ik alle wijzigingen verwerkt heb

**Comment by ElisabethDeVries** [comment]
[[Release note]] De laagnaam BEBOUWING_ENTREE_GARAGE vervalt, entrees worden verder niet uitgesplitst naar gebouwtype. BEBOUWING_OVERIG vervalt, als men de bebouwing verder wil uitsplitsen kunnen daar individuele laagnamen voor worden toegevoegd, of het object kan op de laag BEBOUWING worden geplaatst.
Het object BEBOUWING_STRAATNAAM vervalt, in plaats daarvan komt het object WEG_STRAATNAAM terug. Dit is logischer voor de gebruikers.
