### ISSUE TITLE
NLCS-IMBOR projectie: HC

### ISSUE THREAD

**Issue by wjtmollema** [nl-digigo/NLCS#343]
In dit issue wordt de voortgang van het opstellen van een projectie van de NLCS-laagnamen naar IMBOR-objecttypes voor de hoofdgroep HC weergegeven. Relevante notulen of discussiepunten van de NLCS-IMBOR commissie kunnen ter raadpleging worden bijgevoegd.

**Projectiedocument**
[20240304_NLCS-OBJECTEN-SKOS-Mapping.IMBOR.2022_HC.xlsx](https://github.com/nl-digigo/NLCS/files/14615900/20240304_NLCS-OBJECTEN-SKOS-Mapping.IMBOR.2022_HC.xlsx)

**Status**
Buiten scope. Opgesteld.

**Comment by ElisabethKloren** [comment]
Vastgesteld op buiten scope van IMBOR, daarmee wordt deze issue afgesloten
