### ISSUE TITLE
NLCS-IMBOR projectie: HU

### ISSUE THREAD

**Issue by wjtmollema** [nl-digigo/NLCS#344]
In dit issue wordt de voortgang van het opstellen van een projectie van de NLCS-laagnamen naar IMBOR-objecttypes voor de hoofdgroep HU weergegeven. Relevante notulen of discussiepunten van de NLCS-IMBOR commissie kunnen ter raadpleging worden bijgevoegd.

**Projectiedocument**
[20240304_NLCS-OBJECTEN-SKOS-Mapping.IMBOR.2022_HU.xlsx](https://github.com/nl-digigo/NLCS/files/14637538/20240304_NLCS-OBJECTEN-SKOS-Mapping.IMBOR.2022_HU.xlsx)

**Status**
Buiten scope. Opgesteld.

**Comment by ElisabethKloren** [comment]
@wjtmollema ik snap niet helemaal waarom dit buiten scope is, er zijn wel relaties met IMBOR te zien in de tabel?

**Comment by ElisabethKloren** [comment]
duidelijk, en omdat deze hoofdgroep buiten scope is voor IMBOR sluit ik nu deze issue af
