### ISSUE TITLE
NLCS-IMBOR projectie: KC

### ISSUE THREAD

**Issue by wjtmollema** [nl-digigo/NLCS#348]
In dit issue wordt de voortgang van het opstellen van een projectie van de NLCS-laagnamen naar IMBOR-objecttypes voor de hoofdgroep KC weergegeven. Relevante notulen of discussiepunten van de NLCS-IMBOR commissie kunnen ter raadpleging worden bijgevoegd.

**Projectiedocument**
[20240304_NLCS-OBJECTEN-SKOS-Mapping.IMBOR.2022_KC.xlsx](https://github.com/nl-digigo/NLCS/files/14615945/20240304_NLCS-OBJECTEN-SKOS-Mapping.IMBOR.2022_KC.xlsx)

**Status**
Buiten scope. Opgesteld.

**Comment by ElisabethKloren** [comment]
Buiten scope, daarmee sluit ik deze issue af
