### ISSUE TITLE
NLCS-IMBOR projectie: MC

### ISSUE THREAD

**Issue by wjtmollema** [nl-digigo/NLCS#352]
In dit issue wordt de voortgang van het opstellen van een projectie van de NLCS-laagnamen naar IMBOR-objecttypes voor de hoofdgroep MC weergegeven. Relevante notulen of discussiepunten van de NLCS-IMBOR commissie kunnen ter raadpleging worden bijgevoegd.

**Projectiedocument**
[20240304_NLCS-OBJECTEN-SKOS-Mapping.IMBOR.2022_MC.xlsx](https://github.com/nl-digigo/NLCS/files/14615997/20240304_NLCS-OBJECTEN-SKOS-Mapping.IMBOR.2022_MC.xlsx)

**Status**
Buiten scope. Opgesteld.

**Comment by ElisabethKloren** [comment]
Akkoord buiten scope van IMBOR, daarmee sluit ik deze issue
