### ISSUE TITLE
NLCS-IMBOR projectie: MW

### ISSUE THREAD

**Issue by wjtmollema** [nl-digigo/NLCS#354]
In dit issue wordt de voortgang van het opstellen van een projectie van de NLCS-laagnamen naar IMBOR-objecttypes voor de hoofdgroep MW weergegeven. Relevante notulen of discussiepunten van de NLCS-IMBOR commissie kunnen ter raadpleging worden bijgevoegd.

**Projectiedocument**
[20240304_NLCS-OBJECTEN-SKOS-Mapping.IMBOR.2022_MW.xlsx](https://github.com/nl-digigo/NLCS/files/14616018/20240304_NLCS-OBJECTEN-SKOS-Mapping.IMBOR.2022_MW.xlsx)

**Status**
Buiten scope. Opgesteld.

**Comment by ElisabethKloren** [comment]
buiten scope IMBOR, daarmee sluit ik deze issue
