### ISSUE TITLE
NLCS-IMBOR projectie: SC

### ISSUE THREAD

**Issue by wjtmollema** [nl-digigo/NLCS#359]
In dit issue wordt de voortgang van het opstellen van een projectie van de NLCS-laagnamen naar IMBOR-objecttypes voor de hoofdgroep SC weergegeven. Relevante notulen of discussiepunten van de NLCS-IMBOR commissie kunnen ter raadpleging worden bijgevoegd.

**Projectiedocument**
[20240304_NLCS-OBJECTEN-SKOS-Mapping.IMBOR.2022_SC.xlsx](https://github.com/nl-digigo/NLCS/files/14616056/20240304_NLCS-OBJECTEN-SKOS-Mapping.IMBOR.2022_SC.xlsx)

**Status**
Buiten scope. Opgesteld.

**Comment by ElisabethKloren** [comment]
Akkoord, wegens buiten scope IMBOR sluit ik deze issue
