### ISSUE TITLE
#1476	in de lin file bestaat SWA nog als lijnstyle. echter zijn alle SWA objecten vervallen

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#36]
#1476	in de lin file bestaat SWA nog als lijnstyle. echter zijn alle SWA objecten vervallen

**Comment by ElisabethKloren** [comment]
Reactie Expertcommissie
opmerking is terecht, let ook op ticket #839

**Comment by ElisabethKloren** [comment]
To Do
SWA linetype laten vervallen

**Comment by ElisabethKloren** [comment]
De .LIN file wordt automatisch gegenereerd vanuit de database, dus check of hier een lijnstijl in staat > ik vindt wel RI_SWA lijnstijlen, worden deze bedoeld? Er staan geen SWA lijnstijlen in

**Comment by MvanderHulst** [comment]
RI_SWA wordt inderdaad bedoeld.
Deze kan komen te vervallen, betreft dan de linetypes:
RI-SWA_AANSLUITLEIDING-SO
RI_SWA_VARIANT01-SO
RI-SWA_-SO
V-RI-SWA_AANSLUITLEIDING-SO
V-RI_SWA_VARIANT01-SO
V-RI-SWA_-SO

**Comment by ElisabethDeVries** [comment]
[[Release note]] Uit hoofdgroep RI (RIoleringen) zijn niet-gebruikte lijnstijlen verwijderd.
