### ISSUE TITLE
lijnstijlen markeringen in NLCS

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#364]
Ik ben ook werkzaam bij een gemeente waar ze Microstation gebruiken.
Ook daar komen we erachter dat alle lijnstijlen die voor markeringen worden gebruikt een verkeerde schaal hebben.
In de NLCS 4.2 stond alles perfect , maar nu is het verre van goed.

Onderstaande tekening (uit AutoCAD) met driehoeken 50x50 bij een wegbreedte van 3,0m en schaal 1:500
Wanneer gaan jullie dit herstellen?

![lijnstijlverhardingen](https://github.com/nl-digigo/NLCS/assets/48585720/4b2765aa-ff65-42db-ae91-c41ba61229f9)

**Comment by ElisabethKloren** [comment]
Dit gaan we in versie 5.1 herstellen

**Comment by SanderNijhof** [comment]
Ik zou dit als NLCS-gebruiker ook even met The People Group opnemen. Bij de Optimize tooling worden door The People Group aangepaste lijnstijlen voor markeringen geleverd die afwijken van de standaard NLCS-lijnstijlen. En -SO wordt anders toegepast dan in AutoCAD.

**Comment by MvanderHulst** [comment]
Zie issue #21 , daar is het voorstel uitgewerkt.
