### ISSUE TITLE
#1473	bij het symbool (V-)SVH-SBS_DIKFORMAAT_BLOK(_KL)-SO ontbreken de stipjes

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#37]
#1473	bij het symbool (V-)SVH-SBS_DIKFORMAAT_BLOK(_KL)-SO ontbreken de stipjes hierdoor zijn deze symbolen gelijk aan de BSS variant. Ook omdat de voor ingevulde kleur niet overeenkomt met de overige SBS symbolen (G ipv RD)

**Comment by ElisabethKloren** [comment]
Reactie Expertcommissie
opmerking is terecht, let ook op ticket #882

**Comment by ElisabethKloren** [comment]
To Do
"aanpassen symbolen:
SVH-SBS_DIKFORMAAT_BLOK_KL-SO
V-SVH-SBS_DIKFORMAAT_BLOK_KL-SO
SVH-SBS_DIKFORMAAT_BLOK-SO
V-SVH-SBS_DIKFORMAAT_BLOK-SO
ook symbolen wijzigen in database (d.m.v. Excel)"

**Comment by MvanderHulst** [comment]
Zie ook issue #52

**Comment by ElisabethKloren** [comment]
symbool moet nog worden gemaakt

**Comment by ElisabethDeVries** [comment]
dubbel met #52
