### ISSUE TITLE
Symbool goot, wat is het nut?

### ISSUE THREAD

**Issue by MvanderHulst** [nl-digigo/NLCS#374]
Ik heb 2 blocks aangetroffen:

SVH-GOOT_SYMBOOL_KL-SO
SVH-GOOT_SYMBOOL-SO

Naast de naamgeving.... is dit een symbool voor een functie. Heeft dit een toegevoegde waarde?

![image](https://github.com/nl-digigo/NLCS/assets/144665595/fa775b8a-16a0-4485-84ab-96b6d0ecf0e2)

**Comment by ElisabethKloren** [comment]
nee, deze heeft geen zin, voorstel is verwijderen

**Comment by SanderNijhof** [comment]
Wel eens gebruikt voor visualisatie van een goot, maar ik zal ze niet missen als ze er niet meer zijn.

**Comment by ElisabethDeVries** [comment]
[[Release note]] Uit hoofdgroep VH (VerHardingen) zijn bij het object GOOT de symbolen met zoekterm SVH-GOOT_SYMBOOL verwijderd, deze hadden geen toegevoegde waarde ten opzichte van de specifieke soorten goten.
