### ISSUE TITLE
De tooling moet duidelijk aangeven met welke versie van de NLCS in de tooling wordt gewerkt.

### ISSUE THREAD

**Issue by SanderNijhof** [nl-digigo/NLCS#375]
De tooling moet duidelijk aangeven met welke versie van de NLCS in de tooling wordt gewerkt.
Lijkt me logisch, maar zie het nog niet in de software vereisten staan.

**Comment by ElisabethKloren** [comment]
Yes, toegevoegd: De gebruiker dient in de applicatie te kunnen zien met welke versie van de standaard het model getekend is.
