### ISSUE TITLE
in de database symbolen hoofdgroepen maken voor elke hoofdgroep, ook als zitten er nog geen blocks in

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#378]

**Comment by Dirkjan-CADAC** [comment]
Op dit moment zijn de objectenbibliotheek niet gelijk aan de S-bibliotheek. Voorbeeld: "RO" bestaat wel in de S-bibliotheek, maar niet in de objectenbibliotheek. Mijn idee is om deze gelijk te maken, anders kunnen gebruikers nog steeds hun eigen bibliotheekcodes aanmaken.

**Comment by ElisabethKloren** [comment]
ontstaat hierdoor ook issue #381 ?

**Comment by NielsNederpel** [comment]
@Dirkjan-CADAC 
RO was uiteraard alleen een voorbeeld...en dus sowieso een foutje in de database zoals nu blijkt.
als we RO laten vervallen bij de symbolen bibliotheken hebben we er nog steeds maar 20 symboolbibliotheken.
echter zijn er 35 hoofdgroepen / objectenbibliotheken.

is de vraag dan ook of we alvast de 15 "lege" symbolen bibliotheken gaan aanmaken?

**Comment by MvanderHulst** [comment]
ik denk dat het wel zo consequent is.
een lege bibliotheek aanleveren geeft duidelijk aan dat hij niet vergeten is, maar gewoon geen inhoud heeft.

**Comment by ElisabethKloren** [comment]
Is dit ook wenselijk voor de arceringsbibliotheken? Het valt nu sowieso op, dat de arceringsbibliotheek ACO bestaat (constructies), met links naar objecten in verschillende hoofdgroepen.

**Comment by ElisabethKloren** [comment]
Ik sluit dit issue af, in de publicatie van 5.1 zitten alle symbolenbibliotheken, als zitten er nog geen objecten in.
voor de arceringsbibliotheken even een eigen issue aangemaakt #470

**Comment by ElisabethDeVries** [comment]
[[Release note]] In NLCS 5.0 waren niet voor alle hoofdgroepen symbolenbibliotheken beschikbaar. Om te voorkomen dat in individuele bibliotheken met afwijkende ID's en namen gewerkt gaat worden zijn in NLCS 5.2 Voor alle hoofdgroepen symbolenbibliotheken toegevoegd. Zie [hier](https://nl-digigo.github.io/NLCS/changelog/NLCS_Query_Sbibliotheken-concept-5.2.html) voor een overzicht van bestaande en toegevoegde symbolenbibliotheken.

**Comment by ElisabethDeVries** [comment]
Reopen voor selectie 5.2 publicatie
