### ISSUE TITLE
Plot opmaak voorschrijven?

### ISSUE THREAD

**Issue by SanderNijhof** [nl-digigo/NLCS#379]
Moeten we in de Formele Beschrijving gaan opnemen hoe een plotlayout opgebouwd moet worden? Of laten we dit vrij?
Nu zie ik deze verschillende werkwijzen:

1. Er wordt een tekenkader in het ontwerp geplaatst en geen apart layoutmodel gebruikt. 
2. Er wordt een layoutmodel gebruikt waarbij het ontwerp wordt verschaald naar het layoutmodel. Bij 1:200 wordt het ontwerp 1:1 getekend en verkleint zodat die verschaalt naar het papierformaat.
3. Er wordt een layoutmodel gebruikt waarbij het layoutmodel wordt verschaald naar de schaal van het ontwerp. Bij 1:200 wordt ontwerp 1:1 getekend en het layoutmodel 200x vergroot.

Het zou niet uit moeten maken, maar toch zie ik hierdoor per werkwijze soms verschillende verschalingen van lijnstijlen en symbolen 'op papier'.
zie ook issue #309

**Comment by MvanderHulst** [comment]
Ik ben hier wel voorstander van.

Werkwijze zou moeten zijn:
In de 'MODEL' wordt de tekening opgesteld.
In de 'LAYOUT' wordt een kader geplaatst op ware grootte
In de layout wordt een viewport gemaakt, welke een schaalfactor meekrijgt zodat de verschaling goed staat.
Een kader verschalen zou niet toegestaan moeten zijn.

Het benoemen van de daadwerkelijke 'vergroting' vindt ik wel weer lastig.
In AutoCAD wordt alles in de Model 1-op-1 getekend.
Echter hebben de symbolen een schaal '1' waarbij ze op een 1:200 tekening goed leesbaar zijn.
Bij het plotten met een viewport wordt de viewport schaal 1:200 gezet. Hierbij is geen sprake van een 'verschaling' van 200x groter. Dit is allemaal achtergrond geregeld en ZEER verwarrend en lastig om éénduidig te omschrijven.

**Comment by ElisabethKloren** [comment]
ik heb eerste deel van Michels tekst opgenomen in de eisen aan tekeningen en modellen

**Comment by DerkNouwensTPG** [comment]
Hoi allen,

Ingeborg wees me op dit ticket.

Deze kwam even als een verrassing. 
Paul Haffmans geeft aan dat hij deze niet had vernomen en heeft behoorlijke impact op bv onze software Optimize Plot CE.

Waarom deze keuze en niet eerst voorleggen in expert commissie of een leveranciersoverleg i.p.v. zomaar in de standaard opnemen. Of moet dat voorleggen nog gebeuren. 

Reden wij verschalen in onze software de dgn niet in de afdrukmodel maar juist het kader (want kader is geheel niet interessant in mijn mening, is middel tot het presenteren van wat belangrijk is de tekening), de tekening blijft in onze situatie netjes op coördinaat en blijft eenvoudig meetbaar ook in de Plot layout. Overigens zijn hier ook manieren voor als je wel verschaald.

Dit werkwijze is overigens een werkwijze welke ik in het verleden ook al aanhield toen ik met AutoCAD begon te tekenen half jaren ‘80. Ik ben daar niet meer van afgeweken en toen ik in aanraking kwam met de Optimize Plot software van TPG was dat dus voor mij ook een logische keuze. Ook veel van onze klanten zijn blij met deze keuze. Niet iedereen natuurlijk, zoals je dat hier hoort. Er zijn dus meer dan een geluid. Derhalve zou ik hoe een Plot moet zijn opgebouwd zeker niet vastleggen, veel te betuttelend, je kan een afdruk dus op 2 manieren opbouwen prima toch. Optimize Plot CE doet dat op de ene manier, wil een klant het anders dan maken ze gebruik van standaard Bentley opties of moet software worden aangepast.

Daarnaast hoe verhoud dit zich tot toekomstige wensen in bv de gewenste uitwissel standaard? Daar valt een Plot layout sowieso niet onder verwacht ik. 

Ik ga er wellicht ten onrechte ook vanuit dat als de tekening van AutoCAD naar MicroStation gaat en van buro A naar B deze buro's toch eigen Plot opmaken doorvoeren.

m.v.g. Derk Nouwens

**Comment by MvanderHulst** [comment]
@DerkNouwensTPG 
De toe te passen schaalfactoren van symbolen (SO) vallen en staan onder andere met de fundamentele keuze van de methode van het samenstellen van de kaders.
Het verschalen van kaders is in de AutoCAD wereld een ondenkbare manier van werken. Sinds de jaren 80 is er een hoop veranderd. ;-)
Met uitwisseling tussen CAD en Microstation zit er altijd een probleem in de verschaling, mede door dit euvel.
Vanuit uniformiteit en uitwisseling is deze keuze gemaakt.
Na een grote ronde langs gebruikers is ook gebleken dat deze methodiek de overduidelijke voorkeur heeft.
Ik weet dst TPG hier ook al langere tijd over benaderd is door gebruikers. Dit kan dan ook niet onbekend zijn dat deze wens al heel lang speelt.

**Comment by DerkNouwensTPG** [comment]
Wij (TPG, niet op persoonlijke noot) zijn van mening dat dit een non-issue is. Hoe de plot is opgebouwd is geen onderdeel van de doelstelling van de NLCS namelijk uitwisseling van digitale tekeningen en het verder bouwen op de digitale modellen. Hoe dat digitale model gerepresenteerd wordt op de plot heeft daar geen invloed op. En het resultaat van een papieren kaart is voor alle drie door Sander benoemde werkwijzen gelijk.

Als je dit hard gaat voorschrijven dan heeft dat ook effect op de gebruikers die geen software gebruiken om conform NLCS te werken. Het is dus niet alleen een issue voor de software-leverancier.

Ook in AutoCAD is het mogelijk om te werken met een verschaald kader en viewports met daarin 1:1 het ontwerp. Het feit dat jullie niet op deze manier werken is meer een persoonlijke voorkeur dan een goed onderbouwd gegeven. En heel eerlijk vinden wij de opmerking dat iedereen op jullie manier wil werken ook subjectief. Maar daar willen we onderzoek naar doen. Daar komt bij dat ook buiten de NLCS-gebruikers de Optimize Plot-tool gebruikt wordt, dus die nemen we ook mee in onze inventarisatie.

Als blijkt dat er inderdaad het merendeel van de gebruikers een plotcompositie wil met een 1:1 kader dan zullen wij kijken of wij dat toe kunnen voegen aan de Plottool.

**Comment by MvanderHulst** [comment]
@DerkNouwensTPG 
Binnen AutoCAD wordt gewerkt in de 'Model' en een plot gemaakt in de 'Layout', dit is geen voorkeur, maar gemeen goed.
Je moet als gebruikers serieuze aanpassingen in AutoCAD doen, wil je een kader kunnen verschalen i.p.v. de viewport.
Dit moet gestandaardiseerd worden omdat er nu bij uitwisseling verschalingsproblemen zitten, dit omdat in AutoCAD de -SO symbolen juist fysiek worden vergroot voor de plot en bij de TPG werkwijze wordt het symbool pas op de plot 'vergroot'. Er zit in de brondata dus een verschil in verschalingsfactoren, welke bij uitwisseling voor problemen zorgen.
Dus ja, dit is m.i. zeker wel een punt waar de NLCS iets mee moet.
Officieel staat het op deze manier ook al in de FB, dat een symbool een schaalfactor van 200 moet krijgen bij een overeenkomstige plot. hier gaat de TPG plot-module ook al aan voorbij.

eigenlijk is deze aanpassing niks anders van een verduidelijking van de eisen zoals deze gesteldworden aan het 'SO' principe.

Als de wens is om dit te laten onderzoeken, dan dit graag onafhankelijk vanuit de NLCS laten doen en niet door iemand met belangen bij deze casus, anders kunnen we de uitslag natuurlijk al voorspellen.

Maargoed, deze issue is uitgebreid besproken bij 2 EC sessies en akkoord bevonden, dus het bevreemd mij wel dat dit wéér een onderwerp van discussie moet worden.

**Comment by SanderNijhof** [comment]
@MvanderHulst , @DerkNouwensTPG 
Ik heb gemerkt dat het verschalen bij de opbouw van je plotlayout een relatie heeft met de verschaling van symbolen (SO) en lijnstijlen (SO). Daarvoor zijn verschillende mogelijkheden zowel met als zonder 'annotative' en daar wordt nu niet eenduidig mee omgegaan. Daardoor kun je onbedoelde schaalverschillen krijgen zowel in je ontwerp als in je plotlayout.

Ik denk dat het vooral belangrijk is goede afspraken te maken over gebruik van de lijnstijlschaalfactoren en symboolschaalfactoren. Theoretisch zou het volgens mij dan prima mogelijk moeten zijn om je plotlayout te vergroten naar je ontwerp zoals TPG nu doet.

Dat gezegd hebbende... Ik weet niet beter dat binnen Bentley zeker de afgelopen 20 jaar, ook _in principe_ de plotlayout 1:1 wordt gehouden en de ontwerp-onderdelen verschaald worden naar de plotlayout. In de NLCS tooling voor Microstation v8i was dit ook zo verwerkt. Maar de Bentley-software biedt ook de mogelijkheid om daar van af te wijken. Per Microstation CONNECT is TPG met de NLCS-tooling een andere weg ingeslagen en zijn oude v8i NLCS-tekeningen niet meer met MS-CONNECT NLCS-tooling te gebruiken zonder problemen met verschaling te krijgen.

> Als blijkt dat er inderdaad het merendeel van de gebruikers een plotcompositie wil met een 1:1 kader dan zullen wij kijken of wij dat toe kunnen voegen aan de Plottool.

Heel graag, wij vragen hier al om sinds de pre-release van jullie eerste NLCS-Optimize CE versie. Vanaf deze kant alvast 24 gebruikers stemmen hiervoor.

**Comment by MvanderHulst** [comment]
> Heel graag, wij vragen hier al om sinds de pre-release van jullie eerste NLCS-Optimize CE versie. Vanaf deze kant alvast 24 gebruikers stemmen hiervoor.

Hier ook 8 stuks! :-)

**Comment by ElisabethDeVries** [comment]
[[Release note]] In de documentatie (Eisen aan tekeningen en modellen) is de volgende tekst toegevoegd: 
Plotopmaak
De werkwijze voor het opmaken van plots is:
•	In het model (Modelspace [AutoCAD] / Design model [MicroStation]) wordt de tekening opgesteld.
•	In de Layout (AutoCAD) of Sheet Models (MicroStation) wordt een kader geplaatst op ware grootte.
•	In de layout/sheet wordt een viewport gemaakt, welke een schaalfactor meekrijgt zodat de verschaling goed staat. Een kader verschalen is niet toegestaan.
De achterliggende reden van deze werkwijze: er ontstaan anders problemen bij het uitwisselen van modellen tussen gebruikers en pakketten.

**Comment by ElisabethDeVries** [comment]
Ik ga ervan uit dat dit issue controversieel is voor de 5.2 release en verzet deze naar milestone 6.0 en heropen hem weer. 

De vraag is: gaan we de standaard voor 6.0 terugbrengen tot het uitwisselen van objecten met een visuele representatie en laagnaam in CAD, of blijven we proberen om de problemen met uitwisseling van werk tussen de CAD-pakketten op te lossen?

**Comment by SanderNijhof** [comment]
> De vraag is: gaan we de standaard voor 6.0 terugbrengen tot het uitwisselen van objecten met een visuele representatie en laagnaam in CAD, of blijven we proberen om de problemen met uitwisseling van werk tussen de CAD-pakketten op te lossen?

Volgens mij is het hier vooral belangrijk dat je eerst goed vastlegt wat er precies misgaat bij uitwisseling tussen CAD-pakketten: wat gaat er concreet fout, is dat op te lossen of te voorkomen, en zo ja hoe.

En als iets niet goed oplosbaar is of niet wenselijk is om te ondersteunen, dan kun je dat beter expliciet benoemen en waar mogelijk adviseren om zulke situaties te vermijden. En als ze in de praktijk toch onvermijdelijk blijken, dan moet je dat ook gewoon als beperking accepteren in plaats van het toch in de standaard proberen te krijgen.

Daarnaast is het denk ik belangrijk dat de formele beschrijving van de NLCS gewoon heel duidelijk wordt over wat de bedoeling is van de standaard. Dat geeft softwareleveranciers helderheid over wat ze moeten ondersteunen en welke aanpassingen ze moeten doen. En dan kun je vanuit NLCS ook aangeven wat er op korte termijn (versie 5.1/2) moet gebeuren en wat eventueel later pas in bijv. versie 6.0.

**Comment by MvanderHulst** [comment]
@ElisabethDeVries 
Deze issue heeft raakvlak met issue https://github.com/nl-digigo/NLCS/issues/309

Als deze uitspraak door gaat, moeten alle naamgevingen van de kaders weer herzien worden.
Hoeft geen rem te zijn, maar wel goed om even te borgen.
