### ISSUE TITLE
over -SO

### ISSUE THREAD

**Issue by SanderNijhof** [nl-digigo/NLCS#380]
Dacht dat hier al een issue voor was, maar kan die niet vinden, vandaar alsnog:

Volgens mij wordt in de NLCS-tooling -SO anders toegepast dan in de Formele Beschrijving wordt uitgelegd.
Bijna alle lijnstijlen en symbolen hebben de toevoeging -SO gekregen (????????).

Voorstel: de toevoeging -SO laten vervallen uit alle symbolen en lijnstijlen en daarmee is alles vrij schaalbaar en te regelen via de NLCS-tooling.
Resultaat:  geen verwarring meer over de betekenis van -SO plus de mogelijkheid om de best leesbare tekeningen te maken.

**Comment by MvanderHulst** [comment]
Oneens.
InfraCAD, NedInfra en GWW-CAD verwerken de SO allemaal op dezelfde manier.
Optimze (Microstation) is waarschijnlijk de enigste afwijkende hierin.

Buiten de discussie van 'vroeger' of 'wat het ooit was'.
Laatste inzichten voor SO zijn:

-SO = Schaalbaar Object = 'Annotatief' object = ook uit te leggen als 'Symbolisch Object = niet op ware grootte getekend.
Alle SO objecten zijn leesbaar schaal 1:200 met een schaalfactor 1.
Als de tekening op 1:500 wordt geplot, moet het symbool een schaalfactor 2.5 krijgen.
Hierdoor is het symbool in de MODEL groter, waardoor deze op de 1:200 en 1:500 plot evengroot zichtbaar is.
Inplaats van het toekennen van een andere schaal, kan een symbool ook ANNOTATIEF gemaakt worden.
Hierdoor regelt de software automatisch de verschaling.

Een 'standaard' NIET SO symbool heeft altijd schaalfactor 1.
Hierdoor is deze in de model altijd dezelfde schaal, ongeacht de plot.
Hierdoor is deze op een 1:500 plot dus KLEINER dan een 1:200 plot.
Het symbool schaalt niet mee, dus is altijd op ware grootte.

Alle lijntypes zijn 'SCHAALBARE OBJECTEN' omdat de presentatie (automatisch) een andere schaalfactor krijgt bij een andere schaal. Daar waar je symbolen met de hand moet schalen (of annotatief moet maken) gaat dit voor lijntypes automatisch en dit kan niet anders in AutoCAD. Daarom zijn alle lijntypes SO gemaakt om dit consequent door te voeren voor alle tekenobjecten.

**Comment by SanderNijhof** [comment]
>Alle lijntypes zijn 'SCHAALBARE OBJECTEN' omdat de presentatie (automatisch) een andere schaalfactor krijgt bij een andere schaal. Daar waar je symbolen met de hand moet schalen (of annotatief moet maken) gaat dit voor lijntypes automatisch en dit kan niet anders in AutoCAD. Daarom zijn alle lijntypes SO gemaakt om dit consequent door te voeren voor alle tekenobjecten.

Voor deze functionaliteit hoeft een lijnstijl niet -SO te zijn. Met de toevoeging '-SO' verplicht je een plotverschalingsfactor en sluit je elke andere verschaling uit. Zonder '-SO' is elke verschalingfactor mogelijk conform FB en dat is volgens mij nodig om tekeningen leesbaar te houden. 

Begrijpen we elkaar verkeerd? Volgens mij willen we allebei goed leesbare tekeningen.

>Alle SO objecten zijn leesbaar schaal 1:200 met een schaalfactor 1.
Als de tekening op 1:500 wordt geplot, moet het symbool een schaalfactor 2.5 krijgen.
Hierdoor is het symbool in de MODEL groter, waardoor deze op de 1:200 en 1:500 plot evengroot zichtbaar is.

Een rioolput is een -SO symbool, een Noordpijl is ook een -SO symbool.
Als ik jouw uitleg volg krijg ik dit resultaat:
![image](https://github.com/nl-digigo/NLCS/assets/143598041/fc63b7cd-4320-437f-b71a-0a767f97a435)

De Noordpijl-SO en rioolput-SO behouden op elke afdrukschaal dezelfde grootte, maar voor een rioolput symbool wil je dat toch niet?
Toch zijn bijna alle lijnstijlen en symbolen -SO gemaakt. 

Ik vind dat een rioolput geen -SO symbool moet zijn. Het symbool MAG je dan verschalen, maar je MOET dat niet.
Je krijgt dan dit:
![image](https://github.com/nl-digigo/NLCS/assets/143598041/8328c071-f6dc-4bbc-8f9f-ab427b4a4b3a)

Volgens Formele Beschrijving is dit al meer dan 10 jaar de bedoeling en dat heeft voor mij/ons altijd prima gewerkt. Ik vind dat een veel leesbaarder resultaat. De Formele Beschrijving staat ook toe dat je op een 1:1000 de symbolen zonder '-SO' bijv. een factor 2 groter maakt als je daarmee de tekening duidelijker leesbaar maakt. In jouw voorstel zie ik daarvoor geen ruimte.

Dit is hoe ik de vigerende Formele Beschrijving lees:

1. ALLE symbolen (= met en zonder -SO), lijnstijlen en wat je kunt bedenken zijn 'verschaalbaar' D.w.z. de tekenaar/tooling mag zelf bepalen met welke schaalfactor hij een object, symbool of lijnstijl tekent. 
2. ALLE symbolen zijn dusdanig getekend zodat als je ze met een schaalfactor 1 plaatst goed leesbaar zijn op een tekening 1:200. Op een 1:500 tekening is het symbool dus kleiner, maar nog steeds goed leesbaar. Dit geldt ook voor symbolen die op ware grootte getekend zijn: Of een symbool figuratief bedoeld is of op ‘ware grootte’ is niet relevant voor het plaatsen.
3. ALLE elementen mogen ‘Annotatief’ of ‘Niet-annotatief’ geplaatst worden. Dus zowel elementen met als zonder ‘-SO’ in de naam.
4. Elementen zonder toevoeging van -SO mogen elke schaalfactor krijgen. Bijvoorbeeld een schaalfactor 2.5 en kunnen ‘Annotatief’ of ‘Niet-annotatief’ geplaatst worden, om het gewenste resultaat te hebben. 'Mee schalen' is voor deze symbolen dus optioneel.
5. -SO symbolen worden ALTIJD met schaalfactor 1xplotschaal geplaatst en hebben op papier altijd dezelfde grootte. Een andere schaalfactor, zoals bijvoorbeeld 2.5 is dus niet toegestaan! Een goed voorbeeld van een dergelijk symbool is de Noordpijl. Je hebt bijvoorbeeld voor een 1:200 tekening voor -SO dus 2 opties: a: plaatsen met schaalfactor 1 + eigenschap ‘Annotatief’ zodat deze automatisch via de software met de plotschaal vergroot wordt, of b: handmatig het -SO object een schaalfactor 200 geven zonder eigenschap ‘Annotatief’. Dit maakt -SO symbolen byzonder t.o.v. andere symbolen, vandaar dat ze ook een toevoeging krijgen in de symboolnaam.

Volgens mij bied dit voldoende mogelijkheden voor zowel AutoCAD, Microstation, tekenaars en softwareleveranciers om goed leesbare tekeningen te maken. In tegenstelling tot wat bijna iedereen nu voorstelt.

**Comment by MvanderHulst** [comment]
Ha Sander,

Vooruitlopend op onderstaand, even een 'Microstation  vraag'.
Verschaald een 'Annotatief' symbool in Microstation ALTIJD, of heb je hier controle op?
Binnen AutoCAD kan ik namelijk een symbool wel de eigenschap 'Annotatief' meegeven, zonder dat deze automatisch gaat verschalen. Ik kan dan per schaal aangegeven of deze wel of niet aangepast moet worden.

Zie onderstaand, allemaal -SO symbolen, waarbij ik de maximale controle heb, op welke grote ik symbolen geplot wil hebben.

![image](https://github.com/nl-digigo/NLCS/assets/144665595/2db05882-003b-48a9-b0c5-89972cd33f93)
![image](https://github.com/nl-digigo/NLCS/assets/144665595/842f268d-9561-4936-bf8b-8228bb71132c)
De een tussenvariant wat zelf mogelijk is met SO symbolen.
![image](https://github.com/nl-digigo/NLCS/assets/144665595/3c2f475f-6e6e-45b0-ab8e-44460f019811)


Vanuit AutoCAD perspectief:
Functioneel bedoelen we volgens mij exact hetzelfde. Alleen de 'uitleg' van de definitie beschouwen we andersom.
De noordpijl laat ik even volledig buiten beschouwing, dit omdat de positie van het plaatsen (model of layout) verschilt of hij wel of niet 'verschaald' moeten worden.
De rioolput is een mooi voorbeeld.

Wederom, even helemaal los van wat er op de letter in de formele beschrijving staat. Hoe ik deze interpreteer:

Het symbool van de rioolput is een symbolische weergave van het object, welke dus geen representatie van de werkelijkheid is.
Omdat het slechts een 'Symbolische weergave' is, ben ik vrij om deze elke schaalfactor mee te geven die ik als gebruiker wil.
Dus een 'Schaalbaar Object' (-SO) is schaalbaar met elke schaal die ik als gebruiker wil. Dat het object schaalbaar IS, hoeft m.i. niet te betekenen dat hij verschaald MOET worden. Jou voorbeeld sluit hier perfect op aan:
![image](https://github.com/nl-digigo/NLCS/assets/144665595/891565f8-2c51-4245-837f-6420f6d59382)
Maar als ik het om wat voor reden dan ook zou willen, heb ik wel de vrijheid om de 'minder leesbare' variant te maken.

Idem voor de standaard BGT import, deze 'symbolische' objecten (-SO) zijn prima geschikt om te plotten op 1:200 en 1:500, het is slechts een symbool en geen daadwerkelijke afmeting. Maar als ik de symbolen bij een schaal 1:500, met de grootte van de standaard 1:200 wil plotten, kan dat ook. 'Schaalbare Objecten' MAG je verschalen, maar MOET niet.

Wanneer een symbool op ware grootte is getekend. Bijvoorbeeld een zitbankje, welke exacte afmetingen heeft, heeft geen toevoeging -SO, dit betekend dat het geen 'schaalbaar object' is. Wat logisch is, want als je hem verschaald, kloppen de maten niet meer. Dus 'niet schaalbaar', betekend 'op ware grootte', schaalbaar object, betekend indicatief.

Onderstaand ook een voorbeeld.
![image](https://github.com/nl-digigo/NLCS/assets/144665595/5ae868a0-d08f-4d64-acaf-508562789748)
Het indicatieve symbool met het rondje (SVH-BOOMKRANSBAND-SO), kan ik elke schaal geven die ik als gebruiker wil toekennen.
Het symbool 'SVH-BOOMKRANSBAND_1800X1800' is een vaste afmeting, en mag dus niet verschaald worden.

**Comment by SanderNijhof** [comment]
> Binnen AutoCAD kan ik namelijk een symbool wel de eigenschap 'Annotatief' meegeven, zonder dat deze automatisch gaat verschalen. Ik kan dan per schaal aangegeven of deze wel of niet aangepast moet worden.

Dit kan binnen Microstation ook. Dat was eigenlijk ook een voorwaarde dat dat in beide pakketten moet kunnen en ook dat -SO niet gekoppeld is aan 'Annotatief', MAG wel, MOET niet.

Als ik je goed begrijp: '-SO' wordt nu gebruikt als 'alleen deze SO-elementen mag je vrij verschalen en alle andere elementen mag je niet verschalen' i.p.v. '(alle elementen mag je verschalen, maar) deze SO-elementen krijgen altijd een vaste verschaling'. 

Dat geeft een grotere beperking en totaal andere functionaliteit. Dus graag zou ik het daar nog een keer over willen hebben. Wat het ook wordt, het moet duidelijker in de Formele Beschrijving komen te staan en kloppen met de juiste elementen die -SO in hun naam krijgen of juist niet. Want nu wordt niet éénduidig met -SO omgegaan.

**Comment by MvanderHulst** [comment]
Helemaal met je eens.
Hierzien/vastgesteld moet worden:
- Wat is/wordt de exacte definitie van - SO
- Teksten in FB hierop nalopen.
- Symbolen in de database hierop nalopen.

Functioneel zijn we het 100% met elkaar eens gelukkig. :-)

**Comment by SanderNijhof** [comment]
Dan doe ik toch alvast een voorstel waar iedereen op kan schieten, want ik zie weer een lange discussie in de NLCS-EC tegemoet ;-)

Bijlagen:
[NLCS-OBJECTEN_VOORSTEL 98 SO-Symbolen.xls](https://github.com/nl-digigo/NLCS/files/15203804/NLCS-OBJECTEN_VOORSTEL.98.SO-Symbolen.xls)
[SO overzicht.pdf](https://github.com/nl-digigo/NLCS/files/15203805/SO.overzicht.pdf)

### Over de bijlagen:
- In de pdf bijlage een overzicht ter onderbouwing van mijn voorstel om de objectnamen in de NLCS aan te passen, waarbij het gros van de -SO objecten weer niet -SO objecten worden, zodat er conform de Formele Beschrijving(FB) leesbare tekeningen kunnen worden gemaakt. In de tabellen staan teksten uit de paragrafen in de FB die betrekking hebben op de schaal van objecten. Daarachter heb ik de schaalfactor gezet voor SO-objecten en niet-SO-objecten zoals ik die vertaal uit de betreffende tekst. Teksten die volgens mij hout snijden heb ik groen gemarkeerd, teksten die verwarrend zijn rood gemarkeerd, waarbij de tekst uit paragraaf 5.2.3b de kroon spant. 
Misschien heb ik relevante teksten uit de FB over het hoofd gezien. Dat verneem ik dan graag.
-  In de Excel bijlage een overzicht van alle symbolen in de NLCS 5.0 met in de gele kolom de 98 -SO symbolen die overblijven.

### Het probleem:
Sinds de 1e versie van de NLCS wordt -SO verschillend uitgelegd en toegepast. Bij elke nieuwe NLCS release zijn er aanpassingen gedaan aan zowel de objecten in de database als aan de Formele Beschrijving om ‘-SO’ te verduidelijken. Het resultaat is dat -SO nu een onoplosbare puzzel is geworden en er uit noodzaak verschillende uitleg aan -SO wordt gegeven:
AutoCAD tooling uitleg: 
_-SO = Schaalbaar Object. Dit betekend dat alleen deze objecten verschaald mogen worden. Alle andere objecten zonder -SO mogen NIET verschaald worden._
Hierdoor vervalt de relatie met de plotschaal die de Formele Beschrijving verplicht stelt en krijgen objecten zonder -SO een verplichte schaalfactor 1, waarbij elke ander verschaling van objecten wordt uitgesloten. Er is een nieuw onderscheid ontstaan nl. tussen objecten op ‘ware grootte’ en alle andere objecten in tegenstelling tot het onderscheid dat de Formele Beschrijving maakt.
Microstation tooling uitleg:
_-SO = Schaalbaar Object. Deze objecten krijgen altijd een vaste verschaling gelijk aan de plotschaal. Alle andere objecten mogen vrij verschaald worden._
Op zich klopt dit met de Formele Beschrijving, maar niet met de m.n. in NLCS 5.0 aangepaste naamgeving van de objecten in de database. Daarom heeft de tooling-leverancier alle -SO objecten 200x verkleint om deze -SO objecten met een redelijke grootte in het ontwerp te kunnen plaatsen. Bij schalen kleiner dan 1:200 (bijv. 1:500) worden -SO objecten relatief groot en op schalen groter dan 1:200 (bijv. 1:50) juist relatief klein. Dit kan leiden tot slecht leesbare tekeningen omdat de meeste objecten niet bedoeld zijn om altijd dezelfde grootte op papier te hebben. Daarom heeft de tooling-leverancier kopieën van -SO objecten toegevoegd zonder -SO in de objectnaam om ook andere verschalingen van die objecten mogelijk te maken. 
Hier wordt het onderscheid tussen objecten met vaste grootte op de afdruk en alle andere objecten gevolgd conform de Formele Beschrijving. 

Ik kan dit niet 100% controleren dus mocht bovenstaande over de AutoCAD-tooling en Microstation-tooling niet kloppen of incompleet zijn dan graag verbeteren/aanvullen hoe het wel door de tooling wordt gedaan.

Bij elke NLCS release zijn de naamgevingen van steeds meer objecten aangepast volgens de werkwijze die bij de AutoCAD-tooling wordt gehanteerd. Maar beide oplossingen leveren problemen op doordat de objecten in de database nog steeds niet de juiste benamingen hebben en/of de NLCS-toolings afwijkende werkwijzen hanteren.

### Mijn voorstel:
Oorspronkelijke bedoeling NLCS is eenvoudig:
1.	Alle objecten mogen vrij verschaald worden. 
2.	Alle objecten worden met een schaal in de database opgenomen dusdanig dat bij plaatsing van dat object 1:1 (met een schaalfactor=1) op een afdruk 1:200 dat object goed leesbaar is. Dus zowel objecten op ‘ware grootte’ als figuratieve objecten worden in principe met een schaalfactor 1 geplaatst.
3.	-SO objecten hebben op de afdruk altijd dezelfde grootte. Hiervoor krijgen -SO objecten een schaalfactor die gelijk is aan de afdrukschaal.
De namen van de wel/niet -SO objecten in de database hebben ondanks reparatie pogingen bij geen enkele release goed aangesloten op de Formele Beschrijving, met blijvende verwarring tot gevolg. Daarom het voorstel om de situatie te herstellen en het gros van de objecten weer van een objectnaam zonder -SO te voorzien en slechts de ruime minderheid aan objecten die op papier altijd dezelfde grootte moeten krijgen, -SO te noemen, zodat we het eenvoudig kunnen uitleggen en er conform de Formele Beschrijving goed leesbare tekeningen kunnen worden gemaakt. 
### Concreet:
1.	**Geen** lijntype is -SO: alle linetypes zijn vrij te verschalen
2.	**Geen** arcering is -SO: alle patterns zijn vrij te verschalen
3.	Van **2195** -SO symbolen naar slechts **98** -SO symbolen. Zie gele kolom in het voorstel in de Excel bijlage.

### Wat ‘annotative’ betreft: 
a)	Het ligt voor de hand om alle -SO objecten met eigenschap ‘annotative’ te plaatsen. 
b)	Dat sluit niet uit dat dit met niet -SO objecten niet is toegestaan. 
c)	Ook is het voor -SO objecten niet verplicht om ‘annotative’ te plaatsen. Als -SO objecten zonder de eigenschap ‘annotative’ geplaatst worden moet de tooling handmatig de juiste schaalfactor toepassen. (daarom de toevoeging -SO zodat de tooling deze objecten kan herkennen).
d)	Het ligt voor de hand om objecten die op ‘ware grootte’ getekend zijn nooit met eigenschap ‘annotative’ te mogen plaatsen, maar dit wordt (nog) niet expliciet verboden.

### Is een extra type nodig?
Als er ook een te relateren schaalfactor voor objecten op ‘ware grootte’ nodig is, bijvoorbeeld voor markering-lijnstijlen, dan zou daarvoor een nieuwe lettercombinatie voor bedacht kunnen worden. Als ik het goed heb begrepen geldt dit m.n. voor lijnstijlen en niet voor symbolen en patterns. Ook wordt overwogen om voor markering-strepen gebruik te maken van symbolen ipv lijnen en dan is dit minder aan de orde. 

### Tot slot
Dit lijkt mij een voorstel dat goed uit te voeren is en duidelijk blijft voor iedereen. Maar ik kan e.e.a. verkeerd gezien of begrepen hebben, dus als iemand een beter voorstel heeft, dan graag delen zodat we er bij een NLCS-EC-overleg sneller een klap op kunnen geven. 
In de volgende NLCS-release moet werken met -SO objecten duidelijk en eenduidig zijn binnen zowel AutoCAD als Microstation!

**Comment by MvanderHulst** [comment]
@SanderNijhof vanaf vakantie even een heel kort antwoord. hier kom ik nog even verder op terug.
Maar op basis van het voorstel, snap ik nogsteeds jou logica niet, je schrijft bijvoorbeeld.

Geen lijntype is -SO: alle linetypes zijn vrij te verschalen
Geen arcering is -SO: alle patterns zijn vrij te verschalen

Hier lees is: een lijntype is vrij schaalbaar, dus een schaalbaar object, dus gaan we -SO weghalen.
Dus juist het kenmerk 'schaalbaar object' wil je bij objecten die schaalbaar zijn weghalen.

Even los van van de FB, is het volgens mij nog eenvoudiger te maken dan jou voorstel (en zo is het nu ook in de database opgenomen voor een groot deel):
- SO = Schaalbaar Object
- Een Schaalbaar Object mag je verschalen zoals je zelf wilt, is dus vrij verschaalbaar én kan annotatief geplaatst worden indien gewenst.
- Zonder SO is niet schaalbaar.
- Een Niet Schaalbaar object heeft altijd schaal 1 en is dus een 'ware grootte' symbool.

Een noordpijl wordt (zou altijd) in een layout geplaatst (moeten worden) en heeft altijd schaal 1, dus is een niet-schaalbaar object.
Een kader wordt in een layout op ware groote geplaatst en is dus een niet-schaalbaar object.
Lijntypes mag je elke schaal geven die je wilt en is dus een schaalbaar object (SO). In AutoCAD gaat dit al automatisch, zodoende zijn alle lijntypes SO gemaakt, oftewel, verschaalbaar. 
Alle arceringen met SO zijn vrij verschaalbaar en naar wens aan te passen.
Alle niet SO arceringen zijn niet schaalbaar en dus op 'ware groote'.

Exact bovenstaande logica is nu in de database van de NLCS verwerkt (met uitzondering van de kaders en noordpijlen)

**Comment by SanderNijhof** [comment]
@MvanderHulst Hey Michel! Fijne vakantie! :-)

> Hier lees is: een lijntype is vrij schaalbaar, 

Dat klopt

>dus een schaalbaar object

Klinkt vanuit de tekenaar gezien logisch, maar dit is niet hoe de FB een 'schaalbaar object' beschrijft! Een ongelukkig gekozen term dus.

>Dus juist het kenmerk 'schaalbaar object' wil je bij objecten die schaalbaar zijn weghalen.

Inderdaad, want '_schaalbaar object'_ betekend niet dat het je het object vrij mag verschalen, in tegendeel. Om een object vrij te mogen verschalen MOET volgens de FB het kenmerk '-SO' bij die objecten ontbreken.

Volgens de NLCS teken je in je ontwerpmodel altijd 1:1. Lijnen, symbolen en arceringen plaats je met schaalfactor 1, een afstand van 1 meter = 1 meter in je ontwerpmodel. De tekenaar hoeft zich dus niet bezig te houden met het aanpassen van schalen van objecten, tenzij hij dat zelf nodig vind. Simpel genoeg lijkt me, zowel voor de gebruiker als voor de software.
De NLCS maakt dus (nog) geen onderscheid in figuratieve symbolen en symbolen op 'ware grootte', omdat beide in principe altijd met dezelfde schaalfactor=1 worden geplaatst. Maar je mag daar met een goede reden van afwijken. Als voorbeeld noemt de FB de schaal van lijnen voor kabels en leidingen, waarbij de FB aanbeveelt deze een schaalfactor 50% kleiner te tekenen op drukke 1:500 tekeningen.

De uitzondering zijn elementen die op papier altijd dezelfde grootte hebben. Deze objecten krijgen ALTIJD een schaalfactor die gelijk is aan de plotschaal. Dus plaats je zo’n object in je ontwerp dat je 1:200 afdrukt, dan krijgt dat object een schaalfactor 200, druk je je ontwerp 1:500 af, dan krijgt dat object een schaalfactor 500. Je layout model teken je meestal 1:1 en daar krijgt dat object een schaalfactor 1. Een voorbeeld van zo'n object is de noordpijl. Dit moet door de software geregeld worden. Om ervoor te zorgen dat de software herkent welke objecten ALTIJD een schaalfactor MOETEN krijgen, wordt aan die symboolnamen de lettercombinatie ‘-SO’ toegevoegd (dit is dus in de database de 1e keer gelijk al fout gegaan en nooit meer goed gekomen). **Voor de software zijn dit dus ‘Schaalbare Objecten’**, alle andere objecten zonder ‘-SO’ hoeft de software niet te verschalen, die kunnen zonder schaalfactor, of wel met schaalfactor 1, geplaatst worden. 

Vanuit de gebruiker gezien had ‘SO’ wellicht beter omschreven kunnen worden als ‘Schalende Objecten’ omdat de software ALTIJD de verschaling van die objecten regelt. Zeker nu inmiddels lijnen, arceringen en symbolen annotatief geplaatst kunnen worden. Wellicht een idee voor de FB van 5.1.

**Comment by MvanderHulst** [comment]
@SanderNijhof 
Weer even helemaal los van wat er in de FB staat beschreven en hoe het bedoeld is:

- Als alle -SO objecten vrij verschaald zouden mogen worden naar wens van de gebruiker.
- en alle niet-SO objecten altijd een schaal 1 hebben....
dan ben je er toch? énn geef je de gebruiker toch maximale vrijheid.

-SO kan van annotatief geplaatst worden, maar hoeft niet en zelfs als hij annotatief geplaatst is, kan je met de schaalfactor nogsteeds de algemene grootte regelen.

dat een -SO ALTIJD een schaalfactor moet hebben gelijk aan de plotschaal, vindt ik inderdaad een onwerkbaar uitgangspunt. Dat zou veel vrijer toegepast moeten mogen worden.

**Comment by SanderNijhof** [comment]
@MvanderHulst 

> dan ben je er toch? énn geef je de gebruiker toch maximale vrijheid.

Dat kan inderdaad, werkt, en dat wordt nu ook min of meer afgedwongen door hoe we de naamgeving van objecten hebben aangepast, maar dan is het effect van -SO minimaal om niet te zeggen nodig:
Met ’-SO’ is dan : voor dit object gelden geen bijzonderheden
Zonder ‘-SO’ : Dit object mag je alleen met schaalfactor 1 toepassen.
Beide worden dan in principe met schaalfactor 1 geplaatst. Dus hoe belangrijk is dan de toevoeging -SO nog?

Je beperkt dan de gebruiker in dat symbolen zonder -SO niet als ‘figuratief’ gebruikt mogen worden. 
De controle tooling heeft dan wel een extra mogelijkheid om te controleren dat 'niet -SO objecten' dan altijd een schaalfactor 1 moeten hebben.
De software heeft dan niet meer de mogelijkheid om automatisch een plotschaalfactor toe te passen voor objecten die altijd dezelfde grootte op papier moeten hebben.

In mijn ogen is onderscheid tussen objecten op ware grootte en figuratief niet nodig. De database moet dan in ieder geval opnieuw nauwkeuriger/complexer nagekeken worden op symbolen die verplicht schaalfactor 1 moeten krijgen en -SO dus weggehaald moet worden en welke symbolen alsnog -SO moeten krijgen. Is een noordpijl dan een -SO object of juist niet?
En dan is er nog het verschil in omgang met schalen tussen bijv. AutoCAD en Microstation: Microstation kent lijnstijlen op 'ware grootte' en AutoCAD kent die niet. Beter geen onderscheid maken lijkt me.

Alleen al de logica om van de 4552 objecten juist de ‘normale’ 4327 objecten een toevoeging ‘-SO’ te geven en 225 bijzondere objecten niet, ontgaat mij volledig. Het verbaasd me dat we dat echt gedaan hebben in NLCS 5.0 in strijd met de FB en bovendien nog steeds niet 100% kloppend.

Als we de naamgeving van -SO objecten corrigeren en gaan hanteren zoals het altijd in de Formele Beschrijving heeft gestaan is dat veel eenvoudiger en duidelijker: Géén -SO arceringen en géén -SO lijnstijlen en slechts ca. 100 -SO symbolen. 
Weinig uitzoekwerk en snel aan te passen in zowel de database als de FB en formeel is dat geen wijziging van de NLCS.

**Comment by ElisabethKloren** [comment]
> @SanderNijhof Weer even helemaal los van wat er in de FB staat beschreven en hoe het bedoeld is:
> 
> * Als alle -SO objecten vrij verschaald zouden mogen worden naar wens van de gebruiker.
> * en alle niet-SO objecten altijd een schaal 1 hebben....
>   dan ben je er toch? énn geef je de gebruiker toch maximale vrijheid.
> 
> -SO kan van annotatief geplaatst worden, maar hoeft niet en zelfs als hij annotatief geplaatst is, kan je met de schaalfactor nogsteeds de algemene grootte regelen.
> 
> dat een -SO ALTIJD een schaalfactor moet hebben gelijk aan de plotschaal, vindt ik inderdaad een onwerkbaar uitgangspunt. Dat zou veel vrijer toegepast moeten mogen worden.

Op basis van dit uitgangspunt is het voorstel om de documentatie aan te scherpen:
nummering artikelen conform https://github.com/nl-digigo/NLCS/blob/main/docs/archive/Formele_beschrijving_NLCS_versie_5_0_V1_0.pdf

Te herziene artikelen:
3.5.3.b.OPT.SO >
Een Schaalbaar Object is een symbool (block) dat verschaald mag worden in je tekening. Voorbeeld: inspectieput-symbolen. Zijn een symbool dat er een inspectieput staat, zonder dat je die op de ware grootte tekent. Afhankelijk van de schaal, complexiteit en het doel van je tekening kun je deze symbolen groter of kleiner weergeven. Technisch gezien betekent dit dat de gebruiker of een schaalfactor toekent aan het symbool in de tekening en/of dat het symbool annotatief geplaatst kan worden, dan wordt het symbool groter als je meer uitzoomt in de tekening.


3.5.6 Symbolen   > [dit artikel](https://nl-digigo.github.io/NLCS/requirementscadmodels/#symbolen)
a. Er wordt onderscheid gemaakt in 'objectsymbolen', 'schaalbare symbolen' en 'verwijzingssymbolen'.
b. 'Objectsymbolen' zijn symbolen welke op ware grootte zijn getekend. De afmetingen en vorm van het symbool zijn representatief voor de werkelijkheid.
'Schaalbare Objecten' zijn een vereenvoudigde weergave van objecten. zij geven de locaties van de betreffende objecten in aan, maar niet de daadwerkelijke afmetingen of vorm van het object.
c. Bij NLCS hoort een uitgebreide set van symbolen die worden aangeboden als symbolenbibliotheken. Een symbolenbibliotheek kan één of meer symbolen bevatten.
d. Gebruikers en/of CAD-leveranciers kunnen voor objecten waarvoor in NLCS geen gewenste symbolen zijn opgenomen, eigen symbolenbibliotheken of bibliotheken van derden toevoegen, mits die bibliotheken zijn opgebouwd volgens de NLCS-systematiek (zie paragraaf 5.2.3).
e. Symbolen voor de NLCS zijn primair ontwikkeld voor een leesbare presentatie bij schaal 1:200.
f. ongewijzigd
g. ongewijzigd
h. ongewijzigd
i. ongewijzigd.

4.7.d
De Noordpijl en ruitkruisjes in het bovenstaande voorbeeld zijn ‘schaalonafhankelijke symbolen’. Deze
symbolen hebben op een afgedrukte tekening altijd dezelfde afmetingen, onafhankelijk van de voor
de tekening gehanteerde schaal.

Artikel 4.7.d volledig laten vervallen.
Afhankelijk waar de verschaling van het kader plaatsvindt, kunnen dit dus wel degelijk 'schaalbare Objecten' zijn.
Binnen AutoCAD is dit NOOIT het geval, binnen Microstation (TPG) wel degelijk.

5.2.2.a.OPT.SO
Een Schaalbaar Object is een object dat een verschaling krijgt afhankelijk van de te plotten schaal. Voor arceringen kan dit wordt gedaan door middel van 'Annotative' of het toekennen van een schaalfactor.
'Schaalbare Objecten' zijn in de naam van de arcering te herkennen aan de toevoeging '-SO' als laatste onderdeel van de arceringnaam.
Bij gebruik van een NLCS applicatie zal de SO toevoeging worden herkend en automatisch de verschaling worden toegepast.

5.2.3.b.SYMBOOLNAAM
SYMBOOLNAAM de naam is van het symbool zelf (doorgaans gelijk aan de naam van het betreffende OBJECT of SUBOBJECT). De opbouw van de symboolnaam is vrij.
Er worden underscores (“_”)toegepast om het symbool nader te specificeren (voorbeeld: TROTTOIRBAND_130 150X250);

5.2.3.b.OPT.SO
Een Schaalbaar Object is een object dat een verschaling krijgt afhankelijk van de te plotten schaal. Voor symbolen kan dit wordt gedaan door middel van 'Annotative' of het toekennen van een schaalfactor.
'Schaalbare Objecten' zijn in de naam van het symbool te herkennen aan de toevoeging '-SO' als laatste onderdeel van de symboolnaam.
Bij gebruik van een NLCS applicatie zal de SO toevoeging worden herkend en automatisch de verschaling worden toegepast.

5.2.3.b
laatstebullet, geheel vervallen?

5.2.3.f
Geheel vervallen? staat al in 5.2.3.b.OPT

5.2.3.g
Een symbool wordt geplaatst op een laagnaam, waarbij het symboolnaam minimaalovereenkomstig is met het OBJECT en indien gewenst op een daaraan gerelateerd SUBOBJECT volgens het harmonicamodel. (5.1.a)
Bijvoorbeeld: Symbool N-SVW-VERKEERSTEKEN_BORD_E01-SO, mag geplaatst worden op het OBJECT N-WE-VW-VERKEERSTEKEN_BORD_E01-S, maar ook op N-WE-VW-VERKEERSTEKEN_BORD-S
Bijvoorbeeld: Symbool N-SIE-WEG_ABRI-SO, mag geplaatst worden op het OBJECT N-WE-IE-WEGMEUBILAIR-S, maar ook op N-WE-IE-WEGMEUBILAIR_ABRI-S

5.2.3.h.h.1
o aanpassen naar 0

5.2.3.j
Geheel laten vervallen. Staat allemaal al in de toelichtingen.
We zijn een standaard aan het schrijven, geen AutoCAD handleiding.

5.2.4.bullet4
ALLE LINETYPES ZIJN 'SCHAALBAAR' DOOR STANDAARD AUTOCAD. EN IS GEEN UITZONDERING MEER. OPT KAN M.I. GEHEEL KOMEN TE VERVALLEN. TECHNISCH NIET MOGELIJK IN AUTOCAD OM NIET-SO LINETYPES TE MAKEN.

**Comment by SanderNijhof** [comment]
@ElisabethKloren 
Ik voel me onbegrepen en genegeerd.
Nogmaals tegenvoorstel, fouten in de NLCS-objectnamen en FB herstellen:

1. Alle objecten mogen vrij verschaald worden
2. Symbolen die een verplichte verschaling moeten hebben krijgen de toevoeging -SO
3. -SO komt alleen voor bij symbolen

Hiervoor is nodig: Corrigeren van namen van lijnstijlen, patterns en symbolen. Eenvoudige en duidelijk uit te leggen aanpassingen in de FB.

Dit wordt door alle CAD-pakketten ondersteund en houdt het eenvoudig voor gebruiker en softwareleverancier. Bovendien is dit de werkwijze vanaf de invoering van de NLCS. De wijziging in de FB om SO te vertalen naar ‘Schaalbare Objecten’ is een beslissing geweest met enorme consequenties, verwarring en fouten die tot op de dag vandaag nog steeds groeien. Die vertaling dus bij voorkeur uit de FB halen. ‘-SO’ is alleen van belang voor de softwareleverancier, niet voor de gebruiker!

**Comment by SanderNijhof** [comment]
> Klopt mijn interpretatie dat verschillende software-leveranciers dit verschillend geïnterpreteerd hebben? En dat het daarom controversieel is?

Niet alleen de leveranciers ook de NLCS experts, incl. ik zelf, maken er een potje van. Al vanaf de 1e versie van de NLCS. 
Dus dit verdient zeker de aandacht.

**Comment by ElisabethKloren** [comment]
Het -SO voorstel voor versie 5.1 is uitgewerkt in issue #445 deze discussie is daarmee achterhaald en wordt  afgesloten
