### ISSUE TITLE
Ontbrekend lijntype RO-BESCHERMDSTADSGEZICHT-SO

### ISSUE THREAD

**Issue by gerritversteegh** [nl-digigo/NLCS#381]
In de SQL tabel van de lijntypes stond onder hoofdgroep RO een lijntype genaamd 'RO-BESCHERMDSTADSGEZICHT-SO', in de SQL tabel van de hoofdgroepen ontbreekt RO echter.  Daarom is op dit moment het lijntype **niet** opgenomen in de NLCS. 

Bij de arceringen bestaat een gelijknamige arcering onder de Abibliotheek OG, en bij de NLCS-Objecten bestaat er een object genaamd 'BESCHERMD STADS EN DORPSGEZICHT' onder de hoofdgroep OG. Het zou dus kunnen dat de hoofdgroep van het lijntype niet klopt. 

@ElisabethKloren Kan jij nalopen wat hiermee de bedoeling is? Mocht het lijntype onder OG horen kan ik deze handmatig toevoegen.

**Comment by MvanderHulst** [comment]
@ElisabethKloren hoofdgroep RO bestaat niet.
Deze objecten zijn opgenomen in de hoofdgroep OG.

*RO-BESCHERMDSTADSGEZICHT-SO,619
A,4.75,-2,[SGZ,NLCS.SHX,s=1],-2

moet dan ook aangepast worden naar:

*OG-BESCHERMDSTADSGEZICHT-SO,619
A,4.75,-2,[SGZ,NLCS.SHX,s=1],-2

**Comment by ElisabethKloren** [comment]
Ik heb de lijntypes toegevoegd in de database

**Comment by ElisabethKloren** [comment]
overigens is dit gereviewed in juni 2024 zonder commentaar, vandaar label vastgesteld in Expertcommissie
