### ISSUE TITLE
Referentie naar ontbrekend lijntype met ID 685

### ISSUE THREAD

**Issue by gerritversteegh** [nl-digigo/NLCS#382]
Het NLCS-Object NIETBAGGERVAK uit hoofdgroep GW refereert naar een lijntype met ID 685, maar dit ID ontbreekt in de lijst met lijntypes. Op dit moment is daarom het informatieveld **leeggelaten** (B linetype). Dit zou echter wel een probleem kunnen opleveren omdat alle andere bijbehorende informatievelden wel ingevuld zijn (B linecolor, B lineweight, ... ).

**Comment by MvanderHulst** [comment]
Zowel in 4.2 als 5.0 vindt ik deze 'continuous' in mijn tooling terug.
Wat mij betreft prima.
