### ISSUE TITLE
Referentie naar ontbrekend symbool SVH-OVERIG

### ISSUE THREAD

**Issue by gerritversteegh** [nl-digigo/NLCS#383]
Het NLCS-object 'VERHARDING_OVERIG' uit hoofdgroep VH refereert naar een symbool genaamd 'SVH-OVERIG', maar dit symbool ontbreekt. Op dit moment is er daarom geen relatie gelegd met een symbool.

**Comment by MvanderHulst** [comment]
Dit zijn de OVERIGE symbolen volgens de bibliotheken:
![image](https://github.com/nl-digigo/NLCS/assets/144665595/36930728-739b-42ff-862a-e104874bf265)
