### ISSUE TITLE
Gebruik standaardcoördinaten blocks?

### ISSUE THREAD

**Issue by MvanderHulst** [nl-digigo/NLCS#384]
Het volgende artikel is mij opgevallen:
4.5.11 Coördinaten
a. Coördinaten moeten worden aangegeven in de relevante punten. Hiervoor kunnen de symbolen uit de
bibliotheek SAL gebruikt worden.

![image](https://github.com/nl-digigo/NLCS/assets/144665595/ecfc074a-5c72-49d7-952c-c0d1f25318d2)

Dit zijn m.i. de meest nutteloze blocks die er zijn.
Worden deze door iemand gebruikt? 
Meestal wordt dit toch gewoon met een leader gedaan?

Zou van mij mogen vervallen.

**Comment by MvanderHulst** [comment]
@ElisabethKloren , graag het artikel nog even tekstueel aanpassen.
Symbolen zijn komen te vervallen

**Comment by ElisabethKloren** [comment]
ik heb het hele artikel laten vervallen

**Comment by ElisabethDeVries** [comment]
[[Release note]] Alle symbolen voor coördinaatpunten in de symbolenbibliotheek ALgemeen zijn komen te vervallen. Gebruikers kunnen coördinaatpunten met een leader toevoegen in een tekening.

**Comment by ElisabethDeVries** [comment]
reopen voor acceptatie 5.2
