### ISSUE TITLE
GRONDWERKLIJNEN, onvolledig en kleuren

### ISSUE THREAD

**Issue by MvanderHulst** [nl-digigo/NLCS#387]
GRONDWERKLIJN is een groene lijn, visueel zeer onduidelijk i.r.t. groenobjecten.
Graag de volgende aanpassingen doorvoeren:
GRONDWERKLIJN, kleur 43
GRONDWERKLIJN_TEEN, kleur 33
GRONDWERKLIJN_KRUIN, kleur 53
GRONDWERKLIJN_KNIKLIJN, kleur 63

Aanvulling:
GRONDWERKLIJN_ONDERWATER
Hidden lijntype, kleur rood
Om duidelijk verschil tussen nat en droog grondwerk aan te kunnen geven.

tot slot:
Termen onderling nalopen:
Nu wordt gebruikt;
TEEN
KRUIN
KNIKLIJN

maak hiervan;
GRONDWERK
GRONDWERK_TEENLIJN
GRONDWERK_KRUINLIJN
GRONDWERK_KNIKLIJN

**Comment by MvanderHulst** [comment]
Zie ook #71

**Comment by ElisabethDeVries** [comment]
Voor aanpassing van de kleuren zie issue #275 

naamgeving van objecten: komt in NLCS 6.0
