### ISSUE TITLE
SWA symbolen in database

### ISSUE THREAD

**Issue by MvanderHulst** [nl-digigo/NLCS#388]
In de SRI biebliotheek van 5.0 kom ik nog de volgende SWA symbolen tegen, welke kunnen komen te vervallen.
V-SRI-PUT_SWA_KUNSTSTOF-SO
V-SRI-PUT_SWA-SO
SRI-PUT_SWA_KUNSTSTOF-SO
SRI-PUT_SWA-SO
B-SRI-PUT_SWA_KUNSTSTOF-SO
B-SRI-PUT_SWA-SO

**Comment by ElisabethDeVries** [comment]
[[Release note]] De SWA-symbolen die per abuis nog in de bibliotheek opgenomen waren, komen te vervallen door de keuze om naamgeving van rioleringsstelsels overeen te laten komen met het Gemeentelijk Woordenboek Stedelijk Water (GWSW).
