### ISSUE TITLE
#1420	In de praktijk wordt de materiaalscheidingslijn op situatietekeningen wel eens aangezien voor een 1 - 1 markeringsstreep. 

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#39]
#1420	In de praktijk wordt de materiaalscheidingslijn op situatietekeningen wel eens aangezien voor een 1 - 1 markeringsstreep. Bijvoorbeeld als bij de verharding van een rijbaan verschillende materialen of bestratingsverbanden worden gebruikt. Kan het lijntype wat aangepast worden zodat deze verwarring minder snel kan optreden?

**Comment by ElisabethKloren** [comment]
Reactie Expertcommissie
probleem wordt niet zo zeer gezien, Niels neemt contact op voor voorbeelden, lijnstyle voor de vervallen materiaalgrens betreft ook een doorgetrokken lijn met schrap, hierdoor lijkt dit ook op een object wat verwijderd wordt, terwijl een materiaalgrens uitaard geen object is was verwijderd wordt maar verdwijnt door de objecten ernaast te verwijderen misschien logischer om ook te verwijderen zonder streep

**Comment by ElisabethKloren** [comment]
Actie
Extra info opvragen

**Comment by SanderNijhof** [comment]
Als deze lijnstijl de grootte heeft van een 1-1 markering streep en die lijnstijl -SO geplaatst wordt, vind ik de schaal van de lijnstijl wel erg groot. Bedenk op een trottoir van 1,5m dan is de materiaalgrens amper herkenbaar. Als dit inderdaad 1-1 is dan lijkt me een andere lijnstijl voorstellen een goed idee.

**Comment by MvanderHulst** [comment]
Handhaven zoals het nu is.
Markeringen krijgen ook een dikte mee, als dit als verwarrend wordt gezien kan je geen tekening lezen en dan moet je dat ook vooral niet doen. :-)

**Comment by SanderNijhof** [comment]
Dit moet natuurlijk geen -SO lijnstijl zijn. Als de materiaalscheidingslijn een -SO lijnstijl is van 1-1 meter, dan is die op een trottoir met breedte 1-2m een enkele streep, 2 deelstrepen of zelfs onzichtbaar. Dan nog is verwarren met een 1-1 streep wel knap ;-)

**Comment by MvanderHulst** [comment]
Als ik mij niet vergis zijn alle lintypes standaard -SO gemaakt, simpelweg omdat AutoCAD geen andere optie heeft.
AutoCAD behandeld een linetype altijd als een -SO object, op iedere schaal wordt de weergave aangepast en dit kan helaas niet 'vast' gezet worden...

**Comment by SanderNijhof** [comment]
Dus in AutoCAD hebben lijnstijlen 'op papier' altijd dezelfde grootte/verhouding ongeacht de schaal waarop het ontwerp wordt geplot? Dus een 1-1 markeringstreep kan niet als lijntype in AutoCAD maar moet je altijd 1:1 tekenen als losse elementen?

**Comment by MvanderHulst** [comment]
Antwoord 1 is: ja dat klopt.
Antwoord 2:
Als ik voor markering bijvoorbeeld een 1:200 en 1:500 plot wilt maken, dan teken ik de lijnen 2x in 2 verschillende lagen, met de aanvulling 'SCHAAL'. Door de linetypescale van het de lijn in de properties aan te passen, ik de dan eindpresentatie per schaal regelen.
Alternatief is inderdaad om de lijnen als losse objecten in te tekenen, dan gaat het ook goed.
In de praktijk presenteer ik een tekening het liefste alleen 1:200, dus hoef ik de lijn maar 1x te manipuleren.
Standaard is de 1-1 streep dan een factor 5 te groot en krijgt deze de linetypescale van 0.2 mee, op lijn/entiteit niveau in de properties.

**Comment by MvanderHulst** [comment]
Algemene lijntype issue, oplossing in issue #373 opgenomen.

Ondertussen ben ik een hoop NLCS projecten verder:
Het lijntype 'materiaalgrens' is te grof voor zijn toepassing.
Minimaal een factor 0.5 zou gewenst zijn voor een juiste presentatie.

Voorstel lijntype:
*VH-MATERIAALGRENS-SO,
A,1,-1


Vraag aan het EC:
Een materiaalgrens is een 'stippellijn'.
Overgang naar een ander verband is 'letterlijk gezien' geen materiaalgrens, maar een 'verbandgrens'.
Deze wordt nu vaak getekend met 'openverharding' om het algemeen te houden.
Hiervoor zou ook een oplossing moeten komen, zelf hebben wij 'verbandgrens' als object geintroduceerd. Deze is dan echter weer doorgetrokken.
Een 'molgoot' is eigenlijk ook een materiaalgrens, maar die is weer continuous.
Al met al, is het allemaal hetzelfde doel maar niet erg consquent.

Voorstel:
Materiaalgrens en molgoot (alle betreatte 'goten') gelijk aan elkaar maken.
Verbandgrens toevoegen met dezelfde presentatie

Mijn voorkeur, is om al deze 'grenzen' gestippeld te maken, zoals de materiaalgrens nu is, maar dan met het aangepaste lijntype. dit maar de tekening vele malen duidelijker, ook wanneer er goten langs de doorgetrokken banden lopen.

**Comment by ElisabethDeVries** [comment]
[[Release note]] In hoofdgroep VH (VerHardingen) heeft de MATERIAALGRENS een eigen lijntype gekregen zodat deze beter uitkomt op een tekening waar goten langs doorgetrokken banden lopen.
