### ISSUE TITLE
lagen in symbolen, maatvoeringen, multileaders

### ISSUE THREAD

**Issue by SanderNijhof** [nl-digigo/NLCS#390]
Ik lees bij https://nl-digigo.github.io/NLCS/requirementscadmodels/#hoogtematen 

"Peilmaten als tekst komen op een laag met element T, als het 'block' wordt toegepast op een laag met element S."

Dit is niet de bedoeling toch? Wat is het voordeel daarvan? 
Teksten die onderdeel zijn van een element komen (in principe) op de laag van dat element. 
Is dit ook het probleem bij teksten in maatvoeringen?
Een maatvoering is 1 element en alles in die maatvoering komt op laag -M. Een maatvoering mag je ook niet 'exploderen', dus het blijft 1 element. Dus ook geen -T?? lagen in maatvoeringen.

Symbolen zijn (in principe) opgebouwd in layer '0' of 'default' dus komen ook alle elementen in dat symbool op laag -S. 
Hoe ik de tekst interpreteer mag in SPECIALE GEVALLEN hier van afgeweken worden: FB 5.2.3 e "_Symbolen worden in de NLCS in principe altijd getekend by layer, een beperkt aantal symbolen wordt getekend by object (zie ook punt h.3)._ " 
Als voorbeelden worden genoemd symbolen met details of doorsneden.

**Comment by ElisabethKloren** [comment]
ik heb de tekst hier weggehaald, omdat er op 1 plek moet woprden beschreven hoe met teksten wordt omgegaan, niet bij elk soort tekst. Kunst van het weglaten ;-)
