### ISSUE TITLE
442 arceringen in sql, 5 vervallen, maar 435 in query-output van publicatie. Waar zijn de laatste 2?

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#394]
@gerritversteegh   uit de query van arceringen krijg ik er 435; er zijn er 442 in de sql (hoogste id) waarvan 5 vervallen, mis ik er dan 2 of missen er twee id-nummers?

**Comment by gerritversteegh** [comment]
@ElisabethKloren Er blijken inderdaad 2 IDs te ontbreken in de SQL database; namelijk de IDs 275 en 276. Deze zijn niet gedefinieerd en dus is de publicatie wel compleet. Ook de import is compleet, omdat de vervallen IDs wel zijn geimporteerd (zie screenshot). 
![VervallenArceringenNLCS](https://github.com/nl-digigo/NLCS/assets/157105462/171815e6-d5d7-4901-8714-59a278f2bcf1)

**Comment by ElisabethKloren** [comment]
Topper, dank je wel!
