### ISSUE TITLE
Query hoofdgroep VW, niet alle statussen hebben lijnkleuren enzovoorts

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#396]
ik doe de hoofdgroepen query met VW, daar komen alleen van bestaand de lijntypes, kleuren enzovoorts uitrollen, de andere statussen blijven leeg.
[query hoofdgroep VW.csv](https://github.com/nl-digigo/NLCS/files/15040876/query.hoofdgroep.VW.csv)

Ze zitten wel in de beheeromgeving

Is er iets mis met de query, of is dit niet meegepubliceerd wegens de ENORME dataset?

**Comment by gerritversteegh** [comment]
De informatie bevindt zich wel goed in de publicatie (voor zover ik dat met een steekproef nu zie). Als ik de query uitvoer krijg ik wel de informatie over de andere statussen mee (zie bijlage). Zou het kunnen dat er per ongeluk iets aan de query is veranderd? Aangezien de publicatie en de query vrij zwaar zijn, zou het ook kunnen dat het af en toe even goed is om de pagina te verversen/een nieuwe browser te openen om het werkgeheugen te resetten. Dit was namelijk voor mij de eerste query die ik nu uitvoer en ik vermoed dat alle informatie erin staat.

[Uploading ObjectsVW.csv…]()

**Comment by gerritversteegh** [comment]
Hier lijkt inderdaad iets mis te gaan. De informatie staat wel in de publicatie (zie 
[queryBLINDENGELEIDEROUTE_testQuery.xlsx](https://github.com/nl-digigo/NLCS/files/15041766/queryBLINDENGELEIDEROUTE_testQuery.xlsx)), maar bij de 'echte' query ontbreekt het inderdaad (zie 
[queryBLINDENGELEIDEROUTE_originalQuery.xlsx](https://github.com/nl-digigo/NLCS/files/15041772/queryBLINDENGELEIDEROUTE_originalQuery.xlsx)). Ik ga er naar kijken wat hier mis gaat

**Comment by gerritversteegh** [comment]
Er zat een fout in de query. Dit was niet specifiek het geval voor hoofdgroep VW, maar kan impact hebben op alle hoofdgroepen. Ik heb de fout verholpen en de [query opnieuw gepusht](https://github.com/nl-digigo/NLCS/blob/main/code/NLCS_Query_Objects.rq). Mocht je de query ook al voor andere hoofdgroepen hebben gebruikt, gelieve dit dan even opnieuw doen met de nieuwe query
