### ISSUE TITLE
Verkorte query maken voor objecten per hoofdgroep, zonder URI's en zonder relaties naar arceringen en symbolen

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#399]
Deze query is bedoeld om voor de experts de objectentabellen te kunnen genereren die voor menselijke lezers te interpreteren zijn.

**Comment by ElisabethKloren** [comment]
@gerritversteegh ik ben niet zo goed in sparql, kan jij een verkorte query maken?

**Comment by gerritversteegh** [comment]
@ElisabethKloren Wil je dat de query verder intact blijft? Dus alleen de URIs, en verwijzingen naar symbolen/arceringen eruit?

**Comment by gerritversteegh** [comment]
[query ](https://github.com/nl-digigo/NLCS/blob/main/code/NLCS_Query_Objects_Verkort.rq) geupdated.

**Comment by ElisabethKloren** [comment]
@gerritversteegh nu krijg ik weer geen lijnkleuren enzovoorts van andere statussen dan b

**Comment by gerritversteegh** [comment]
@ElisabethKloren opgelost!
