### ISSUE TITLE
Lijnweight/lijnkleur met ID -1 niet geïmporteerd?

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#400]
@gerritversteegh waarom is lijnweight met ID -1 niet geimporteerd?

INSERT INTO `lijnweights` VALUES('-1','0.00','','0.00','0.00');

en idem voor lijnkleuren
INSERT INTO `lijnkleuren` VALUES('-1','','-1','','','0','0','0','');

**Comment by gerritversteegh** [comment]
Als ik het me goed herinner van een gesprek vorig jaar met Niels mbt de NLCS dataset, wordt in de lijst met NLCS objecten een waarde van -1 ingevuld bij de lijnkleuren en lijntypes en een 0 bij lijnweights als er **geen** waarde is bij deze status. Vanwege de mogelijkheden van Linked Data hebben we er toentertijd voor gekozen om deze informatie niet over te nemen, maar om deze relaties simpelweg niet aan te maken. Het leek me hierdoor ook overbodig om deze 'kale' lijntypes/lijnkleuren/lijnweights op te nemen in de NLCS, maar voor zowel de relaties als de ontbrekende concepten geldt dat dit natuurlijk alsnog toegevoegd kan worden. Laat het aub weten als dit gewenst is.

De volgende concepten zijn hierdoor dus genegeerd:
- Lijntype IDs -2 en -1
- Lijnkleur ID -1
- Lijnweight ID -1

**Comment by ElisabethKloren** [comment]
bedankt voor de uitleg, ik neem het op in de documentatie over de overstap naar linked data

**Comment by ElisabethKloren** [comment]
opgenomen als uitleg bij release 5.01 in dit document: https://nl-digigo.github.io/NLCS/functionalspecification/#releases
