### ISSUE TITLE
laag OPENVERHARDING_STRAATBAKSTEEN-OP DE KOP

### ISSUE THREAD

**Issue by SanderNijhof** [nl-digigo/NLCS#401]
Is deze laag wel terecht aanwezig ins de NLCS?
Straatbakstenen hebben geen boven of onderkant. Betonstraatstenen daarentegen wel, maar daarvan ontbreekt de 'op de kop' NLCS-laag.
'OP DE KOP' is een bewerking maar ook een 'toestand'.

**Comment by MvanderHulst** [comment]
Ik heb dit intern nog even voorgelegd.
De uitleg is dat het regelmatig voorkomt dat gebruikte stenen 'met de oude kant' naar beneden worden aangebracht en dus op de kop worden aangelegd t.o.v. de oude situatie.
Zodoende beschikbaar gesteld voor BSS en SBS.

De verplaatsing van bewerking naar subobject even gelaten voor wat het is, met de wetenschap dat vanuit netbeheer TOESTAND/BEWERKING beschikbaar komt.

**Comment by SanderNijhof** [comment]
> De uitleg is dat het regelmatig voorkomt dat gebruikte stenen 'met de oude kant' naar beneden worden aangebracht en dus op de kop worden aangelegd t.o.v. de oude situatie.

Punt was dat dit bij SBS wel in de NLCS is opgenomen en bij BSS niet, dus als dit bij beide wordt opgenomen is dat altijd goed :-)
Op het moment dat je BSS op de kop gaat aanbrengen is dat wel een bewerking/wijze van uitvoering.

**Comment by ElisabethDeVries** [comment]
[[Release note]] De laagnaam OPENVERHARDING_BETONSTRAATSTEEN-OP DE KOP is toegevoegd.
