### ISSUE TITLE
lagen voor REPARATIES, HERSTRATEN, KNIPLIJN, VERKANTING

### ISSUE THREAD

**Issue by SanderNijhof** [nl-digigo/NLCS#402]
In de hoofdgroep VH:Zijn REPARATIES, HERSTRATEN, KNIPLIJN, VERKANTING, LEVENSDUURVERLENGENDE MAATREGEL, MATERIAALGRENS geldige objecten?

Moet dit niet bijv. GESLOTENVERHARDING_REPARATIES of OPENVERHARDING_HERSTRATEN zijn?
Is HERSTRATEN niet een bewerking?
Is het onderscheid tussen OPENVERHARDING en GESLOTENVERHARDING noodzakelijk? Het ligt toch voor de hand dat asfalt gesloten is en klinkers open?
Waarom is het wel OPENVERHARDING_BETONELEMENT maar BEDRIJFSVLOERPLAAT_BETON ipv OPENVERHARDING_BEDRIJFSVLOERPLAAT_BETON?

en de lagen SPECIAAL, SPECIAAL_SPORT. Dat is geen GESLOTEN- of OPEN-VERHARDING?

**Comment by MvanderHulst** [comment]
@SanderNijhof 
Dit zijn inderdaad objecten waar ik ook wat moeite mee heb.
REPARATIES zou enkel op 'Gesloten verharding' van toepassing zijn'.
Voor openverharding ga je dan 'HERSTRATEN' danwel opbreken en aanbrengen (vervangen).

REPARATIES en HERSTRATEN zijn vaak contouren die je aanvullend aangeeft, maar wat geen daadwerkelijk object is in de tekening. Zie ook onderstaand (zeer lelijke) voorbeeld:
![image](https://github.com/nl-digigo/NLCS/assets/144665595/5bc41d20-87dc-4652-8149-e6a54b279ca3)
Zoals jou voorstel, zou ik dat inderdaad logischer vinden.
-GESLOTENVERHARDING_REPARATIES
- OPENVERHARDING_HERSTRATEN
Ik zou dit weer niet als een bewerking opnemen, omdat het vaak geen 'bestaande lijnen' in de tekening zijn.
Valt eerder in de categorie 'hulplijn'..

KNIPLIJN zou m.i. mogen vervallen. Dit is een resultante van de uitvoering, niet van een ontwerp.
Relevant om dit te borgen? zie ook issue #39 , waarin een voorstel voor 'verbandgrens' is opgenomen.

MATERIAALGRENS vindt ik wel fijn, om de grens tussen 2 materialen aan te kunnen geven.
Wel is deze vreemd, in combinatie met de 'molgoot' e.d. zie ook issue #39 
![image](https://github.com/nl-digigo/NLCS/assets/144665595/69377baf-cad3-4fef-9e79-594d00e1222b)

VERKANTING mag van mij ook vervallen. Mij onduidelijk wat hier het doel van is.
Wel is dit iets 'algemeens' wat bij behoud een eigen positie verdiend.

LEVENSDUURVERLENGENDE MAATREGEL mag van mij vervallen. Je doet 'iets' om de levensduur te verlengen. Datgene verklaar je als werkzaamheid danwel bewerking. Dit is een schot hagel.

Geslotenverharding = asfalt of beton, dus het OBJECT GESLOTENVERHARDING zou ik wel behouden.
openverharding = betonstraatstenen, straatbakstenen, betontegels e.d. dus ook deze eerste schifting vindt ik wel prettig.
Je zou dit eventueel ook allemaal als OBJECTEN kunnen opnemen, maar dan wordt de eerste OBJECTEN structuur mogelijk weer wat lang?

BEDRIJFSVLOERPLAAT zou inderdaad onderdeel van 'OPENVERHARDING' moeten zijn.

DREMPEL is hierbij ook een vreemde. DREMPEL is een functie, zou onder de materiaal moeten staan.
idem voor GOOT en ROOSTER, VERKEERSTEGEL.

SPECIAAL_SPORT zijn ook allemaal 'functies' is worden samengesteld uit materiaal.
Mag m.i. vervallen.

**Comment by MvanderHulst** [comment]
@ElisabethKloren zie bovenstaande toelichting, wat mij betreft kan deze mee met de 5.1 minor fixes, gezien het raakvlak met de andere issues welke ook verwerkt gaan worden.

**Comment by ElisabethKloren** [comment]
Prima, maak jij een concreet voorstel voor te vervallen en nieuwe laagnamen, en eventueel aan te passen symbolen?

**Comment by ElisabethKloren** [comment]
Reviewperiode Expertcommissie juni 2024 is gepasseerd, verwerking volgens voorstel
