### ISSUE TITLE
Verschil naamgeving symbool en arcering RIET / RIETLAND

### ISSUE THREAD

**Issue by MvanderHulst** [nl-digigo/NLCS#405]
Symbolen riet:
SGR-RIETLAND-SO
SGR-RIETLAND_KL-SO

Arcering riet:
AGR-RIET_01-SO
AGR-RIET_02-SO
AGR-RIET_03-SO

Dit is de enige van de GR bibliotheek waar deze mismatch inzit.
Op basis van de presentatie en de noodzaak, voorstel om AGR-RIET_02 en AGR-RIET_03 te laten vervallen.
AGR-RIET_01-SO te hernoemen naar AGR-RIETLAND-SO

bij aanpassing ook de inhoud van symbool SGR-RIETLAND-SO herzien!

**Comment by ElisabethDeVries** [comment]
[[Release note]] De varianten in arceringen AGR-RIET vervallen er hoeft visueel geen onderscheid gemaakt te worden in soorten riet.

**Comment by MvanderHulst** [comment]
@ElisabethDeVries is de inhoud van het symbool ook gewijzigd naar een bestaande hatch, net als de beplantingen issue?
