### ISSUE TITLE
formaten bij verhardingcellen

### ISSUE THREAD

**Issue by SanderNijhof** [nl-digigo/NLCS#406]
Ik weet niet of dit ook in de originele autocadblock zo voorkomt maar in de Microstation-set van NLCS 5.0:

Bij blocks met lingeformaat worden zowel de letters ‘LG’ als ‘LF’ gebruikt. Niet consequent. (‘LF’ vind ik logischer)

Bij blocks SVH-TEGEL_150X300 en SVH-TEGEL_300X150 en de V-varianten staan als afmeting ‘30x20’, ‘30x15’ en ‘15x30’ genoemd maar niet altijd overeenkomstig met de blocknaam. Fout/Niet consequent.

**Comment by MvanderHulst** [comment]
@SanderNijhof 
Dit ben ik inderdaad ook tegen gekomen.
In issue #56 heb ik hiervoor de oplossing klaarstaan.

**Comment by ElisabethKloren** [comment]
wegens dubbel sluit ik dan deze issue
