### ISSUE TITLE
Lijntypes hagen kloppen niet

### ISSUE THREAD

**Issue by MvanderHulst** [nl-digigo/NLCS#415]
Inconsequente toepassing van HAGEN i.r.t. lijntypes
Naamgeving niet consequent.
Ook in de Database kloppen de toegewezen lijntypes niet.

*V-GR-HAAG-SO,744
A,3,[VERWIJDEREN2,NLCS.shx,s=1],3,[HAAG1,NLCS.shx,s=0.125],-2

*GR-HAAG1-SO,80
A,6,[HAAG1,NLCS.shx,s=0.125],-2

*GR-HAAG2-SO,81
A,6,[HAAG2,NLCS.shx,s=0.5],-2

*GR-HAAG3-SO,82
A,6,[HAAG3,NLCS.shx,s=0.1815],-2

*V-GR-HAAG_VARIANT01-SO,745
A,3,[VERWIJDEREN2,NLCS.shx,s=1],3,[HAAG2,NLCS.shx,s=0.5],-2

*V-GR-HAAG_VARIANT02-SO,746
A,3,[VERWIJDEREN2,NLCS.shx,s=1],3,[HAAG3,NLCS.shx,s=0.1815],-2

In overeenstemming met issue #174 zouden dit de juiste definities zijn:

OBJECT:
HAAG 		- CONTINUOUS en V-CONTINUOUS-SO
HAAG1 		- GR-HAAG1-SO en V-GR-HAAG1-SO
HAAG2 		- GR-HAAG2-SO en V-GR-HAAG2-SO
HAAG3 		- GR-HAAG3-SO en V-GR-HAAG3-SO
HAAG_RUW	- CONTINUOUS en V-CONTINUOUS-SO
HAAG_STRAK	- CONTINUOUS en V-CONTINUOUS-SO

Te vervallen:
*V-GR-HAAG-SO,744
A,3,[VERWIJDEREN2,NLCS.shx,s=1],3,[HAAG1,NLCS.shx,s=0.125],-2

*V-GR-HAAG_VARIANT01-SO,745
A,3,[VERWIJDEREN2,NLCS.shx,s=1],3,[HAAG2,NLCS.shx,s=0.5],-2

*V-GR-HAAG_VARIANT02-SO,746
A,3,[VERWIJDEREN2,NLCS.shx,s=1],3,[HAAG3,NLCS.shx,s=0.1815],-2

BEHOUDEN:
*GR-HAAG1-SO,80
A,6,[HAAG1,NLCS.shx,s=0.125],-2

*GR-HAAG2-SO,81
A,6,[HAAG2,NLCS.shx,s=0.5],-2

*GR-HAAG3-SO,82
A,6,[HAAG3,NLCS.shx,s=0.1815],-2

Hernoemd:
*V-GR-HAAG2-SO,745
A,3,[VERWIJDEREN2,NLCS.shx,s=0.5],3,[HAAG2,NLCS.shx,s=0.5],-2

*V-GR-HAAG3-SO,746
A,3,[VERWIJDEREN2,NLCS.shx,s=0.5],3,[HAAG3,NLCS.shx,s=0.1815],-2

Toevoegen:
*V-GR-HAAG1-SO,???????
A,3,[VERWIJDEREN2,NLCS.shx,s=0.5],3,[HAAG1,NLCS.shx,s=0.125],-2

TOTAAL LIJST:
*GR-HAAG1-SO,80
A,6,[HAAG1,NLCS.shx,s=0.125],-2

*GR-HAAG2-SO,81
A,6,[HAAG2,NLCS.shx,s=0.5],-2

*GR-HAAG3-SO,82
A,6,[HAAG3,NLCS.shx,s=0.1815],-2

*V-GR-HAAG2-SO,745
A,3,[VERWIJDEREN2,NLCS.shx,s=0.5],3,[HAAG2,NLCS.shx,s=0.5],-2

*V-GR-HAAG3-SO,746
A,3,[VERWIJDEREN2,NLCS.shx,s=0.5],3,[HAAG3,NLCS.shx,s=0.1815],-2

*V-GR-HAAG1-SO,???????
A,3,[VERWIJDEREN2,NLCS.shx,s=0.5],3,[HAAG1,NLCS.shx,s=0.125],-2

![image](https://github.com/nl-digigo/NLCS/assets/144665595/0312dc5f-39f4-49e8-b367-3d92ec570694)

**Comment by ElisabethKloren** [comment]
Reviewperiode Expertcommissie juni 2024 is gepasseerd, verwerking volgens voorstel

**Comment by ElisabethDeVries** [comment]
dubbel met #174
