### ISSUE TITLE
 'Betonrug', 'stelspecie', 'steunrug', 'stampbeton'

### ISSUE THREAD

**Issue by MvanderHulst** [nl-digigo/NLCS#417]
In de NLCS kom ik onder VH-KANTOPSLUITING een 'betonrug' tegen.
Dit is iets dat niet bestaat en mag komen te vervallen.
Als hiermee een 'varkensrug' of 'jumboblok' bedoeld wordt, staat deze onder de inrichtingselementen waar hij thuis hoort.
Nog met de naam 'HUNNENBED' welke wel aangepast dient te worden volgens issue #164 

Wat wel ontbreekt zijn de materialen om een band in te kunnen stellen.
Dit gebeurd in 'stelspecie' of 'stampbeton' met een steunrug van 'stampbeton'.
Deze moeten toegevoegd worden aan de standaard

Persoonlijk zou ik deze willen zetten onder:
VH-FUNDERING_STELSPECIE
VH-FUNDERING_STAMPBETON
Gezien het een onderdeel is van de fundatie van de wegopbouw.
Zowel 'openverhardingen' en 'kantopsluitingen' kunnen hierin gesteld worden.

**Comment by ElisabethKloren** [comment]
In de reviewperiode van de EC in juni 2024 is hier geen commentaar op gekomen, issue kan volgens voorstel verwerkt worden

**Comment by ElisabethKloren** [comment]
zie vooral ook even de discussie bij #441 en check of dit een nlcs probleem is of in eigen bibliotheek / software zit
