### ISSUE TITLE
wat betekent 'lijngroep35', als eigenschap van lijnweigths?

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#419]
dit is wat er in sql stond, de lijngroep35 heeft een X of niks als waarde:

CREATE TABLE `lijnweights` (
  `id` int(11) NOT NULL DEFAULT 0,
  `omschrijving` double(3,2) NOT NULL DEFAULT 0.00,
  `lijngroep35` text NOT NULL,
  `dunner` double(3,2) NOT NULL DEFAULT 0.00,
  `dikker` double(3,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

INSERT INTO `lijnweights` VALUES('1','0.18','X','0.13','0.25');
INSERT INTO `lijnweights` VALUES('2','0.25','','0.00','0.00');
INSERT INTO `lijnweights` VALUES('3','0.35','X','0.25','0.50');
INSERT INTO `lijnweights` VALUES('4','0.50','','0.00','0.00');
INSERT INTO `lijnweights` VALUES('5','0.70','X','0.50','1.00');
INSERT INTO `lijnweights` VALUES('6','1.00','','0.00','0.00');
INSERT INTO `lijnweights` VALUES('0','0.13','','0.00','0.00');
INSERT INTO `lijnweights` VALUES('-1','0.00','','0.00','0.00');

**Comment by MvanderHulst** [comment]
Zie issue #276 en onderstaande artikel uit de FB:

Wat mij betreft een volledig nutteloos hoofdstuk wat eenvoudiger kan worden uitgewerkt.
![image](https://github.com/nl-digigo/NLCS/assets/144665595/1ce2f58b-05f4-4ba2-b6fc-c32e1e3032de)

**Comment by ElisabethKloren** [comment]
Ja, duidelijk, mijn voorstel voor aanpassing van de documentatie wordt: 

In de [Toelichting informatiemodel](https://nl-digigo.github.io/NLCS/code_documentation/) komt de verwijzing naar de NEN-norm te staan; en de conversietabel naar MicroStation; waarbij we in de toekomst de conversietabel opnemen bij de lijndiktes  in de database

In de [Eisen aan tekeningen en modellen](https://nl-digigo.github.io/NLCS/requirementscadmodels/) stel ik de volgende tekst voor: 

> In NLCS krijgen objecten per status een standaard lijndikte mee; het is toegestaan om een lijndikte dikker of dunner te kiezen conform de tabel

In de [Eisen aan de software-implementatie van NLCS](https://nl-digigo.github.io/NLCS/requirementssoftware/) komt te staan:

> De software moet zorgen dat de gebruiker in de juiste standaard lijndikte tekent zoals aangegeven per laag en per status; waarbij de gebruiker ook de in de standaard gespecificeerde lijndikte dikker of dunner moet kunnen gebruiken.

**Comment by ElisabethKloren** [comment]
De nen-norm is ingetrokken

**Comment by MvanderHulst** [comment]
@ElisabethKloren 
- De verwijziging naar de NEN-norm lijkt mij overbodig, gezien deze niet meer bestaat.
- Per status een standaard lijndikte is ook niet juist. voor status N wordt 0.25, 0.35 en 0.50 toegepast. Hiervoor moet een algemene toelichtende tekst worden opgesteld t.z.t.
- Bij de eisen moet gewoon staan: lijndikte toekennen volgens de database.

Ik maar wel even een voorstel morgen.

**Comment by ElisabethKloren** [comment]
ik check even of dit nu is opgenomen in NEN-EN-ISO 128-2:2022

**Comment by ElisabethKloren** [comment]
in de objectentabellen staan gewoon lijndiktes aangegeven per status. De vraag is, gaat dit met een algemeen principe, dan kunnen we dit wellicht efficiënter beheren in de database.

**Comment by MvanderHulst** [comment]
> in de objectentabellen staan gewoon lijndiktes aangegeven per status. De vraag is, gaat dit met een algemeen principe, dan kunnen we dit wellicht efficiënter beheren in de database.

Klopt. ieder OBJECT heeft per status een lijndikte.
Het is niet zo dat één status altijd dezelfde lijndikte heeft.
N is bijvoorbeeld niet standaard 0.35.

**Comment by ElisabethKloren** [comment]
Ik heb de documentatie aangepast voor versie 5.02, reviewen van deze teksten kan wel voor versie 5.1, hier vloeit geen bloed uit
