### ISSUE TITLE
#1398	"In de NLCS norm is niet beschreven hoe een aanpijling is opgebouwd.

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#42]
#1398	"In de NLCS norm is niet beschreven hoe een aanpijling is opgebouwd.
een aanpijling is lijn, maar binnen MicroStation een onderdeel van een tekst en/of maatvoering.
Nu kan het complete aangepijlde tekst object onder -G staan (dat is nu zo bij ons het geval en wij denken dat dit niet juist is) of onder bv -T18 of -T25 of -M. Of wordt het een mixte opbouw, Dus moeten we tekst plaatsen op een tekst (-T18 of -T25) laag en de lijnen op een -G laag? Het wordt hiermee dus een samengesteld object bestaande uit verschillende lagen."

**Comment by ElisabethKloren** [comment]
Reactie Expertcommissie
"In het Expert-Commissie-overleg afgelopen 15 juni is snel besloten dat aanpijlingen op een tekstlaag komen te staan.
Veel voor te zeggen, maar…
Volgens de Formele Beschrijving 5.0_V1.0 21 april 2022 vallen aanpijlingen onder ‘hulp-geometrie’, zie par. 5.1.4 lid j.
De NLCS kent daarvoor in de groep ZZ de toevoeging AANPIJLING-G, een geometrie laag.

De beslissing om aanpijlingen in het vervolg op tekstlagen te plaatsen betekent dus aanpassing van de Formele Beschrijving.

Dan zou het wellicht ook eenduidig/duidelijker zijn om ‘AANPIJLING-G’ in de ZZ-groep te laten vervallen.
En in de formele beschrijving aan te geven dat bijschriften én aanpijlingen (multileaders) op een -T laag komen te staan.

Conform Formele Beschrijving NLCS hoort de NLCS-tooling aanpijlingen (nu ngo) op een AANPIJLING-G laag te zetten.

Op basis van het genoemde artikel, krijg ik haast het gevoel dat met 'aanpijlingen' iets anders wordt bedoeld dat een 'leader'? In de tekst:

De NLCS voorziet per HOOFDGROEP in aparte lagen voor het plaatsen van tekst, maatvoering en
‘hulpgeometrie’ als aanpijlingen, afbreeklijnen, hoogtelijnen, constructielijnen en stramienlijnen. De
betreffende standaard lagen zijn verzameld in een separate objectentabel

 

snap ik de overeenkomsten tussen aanpijlingen en afbreeklijnen, hoogtelijnen e..d. dan ook totaal niet.

Door deze 'logische aanpassing'. Artikel 4.6.6. zal ook aangepast moeten worden. Bij de volgende wijzigingsronden hier even goed de aandacht voor houden!"

**Comment by SanderNijhof** [comment]
Ik begrijp de gedachte erachter, maar ik vrees dat aanpijling op een T-laag plaatsen eigenlijk nog incorrecter is dan aanpijling op een G-laag plaatsen, omdat:
	

1. Een aanpijling geen textelelement is. 
2. Dat aanpijlingen op een G-laag staan is niet 100% correct, maar ook geen probleem en meer correct dan ze op een T-laag te plaatsen.
3. Volgens de huidige Formele Beschrijving komen multileaders/aanpijlingen op een laag *-AANPIJLING-G. De eigenschappen van die laag zijn voor alle statussen gelijk, nl. kleur 7, lijndikte 0.18mm. Als de multileaders naar tekstlagen gaan, krijgen ze verschillende kleuren en verschillende lijndiktes. Met name de lijndikte heeft dan een negatieve invloed op de leesbaarheid van de symbolen.

Ik denk echt dat we multileaders beter op de laag AANPIJLING-G kunnen laten staan. Er is geen noodzaak om dat te wijzigen.

**Comment by MvanderHulst** [comment]
Helaas een software probleem.
AutoCAD ziet een multileader wel degelijk als een tekst.
M.i. ook logisch, want je past een aanpijling toe, als je de tekst niet kwijt kan.... dan is de lijn een verwijzing naar de plek waar de tekst zou moeten staan.

**Comment by SanderNijhof** [comment]
In Microstation is een aanpijling een cell/Block, samen gesteld uit een textnode en een dimensionline. Dus eigenlijk zou dat een -S laag zijn. Als het in AutoCAD een textelement _is_, mag die dan al niet sowieso gewoon op een textlaag staan? Net als dat je een block hebt voor putnummers op -S, maar ook putnummer als text op een -T laag kunt plaatsen?
In de bijlage een voorbeeld van een aanpijling in Microstation. Wat maakt AutoCAD daarvan? Blijft het een block?
[aanpijling.zip](https://github.com/bimloket/NLCS/files/12593808/aanpijling.zip)

**Comment by MvanderHulst** [comment]
In AutoCAD wordt hij weergegeven als een niet aanpasbaar, statisch 'block-object'. De convertie tussen AutoCAD en Microstation is dus echt op het niveau dat het 'getoond' kan worden, maar is verder niet werkbaar.
Dit zal dus altijd een probleem blijven met leaders ben ik bang.

**Comment by ElisabethKloren** [comment]
EC 2024-01-11 autocad behandelt aanpijling als tekstobject (T-laag), microstation als maatvoeringsobject (m-laag), in nlcs moet het op een G-laag, dat wordt niet gebruikt; uitwisseling: een leader in microstation wordt een block in autocad, 

1. Er is een verschillend gebruik van de aanpijling; je kan het toestaan als tekst of maatvoering >vrijheid toestaan, dus lagen toevoegen

2. in de formele beschrijving 4.6.7 aanpijling als subonderdeel van een tekst > wijzigen, uitleggen hoe het verschillend werkt tussen pakketten, en hoe je daar mee om kunt gaan

![aanpijlinsvraag_issue42](https://github.com/nl-digigo/NLCS/assets/48585720/32073769-1d2a-40a0-9844-5d8626b3e9f4)

**Comment by SanderNijhof** [comment]
> 1. Er is een verschillend gebruik van de aanpijling; je kan het toestaan als tekst of maatvoering >vrijheid toestaan, dus lagen toevoegen; Aanpijlingen zijn teksten; dat is niet het object maatvoering; voorstel: aanpijling verwijderen

Uiteindelijk voorstel was om de laag AANPIJLING-G **niet te verwijderen** maar te handhaven! Daarnaast ook andere lagen voor aanpijlingen toe te staan: aanpijlingen kunnen zijn tekst-elementen, maatvoering-elementen of symbolen (Blocks). De NLCS-controletooling zou daar dan op aangepast kunnen worden.

Volgens FB par 5.1.4j staan aanpijlingen omschreven als ‘hulpgeometrie’. Vandaar waarschijnlijk de laag #-##-##-AANPIJLING-G in de NLCS. Mogelijk is voor AANPIJLING-G gekozen juist omdat de CAD-pakketten verschillend met dit element omgaan?

**Comment by MvanderHulst** [comment]
Als aanpijling als 'hulpgeometrie' is bestempeld, vindt ik dat helemaal vreemd.
Als leaders als 'tekst' of maarvoering worden behandeld, kan het object weg. inconsequent met de rest.
Als hij moet blijven, moeten we deze als 'wildcard' of 'special' omschrijven in de FB.

**Comment by SanderNijhof** [comment]
> Voor teksten en maatvoeringen zijn geen eigen lagen beschikbaar binnen de NLCS.

Jawel, middels elementtype. Onderscheid kan gemaakt worden met het -ELEMENT veld in de laagnaam, type -T?? en -M
Objecten hiervoor toevoegen is niet nodig toch? 

par 5.1 g.  "Tekst en bemating kunnen op elk niveau voorkomen (achter HOOFDGROEP, achter OBJECT, achter 
SUBOBJECT enzovoort), maar staan default achter HOOFDGROEP (zie ook paragraaf 5.1.4). "

**Comment by MvanderHulst** [comment]
@SanderNijhof klopt, maar logisch vindt ik het persoonlijk niet.
Waarom moet een TEKST en maatvoering altijd aan een object gekoppeld zitten, en heeeft een aanpijling een eigen object.

Huidige situatie:
N-WE-VH-T18
N-WE-VH-M
N-WE-VH-AANPIJLING-T18 (of N-WE-VH-AANPIJLING-M of N-WE-VH-AANPIJLING-G)

Consequent zou zijn:
N-WE-VH-TEKST-T18
N-WE-VH-MAATVOERING-M
N-WE-VH-AANPIJLING-T18 (of N-WE-VH-AANPIJLING-M of N-WE-VH-AANPIJLING-G)

of
N-WE-VH-T18
N-WE-VH-M
N-WE-VH-T18 (of N-WE-VH-M) waarbij ik uitga dat een aanpijling een tekst of maatvoeringsobject is.

In de huidige situatie krijgt de aanpijling een eigen object, omdat er geen element voor is.
Terwijl het een tekst of maatvoering is, afhankelijk van het systeem.

**Comment by MvanderHulst** [comment]
zie ook issue #76 diverse tegenstrijdigheden, die bovenstaande voorstel raken.

**Comment by ElisabethKloren** [comment]
dus het voorstel is om zz-(m) ook uit te breiden met teksthoogtes, en het object zz-aanpijling ook te veranderen in een element zz-(L) (leader) met eigen teksthoogtes

elementen = overal te plaatsen, komt achteraan de laagnaam. check functionele beschrijving

**Comment by ElisabethKloren** [comment]
werken met zz in eisen aan applicaties opnemen

**Comment by SanderNijhof** [comment]
> Huidige situatie:
N-WE-VH-T18
N-WE-VH-M
N-WE-VH-AANPIJLING-T18 (of N-WE-VH-AANPIJLING-M of N-WE-VH-AANPIJLING-G)

Ik zie de logica, maar vind de huidige situatie de beste optie. 
'TEKST-T' en 'MAATVOERING-M' lijkt me niet goed om aan de ZZ groep toe te voegen. Wat zijn de voordelen daarvan?
-M en -T geven al aan dat het een maatvoering of een tekst betreft. Ik heb hier nog nooit problemen mee gehad en het is mooi dat je deze lagen ook kunt gebruiken zonder een object te specificeren, omdat het op zichzelf geen objecten zijn.
Als een aanpijling een tekstelement is mag(/moet?) die ook op een laag N-WE-VH-T18. Of N-WE-VH-AANPIJLING-T18 ook mag heb ik me wel vaker afgevraagd omdat je dan 2 elementen uit de ZZ groep achter elkaar zet, maar ik zie het probleem niet om dit wil toe te staan. In Microstation is een aanpijling een apart element-type 'note' (die wordt gespecificeerd via een dimstyle en naar wordt behandeld als een cell/block en naar Autocad wordt geëxporteerd naar een block) dus zet ik die zelf op AANPIJLING-G conform de ZZ-tabel.
Als je 'AANPIJLING-G' 'TEKST-G' en 'MAATVOERING-G' bijv. aan de AL tabel toevoegt dan maakt dat wel duidelijker lagen mogelijk als:
N-WE-VH-AANPIJLING-T18
N-WE-VH-AANPIJLING-M
N-WE-VH-TEKST-T18
N-WE-VH-MAATVOERING-M
Maar willen we dat en is dat nodig?

**Comment by SanderNijhof** [comment]
> > Huidige situatie:
> > N-WE-VH-T18
> > N-WE-VH-M
> > N-WE-VH-AANPIJLING-T18 (of N-WE-VH-AANPIJLING-M of N-WE-VH-AANPIJLING-G)
> 
> Ik zie de logica, maar vind de huidige situatie de beste optie. 'TEKST-T' en 'MAATVOERING-M' lijkt me niet goed om aan de ZZ groep toe te voegen. Wat zijn de voordelen daarvan? -M en -T geven al aan dat het een maatvoering of een tekst betreft. Ik heb hier nog nooit problemen mee gehad en het is mooi dat je deze lagen ook kunt gebruiken zonder een object te specificeren, omdat het op zichzelf geen objecten zijn. Als een aanpijling een tekstelement is mag(/moet?) die ook op een laag N-WE-VH-T18. Of N-WE-VH-AANPIJLING-T18 ook mag heb ik me wel vaker afgevraagd omdat je dan 2 elementen uit de ZZ groep achter elkaar zet, maar ik zie het probleem niet om dit wil toe te staan. In Microstation is een aanpijling een apart element-type 'note' (die wordt gespecificeerd via een dimstyle en naar wordt behandeld als een cell/block en naar Autocad wordt geëxporteerd naar een block) dus zet ik die zelf op AANPIJLING-G conform de ZZ-tabel. Als je 'AANPIJLING-G' 'TEKST-G' en 'MAATVOERING-G' bijv. aan de AL tabel toevoegt dan maakt dat wel duidelijker lagen mogelijk als: X-XX-AL-AANPIJLING-T18 X-XX-AL-AANPIJLING-M X-XX-AL-TEKST-T18 X-XX-AL-MAATVOERING-M Maar willen we dat en is dat nodig?

lagen als N-WE-VH-KANTOPSLUITING_VOORKANTBAND_**MAATVOERING**-M
of N-WE-VH-KANTOPSLUITING_VOORKANTBAND_**TEKST**-T25
vind ik niet nodig.

**Comment by MvanderHulst** [comment]
@SanderNijhof 
Ik ben vooral aan het zoeken aan een stuk 'consequent' maken'.
Voorstander van het toevoegen van MAATVOERING en TEKST ben ik geen voorstander van, maar dat AANPIJLING er dan wél is, vindt ik onlogisch.
- Of alle 3 toevoegen als object, of geen van de 3 aanbieden.
- Omdat de omgang van aanpijlingen tussen AutoCAD en Microstation verschillen, is het het mooiste als een aanpijling een eigen element krijgt, dan wordt de logica:

- N-WE-VH-T18, teksten
- N-WE-VH-M, maatvoeringen
- N-WE-VH-L, aanpijlingen (leaders).

Voor de volledigheid:
- N-WE-VH-T18, teksten
- N-WE-VH-M18, maatvoeringen
- N-WE-VH-L18, aanpijlingen (leaders).
Dit om ook de tekstgrootte op layer niveau te kunnen regelen.

**Comment by SanderNijhof** [comment]
> * N-WE-VH-L, aanpijlingen (leaders).

Jezus, dat ik daar niet aan gedacht heb! :) Weet niet of het echt nodig is maar vind ik wel een prima voorstel! 



> * N-WE-VH-T18, teksten
> * N-WE-VH-M18, maatvoeringen
> * N-WE-VH-L18, aanpijlingen (leaders).

Dat wil je dan omdat je maatvoeringen met teksthoogte 1.8mm andere laageigenschappen wilt geven dan maatvoeringen met teksthoogte 2.5mm? En aanpijlingen wil je ook in verschillende kleuren weer kunnen geven?
Ik zie ook wel eens dit:
![image](https://github.com/nl-digigo/NLCS/assets/143598041/9200f0c7-a457-4c48-8fb8-2a3eff89f45e)

Dat is niet de bedoeling neem ik aan?

**Comment by MvanderHulst** [comment]
@SanderNijhof 
Het bovenste scenario komt nu wel voor inderdaad.
Dit omdat volgens de FB maatvoering altijd kleur 7 moet hebben, maar de tekst weer een andere kleur.
Jou 2e afbeelding is hoe het zou moeten zijn.
Per lettergrootte de bijbehorende layer en alles by-layer geregeld.
Daarvoor is de aanvulling M** noodzakelijk, net als bij T**.

In de huidige situatie worden de propperties hard overruled, wat geen wenselijke situatie is.
Hierover is Arkance al meerdere malen in de lucht gekomen, maar is nooit doorgevoerd om onduidelijke redenen.

Mooi te horen dat we het eens zijn. :-)

**Comment by ElisabethKloren** [comment]
> Jezus, dat ik daar niet aan gedacht heb! :) Weet niet of het echt nodig is maar vind ik wel een prima voorstel!

er is nu echt een héél dappere expert nodig om dit voorstel nog controversieel te verklaren ;-)

**Comment by SanderNijhof** [comment]
> In de huidige situatie worden de properties hard overruled, wat geen wenselijke situatie is.
> Hierover is Arkance al meerdere malen in de lucht gekomen, maar is nooit doorgevoerd om onduidelijke redenen.

Wat mij bijstaat is gezegd dat geen aanpassing in de FB nodig is:
Als een leverancier voor elementen harde properties toepast wijkt zij af van de FB: Elementen zijn bylayer, dus ook de tekstelementen in bijvoorbeeld maatvoeringen en blocks.
De laageigenschappen bepalen de kleur. Teksten in maatvoeringen komen op laag -M dus kleur 7, teksten in blocks komen op lagen -S dus kleur van het block. Alleen teksten op eigen -Txx lagen hebben een eigen kleur (bylayer).

**Comment by MvanderHulst** [comment]
@SanderNijhof 
Het voorstel is de aanvulling van elementen.
-M wordt aangevuld met:
M18
M25
etc.

Anders is dit:
![image](https://github.com/nl-digigo/NLCS/assets/144665595/55c41979-dad0-4e83-871f-41c3b6332481)

Niet mogelijk.

**Comment by SanderNijhof** [comment]
> @SanderNijhof
> Het voorstel is de aanvulling van elementen.
> -M wordt aangevuld met:
> M18
> M25
> etc.

Ja precies en voor -Lxx net zo dan. 
(Bedoelde in mijn vorige comment met "_Teksten in maatvoeringen komen op laag -M dus kleur 7_" hoe het in de huidige situatie is/zou moeten zijn).
Zou M18 en M25 voldoende zijn? Als we ook M35, M50 en M70 toevoegen geven we daarmee aan dat er ook maatvoeringen geplaatst mogen worden met andere teksthoogten.

**Comment by MvanderHulst** [comment]
@ElisabethKloren deze wijziging heeft invloed voor de leveranciers.
Kan deze al mee in 5.1?

**Comment by ElisabethKloren** [comment]
Ik denk het wel, we gaan maximale vrijheid geven omdat we de verschillend tussen de pakketten niet kunnen oplossen. 

Ik ben wel een lijst met issues aan het opstellen die ik nog aan de expertcommissie ga mailen voor extra reviewronde, daar komt deze issue bij te staan.

**Comment by MvanderHulst** [comment]
@ElisabethKloren 
Gaat inderdaad om de aanvulling van diverse elementen voor M** en de L** en de juiste toepassing en verwerking ervan.

**Comment by ElisabethKloren** [comment]
Voorstel voor wijziging in  5.1, als er een correctie nodig is mag je deze issue weer openen:
ZZ-(M) verwijderd
ZZ-(M18) toegevoegd
ZZ-(M25) toegevoegd

ZZ-AANPIJLING verwijderd
ZZ-(L1.8) toegevoegd
ZZ-(L2.5) toegevoegd

Aanpassing formele beschrijving:

Toevoegen het element L in de lijst met elementen

De opbouw van een aanpijlingen verschilt sterk tussen verschillende softwarepakketten.
Het is toegestaan om een aanpijling op te nemen met het ELEMENT L** en T**, al naar gelang de standaard van het pakket.

Maatvoeringen krijgen een verschillende kleur en lijndikte, afhankelijk van de gebruikte teksthoogte:

<img width="239" alt="maatvoering-voorbeeld" src="https://github.com/nl-digigo/NLCS/assets/48585720/e5610f11-6f4f-4e1c-ac12-4cc60e1e957a">

Over hoe met ZZ wordt omgegaan, stond nog niks bij de eisen aan applicaties, ik stel voor om dit toe te voegen:
Bij het plaatsen van teksten, maatvoeringen of aanpijlingen uit hoofdgroep ZZ moeten elementen worden toegevoegd aan de laagnaam, dit mogen zowel element T**, L** als M** zijn
Voorbeeld:
N-WE-VH-T18, teksten
N-WE-VH-M18, maatvoeringen
N-WE-VH-L18, aanpijlingen (leaders).

**Comment by MvanderHulst** [comment]
@ElisabethKloren bijna correct:
onderstaand zin klopt alleen niet:

De opbouw van een aanpijlingen verschilt sterk tussen verschillende softwarepakketten.
Het is toegestaan om een aanpijling op te nemen met het ELEMENT L** en T**, al naar gelang de standaard van het pakket.

Het idee is juist om aanpijlingen nu ALTIJD op het element L** te zetten.
Dan is duidelijk uit te leggen dat het element L alle 'problemen voor uitwisseling' bevat. ;-)
Dat in autoCAD een leader dan vanuit een textstyling wordt opgemaakt en vanuit microstation als dimension maakt dan niet uit.
Dan is het Element voor een leader altijd hetzelfde, tussen de paketten.

**Comment by SanderNijhof** [comment]
> Het idee is juist om aanpijlingen nu ALTIJD op het element L** te zetten.

Precies! Maar is -L dan niet voldoende of is L18, L25, L35, L50 en L70 nodig?

**Comment by MvanderHulst** [comment]
@SanderNijhof 
Ik stel voor om tekst, maatvoering en leaders allemaal hetzelfde te behandelen.
Dus als 18, 25, 35, 50 en 70 beschikbaar te stellen.

Dit omdat AutoCAD leaders als tekst behandeld en je dus standaard alle 5 de maten al beschikbaar hebt vanuit de 'tekststijling'.

Geeft de gebruiker vrijheid, maar zit niemand in de weg.

**Comment by SanderNijhof** [comment]
Ik zie ook wel eens -T lagen in een tekening, Die zijn niet toegestaan(?)
Nu zijn -M lagen wel toegestaan, maar straks vanaf NLCS 5.1 niet meer? Ik zie de logica van -M18 en -M25 wel en ben in dat opzicht voorstander ook voor de uniformiteit, maar zie de noodzaak hiervoor niet en voor de gebruikers en software is het wel een hele verandering. Om -M wel toe te staan naast -M18 en -M25 is ook een optie, maar dan moeten we -T ook toe gaan staan(?). Maatvoering is wat anders dan tekst, ook al wordt in de opbouw van maatvoering gebruik gemaakt van tekststijlen.


> Dit omdat AutoCAD leaders als tekst behandeld en je dus standaard alle 5 de maten al beschikbaar hebt vanuit de 'tekststijling'.

Ook daarvan zie ik de noodzaak niet, maar vind het wel heel logisch vanwege dat het in AutoCAD een tekstelement is en teksten per grootte ook een eigen laag hebben gekregen en omdat het -L element nog niet bestond, dus van daaruit ook geen verwarring geeft.

**Comment by MvanderHulst** [comment]
@SanderNijhof 
Vanuit de huidige standaard is -T niet toegestaan en dient deze altijd aangevuld te zijn met de tekstgrootte.
Voor maatvoering was dit altijd enkel -M.
Wat mij betreft wordt dit dan ook altijd 'standaard' M18 of M25, waarbij regulier M niet meer toegestaan is.

**Comment by ElisabethKloren** [comment]
Beste Expertcommissie NLCS,

In de issues van 5.1 zitten een paar, die impact hebben op software implementatie of controle tooling. Dat zijn de issues waarvan ik graag zou willen, dat jullie die met extra aandacht reviewen. Ik weet dat de officiële reviewperiode van juni al voorbij is…. Maar denk dat het belangrijk is om voor deze meer tijd te geven, terwijl we al aan de slag zijn met de kleine verbeteringen. 

Ik zou jullie willen vragen om deze issues voor 1 september te reviewen en daarbij duidelijk aan te geven of het voorstel moet worden aangepast of uitgesteld naar een volgende release als deze te veel impact heeft.

**Comment by SanderNijhof** [comment]
> Wat mij betreft wordt dit dan ook altijd 'standaard' M18 of M25, waarbij regulier M niet meer toegestaan is.

Daarbij dan wel in de gaten houden dat zowel bij M18 als M25 de maatlijnen een lijndikte 0,18mm krijgen, of worden de maatlijnen bij M25 dan ook 0,25mm dik?

**Comment by MvanderHulst** [comment]
@SanderNijhof wanneer de lineweight overeenkomt met de texthoogte, worden de maatlijnen inderdaad dikker naarmate de lettergrootte meer wordt.

opzich logisch, anders is de verhouding helemaal weg.

**Comment by ElisabethKloren** [comment]
> @SanderNijhof Ik stel voor om tekst, maatvoering en leaders allemaal hetzelfde te behandelen. Dus als 18, 25, 35, 50 en 70 beschikbaar te stellen.

Ik heb dit nog toegevoegd in de database.

**Comment by SanderNijhof** [comment]
> @SanderNijhof wanneer de lineweight overeenkomt met de texthoogte, worden de maatlijnen inderdaad dikker naarmate de lettergrootte meer wordt.
> 
> opzich logisch, anders is de verhouding helemaal weg.

Voor elementen L** zou ik dat logischer vinden dan voor elementen M** (conform FB nu lijnen altijd 0.18mm). 
Ik ga daar even e.e.a. mee proberen...

**Comment by SanderNijhof** [comment]
Een toelichting waarom voorkeur de lijndikte ook bij aanpijlingen op 0.18mm te houden, ivm behouden van de vorm van de terminator, m.n. voor de pijlpunten en openbol.
Links met lijndikten afhankelijk van teksthoogte, rechts met constante lijndikte 0.18mm, ziet er in Microstation dan zo uit:
![image](https://github.com/user-attachments/assets/cb1819c2-b851-4744-86ea-a8b66b487a35)

**Comment by MvanderHulst** [comment]
@SanderNijhof 
De excel ziet er volgens mij goed uit zo. Met inderdaad aandacht voor de lijndiktes.
Wat mij betreft zouden alle eigenschappen van de objecten op 'ByLayer/ByLevel' moeten staan.
De relatie texthoogte/lineweight zou hierbij losgelaten mogen worden.
Alle lineweights voor de annotaties op 0.18 is wat mij betreft prima.
Dan krijg je dus de rechter variant als resultaat. Dit moet dan wel in de tabel aangepast worden.

**Comment by ElisabethKloren** [comment]
Expertcommissie 2024-09-19:
Leaders zijn verschillen in AutoCAD en Microstation, daarom gebeuren er gekke dingen bij uitwisseling, interpretatieverschillen. Daarom voorstel leader eigen element, letter L. Leader + tekst worden op dezelfde laag geplaatst. Daarbij ook issue #422 > kleuren worden aangepast, alle annotaties gaan op dezelfde manier. 
Dan kun je bij uitwisseling zoeker op L en daar aandacht aan besteden bij uitwisseling tussen pakketten. 
Akkoord expertcommissie

**Comment by SanderNijhof** [comment]
> Akkoord expertcommissie

Is ook akkoord dat de pijlpunt 1.8mm lang wordt ipv 2.5mm?

Aandachtpunt is dat een leaderelement element in z'n geheel op een -L laag komt te staan met bylayer eigenschappen. Dus niet de tekst van de leader op een aparte laag of overrides.  Hetzelfde geldt voor maatvoeringen: de maatvoeringlijnen en de tekst van de maatvoering hebben allen de zelfde bylayer eigenschappen en staan op de dezelfde laag.

**Comment by MvanderHulst** [comment]
Standaard 1.8 is akkoord bevonden. en je aandachtspunt is volledig terrecht.

**Comment by MvanderHulst** [comment]
Ook de M18 en M25 zijn akkoord bevonden.

**Comment by ElisabethKloren** [comment]
als zodanig opgenomen in de database
