### ISSUE TITLE
query objects en objects verkort aanpassen / of is responstijd hub te groot? 

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#420]
@gerritversteegh ik denk dat ik de [query van objects verkort](https://github.com/nl-digigo/NLCS/blob/main/code/NLCS_Query_Objects_Verkort.rq)  niet goed heb aangepast (hij deed de rgb kleuren nog niet goed, ik heb een kopie gemaakt van de query objects en alleen de opsomming van de tabel erin geplakt) , als ik deze query in de hub invoer en de hoofdgroep GC invoer, krijg ik geen respons (dit heb ik al een paar keer geprobeerd), bij kleinere datasets zoals AL wel 

Zou jij kunnen kijken waarom het niet werkt?

Herstel: als ik GC invul bij de [query objects](https://github.com/nl-digigo/NLCS/blob/main/code/NLCS_Query_Objects.rq) geeft deze ook geen respons, wel als ik AL invul

Beide query's werken wel als ik FC invul, mijn theorieën voor zover ze wat waard zijn: 
1. de query is te complex, bij een grotere dataset duurt het te lang en de hub gaat "out". Zou het dan wel werken bij een rechtstreekse call naar het sparql-endpoint? Kan dat wel sneller complexere query's aan? 
2. er is iets mis met de publicatie van GC (snap ik niet, want de andere hoofdgroepen lijken wel goed te gaan)
3. Ik heb alleen een verbinding met wifi en dat is te traag voor deze grote vraag? kan het aan mijn slome laptop / thuisnetwerk liggen?

**Comment by ElisabethKloren** [comment]
KL werkt ook niet, ook te grote dataset

**Comment by gerritversteegh** [comment]
@ElisabethKloren De query klopt, de grootte van de dataset resulteert inderdaad in een timeout van het request. Ik heb hiervoor een ticket aangemaakt bij IT en laat het weten als ik hier reactie op heb

**Comment by gerritversteegh** [comment]
@ElisabethKloren Ik heb beide versies van de queries ([verkort ](https://github.com/nl-digigo/NLCS/blob/main/code/NLCS_Query_Objects_Verkort.rq)en [niet verkort](https://github.com/nl-digigo/NLCS/blob/main/code/NLCS_Query_Objects.rq)) aangepast. Er zat een triple tussen die de query flink vertraagde, dus die heb ik eruit gehaald. Daarnaast heb ik de properties nu expliciet opgenomen ipv dat deze properties opgezocht moeten worden in de publicatie. Dit maakt de query iets minder leesbaar (vandaar heb ik de oude triples als comments erachter laten staan), maar versnelt de query wel enorm. Het is mijn nu gelukt om GC te bevragen, laat het aub even weten als je nog problemen ervaart

**Comment by gerritversteegh** [comment]
De queries geven nu trouwens ook geen time out error meer als het filter voor de hoofdgroep weggelaten wordt, dus alle objecten kunnen nu in één keer bevraagd worden .

**Comment by ElisabethKloren** [comment]
Supergoed, en dat in je vakantie :-)

**Comment by ElisabethKloren** [comment]
Yes, alles werkt
