### ISSUE TITLE
Object HULPLIJN als wildcard in NLCS

### ISSUE THREAD

**Issue by MvanderHulst** [nl-digigo/NLCS#421]
De NLCS biedt een standaard voor het opstellen van tekeningen.
Echter worden er in dezelfde model tekeningen vaak ook hoeveelheden bepaald. Dit gebeurd op lagen die afwijken op de NLCS. Deze komen als 'foutmelding' uit de controlerapportages (het zijn tenslotte geen NLCS lagen).

Graag zou ik in de FB een uitzondering willen opnemen dat alle laagnamen met het object 'HULPLIJN_eigen aanvulling' worden uitgesloten van de controle. Hiermee wordt voor de tekenaar een groep gemaakt waarop ze ALLES kwijt kunnen wat geen onderdeel is van de daadwerkelijke engineering, maar echt alleen eigen hulplijnen zijn voor welk doel dan ook.

**Comment by ElisabethKloren** [comment]
@MvanderHulst deze snap ik niet, er is toch een zz-object hulplijn die je kunt gebruiken om hulplijnen te tekenen? Hoezo is die niet gekoppeld aan een bekende laagnaam (je bepaalt toch de hoeveelheid van een object, dus maak je een hulplijn op een bekende laag?

**Comment by MvanderHulst** [comment]
Alle OBJECTEN van de NLCS waarmee de engineeringstekening zijn opgesteld, zijn niet geschikt voor het bepalen van hoeveelheden. Je maakt dus altijd extra hoeveelheden lagen aan om de hoeveelheden te borgen.
Hiervoor wordt meestal HULPLIJN gebruikt, waarbij de basis is:
X-XX-AL-HULPLIJN-G
Welke aangepast wordt met de hand naar:
X-XX-AL-HULPLIJN_RIJWEG-S

**Comment by ElisabethKloren** [comment]
ok, nu snap ik wat je met eigen aanvulling bedoelt, een rijweg is geen object maar je tekent toch een hulplijn. Ik zou deze verwachten in VW en niet in AL, maar alla.

Voorstel: toch nog een nieuwe eis aan softwareleveranciers in versie 5.1, in de controletool, maar geen zware eis

**Comment by MvanderHulst** [comment]
Hoofgroep en status zijn in dit geval niet relevant. ;-)
SCenario blijft hetzelfde.

**Comment by SanderNijhof** [comment]
> Echter worden er in dezelfde model tekeningen vaak ook hoeveelheden bepaald. Dit gebeurd op lagen die afwijken op de NLCS.

Waarom?

> Deze komen als 'foutmelding' uit de controlerapportages (het zijn tenslotte geen NLCS lagen).
> 
> Graag zou ik in de FB een uitzondering willen opnemen dat alle laagnamen met het object 'HULPLIJN_eigen aanvulling' 

Dit zouden best geldige NLCS-lagen kunnen zijn. Als een laag niet is opgenomen in de database, maar wel voldoet aan de NLCS-laagopbouw, zou de controle tool die laag goed moeten keuren, evt. met een opmerking 'niet uit database'


> Alle OBJECTEN van de NLCS waarmee de engineeringstekening zijn opgesteld, zijn niet geschikt voor het bepalen van hoeveelheden. 

Toch zijn ze daar in de basis wel voor bedoeld!

>Je maakt dus altijd extra hoeveelheden lagen aan om de hoeveelheden te borgen.
> Hiervoor wordt meestal HULPLIJN gebruikt, waarbij de basis is:
> X-XX-AL-HULPLIJN-G

Ik neem aan dat je de HULPLIJNen gebruikt voor oppervlakken? Daar is ook element -O voor. Zie FB 3.5.7: "_Het ELEMENT Oppervlak (O) wordt met name gebruikt, wanneer voor (terrein-)oppervlakken met behulp van het model hoeveelheden moeten worden bepaald._"

'HULPLIJN' zit in de groep ZZ dus logischer zou zijn bijv. N-WE-VH-HULPLIJN-G, maar X-XX-AL-HULPLIJN-G is uiteraard ook toegestaan.

Volgens mij volstaan de bestaande eisen aan de controletooling het beste. Vraag is of de leveranciers die allemaal identiek geïmplementeerd hebben.

**Comment by SanderNijhof** [comment]
> Hiervoor wordt meestal HULPLIJN gebruikt, waarbij de basis is:
> X-XX-AL-HULPLIJN-G
> Welke aangepast wordt met de hand naar:
> X-XX-AL-HULPLIJN_RIJWEG-S

Twee opmerkingen hierover:
1. X-XX-AL-HULPLIJN_RIJWEG-S
a. De '-S' een tiepvout en er was -G bedoeld?
b. De laag **X-XX-AL-HULPLIJN_RIJWEG-G** voldoet aan de NLCS laagnaamopbouw en is een **geldige NLCS laagnaam**. In de uitgangspunten voor controle tool NLCS (sinds 2018?) is opgenomen dat de controletool bij dit soort lagen moet vermelden 'Aanvulling op NLCS' en geen(!) foutmelding.

2. Ik zie in de NLCS nog dat zowel **#-##-OG-HULPLIJN-G** als **#-##-ZZ-HULPLIJN-G** zijn opgenomen met verschillende laageigenschappen. Dat klopt niet. Bij deze (volgens mij op herhaling) het voorstel om de laag #-##OG-HULPLIJN-G (ID2919) te laten vervallen.

**Comment by MvanderHulst** [comment]
@SanderNijhof 
De -S is inderdaad een typfout.
Precies wat je bij punt 1 aangeeft. Is mijn wens om alles in 'HULPLIJN' volledig te negeren en ook niet als 'aanvulling' te bestempelen. Vanuit de rapportages zien opdrachtgevers dit ook als een 'probleem' wanneer ze vragen om 100% standaard NLCS. Uitleggen dat dit niet altijd kan is erg ingewikkeld...

**Comment by MvanderHulst** [comment]
@SanderNijhof 
Punt 2 is inderdaad in het 5.1 voorstel gecorrigeerd. ZZ-HULPLIJN blijft en de OG-HULPLIJN komt te vervallen.

**Comment by ElisabethKloren** [comment]
Ik heb dit als extra eis opgenomen in de eisen aan applicaties: 

indien de laagnaam de tekst HULPLIJN bevat, dient de controletool geen melding te maken van het object.
