### ISSUE TITLE
conversietabel lijndiktes microstation opnemen in de database; query maken en tabel publiceren 

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#423]
<img width="277" alt="conversietabellijndiktesmicrostation" src="https://github.com/nl-digigo/NLCS/assets/48585720/f3cbaba2-7e73-48e4-ae68-1a6772242f0b">

- [x] Deze kan worden opgenomen in de database 
- [x] Documentatie aanpassen
- [ ] Query uitbreiden

**Comment by SanderNijhof** [comment]
Dit is toch niet specifiek voor MicroStation, maar voor NLCS algemeen, dus ook voor AutoCAD?

**Comment by gerritversteegh** [comment]
Het ophalen van de MicrostationNummers is nu opgenomen in de [query van de lineweights](https://github.com/nl-digigo/NLCS/blob/main/code/actueel/NLCS_Query_Lijnweights.rq)

**Comment by ElisabethKloren** [comment]
de query is verplaatst: https://github.com/nl-digigo/NLCS/blob/main/code/5.1/NLCS_Query_Lijnweights.rq
