### ISSUE TITLE
Hoofdgroep KL => Combikabel

### ISSUE THREAD

**Issue by MvanderHulst** [nl-digigo/NLCS#427]
In de hoofdgroep KL komt voor:

KL-COMBIKABEL
deze hoort onder:
KL-ET_LS_COMBIKABEL, gezien een combikabel altijd laagspanning is.

**Comment by NielsNederpel** [comment]
in principe akkoord, maar misschien laten afhangen van de wijziging m.b.t. netbeheer?

**Comment by ElisabethKloren** [comment]
Akkoord, deze issue plaats ik bij release 5.4 om dat vanuit netbeheer een nieuw voorstel komt voor de hoofdgroep KL

**Comment by ElisabethKloren** [comment]
en omdat het nu in één geheel gepubliceerd gaat worden, ik heb de wijziging vast doorgevoerd.

**Comment by ElisabethDeVries** [comment]
heropenen en meenemen na 5.2 release
