### ISSUE TITLE
PUTDEKSELHOOGTE <> PUTDEKSELNIVEAU

### ISSUE THREAD

**Issue by MvanderHulst** [nl-digigo/NLCS#428]
In hoofdgroep RI is het OBJECT aanwezig:
RI-PUTDEKSELNIVEAU

de bijbehorende symbolen heten:
SRI-PUTDEKSELHOOGTE.

Inconsequent en gewenst om gelijk te trekken.

Wat zegt de GWSW hierover?

**Comment by ElisabethKloren** [comment]
in de gwsw ontologie zijn dit synoniemen: https://data.gwsw.nl/1.6/Basis/index.html?menu_item=classes&item=../../def/1.6/Basis/Putdekselniveau

Putdeksel heeft een attribuut dat heet HoogteDeksel  https://data.gwsw.nl/1.6/Basis/index.html?menu_item=classes&item=../../def/1.6/Basis/Putdeksel

Voorstel: RI-PUTDEKSELNIVEAU wordt RI-PUTDEKSELHOOGTE

**Comment by MvanderHulst** [comment]
Goed plan. Dit is ook in de civiele wereld de gangbare term. :-)

**Comment by NielsNederpel** [comment]
Eens om gelijk te trekken tussen object en symboolnamen. echter is er waarschijnlijk bewust gekozen om pudekselniveau op te nemen (ivm de mapping tussen GWSW en NLCS die voor 5.0 is bewerkstelligt.) omdat je die "in de lijst" staat waarbij putdekselhoogte dan het synoniem is...had dit andersom geweest (dus putdekselhoogte "in de lijst" en putdekselniveau als synoniem) had dit mogelijk "andersom" in de NLCS gekomen. omdat het synoniemen zijn kan het (in mijn idee) geen kwaad om voor putdekselhoogte te kiezen in de NLCS.

**Comment by ElisabethKloren** [comment]
akkoord om putdekselhoogte te verwerken

**Comment by ElisabethDeVries** [comment]
in 6.0 om zo weinig mogelijk impact te hebben op individuele implementaties bij 5.2 release
