### ISSUE TITLE
#1079	Waarom is de symbool voor een trekker oplegger een combinatie van 18,5m? Wettelijk gezien is de maximale lengte 16,5m.

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#43]
#1079	Waarom is de symbool voor een trekker oplegger in de NLCS een combinatie van 18,5m? Wettelijk gezien is de maximale lengte 16,5m.

**Comment by ElisabethKloren** [comment]
Reactie Expertcommissie
opmerking is terecht

**Comment by ElisabethKloren** [comment]
To Do
"aanpassen symbolen:
SAL-AANKLEDING_VRACHTAUTO_ZIJAANZICHT_18.5-D
SAL-AANKLEDING_VRACHTAUTO_BOVENAANZICHT_18.5
ook symbolen wijzigen in database (d.m.v. Excel)"

**Comment by SanderNijhof** [comment]
Astublief. Trekker+Oplegger 16,5m gebaseerd op 18.5m. Gemaakt met Microstation, dus nog wel een block van maken op juiste coördinaten en met juiste plaatsingspunt.

[SAL-AANKLEDING_VRACHTAUTO_BOVENAANZICHT_16.5.zip](https://github.com/bimloket/NLCS/files/12612124/SAL-AANKLEDING_VRACHTAUTO_BOVENAANZICHT_16.5.zip)

**Comment by ElisabethDeVries** [comment]
[[Release note]] In de symbolenbibliotheek van hoofdgroep ALgemeen is een symbool toegevoegd voor een trekker oplegger met maatvoering 16.5 m: SAL-AANKLEDING_VRACHTAUTO_BOVENAANZICHT_16.5.dwg

**Comment by ElisabethDeVries** [comment]
reopen voor acceptatie 5.2
