### ISSUE TITLE
Controle Shape bestand - Deze functie controleert het voorkomen in de NLCS lijntypes van shapes uit een te selecteren NLCS shape bestand - ????

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#430]
deze tekst stond in een checklist voor de nieuwe linked-database, maar waar gaat dit over?

**Comment by MvanderHulst** [comment]
@ElisabethKloren zie #278 

Lijntypes kunnen zijn aangevuld met een SHAPE uit de NLCS.SHX.
Ik vermoed dat het gewenst is om te controleren of alle toegepaste SHAPES in de NLCS.LIN ook daadwerkelijk voorkomen in de NLCS.SHX.

Deze analyse had ik gedaan in de genoemde issue. Hopelijk heb je daar wat aan.

**Comment by ElisabethKloren** [comment]
Dank,nu snap ik het. Ik zal de documentatie van NLCS aanpassen, zowel de beheerhandleiding om die controle uit te voeren voor publicatie van een nieuwe versie, als de beschrijving van onderdelen van de standaard
