### ISSUE TITLE
inritblok moet vervangen door term inritband

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#440]

**Comment by SanderNijhof** [comment]
Deze issue komt denk ik doordat ik inritblokken noemde in een reactie?
Maar inritblokken komen niet voor in de NLCS 5.0
NLCS 5.0 kent de laagnaam x-xx-VH-KANTOPSLUITING_ELEMENT_INRITBAND-G/S met als symbool SVH-KANTOPSLUITING_INRITBAND
Staat ook correct in het overzicht van Michel.
deze blokken zijn er wel wel:
_KANTOPSLUITING_ELEMENT_HOEKBLOK_
KANTOPSLUITING_LEICONBLOK
KANTOPSLUITING_ROTONDEBLOK
KANTOPSLUITING_ROTONDEBLOK_500 200

Dat deze blokken vallen onder 'kantopsluiting' lijkt mij goed.

**Comment by ElisabethKloren** [comment]
dan was deze issue een vergissing, ik sluit hem af
