### ISSUE TITLE
VH-KANTOPSLUITING_ELEMENT

### ISSUE THREAD

**Issue by MvanderHulst** [nl-digigo/NLCS#441]
Samenstelling van VH-KANTOPSLUITING_ELEMENT is zeer onlogisch opgemaakt.
Diverse SUBOBJECTEN dienen altijd onderdeel te zijn van een gespecifieerde afmeting en kan nooit zelfstandig bestaan.

ELEMENT_BOOMKRANS_ELEMENT <- overbodig, zonder laatste _ELEMENT is voldoende.
ELEMENT_HOEKBLOK <- overbodig, is onderdeel van het gemaatvoerde object.
ELEMENT_HOEKSTUK <- overbodig, is onderdeel van het gemaatvoerde object.
ELEMENT_INRIT_PERRONBAND <- overbodig, is onderdeel van het gemaatvoerde object.
ELEMENT_PARKEERBAND <- overbodig, is een soort.
ELEMENT_PERRONBAND <- overbodig, is onderdeel van het gemaatvoerde object.
ELEMENT_PUNTSTUK <- overbodig, is onderdeel van het gemaatvoerde object.
ELEMENT_VERLAAGDEBAND <- overbodig, is onderdeel van het gemaatvoerde object.
ELEMENT_VERLOOPBAND <- overbodig, is onderdeel van het gemaatvoerde object.

Enkel ELEMENT_BOOMKRANS blijft dan over.
Dit kan een OBJECT worden en dan kan ELEMENT geheel vervallen?

**Comment by SanderNijhof** [comment]
@MvanderHulst 
>Diverse SUBOBJECTEN dienen altijd onderdeel te zijn van een gespecifieerde afmeting en kan nooit zelfstandig bestaan.

Bedoel je dan dat de laag VH-KANTOPSLUITING_ELEMENT_HOEKBLOK-G/S hernoemt moet worden naar VH-KANTOPSLUITING_HOEKBLOK-G/S of dat deze lagen helemaal uit de NLCS kunnen?

KANTOPSLUITING_ELEMENT_BOOMKRANS_ELEMENT-G/S bestaat in de hoofdgroep IE ipv VH?

**Comment by MvanderHulst** [comment]
@SanderNijhof 
Een hoekblok is altijd een onderdeel van een specifieke afmeting van een band.
Zie onderstaande voorbeeld:
![image](https://github.com/nl-digigo/NLCS/assets/144665595/09db60ee-50ce-46d1-98f6-b8f251a4662e)

De bovenste is onjuist en onbruikbaar, het hoekblok ondergebracht onder de admeting van de band is waar hij thuis hoort.

**Comment by SanderNijhof** [comment]
@MvanderHulst 
Dus je voorstel is die lagen te laten vervallen en aparte lagen voor HOEKBAND te hanteren?
Of een heleboel nieuwe lagen met afmeting_HOEKBAND toe te voegen?

**Comment by NielsNederpel** [comment]
> ELEMENT_BOOMKRANS_ELEMENT <- overbodig, zonder laatste _ELEMENT is voldoende.

?? dit object bestaat helemaal niet in de VH-Excel...
binnen InfraCAD kom ik m wel tegen, maar dan wordt ID 528 aangegeven en die vind ik niet in de VH- excel...
het nummer is sowieso te "laag" voor VH binnen IE zie ik m echter ook niet en wordt deze als enige overgeslagen want 527 en 529 zie ik wel. 
inderdaad zoals Sander ook aangeeft: binnen InfraCAD wordt het object opeens op hoofdgroep IE getekend ipv VH

> ELEMENT_HOEKBLOK <- overbodig, is onderdeel van het gemaatvoerde object.
ELEMENT_HOEKSTUK <- overbodig, is onderdeel van het gemaatvoerde object.
ELEMENT_INRIT_PERRONBAND <- overbodig, is onderdeel van het gemaatvoerde object.

dit is op dit moment hoe het in InfraCAD al werkt maar deze objecten bestaan dus niet binnen de NLCS. zelfs hun ouders bestaan nog niet (de hoogte van de betreffende banden) in de NLCS. Dit zijn allemaal "extra" objecten uit de InfraCAD bibliotheek. dus dan worden dit inderdaad héél veel extra lagen zoals Sander ook al aangeeft, die toegevoegd moeten worden aan de NLCS.

> ELEMENT_PARKEERBAND <- overbodig, is een soort.

ja volgens mij is dit meer bekend als stootband? parkeerband zegt mij niet zo veel.

> ELEMENT_PERRONBAND <- overbodig, is onderdeel van het gemaatvoerde object.
ELEMENT_PUNTSTUK <- overbodig, is onderdeel van het gemaatvoerde object.
ELEMENT_VERLAAGDEBAND <- overbodig, is onderdeel van het gemaatvoerde object.
ELEMENT_VERLOOPBAND <- overbodig, is onderdeel van het gemaatvoerde object.

dit is op dit moment hoe het in InfraCAD al werkt maar deze objecten bestaan dus niet binnen de NLCS. dit zijn "extra" objecten uit de InfraCAD bibliotheek. dus dan worden dit inderdaad héél veel extra lagen zoals Sander ook al aangeeft.

> Enkel ELEMENT_BOOMKRANS blijft dan over.
Dit kan een OBJECT worden en dan kan ELEMENT geheel vervallen?

even afhankelijk dus of we al die lagen gaan toevoegen voor hoekblokken, hoekstukken, perronbanden, puntstukken etc.

**Comment by MvanderHulst** [comment]
@NielsNederpel en @SanderNijhof ik zie dat ik inderdaad wat InfraCAD-vervuiling in het voorstel heb zitten...
Standaard NLCS is wel deze vreemde logica te vinden.
Onderstaand in het rood aangegeven welke objecten altijd onderdeel van een afmeting band zouden moeten zijn.
Deze 'losse' maatloze posities voegen voor mij tekenwerk en hoeveelheden niks toe. want dan moet ik ze altijd nog verder gaan specificeren.

![image](https://github.com/nl-digigo/NLCS/assets/144665595/915404e1-a541-4a43-a3a6-bac6f51d00ce)

Logische opties zouden m.i. zijn:
- Deze objecten onderbrengen onder alle daadwerkelijke banden, zodat de hulpstukken definieert staan bij de afmeting waar ze thuis horen.
- De 'detail' objecten geheel laten vervallen, gezien ze toch weinig zeggen in de huidige situatie.

INRITBAND is dan nog de engiste twijvelachtige, waarvan je kan zeggen dat je alle inritbanden daar onderbrengt, inplaats van onder de afmetingen... INRITBAND is in dat opzicht wel redelijk 'algemeen bekend'.

**Comment by ElisabethKloren** [comment]
De reviewperiode voor de expertcommissie van juni 2024 is afgelopen, dus ik wijzig de status naar vastgesteld,

**Comment by ElisabethDeVries** [comment]
[[Release note]] Alle speciale elementen van kantopsluitingen zoals hoekstuk, puntstuk zaten verzameld onder "KANTOPSLUITING_ELEMENT". Terwijl de meeste elementen tijdens het tekenen moeten aansluiten op de banden waar ze naast liggen, en ook de maatvoering van deze banden moeten hebben. Daarom worden deze elementen mét maatvoering toegevoegd bij de banden waar ze op aansluiten. De boomkrans met -band wordt een apart object.

**Comment by ElisabethDeVries** [comment]
zeer grote wijziging, gaat mee in 6.0

**Comment by SanderNijhof** [comment]
> De bovenste is onjuist en onbruikbaar, het hoekblok ondergebracht onder de admeting van de band is waar hij thuis hoort.

De bovenste regel is juist en uniform toepasbaar.

Deze voorgestelde wijziging leidt tot een forse uitbreiding van het aantal lagen, waarvan veel slechts in specifieke situaties gebruikt zullen worden. 
Ik vind het belangrijker om voor dit soort detailleringsvraagstukken een principieel standpunt in te nemen en te kiezen voor een uniforme oplossing via software, dan om steeds meer detaillering in de NLCS zelf op te nemen.

**Je kunt immers nooit alle mogelijke afmetingen, materialen, hulpstukken en andere details in de standaard onderbrengen.** De NLCS biedt hiervoor al een mechanisme: aanvullende details kunnen aan laagnamen worden toegevoegd en de formele beschrijving van de NLCS legt ook vast hoe dat moet gebeuren.
Idealiter kan met een softwareoplossing die detaillering op een uniforme manier worden toegevoegd waar daar behoefte aan is, zonder dat de standaard zelf telkens verder hoeft uit te breiden.
