### ISSUE TITLE
NLCS Verkeersborden: tabel en symbolen leveren voor advies Expertcommissie

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#443]
Beste Expertcommissie, de voorgenomen toevoeging van de verkeersborden staat hier: https://github.com/nl-digigo/NLCS/tree/main/ontwikkeling/verkeersborden

De levering van de bibliotheek met verkeersborden omvat de volgende documenten:
-	Zipfiles met de verkeersborden in AutoCAD formaat, gesplitst op status ivm omvang; 
-	NLCS-OBJECTEN-SVW-5.1.xlsx. Excel met een overzicht van de verkeersborden. Ik vermoed dat Semmtech dit zelf genereerd met het importeren van de symbolen in Laces; 
-	Objectentabel-VW-VerkeersmaatregelenWeg 5.1.xlsx. Excel met een overzicht van de laagnamen en bijbehorende filters op de symbolen bibliotheek;

**Comment by NielsNederpel** [comment]
de symbolen voor de rechthoekige zone borden hebben een grootte van circa 10x12 dit waarschijnlijk om met te T25 de juiste verhouding tussen maximum snelheid en het bord te laten overeenkomen met werkelijke afmetingen / verhouding van de verkeersborden.
echter worden symbolen in principe 1:1 opgebouwd (zie 3.5.6 bullet e in FB)
zodat deze dus ook in 1:1000 de schaal 1 hebben en kunnen worden verschaald (ivm -SO symbolen) met de schaalfactor.
echter is in de borden met tekst de schaal "M200" in de style opgenomen (NLCS-RVV-M200-T25) terwijl de teksthoogte wel 2.5 is. en deze combinatie dus eigenlijk nooit kan. aanpassen naar "M1000" of geheel achterwege laten? aangezien ook de overige teksten (bij o.a. zone borden) met style NLCS-RVV-M200-T25 aangegeven zijn, terwijl daarbij dan de teksthoogte niet overeenkomt met T25
in andere symbolen binnen de NLCS (verharding e.d.) wordt over het algemeen de "kale" style gebruikt. 
in het geval van de verkeersborden zou dat dan NLCS-RVV worden.

**Comment by ElisabethKloren** [comment]
In de reviewperiode van de EC in juni 2024 is hier geen commentaar op gekomen, issue kan volgens voorstel verwerkt worden

**Comment by FrankvdHeijden** [comment]
Schaal:
_De symbolen voor de rechthoekige zone borden hebben een grootte van circa 10x12 dit waarschijnlijk om met te T25 de juiste verhouding tussen maximum snelheid en het bord te laten overeenkomen met werkelijke afmetingen / verhouding van de verkeersborden.
Echter worden symbolen in principe 1:1 opgebouwd (zie 3.5.6 bullet e in FB) zodat deze dus ook in 1:1000 de schaal 1 hebben en kunnen worden verschaald (ivm -SO symbolen) met de schaalfactor._

**Antwoord**:
niet juist; voor schaalbare objecten gelden andere regels zoals ook wordt aangegeven bij punt a van de formele beschrijving (echter klopt hier de verwijzing in de formele beschrijving niet). 
SO symbolen kunnen niet 1:1 getekend worden omdat zij enkel een locatie presenteren en geen werkelijke afmetingen bevatten.
 
Tekststyle in borden
_Echter is in de borden met tekst de schaal "M200" in de style opgenomen (NLCS-RVV-M200-T25) terwijl de teksthoogte wel 2.5 is. en deze combinatie dus eigenlijk nooit kan.
Aangezien ook de overige teksten (bij o.a. zone borden) met style NLCS-RVV-M200-T25 aangegeven zijn, terwijl daarbij dan de teksthoogte niet overeenkomt met T25
In andere symbolen binnen de NLCS (verharding e.d.) wordt over het algemeen de "kale" style gebruikt. In het geval van de verkeersborden zou dat dan NLCS-RVV worden._
 
Vraag:
Aanpassen naar "M1000" of geheel achterwege laten?
 
**Antwoord:**
"kale style toepassen" zoals ook wordt beschreven in de Formele Beschrijving in plaats van aanduiding in style definitie
“NLCS-RVV” toepassen zonder aanduiding. Formele Beschrijving moet dit dan ook ondersteunen door middel van tekstuele beschrijving gelijk aan dat van “NLCS-ISO”

**Comment by ElisabethKloren** [comment]
nieuwe concept  https://github.com/nl-digigo/NLCS/tree/main/ontwikkeling/verkeersborden/v0.3

Wijzigingen die zijn doorgevoerd zijn: 

1.	Toevoegen symbool E08c
E08C voor de drie statussen *-SVW-VERKEERSTEKEN_BORD_E08C-SO
2.	Hernoemen E08 van cijfers naar letters
*-SVW-VERKEERSTEKEN_BORD_E08_01-SO	*-SVW-VERKEERSTEKEN_BORD_E08B-SO
*-SVW-VERKEERSTEKEN_BORD_E08_05-SO	*-SVW-VERKEERSTEKEN_BORD_E08A-SO
*-SVW-VERKEERSTEKEN_BORD_E08_02-SO	*-SVW-VERKEERSTEKEN_BORD_E08D-SO
*-SVW-VERKEERSTEKEN_BORD_E08_03-SO	*-SVW-VERKEERSTEKEN_BORD_E08E-SO
*-SVW-VERKEERSTEKEN_BORD_E08_04-SO	*-SVW-VERKEERSTEKEN_BORD_E08F-SO
*-SVW-VERKEERSTEKEN_BORD_E08_06-SO	*-SVW-VERKEERSTEKEN_BORD_E08G-SO
*-SVW-VERKEERSTEKEN_BORD_E08_07-SO	*-SVW-VERKEERSTEKEN_BORD_E08H-SO
*-SVW-VERKEERSTEKEN_BORD_E08_08-SO	*-SVW-VERKEERSTEKEN_BORD_E08I-SO
*-SVW-VERKEERSTEKEN_BORD_E08_09-SO	*-SVW-VERKEERSTEKEN_BORD_E08J-SO
*-SVW-VERKEERSTEKEN_BORD_E08_10-SO	*-SVW-VERKEERSTEKEN_BORD_E08K-SO
*-SVW-VERKEERSTEKEN_BORD_E08_11-SO	*-SVW-VERKEERSTEKEN_BORD_E08L-SO
*-SVW-VERKEERSTEKEN_BORD_E08_12-SO	*-SVW-VERKEERSTEKEN_BORD_E08M-SO
*-SVW-VERKEERSTEKEN_BORD_E08_13-SO	*-SVW-VERKEERSTEKEN_BORD_E08N-SO
*-SVW-VERKEERSTEKEN_BORD_E08_14-SO	*-SVW-VERKEERSTEKEN_BORD_E08O-SO
*-SVW-VERKEERSTEKEN_BORD_E08_15-SO	*-SVW-VERKEERSTEKEN_BORD_E08P-SO
*-SVW-VERKEERSTEKEN_BORD_E08_16-SO	*-SVW-VERKEERSTEKEN_BORD_E08Q-SO
*-SVW-VERKEERSTEKEN_BORD_E08_17-SO	*-SVW-VERKEERSTEKEN_BORD_E08R-SO
3.	Aanmaken attribuut symbolen vrije teksten
>> tag: textSigns (Locatie per bord verschillend)
Destijds hadden we daar de verkeersborden voor aangeleverd zonder nog naar het importeren / exporteren in george / de dataset van ndw te kijken. 
Ondertussen is duidelijk geworden dat om het goed werkend te kunnen krijgen er nog enkele attributen aan de symbolen bibliotheek toegevoegd moeten worden. 

*SVW-VERKEERSTEKEN_BORD_A01_100_S_TIJD-SO.dwg
*SVW-VERKEERSTEKEN_BORD_A01_120_S_TIJD-SO.dwg
*SVW-VERKEERSTEKEN_BORD_A01_130_S_TIJD-SO.dwg
*SVW-VERKEERSTEKEN_BORD_B06_F_OB401-SO.dwg
*SVW-VERKEERSTEKEN_BORD_B07_F_OB401-SO.dwg
*SVW-VERKEERSTEKEN_BORD_C17-SO.dwg
*SVW-VERKEERSTEKEN_BORD_C18-SO.dwg
*SVW-VERKEERSTEKEN_BORD_C19-SO.dwg
*SVW-VERKEERSTEKEN_BORD_C20-SO.dwg
*SVW-VERKEERSTEKEN_BORD_C21-SO.dwg
*SVW-VERKEERSTEKEN_BORD_E01_ZB_TIJD-SO.dwg
*SVW-VERKEERSTEKEN_BORD_E01_ZH_TIJD-SO.dwg
*SVW-VERKEERSTEKEN_BORD_E01_ZE_TIJD-SO.dwg
*SVW-VERKEERSTEKEN_BORD_E10_ZB-SO.dwg
*SVW-VERKEERSTEKEN_BORD_E10_ZH-SO.dwg
*SVW-VERKEERSTEKEN_BORD_E10_ZE-SO.dwg
*SVW-VERKEERSTEKEN_BORD_E10_ZB_KLEM-SO.dwg
*SVW-VERKEERSTEKEN_BORD_E10_ZH_KLEM-SO.dwg
*SVW-VERKEERSTEKEN_BORD_E10_ZE_KLEM-SO.dwg
*SVW-VERKEERSTEKEN_BORD_E10_ZB_SLEEP-SO.dwg
*SVW-VERKEERSTEKEN_BORD_E10_ZH_SLEEP-SO.dwg
*SVW-VERKEERSTEKEN_BORD_E10_ZE_SLEEP-SO.dwg
*SVW-VERKEERSTEKEN_BORD_E10-SO.dwg
*SVW-VERKEERSTEKEN_BORD_J06-SO.dwg
*SVW-VERKEERSTEKEN_BORD_J07-SO.dwg
*SVW-VERKEERSTEKEN_BORD_J20_F-SO.dwg
*SVW-VERKEERSTEKEN_BORD_L19_L-SO.dwg
*SVW-VERKEERSTEKEN_BORD_L19_R-SO.dwg
4.	borden E11 serie met ook attributen 
*-SVW-VERKEERSTEKEN_BORD_E11-SO
*-SVW-VERKEERSTEKEN_BORD_E11_ZE-SO
5.	Toevoegen algemene attribuut alle symbolen 
tag: ID
tag: PLACEMENT
visibility; not visible
Locatie: 0,0 BL en TL
6.	Aanpassen naamgeving N- naar Generiek

**Comment by ElisabethKloren** [comment]
verwerkt in concept-publicatie

**Comment by ElisabethDeVries** [comment]
[[Release note]] De NLCS bibliotheek is aangevuld met de meest voorkomende verkeersborden uit het [Reglement verkeersregels en verkeerstekens 1990 (RVV 1990)](https://wetten.overheid.nl/BWBR0004825), Categorie A t/m J.. In overleg met de Expertcommissie zijn daarbij de volgende spelregels gebruikt voor de symbolen. ,
1. Om de ketenuitwisseling van objectinformatie te kunnen ondersteunen naar bijvoorbeeld het George-dataportaal van het NDW zijn attribuutsymbolen toegevoegd voor vrije teksten met tag: textSigns (Locatie per bord verschillend). 
2. Ook zijn algemene attributen toegevoegd aan alle symbolen:
- tag: ID
- tag: PLACEMENT
- visibility; not visible
- Locatie: 0,0 BL en TL
3. Schaal en tekstgebruik zijn doorgevoerd conform de technische documentatie van de standaard met toepassen van de “kale” NLCS‑RVV tekststijl.
