### ISSUE TITLE
Aanvullende rioleringssymbolen

### ISSUE THREAD

**Issue by MvanderHulst** [nl-digigo/NLCS#446]
Graag zou ik nog een aantal aanvullende rioleringssymbolen willen toevoegen:

Ontstoppingsstuk
Controleput
Geleidebandkolk
Tegelpadkolk
Straatkolk_04 (met centraal insertionpoint)
Trottoirkolk_04 (met centraal insertionpoint)

Ronde putsymbolen voor alle soorten stelsels.

![image](https://github.com/nl-digigo/NLCS/assets/144665595/dfe58a18-636a-4a21-9c91-a0fd6e2d9680)

**Comment by ElisabethKloren** [comment]
dit lijkt me een no regret, ik heb het label voorgenomen wijziging toegevoegd en stel voor dat je deze direct verwerkt in de 5.1 set voor rioleringen

**Comment by ElisabethKloren** [comment]
In de reviewperiode van de EC in juni 2024 is hier geen commentaar op gekomen, issue kan volgens voorstel verwerkt worden

**Comment by NielsNederpel** [comment]
ik neem aan dat het inderdaad aanvullende ronde symbolen voor de putten zijn? maw de vierkanmt huidige symbolen blijven wel bestaan?

je wilt ook een antal nieuwe symbolen (o.a. tegelpadkolk) hier gaan dus ook objecten voor gemaakt worden neem ik aan?

**Comment by MvanderHulst** [comment]
@NielsNederpel 
Het betreffen aanvullingen inderdaad.
In de NLCS zitten dan symbolische weergaven voor ronde en vierkante putten, zodat je alle kanten op kan in de toepassing.

Voor de tegelpad en geleidebandkolken heb ik wat aanvullende goed identificeerbare symbolen opgesteld.

**Comment by NielsNederpel** [comment]
ja helemaal prima, maar die gaan dus wel aan het object tegelpadkolk en geleidebandkolk hangen? ofwel nieuwe objecten?
of wordt dit gezien als "straatkolk" en "trottoirkolk". want dan uiteraard rekening houden met de benaming van de symbolen zodat deze wél aan een object hangen.

**Comment by MvanderHulst** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mht/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mht/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


RI | - | HWA | _ | KOLK | _ | COMBIKOLK |   |   |   |   |   |   |   | - | G/S |   |   |   | SRI:SRI-KOLK_COMBINATIE
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
RI | - | HWA | _ | KOLK | _ | INFILTRATIE |   |   |   |   |   |   |   | - | G/S |   |   |   | SRI:SRI-KOLK_IFILTR
RI | - | HWA | _ | KOLK | _ | RWSKOLK |   |   |   |   |   |   |   | - | G/S |   |   |   | SRI:SRI-KOLK_RWS
RI | - | HWA | _ | KOLK | _ | GELEIDEKOLK |   |   |   |   |   |   |   | - | G/S |   |   |   | SRI:SRI-KOLK_GELEIDE
RI | - | HWA | _ | KOLK | _ | STRAATKOLK |   |   |   |   |   |   |   | - | G/S |   |   |   | SRI:SRI-KOLK_STRAAT
RI | - | HWA | _ | KOLK | _ | TEGELPADKOLK |   |   |   |   |   |   |   | - | G/S |   |   |   | SRI:SRI-KOLK_TEGELPAD
RI | - | HWA | _ | KOLK | _ | TROTTOIRKOLK |   |   |   |   |   |   |   | - | G/S |   |   |   | SRI:SRI-KOLK_TROTTOIR



</body>

</html>

**Comment by NielsNederpel** [comment]
@MvanderHulst ik loop nu zelf tegen een puntje aan en vraag me af of dit in 5.1 meegenomen is.
onder veel subobjecten (OVERSTORTPUT/POMPPUT etc) onder het object RIOOLPUT hangen de subobjecten _BETON en _PE.
Aan deze subobjecten hangen dan geen symbolen. 
zijn in jouw toevoeging deze symbolen wel meegenomen?

want voor het mooie zouden we dus van dit soort putten 2 verschillende symbolen moeten hebben zoals we eigenlijk ook bij het object RIOOLPUT is geregeld. ofwel 1 symbool voor RIOOLPUT en 1 voor RIOOLPUT_BETON en 1 voor RIOOLPUT_KUNSTSTOF (zie groene regels)

zie in ieder geval de rode regels die dan een symbool voor dit type put zouden moeten hebben en dan de oranje waarbij er dan 2 onderscheidende symbolen zouden moeten toegevoegd

misschien kan hier ook het principe van vierkant voor beton en rond voor kunststof/PE worden aangehouden? 

![image](https://github.com/user-attachments/assets/fe8d4292-b787-43e1-8aea-b4f32c20b238)

**Comment by MvanderHulst** [comment]
@NielsNederpel Er is voor 5.1 een behoorlijke opschoning gedaan in de vele tegenstrijdigheden binnen RI.
Inhoudelijk met beton/kunststof zit echt nog wel ruimte voor verbetering, maar ik heb eerst de basis weer even goed gemaakt.
Het maten van onderscheid per materiaal zou ik graag in 6.0 kwa visuele presentatie nog eens naar willen kijken.

Ik heb de 5.1 versie even bekeken, maar daar zit de logica niet in de database. 
Met de InfraCAD logica worden de symbolen echter wel op de juiste plek gepresenteerd, zoals jij nu eigenschijk schetst.

**Comment by NielsNederpel** [comment]
ok thanks! ik wacht het even af en anders kunnen we e.e.a. mooi voor 6.0 op de rol zetten

**Comment by ElisabethDeVries** [comment]
[[Release note]] Er is een uitbreiding gedaan op de symbolen voor putten en kolken, met ronde putsymbolen voor alle stelsels naast de bestaande vierkante putten; daarnaast ook extra ontstoppingsstuk, uitstroombak, uitstroomvoorziening en hulpstukken.
