### ISSUE TITLE
#890	SAL-VERWIJZING_WIJZIGING_RECHTS-SO en SAL-VERWIJZING_WIJZIGING_LINKS-SO zijn niet goed zichtbaar.

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#45]
#890	SAL-VERWIJZING_WIJZIGING_RECHTS-SO en SAL-VERWIJZING_WIJZIGING_LINKS-SO zijn niet goed zichtbaar. Kan hier of een grijze vlakvulling of een “wipeout” worden toegevoegd?

**Comment by ElisabethKloren** [comment]
To Do
symbool aanpssen met vlakvulling

**Comment by MvanderHulst** [comment]
Voorstel:
![image](https://github.com/nl-digigo/NLCS/assets/144665595/03e268e7-56ba-46b2-a396-e9cf2c55b0e3)
Background color 254, net als de verhardingen.

**Comment by ElisabethDeVries** [comment]
[[Release note]] In de hoofdgroep AL zijn de symbolen SAL-VERWIJZING aangepast met een grijze vlakvulling om de symbolen beter zichtbaar te maken.

**Comment by ElisabethDeVries** [comment]
reopen voor acceptatie 5.2
