### ISSUE TITLE
verhardingssymbolen bevatten soms een vulling, is dit bewust of een fout in het betreffende symbool. 

### ISSUE THREAD

**Issue by DerkNouwensTPG** [nl-digigo/NLCS#454]
Een klant vermeldde dat een verhardingssymbool een vulling bevat, bv. **SVH-TEGEL_300X33--_DIK_BLOK-SO.dwg**.

![image](https://github.com/nl-digigo/NLCS/assets/174787413/b2bc3d9d-0faf-449f-a9ce-5382881b763f)

Is dit een bewuste keuze of een fout in het betreffende symbool.
Voor hoeveel symbolen dit voorkomt hebben we niet onderzocht.

**Comment by MvanderHulst** [comment]
@DerkNouwensTPG er zijn inderdaad een aantal verhardingssymbolen waar dit voorkomt.
Voornamelijk de betontegelsymbolen om visueel verschil tussen dunne en dikke tegels te kunnen maken.
