### ISSUE TITLE
Check: de aanduiding van t ELEMENT G - S - A in de database is overbodig, want is al duidelijk doordat er een symbool of arcering beschikbaar is

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#455]
Dubbelcheck naar aanleiding van issue #236 

De aanduiding A of S is niet meer dan een aanduiding, dat NLCS voor het objecttype een arcering of symbool beschikbaar is
Als een gebruiker zelf een arcering of symbool toevoegt dan moet alleen het element in de laagnaam correct worden ingevuld met S of A. 

Kan ik dus inderdaad de aanduiding van ELEMENT volledig weghalen uit de database?

Graag reactie van de experts voor ik dit uitvoer.

**Comment by ElisabethKloren** [comment]
Beste Expertcommissie NLCS,

In de issues van 5.1 zitten een paar, die impact hebben op software implementatie of controle tooling. Dat zijn de issues waarvan ik graag zou willen, dat jullie die met extra aandacht reviewen. Ik weet dat de officiële reviewperiode van juni al voorbij is…. Maar denk dat het belangrijk is om voor deze meer tijd te geven, terwijl we al aan de slag zijn met de kleine verbeteringen. 

Ik zou jullie willen vragen om deze issues voor 1 september te reviewen en daarbij duidelijk aan te geven of het voorstel moet worden aangepast of uitgesteld naar een volgende release als deze te veel impact heeft.

**Comment by MvanderHulst** [comment]
Vanuit de gebruiker heeft deze kolom inderdaad geen toegevoegde waarde.
Kolom' symboolbibliktheen' en 'arceringbibliotheek' zijn hierbij veel belangrijker. :-)

**Comment by NielsNederpel** [comment]
dat idee heb ik inderdaad ook...
ik verwacht ook voor de leveranciers het geval is, maar ben daar uiteraard niet zeker van. 

wat de toegevoegde waarde van deze kolom is weet ik niet helemaal, maar in theorie het zou kunnen dat de leveranciers hier nu als zou je eerder kunnen zeggen standaard is het -G en indien kolom Symboolbibliotheek en/of arceringsbibliotheek een waarde heeft zijn ook -S en -A "toegestaan" ik verwacht dus ook dat we de kolom niet nodig hebben, want het wordt al nu zou er in theorie alleen maar verwarring /foutje in kunnen ontstaan door dat er géén bibliotheek aan hangt maar wél
tenzij we er ooit voor gekozen hebben om geen bibliotheek aan te leveren, maar wel de element kolom te vullen met een A/S.
Misschien sluiten dan hier de onderstaande issues wel op aan.  
#378 
#470
in mijn idee moeten hier echt de leveranciers iets van vinden.

**Comment by ElisabethKloren** [comment]
nee, de leveranciers moeten alleen weten of ze in de controletool een foutmelding moeten geven, als er geen A of S gedefinieerd is, en er wel een laag met A of S is. Of als er geen G staat, mag je het object dan niet als G tekenen? Wat hebben we met z'n allen bedoeld in de standaard?

Dus graag uitspraak van de experts of de kolom leidt tot een extra eis aan de controletool, of niet > wil ik dit graag verwijderen gezien het feit dat je dit ook de de relaties uit de database kunt halen. is dus dubbel werk en daarmee ook foutgevoelig.

**Comment by MvanderHulst** [comment]
In de database staan kollom Y en Z, zijnde ARCERING SYMBOOL
Als deze ingevuld staan, zijn er vanuit de NLCS symbolen en arceringen aangeleverd.
Kolom 'ELEMENT' is m.i. dan overbodig omdat je uiteindelijk toch alles op het object mag plaatsen.

**Comment by ElisabethKloren** [comment]
zo heb ik het inderdaad ook in andere issues gezien, bij deze besluit ik het veld ELEMENT niet meer te publiceren.

**Comment by NielsNederpel** [comment]
aha ok...op controle gebied vlak dan even deze:

Er wordt inderdaad wel een melding gegeven van object X is aanwezig in NLCS bibliotheek, maar niet van toepassing van elementcode -S bijvoorbeeld. zie voorbeeld hieronder vanuit InfraCAD

wat ook logisch is aangezien dit altijd een eis is geweest aan de controle (zie hieronder)

echter hoe deze controle plaats vindt is mij niet bekend en zoals aangegeven kan deze info ook uit de andere kolom worden gedistilleerd (als dat dus al niet gedaan wordt.)
in die zin zal er geen bloed uit vloeien om de kolom element te verwijderen lijkt me.

echter hoe deze controle plaats vindt is mij niet bekend en zoals aangegeven kan deze info ook uit de andere kolom worden gedistilleerd (als dat dus al niet gedaan wordt.)
in die zin zal er geen bloed uit vloeien om de kolom element te verwijderen lijkt me.

maar dan
In die zin geen éxtra eis, maar iets wat altijd zo geweest is...
is de vraag nu ook of je die onderstaande eis wil loslaten?
of alleen de kolom element wil verwijderen?
want in het laatste geval is dat geen bezwaar om toch nog de eis te laten staan in mijn idee.

![image](https://github.com/user-attachments/assets/f48be327-100e-4ffa-a93f-e88d19ed1bca)

![image](https://github.com/user-attachments/assets/0d7793c2-448c-443c-a36f-1fc81ce3821a)

**Comment by MvanderHulst** [comment]
De controle moet wel blijven naar mijn idee, maar kan inderdaad op basis van de aanwezigheid van de kolom voor de arceringen en symbolen bibliotheek worden getoets. Gevoelsmatig is de extra 'element' kolom een dubbeling met kans op fouten en discrepanties, zoals we eigenlijk nu ook zien gebeuren.

Ik vraag mij wel af of de bovenstaande aangegeven controle regel niet anders bedoeld is.
Controleer deze niet gewoon of lijnen op G staan en symbolen op S enzo?
Om te voorkomen dat lijnen op symboollagen staan e.d.?
Er staat op in de tabel 'Niet in database', dus is dit geen controle in de tekening zelf?

**Comment by NielsNederpel** [comment]
> De controle moet wel blijven naar mijn idee, maar kan inderdaad op basis van de aanwezigheid van de kolom voor de arceringen en symbolen bibliotheek worden getoets. Gevoelsmatig is de extra 'element' kolom een dubbeling met kans op fouten en discrepanties, zoals we eigenlijk nu ook zien gebeuren.

helemaal eens

> Ik vraag mij wel af of de bovenstaande aangegeven controle regel niet anders bedoeld is.
Controleer deze niet gewoon of lijnen op G staan en symbolen op S enzo?
Om te voorkomen dat lijnen op symboollagen staan e.d.?
Er staat op in de tabel 'Niet in database', dus is dit geen controle in de tekening zelf?

hmmm tja dat zou kunnen. maar doet dat eigenlijk ook 2e dit niet al? want daar checkt hij ook de laag voor symbolen/arceringen.

De toevoeging in database snap ik sowieso niet helemaal...het gaat sowieso toch om een controle "in" de tekening. de kop is tenslotte "checklist controle tooling NLCS **tekeningen**"
geeft die kolom niet aan wáár de zaken, waarop gecontroleerd moet worden, gevonden kunnen worden?
waarbij we dus eigenlijk keus hebben uit in de database en in de formele beschrijving?

**Comment by ElisabethKloren** [comment]
Ja, de eis blijft staan, uiteraard moet een su7ymbool op een S-laag staan, het gaat erom dat in de database niet meer wordt aangeduid of er bij het object een S of A aanwezig is - dat weet je al doordat er een relatie gemaakt wordt. 

De interpretatie is: als er G staat, is dat geen verbod op het gebruiken van een symbool, ook al is dat symbool niet opgenomen in NLCS.
