### ISSUE TITLE
#888	Bij het symbool SIE-FIETSENKLUIS-SO vraag ik af of het symbool wel -SO moet zijn. 

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#46]
#888	Bij het symbool SIE-FIETSENKLUIS-SO vraag ik af of het symbool wel -SO moet zijn. Dit ligt er uiteraard aan waarvoor het symbool gebuikt wordt. Indien het slechts een symbool is of dat er de daadwerkelijke afmetingen mee benaderd willen worden. bij het toepassen van het symbool op werkelijke afmetingen is vaak van belang naar welke zijde de kluis open gaat. Kan het symbool worden aangepast of kan er een “niet -SO symbool” worden toegevoegd waarbij duidelijk is aan welke zijde de kluis open gaat? Daarnaast is een kluis in mijn idee een “fietskast” voor slechts 1 fiets. Al worden er dan vaak meerdere kluizen geschakeld om meer fietsen kwijt te kunnen, maar iedere kluis heeft een eigen ‘deur’. Binnen de bibliotheek ontbreekt echter wel een symbool voor een zogenaamde “fietstrommel”. In een fietstrommel passen 4 fietsen en is dus echt een ander object en zal dus derhalve een ander symbool moeten hebben. Er is een symbool SIE-FIETSTROMMEL naar Corné Helmons gestuurd. De fietstrommel is gebaseerd op de afmetingen van 2,30 bij 1,83

**Comment by ElisabethKloren** [comment]
Reactie Expertcommissie
genereik symbool voor fietstrommel (-SO) toeveogen gaan geen bibliotheken bijhouden van allee verschillende afmetingen

**Comment by ElisabethKloren** [comment]
To Do
symbool fietstrommel maken en toeveogen aan database

**Comment by MvanderHulst** [comment]
-SO is 'positieaanduiding' maar geen ware afmeting. Ware afmeting zo min mogelijk aanbieden. Zeker niet voor meubilair

**Comment by MvanderHulst** [comment]
Symbool voor een fietstrommel:
SIE-WEG_FIETSTROMMEL-SO

Aanvullend:
SIE-FIETSENKLUIS-SO hernoemen naar SIE-WEG_FIETSKLUIS-SO
SIE-WEG_FIETSREK-SO hernoemen naar SIE-WEG_FIETSENREK-SO
SIE-WEG_FIETSENREK-SO hernoemen naar SIE-WEG_FIETSKLEM-SO


![image](https://github.com/nl-digigo/NLCS/assets/144665595/f85267ee-68bd-4bbd-b944-688b863c509e)

**Comment by ElisabethDeVries** [comment]
[[Release note]] In hoofdgroep IE (InrichtingsElementen) is gekeken naar de verschillende soorten objecten voor het stallen van fietsen, met bijbehorende symbolen. In NLCS 6.0 zal in het kader van vereenvoudiging de aanduiding 'WEGMEUBILAIR" worden weggelaten, daarom zijn de bestaande objecten in versie 5.2 ook vervallen en vervangen door nieuwe:
Vervallen objecten: MEUBILAIR_WEGMEUBILAIR_FIETSENREK; FIETSENKLUIS
Nieuwe objecten: MEUBILAIR_FIETSENREK; MEUBILAIR_FIETSKLEM; MEUBILAIR_FIETSKLUIS; MEUBILAIR_FIETSNIET; MEUBILAIR_FIETSTROMMEL
