### ISSUE TITLE
Discrepantie in NLCS 5.0 documentatie over symbolen

### ISSUE THREAD

**Issue by DerkNouwensTPG** [nl-digigo/NLCS#462]
Wellicht al gemeld maar we hebben een verschil ontdekt tussen de weergave van symbolen in tabel en tekst zie bijlage (specifiek doorsnede symbolen). Eerste deel in tekst betreft een bug in onze eigen software en kan je negeren.
We houden nu de tabel aan. Maar weten niet wat de wens in deze is. Graag uniform opnemen in de formele beschrijving en graag terugkoppeling wat beoogd wordt.

[nlcs50_symbool_discrepantie.docx](https://github.com/user-attachments/files/16246858/nlcs50_symbool_discrepantie.docx)

**Comment by ElisabethKloren** [comment]
Bedankt voor je melding. Dit wordt inderdaad opgepakt in issue #122 , maar ik ga specifiek ook nog even deze foutmelding bekijken om te controleren of het nu goed is opgelost.

**Comment by ElisabethKloren** [comment]
mmm, na enig uitzoekwerk, er is nu maar één plek waar de representatie word bijgehouden en dat is het [overzicht representatie](https://nl-digigo.github.io/NLCS/requirementscadmodels/#overzicht-representatie)

Voor het element GD ben ik gecorrigeerd dat dit dezelfde lijndikte krijgt als G, niet dikker; dan is het logisch als dat ook zo is voor SD. Dus: lijndikte van objectentabellen voor G ook aanhouden voor GD

**Comment by DerkNouwensTPG** [comment]
Hoi Elisabeth,

Bij de nlcs-documentatie.nl worden alle elementtypen weergegeven.

Ik denk dat het handig is als de verwijzing hier ook t.z.t. wordt aangepast, als deze ingang behouden blijft.

Daarnaast is het praktisch dat bv bij GV ipv color ook color G worden genoemd. En dit ook voor de lijnstijl geldt. Dus ipv linetype, linetype G

Dit gaat in bij NLCS 5.1 neem ik aan. Want NLCS 5.0 is al gepubliceerd.


Met vriendelijke groet,

Derk Nouwens
Consultant

The People Group | Driven by technology Created by people

Middelweg 2 | 5253 CA NIEUWKUIJK | Nederland

T +31(0)85 224 00 00<tel:+310852240000> M +31(0)6 54 93 72 54<tel:+310654937254>

https://www.thepeoplegroup.nl/e-mail-disclaimer/

________________________________

**Comment by ElisabethKloren** [comment]
Hoi Derk, in de database en de documentatie heten de kolommen B color, B color A enzovoorts (en dat voor alle statussen). Er staat dus niet bij dat dit alleen bedoeld is voor G. Daarom gebruik ik in de tabel in de documentatie ook deze termen dus [status] lineweight  dat betekent: B lineweigt of N lineweight of... toepassen

Of snap ik nu niet goed wat je bedoelt?

**Comment by DerkNouwensTPG** [comment]
Hoi Elisabeth,

Volgens is er geen officiële kolom voor bv GV. Althans die hebben wij niet in de database van Optimize. Ik verwacht dat deze dus nooit via SQL scripts zijn aangeleverd. Ik zal dat kortsluiten met ons ontwikkelteam. Echter zitten we nu in de vakantie periode dus dat zal nog ca 3 weken duren voordat ik hier helderheid overheb. Ik zal eens kijken wat we normaal gebruiken misschien kan ik iets terugvinden. Maar goed er mag geen twijfel over bestaan wat toegepast moet worden. En daar liepen we met de vorige versies wel tegenaan.


Met vriendelijke groet,

Derk Nouwens
Consultant

The People Group | Driven by technology Created by people

Middelweg 2 | 5253 CA NIEUWKUIJK | Nederland

T +31(0)85 224 00 00<tel:+310852240000> M +31(0)6 54 93 72 54<tel:+310654937254>

https://www.thepeoplegroup.nl/e-mail-disclaimer/

________________________________

**Comment by ElisabethKloren** [comment]
Het klopt wat je zegt, er is geen kolom voor GV in de database, strikt gesproken is er ook geen kolom voor G, er wordt alleen generiek een kleur gegeven (kl_b, kl_n enzovoorts), deze is zowel van toepassing op G als op andere elementen volgens die tabel in de documentatie

**Comment by DerkNouwensTPG** [comment]
HoI Elisabeth,

Waar ik op doel is dat inderdaad de algemene kolom wordt toegepast dus bestaand dan B color etc, je ziet echter dat bv voor bv B color GV er geen kolom is. Wij hebben derhalve in onze versies ten onrechte de B color V gebruikt, in een komende release lossen we dat op en kijken we naar de G object tabelkolommen dus B color , N Color etc. Maar het is handig als je dan in de tabel benoemt dat color gelijk is aan objecttabellen G om discussie te voorkomen.
***@***.***

***@***.***

Met vriendelijke groet,

Derk Nouwens
Consultant
***@***.***<http://www.thepeoplegroup.nl/>

The People Group | Driven by technology Created by people
Middelweg 2 | 5253 CA  NIEUWKUIJK | Nederland
M +31 6 54 93 72 54 | T +31 85 224 00 00
E ***@***.*** | www.thepeoplegroup.nl<http://www.thepeoplegroup.nl/>

[Twitter]<http://www.twitter.com/peoplegroupnl>

[LinkedIn]<https://www.linkedin.com/company/thepeoplegroupnl/>

[Facebook]<https://www.facebook.com/peoplegroupnl/>

[YouTube]<https://www.youtube.com/channel/UCZhyfigEpBc5ZtYN3SgCr0Q/>

***@***.***<https://www.thepeoplegroup.nl/stay-healthy-connected-and-positive/>
E-mail disclaimer<https://www.thepeoplegroup.nl/e-mail-disclaimer/>

Van: Elisabeth de Vries ***@***.***>
Verzonden: vrijdag 2 augustus 2024 10:07
Aan: nl-digigo/NLCS ***@***.***>
CC: Derk Nouwens | The People Group ***@***.***>; Author ***@***.***>
Onderwerp: Re: [nl-digigo/NLCS] Discrepantie in NLCS 5.0 documentatie over symbolen (Issue #462)


Het klopt wat je zegt, er is geen kolom voor GV in de database, strikt gesproken is er ook geen kolom voor G, er wordt alleen generiek een kleur gegeven (kl_b, kl_n enzovoorts), deze is zowel van toepassing op G als op andere elementen volgens die tabel in de documentatie

**Comment by ElisabethKloren** [comment]
Ik snap het, ik zal het erbij zetten om te zorgen dat er inderdaad geen misverstanden over bestaan
