### ISSUE TITLE
informatie- en verkeersborden: staan nu zowel bord in IE, VW en VV

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#464]
Vraag: horen borden wel thuis in inrichtingselementen IE? 

Soorten borden (symbolen) in IE: 

|   |   |   |  
-- | -- | -- | -- | --
DSI |   |   |   |  
INFORMATIE |   |   |  
LOCATIEPAAL |   |   |  
PLAATSNAAMBORD |   |  
RECLAME |   |   |  
SCHEEPVAARTVERKEER |   |  
STRAATNAAMBORD |   |  
STRAATNAAMBORD | _ | MODEL |   |  
STRAATNAAMBORD | _ | MODEL | _ | PAAL
VERKEERSBORD |   |   |  
VERKEERSBORD | _ | MODEL |   |  
VERKEERSBORD | _ | MODEL | _ | PAAL
WAARSCHUWINGSHEK |   |  
WEGWIJZER |   |   |  

Bij verkeersmaatregelen weg VW en Verkeersmaatregelen Vaarweg VV staan in elk geval ook  Bewegwijzering en Verkeersteken

**Comment by MvanderHulst** [comment]
Jazeker, deze zijn in de 4.2 versie toegevoegd voor de BGT mapping.
Hier zijn ENORME discussies over (destijds) met Wouter en Corné over geweest.

Vanuit 'Engineering' en de 'RAW systematiek' zijn palen, borden en hekwerken 'inrichtingslementen' / terreininrichting.
Mijn definitie hiervan is dan ook: alles waar je tegen aan kan rijden en meestal van staal is een inrichtingselement'.

De hoofdgroep 'VW' vindt ik persoonlijk dan ook totaal onnodig dat deze bestaat. Origineel heette deze 'Verkeerskunde Wegen', waar wegmarkeringen en borden op te vinden waren. Omdat een 'wegbeheerder' dit in beheer heeft...
Maar... maken we hoofdgroepen per soort beheerder, of vanuit de 'techniek' met de visie richting RAW?
Vanuit die discussie is VW omgedoopt tot 'Verkeersmaatregelen', wat ik nogsteeds een wollen-sokken term vindt.

Waarom vindt ik ALLE verhardingsmaterialen onder de hoofdgroep Verhardingen (VH), behalve de klinker voor een parkeervak markering. Deze staat onder VW, omdat markeringen daar staan.
Idem voor asfalt... alles wat met asfalt te maken heeft staat onder VH, behalve de stepen op de weg.
Een 'Verkeerskunde Wegen' kan je niet aanschaffen. Een 'Verharding' en 'Inrichtingselement' wel.

Kort antwoord:
Ja, ZEER graag de borden in IE houden en de aanwezigheid van VW en VV heroverwegen.

**Comment by ElisabethKloren** [comment]
dit vind ik moeilijk want inrichting is wel een heel brede categorie zie mijn andere blonde vragen in nieuwe issue\

en nu we veel soorten verkeersborden gaan ondersteunen en wellicht ook willen relateren aan een wegennetwerk met knopen en lijnen ipv de fysieke verharding zou de categorie vw gebruikt kunnen worden voor een heel ander soort tekeningen... food for thought

**Comment by ElisabethKloren** [comment]
in IE zijn indicatieve symbolen op basis van de topografie

in VW, VV zijn heel specialistische symbolen voor de verkeerskundigen

**Comment by MvanderHulst** [comment]
Dit is inderdaad wel het huidige uitgangspunt.
Ik ben benieuwd naar de ontwikkeling zoals hierboven beschreven. Anders vind ik een bord een bord. Er zit geen inhoudelijke techniek in zoals bij OVL en VRI wel het geval is.
Voor borden zie ik de toegevoegde waarde voor 'verkeerskundige' niet, behalve dat het 'lekker makkelijk' is voor zijn functie.

**Comment by ElisabethKloren** [comment]
er wordt nu een bordenbiblioitheek opgenomen met de inhoud van de borden, daarom is het wel logisch om dit in een specialistischer hoofdgroep op te nemen. Ik heb een toelichting op de hoofdgroep ie opgenomen in de [Uitleg standaard](https://nl-digigo.github.io/NLCS/functionalspecification): De uitleg van de standaard met daarin de toelichting op het beoogd doel en de werking van de standaard

**Comment by ElisabethDeVries** [comment]
Heroverweging voor vereenvoudiging van de standaard, deze issue wordt verwerkt in de 6.0 waarbij we met de expertcommissie de vraag: welke vereenvoudiging is wenselijk? willen we objecten dubbel hebben in verschillende hoofdgroepen omdat deze een andere functie dienen, bijvoorbeeld IE is bedoeld om alle dingen die in de weg staan van een ruimtelijk ontwerp te kunnen tonen op tekening, of om de bestaande BGT kaart als achtergrond te kunnen inladen, maar niet voor ontwerp,  VW om verkeerskundige ontwerpen te maken? food for thought
