### ISSUE TITLE
Inrichtingselementen IE uitbreiding vervallen symbolen logischer inrichting objectenboom

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#465]
Inrichtingselementen IE uitbreiding vervallen symbolen logischer inrichting objectenboom

rare rare categorie 

Eén gekke product manager kan meer vragen dan alle experts kunnen beantwoorden

* is het onderscheid weg en water niet erg handig voor de ontwerper, qua keuze meubilair?
* woord meubilair is nu wel erg breed, zijn palen lpg vulpunten kasten meubilair? waarom niet een groep hoger zonder het woord meubilair, meubilair echt houden voor verbliijfselementen zoals bankjes, afvalbakken ed?
* is een sensor meubilair? of moeten dat monitoringselement oid zijn samen met camera's
* waarom het woord constructieve afscheiding gebruiken, kan deze groep een kortere laagnaam krijgen door deze term etussenuit te halen: 		SIE	-	CONSTRUCTIEVE AFSCHEIDINGEN	_	HEKWERK	_	DOORGANG	_	DRAAIPOORT
* andere issue gaat al over verkeersborden
* zijn debietmeter en waterstandmeter sensoren? 
* zijn meerpaal en merkpaal palen? Waarom niet? 
* is een camera meubilair > zelfde soort vraag als bij sensor
* waarom de palen niet als onderdeel van het object waar ze bij horen, maar apart?
* putten, ook heel gek, een rioolput is geen onderdeel riolering? gasput, is iets heel anders? 
* slagboom, is meer een verkeersmaatregel weg dan een meubilair, toch? 
* boomrooster, is meer onderdeel van verharding ?
* et cetera et cetera

Uitleg nodig van logica hoofdcategoriën

**Comment by ElisabethKloren** [comment]
wellicht beschrijven hoe de hudige inrichting bepaald is, is de RAW logica leidend?

**Comment by ElisabethKloren** [comment]
term meubilair wordt ertussen gezet, om alle objecten op één laag te kunnen zetten om aan- en uit te kunnen zetten in je tekening; de inrichtingselementen zijn eigenlijk "achtergrondruis" voor de tekenaar

ondergrond = topografie
inrichtingselementen = wat daar bovenop staat

**Comment by ElisabethDeVries** [comment]
[[Release note]] Toelichting over IE opgenomen in de [functionele beschrijving](https://nl-digigo.github.io/NLCS/functionalspecification/5-2/):

De hoofdgroep inrichtingselementen is een vergaarbak van allerlei objecten die in de openbare ruimte voorkomen: prullenbakken en bankjes, maar ook putdeksels, boomroosters en lpg vulpunten. 
Deze hoofdgroep bestaat vooral, om in tekeningen ten behoeve van een specialisme zoals verhardingen of rioleringen, ook de "in de weg staande objecten" te kunnen weergeven en in een keer uit of aan te kunnen zetten tijdens het tekenen.

Daarnaast wordt de hoofdgroep inrichtingselementen gebruikt om objecten uit de BGT in een CAD tekening te plaatsen. Het betreft dan deze objecten in een zeer abstracte, eenvoudige weergave zoals op een kaart. De specialistische uitwerking naar types staat in andere hoofdgroepen; bijvoorbeeld er komt één put voor in inrichtingselementen, voor de BGT. De typen rioolputten zoals een ontwerper en beheerder nodig heeft staan in de hoofdgroep rioleringen.
