### ISSUE TITLE
kasten k&l in hoofdgroep inrichtingselementen, behalve pollerkast??

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#466]
rare gewaarwording, het hele netwerk in een hoofdgroep maar de kasten bij inrichting. Snap het wel ergens, maar??? dan moet de pollerkast ook bij de inrichting, of bij VW ;-)

hier zie ik wel reden om de functie in één hoofdgroep te doen en de kasten dus wel onder de netten te plaatsen?

**Comment by MvanderHulst** [comment]
Ik weet dat ik hier koppig in ben, als ik alle lagen van de ONDERGRONDSE hoofdgroep kabels en leidingen uitzet. Dan verwacht ik dat de bovengrondse informatie zichtbaar blijft, wat de belemmeringen in het maaiveld zijn.
Als de kasten standaard als KL worden gedefineerd, gaan ze gegarandeerd gemist worden.
Het is niet logisch om bovengrondse inrichtingselementen in een ondergrondse hoofdgroep onder te brengen.
Dat het voor een beheerder lekker makkelijk is, dat snap ik dan weer wel.

**Comment by ElisabethKloren** [comment]
akkoord, dan verplaats ik de pollerkast ook naar de inrichtingselementen

**Comment by ElisabethKloren** [comment]
onduidelijkheid is opgelost: ook de kasten staan dubbel in zowel de inrichtingselementen als bij de specifieke hoofdgroepen zoals k7l; de poller en kast heb ik verplaatst van k&l naar VW omdat een poller toch echt bij het verkeerskundige ontwerp van de weg hoort

**Comment by ElisabethDeVries** [comment]
[[Release note]] Ten behoeve van ruimtelijke ontwerpen is het object MEUBILAIR_KAST toegevoegd aan hoofdgroep IE; deze algemene kast is bedoeld voor weergave van bestaande kasten in de openbare ruimte voor integrale ontwerpen. Specifieke kasten zoals POLLERKAST blijven staan in de domein specifieke hoofdgroepen.

**Comment by ElisabethDeVries** [comment]
issue #869 is voor herbeoordeling van resterende issues uit https://github.com/nl-digigo/NLCS/issues/466 voor NLCS 6.0
