### ISSUE TITLE
Waarom in KG KADASTRAAL_BEBOUWING en in OG ook een object KADASTRAAL? Wat is het verschil?

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#467]
Waarom in KG KADASTRAAL_BEBOUWING en in OG ook een object KADASTRAAL? Wat is het verschil?

**Comment by MvanderHulst** [comment]
Terechte vraag, volgens mij kan de OG-KADASTRAAL komen te vervelen.

**Comment by ElisabethKloren** [comment]
akkoord, ik heb het verwerkt

**Comment by ElisabethDeVries** [comment]
[[Release note]] Het object OG-KADASTRAAL komt te vervallen, deze is dubbel met het object KG-KADASTRAAL_BEBOUWING
