### ISSUE TITLE
Heeft iemand het fontstijl NLCS-RVV.ttf?

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#469]
Dit staan in de documentatie maar ik kan het niet vinden: Andere fontstijlen mogen alleen worden toegepast in situaties waar geen sprake is van bijschriften van technische aard. Denk bijvoorbeeld aan tekeninghoofden en presentatietekeningen of aan teksten binnen een model, zoals teksten op ANWB-borden. Voor teksten en cijfers op de RVV verkeersborden is de fontstijl NLCS-RVV beschikbaar (bestand NLCS-RVV.ttf).

**Comment by MvanderHulst** [comment]
Zie mail.

**Comment by ElisabethKloren** [comment]
Top, bedankt. Is nu beschikbaar bij de actuele font-bestanden

**Comment by ElisabethDeVries** [comment]
[[Release note]] Voor teksten en cijfers op de RVV verkeersborden is de fontstijl NLCS-RVV toegevoegd (bestand NLCS-RVV.ttf).
