### ISSUE TITLE
#887	Verwijzing naar een doorsnede moet volgens formele beschrijving een lijndikte van 0.18 mm hebben

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#47]
#887	Verwijzing naar een doorsnede moet volgens formele beschrijving een lijndikte van 0.18 mm hebben. dit is echter erg dun en valt bijna weg in een tekening Kan dit dikker worden? overige verwijzingen hebben allemaal en lijndikte van 0.35

**Comment by ElisabethKloren** [comment]
To Do
aanpassen naar 0.35 in FB en Objectentabellen

**Comment by MvanderHulst** [comment]
4.4.2.a aanpassen
Een verwijzing naar een doorsnede wordt aangeven met een doorsnedensymbool. Dit bestaat uit een lijn van het type "gemengde streeplijn" met een lijndikte van 0.35 mm. Haaks op de lijn staan pijlen, die de kijkrichting aangeven. De pijlen zijn voorzien van een letter die de doorsnede specificeert. De (geplotte) teksthoogte is 5.0 mm.

en in de database nalopen.
