### ISSUE TITLE
Moeten de arceringsbibliotheken overeenkomen met de hoofdgroepen?

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#470]
zie #378; moet dit ook voor arceringsbibliotheken? En voor lijnenbibliotheken?

 de arceringsbibliotheek ACO bestaat (constructies), met links naar objecten in verschillende hoofdgroepen.

**Comment by MvanderHulst** [comment]
Ik zou dit inderdaad éénduidig aanbieden.
Als ze leeg zijn worden ze in de software niet getoont, maar voor het overzich goed om volledig te houden.

Gevallen als RO, dat hoofdgroepen achterblijven die niet bestaand zijn hiermee makkelijk in de database te ondervangen.

**Comment by ElisabethKloren** [comment]
Done, er bestaat een arcewringsbibliotheek meer dan er hoofdgroepen zijn door de combinatiegroep ACO

**Comment by MvanderHulst** [comment]
Dit was mij niet eerder opgevallen en roept gelijk veel vragen bij mij op. maar dat voor een volgende versie! :-)

**Comment by ElisabethDeVries** [comment]
[[Release note]] In NLCS 5.0 waren niet voor alle hoofdgroepen arceringsbibliotheken beschikbaar. Om te voorkomen dat in individuele bibliotheken met afwijkende ID's en namen gewerkt gaat worden zijn in NLCS 5.2 Voor alle hoofdgroepen arceringsbibliotheken toegevoegd. Zie [hier](https://nl-digigo.github.io/NLCS/changelog/NLCS_Query_Abibliotheken-concept-5.1.html) voor een overzicht van bestaande en toegevoegde arceringsbibliotheken.

**Comment by ElisabethDeVries** [comment]
Reopen voor selectie 5.2 publicatie
