### ISSUE TITLE
_BG voor tekststijlen met achtergrond

### ISSUE THREAD

**Issue by SanderNijhof** [nl-digigo/NLCS#471]
- Conform de FB krijgen maatvoeringstijlen met een aanhaallijn een '_A' aan de maatvoeringstijlnaam toegevoegd. Maatvoeringstijlen zonder aanhaallijnen hebben t/m NLCS 5.0 geen toevoeging in de stijlnaam óf de toevoeging '_X'. 
- In Microstation is het toevoegen van een achtergrond bij tekst, een zgn ‘Mask’ opgenomen in de tekststijl. Daarom hebben tekststijlen met een achtergrond/mask t/m NLCS 5.0 in Microstation de toevoeging ‘_A’ gekregen en tekststijlen zonder een achtergrond geen toevoeging.

In de NLCS-EC is afgesproken dat vanaf NLCS 5.1:
1.	Maatvoeringstijlen zonder aanhaallijnen ALTIJD de toevoeging ‘_X’ krijgen. #32 
2.	Tekststijlen geen toevoeging ‘_A’ meer mogen hebben.

In Microstation is het noodzakelijk om gebruik te maken van aparte tekststijlen met achtergrond en tekststijlen zonder achtergrond, net als bij cursief en niet cursief, om een achtergrond/mask bij maatvoeringen onafhankelijk te kunnen toepassen.

Daarom het volgende voorstel:
1.	In de Formele Beschrijving niet de toevoeging ‘_X’ aan maatvoeringstijlen verplichten. 
2.	In de Formele Beschrijving opnemen dat tekststijlen met een achtergrond de toevoeging ‘_BG’ krijgen.
Hier is gekozen voor de letters ‘_BG’ voor BackGround en niet meer voor ‘_A’ van Achtergrond om verwarring met ‘_A’ van aanhaallijnen die bij maatvoeringstijlen wordt gebruikt te voorkomen. ‘_BG’ komt overeen met BG in de Microstation tekststijl dialog).
Dus bijvoorbeeld:
•	NLCS-ISO-T35
•	NLCS-ISO-T35_BG
•	NLCS-ISO-T18_CURSIEF
•	NLCS-ISO-T18_CURSIEF_BG

Toelichting: In Microstation zijn de maatvoeringstijlen gekoppeld aan de tekststijlen. Wijzig je dus de achtergrond van een tekststijl, dan wijzigen ook alle maatvoeringen die met die tekststijl zijn geplaatst. De enige goede mogelijkheid om zowel teksten als maatvoeringen met en zonder achtergrond te kunnen plaatsen is door hiervoor 2 aparte tekststijlen te definiëren.
Letters toevoegen aan een tekststijlnaam voor een tekststijl specifiek zonder ‘Achtergrond’ past niet met AutoCAD. In lijn daarmee zou het ook logisch zijn om ‘_X’ achterwege te (mogen) laten bij maatvoeringstijlen zonder aanhaallijnen.

**Comment by MvanderHulst** [comment]
Hi Sander,
Wederom een interesant onderwerp én en verschil met AutoCAD.

De huidige situatie is de maatvoeringsopmaak in versie 4.1:
![image](https://github.com/user-attachments/assets/cc0dd27b-71fe-4531-96b1-6d7de0793301)
Versie 4.1:
![image](https://github.com/user-attachments/assets/c635242e-8983-451a-a721-316b75efb461)
Versie 5.0:
![image](https://github.com/user-attachments/assets/627556f3-87b3-4576-8e44-869410c51ca5)

Altijd geweest:
NLCS-EENHEID SCHAAL-TEKSTHOOGTE-MAATVOERINGSYMBOOL-[AANHAALLIJNEN]-[AANTAL DECIMALEN LINEAR]-[AANTAL DECIMALEN HOEK]
Dus bijvoorbeeld:
NLCS-ANNOTATIEF-T25-OPENBOL_A met aanhaallijnen
NLCS-ANNOTATIEF-T25-OPENBOL_X zonder aanhaallijnen
Echter is de toepassing altijd OPTIONEEL geweest.
Het voorstel was om dit veld VERPLICHT te maken, omdat je anders problemen met uitwisseling krijgt.

Microstation misbruikte _A voor achtergrondmasker, wat sowieso tegen de regels was.

Binnen AutoCAD kan je voor een tekststyle en een leaderstyle geen backgroundmask toepassen.
Voor een dimension (maatvoering) kan dit wel.
![image](https://github.com/user-attachments/assets/4647257a-e536-4c5f-ad89-11f5cc4c1ffe)

Hiervoor moet je in AutoCAD dus ook 2 styles maken, als je er 1 mét en 1 zonder background mask wilt toepassen.

De aanvulling _BG lijkt mij dan een goede, maar jou voorstel moet dan iets anders:

NLCS-ANNOTATIEF-T25-OPENBOL_A met aanhaallijnen zonder masker
NLCS-ANNOTATIEF-T25-OPENBOL_A_BG met aanhaallijnen met masker
NLCS-ANNOTATIEF-T25-OPENBOL_X zonder aanhaallijnen zonder masker
NLCS-ANNOTATIEF-T25-OPENBOL_X_BG zonder aanhaallijnen met masker

Voor consequente opbouw zou je nog kunnen kiezen voor:
NLCS-ANNOTATIEF-T25-OPENBOL_MA_XBG met aanhaallijnen zonder masker
NLCS-ANNOTATIEF-T25-OPENBOL_MA_MBG met aanhaallijnen met masker
NLCS-ANNOTATIEF-T25-OPENBOL_XA_XBG zonder aanhaallijnen zonder masker
NLCS-ANNOTATIEF-T25-OPENBOL_XA_MBG zonder aanhaallijnen met masker

Het format moet dan zijn:
NLCS-EENHEID SCHAAL-TEKSTHOOGTE-MAATVOERINGSYMBOOL_AANHAALLIJNEN_BACKGROUNDMASK_[AANTAL DECIMALEN LINEAR]_[AANTAL DECIMALEN HOEK]

**Comment by SanderNijhof** [comment]
Dus voor Microstation is _BG een handige toevoeging voor tekststijlen en voor AutoCAD juist voor maatvoeringstijlen. :punch:

Ik laat 'ANNOTATIEF' altijd weg uit de tekststijlnaam, voegt vooral letters toe en is eigenlijk misleidend: je kunt de tekststijl ook 'niet annotatief' toepassen en zelf een schaalfactor geven.

De 'eenheid schaal' en teksthoogte is bij tekststijlen optioneel en bij maatvoeringstijlen en multileaderstijlen verplicht: 
`4.6.7 Benaming tekststijlen
`
`
a. tekststijlen:       NLCS-ISO-[EENHEID SCHAAL][-TEKSTHOOGTE][_CURSIEF]
`
`
b. multileaderstijlen:
NLCS-EENHEID SCHAAL-TEKSTHOOGTE_[CURSIEF]-AANPIJLINGSYMBOOL 
`

Mijn voorkeur heeft het sowieso om dit voor alle stijlen gelijk te trekken en dan niet meer te verplichten maar meer optioneel te maken, om de stijlnamen zo kort mogelijk maar toch voldoende functioneel te houden.

> Het voorstel was om dit veld VERPLICHT te maken, omdat je anders problemen met uitwisseling krijgt.

Welke problemen zien we met uitwisseling die oorzaak vinden in de stijlnamen? In Microstation worden de tekst- en maatvoeringstijlen vooraf (door de softwareleverancier) gedefinieerd en toegepast. De stijlen liggen dan vast.

Eentje die we al jaren toepassen in Microstation die ik over het hoofd had gezien is [_CURSIEF] voor maatvoeringstijlen. Die is niet opgenomen in de stijlnaamopbouw in de FB maar wel 2x als voorbeeld genoemd bij 4.5.12 en nodig voor aanpijlingen omdat Microstation daarvoor maatvoeringstijlen gebruikt.

Wat mij betreft mag je de stijlnamen voor de leesbaarheid zo kort mogelijk houden. 
Dan worden de formats:
### 4.6.7 a. tekststijlen
NLCS-ISO-[EENHEID SCHAAL]**-TEKSTHOOGTE**[_CURSIEF]**[_BACKGROUNDMASK]**
NLCS-RVV-[EENHEID SCHAAL]**-TEKSTHOOGTE**[_CURSIEF]**[_BACKGROUNDMASK]**
_(teksthoogte ook bij tekststijlen verplicht)._

### 4.6.7 b. multileaderstijlen (Microstation gebruikt hiervoor de maatvoeringstijlen)
NLCS-[EENHEID SCHAAL-]TEKSTHOOGTE_[CURSIEF]**[_BACKGROUNDMASK]**-AANPIJLINGSYMBOOL 
_(backgroundmask heeft voor AutoCAD en Microstation hier geen functie, maar voor de consequente stijlnaamopbouw en in een ander CAD-pakket wellicht wel?)._

### 4.5.12 a. maatvoeringstijlen
NLCS-[EENHEID SCHAAL]-TEKSTHOOGTE_**[CURSIEF]**-MAATVOERINGSYMBOOL[_AANHAALLIJNEN]**[_BACKGROUNDMASK]**[_AANTAL DECIMALEN LINEAR][_AANTAL DECIMALEN HOEK]

**Met de betekenis: als je het niet in de stijlnaam vermeld, dan is het niet in de stijl van toepassing.**

Voorbeelden zijn dan:
**NLCS-T25-OPENBOL_A** met aanhaallijnen zonder masker
**NLCS-T25-OPENBOL_A_BG** met aanhaallijnen met masker
**NLCS-T25-OPENBOL** zonder aanhaallijnen zonder masker
**NLCS-T25-OPENBOL_BG** zonder aanhaallijnen met masker
Kort, functioneel en duidelijk.

Als je ze uitgebreider wilt kan dat ook:
**NLCS-ANNOTATIEF-T25-OPENBOL_A** met aanhaallijnen zonder masker
**NLCS-ANNOTATIEF-T25-OPENBOL_A_BG** met aanhaallijnen met masker
**NLCS-ANNOTATIEF-T25-OPENBOL_X** zonder aanhaallijnen zonder masker
**NLCS-ANNOTATIEF-T25-OPENBOL_X_BG** zonder aanhaallijnen met masker

Maar persoonlijk voldoen voor mij de korte versies beter. Zou het wel prettig vinden als e.e.a. optioneel blijft/wordt.
Voorwaarde is wel dat het kan zonder problemen te geven met uitwisseling.

**Comment by MvanderHulst** [comment]
Voor wat de uitwisseling betreft:
Als de positie 'aanhaallijnen' optioneel is, dan ik dus een style toepassen met de aanhaal lijnen. een andere organisatie kan dezelfde stylenaam toepassen, maar dan zonder de aanhaallijnen.

Als de vermelding 'backgroundmask' optioneel zou zijn idem ditto.
Jij kan het aan hebben staan, zonder dat het in de stylenaam zichtbaar is. Ik kan dezelfde stylenaam hebben, maar dan zonder de backgroundmask.

Om eigenschappen van de presentatie 'optioneel' te maken, kan dus verschillende presentaties met dezelfde naam geven, wat je bij uitwisseling vreemd gedrag kan krijgen.
Dus standaard te vermelden of het er wel of niet in zit, is het niet optioneel en uniform en eenduidig.

**Comment by SanderNijhof** [comment]
Scherp, dat is niet hoe ik 'optioneel' had gezien. In plaats van 'optioneel' zou de uitleg 'indien van toepassing' moeten zijn.

De onderdelen tussen [ ] zijn dan zeker niet vrijblijvend, maar verplicht 'indien van toepassing'. En als ze niet van toepassing zijn laat je ze weg. 
Als je '_A' niet opneemt in de stijlnaam, dan mogen er dus geen aanhaallijnen in de stijl zijn opgenomen, idem dito voor 'cursief'. 

Voor 'backgroundmask' lijkt het een aparte situatie wat betreft tekststijlen in AutoCAD omdat autocadtekststijlen die eigenschap niet bevatten en daarom in Autocad tekststijlen met 'backgroundmask' niet voor kunnen komen. 
Voor maatvoeringstijlen voegt 'backgroundmask' wel voor zowel AutoCAD als Microstation iets toe.

**Comment by ElisabethKloren** [comment]
ok, ik heb het zo goed en zo kwaad mogelijk verwerkt in de tekst, mijn voorstel is dit te reviewen als ik de expertcommissie de reviewbare versies van de documentatie verstuur, en dus niet via deze issue. Deze issue alleen heropenen als er nog iets moet veranderen in de uitgangspunten

**Comment by ElisabethKloren** [comment]
sander vraagt per mail: In het overleg hebben we het ook kort gehad over _A bij bij tekststijlen en voorstel om hier _BG voor gaan te gebruiken bij zowel tekststijlen als maatvoeringstijlen.
Daar hebben volgens mij geen beslissing over genomen of iets over vastgelegd. Ik denk dat dit wel belangrijk en haalbaar is voor release 5.1.

**Comment by SanderNijhof** [comment]
Wat mij betreft pas je _A en _BG verplicht toe als die van toepassing zijn en als ze niet van toepassing zijn laat je ze weg. 
Een _X toevoegen kan, maar ik houd (stijl)namen graag zo kort en duidelijk mogelijk.
Een maatvoeringstijl zonder aanhaallijnen en zonder mask wordt dan bijv. **NLCS-T25-OPENBOL** 
en met aanhaallijnen en met mask **NLCS-T25-OPENBOL_A_BG**
Een _X is al voor 'zonder aanhaallijnen' dus dan zou voor 'zonder mask' iets anders bedacht moeten worden:
bij **NLCS-T25-OPENBOL_X** weet je anders niet of _X voor 'zonder aanhaallijnen' staat of 'zonder mask'. 

Maar nogmaals mijn voorkeur gaat uit naar eenvoud en dan denk ik aan verplicht toevoegen van _A en _BG als ze van toepassing en verplicht weglaten van _A en _BG als ze niet van toepassing zijn.
Dat wil dus zeggen dat een stijl **NLCS-T25-OPENBOL** nooit aanhaallijnen of een mask mag hebben. 
Net als bijvoorbeeld bij [_CURSIEF] dat moet worden toegevoegd als de stijl cursief is, maar weggelaten wordt als die niet cursief is.

Wat mij betreft zijn dit de minimale onderdelen die in een stijlnaam voorkomen: **"NLCS"**, **TEKSTHOOGTE** en **MAATVOERINGSYMBOOL**. De overige ben je verplicht op te nemen als ze van toepassing zijn. Het aantal decimalen voor lineaire maten en hoeken is vastgesteld in de FB, als je daar in je stijl van afwijkt moet je dat verplicht in je stijlnaam opnemen.

**Comment by MvanderHulst** [comment]
@SanderNijhof en @ElisabethKloren ik kan mij vinden in het zo kort mogelijk houden van de stijlnamen.
De 'optioneel' vermelding moet dan inderdaad wel verdwijnen uit de standaard.
Zoals Sander aangeeft, Als er een _A staat is het mét, als er niks staat is het zonder. Nu is het optioneel en kunnen alle combinaties voorkomen.
Idem voor het achtergrondmasker.
Als de style een mask heeft staat er _BG bij, als er niks bij staat heeft hij dus geen mask.

Dit in lijn met de cursief toepassen zoals Sander aangeeft. :-)

**Comment by ElisabethKloren** [comment]
Ik snap jullie punt, verplichting verkort inderdaad de verkorte stijlnamen zijn wel handig heb ik laatst in een van de NLCS applicaties gezien,. dit in tegenstelling tot eerder beschreven, ik pas de documentatie hierop aan.

**Comment by ElisabethKloren** [comment]
Afgehandeld, teksten gelijkgetrokken voor maatvoeringsstijlen en tekststijlen, bij die laatste ga ik ervan uit de A niet van toepassing is.
