### ISSUE TITLE
VERKANTING en ALIGNEMENT

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#475]
komt nu voor in VH en VW, klopt dat? Of zouden alignementen en alignementinformatie zoals VERKANTING in AM thuishoren? En moet het bij VH niet eerder afschot / hellingspercentage  zijn dan verkanting?

**Comment by MvanderHulst** [comment]
Een Alignement is een (excentrische)-as waaraan zaken gerelateerd worden en hoort dus thuis onder hoofdgroep AM.
Aan een Alignement kan verharding, riolering, gronwerk e.d. gekoppeld worden.

Onderstaand uitgebreide uitleg. Korte samenvatting:
Als je de een verkanting intekend, geeft je de mate aan met het afschot 1:50 of een hellingspercentage van bijvoorbeeld 2%.
Voor riolering wordt de term afschot gebruikt voor de aanleg van riolering.
Zou dus wel ergens als 'algemeen' object opgenomen mogen worden..
Spontaan idee hiervoor... wordt andere issue.


Verklaring van Termen
Verkanting:
Definitie: Verkanting is de dwarshelling van een weg of spoorlijn, waarbij de buitenbocht hoger ligt dan de binnenbocht. Dit helpt voertuigen om de bocht te maken zonder te slippen door de centrifugale krachten te compenseren.

Afschot:
Definitie: Afschot is de lichte helling van een oppervlak, zoals een wegdek of dak, die ervoor zorgt dat water kan wegstromen. Het wordt meestal toegepast om waterophoping en schade te voorkomen.

Hellingspercentage:
Definitie: Het hellingspercentage geeft de steilheid van een helling aan als een percentage. Het wordt berekend door de verticale stijging te delen door de horizontale afstand en het resultaat met 100 te vermenigvuldigen.


Onderlinge Verhoudingen
Verkanting en Afschot:

Beide termen hebben te maken met het creëren van een helling, maar verkanting wordt specifiek toegepast in bochten om de zijdelingse krachten te beheersen, terwijl afschot voornamelijk gericht is op waterafvoer.
Verkanting en Hellingspercentage:

Verkanting kan ook worden uitgedrukt in termen van hellingspercentage om de steilheid van de verkanting te kwantificeren, vooral in technische tekeningen en ontwerpen.
Afschot en Hellingspercentage:

Afschot wordt vaak berekend en weergegeven als een hellingspercentage om de mate van afschot te beschrijven. Dit helpt bij het bepalen van de juiste hoek voor effectieve waterafvoer.
Samengevat, verkanting, afschot en hellingspercentage beschrijven allemaal een vorm van helling of schuinte, maar ze worden in verschillende contexten en toepassingen gebruikt. Verkanting richt zich op stabiliteit in bochten, afschot op waterafvoer, en hellingspercentage geeft de mate van helling weer.

**Comment by ElisabethKloren** [comment]
Als ik het goed begrijp dan: 

1. ik verplaats de spoor alignementen naar assen en metrering; verkanting ook, hoort bij het alignement;
2. het woord verkanting in VH vervang ik voor AFSCHOT (of is dat gewoon een tekstlaag bij het object?);
3. de verkanting in VW gaat eruit, komt in AM als daar nog geen laag met verkanting stond.

**Comment by ElisabethKloren** [comment]
akkoord, zo ga ik het uitvoeren. Dank voor het meedenken

**Comment by ElisabethKloren** [comment]
verkanting komt voor in VH, maar ook bij assen en metrering, want bij het alignement van een weg of spoor wordt ook de verkanting aangegeven bij bogen, op bovenaanzichten. Zo kunnen alle soorten tekeningen gemaakt worden.

**Comment by MvanderHulst** [comment]
@ElisabethKloren 
Niet eens met de conclusie.
een verkanting is geen as of metrering.
De getrokken conclusie is als een boom bij verhardingen indelen, omdat deze in straatwerk kan staan.

er zijn 2 mogelijkheden:
Of de verkanting ook in hoofdgroep SB toevoegen.
Of aanbieden middels ZZ en dan in VH laten vervallen.

Persoonlijk ga ik voor de eerste optie, omdat er buiten deze disciplines geen andere hoofdgroepen zijn waar dit voorkomt.

**Comment by ElisabethKloren** [comment]
Ik ga met je mee om het bij verhardingen VH VERKANTING te laten staan, met interpretatie dat dit de plek is voor alle verkanting, hellingen en afschotten volgens jou definities, blijkbaar wordt dat bij verhardingen als overkoepelende term gebruikt. Bij VW vervalt de term dan. 

daarnaast is er ook sprake van een eigenschap van een as (alignement), dat heet ook verkanting. Maar inderdaad, ik zie dat dat tot nu toe niet is toegevoegd aan nlcs, dus niet gemist is? of dat dit gewoon op een T-laag wordt getekend bij de bogen en op tekening de verkanting wordt gezet?  dus akkoord om het woord verkanting alleen op te nemen bij VH

**Comment by ElisabethDeVries** [comment]
[[Release note]] Verkanting is geen onderdeel van verkeersmaatregelen weg maar een geometrische eigenschap van verhardingen, een laag waarop de tekenaar verschillende zaken kan weergeven: dwars op de weg voor waterafvoer (afschot) of voertuigligging in bochten (verkanting in het "alignement") met teksten als 1:200; in langsrichting langs de weg voor het hellingspercentage (2%). Het object VERKANTING is daarom vervallen in hoofdgroep VW.

**Comment by ElisabethDeVries** [comment]
Reopen voor heracceptatie in 5.2
