### ISSUE TITLE
#886	een Engelse benaming in een Nederlandse standaard? Volgens mij kan SVH-COBBLESTONE 

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#48]
#886	een Engelse benaming in een Nederlandse standaard? Volgens mij kan SVH-COBBLESTONE vervangen worden door SVH-KEI, of anders als subobject van natuursteen worden gezien.bijvoorbeeld “SVH-NATUURSTEEN_KEI” Daarnaast bestaat er wel ook een SVH-NATUURSTEEN_KINDERKOP dit is mogelijk ook al hetzelfde als cobblestone? Ook bestaat er een laag *-**-VH-VERHARDING-COBBLESTONE-G deze dient dan ook gewijzigd te worden. De laag *-**-VH-VERHARDING-NATUURSTEEN_KINDERKOP-G bestaat dan weer niet. Indien “kei”wordt geintroduceerd kan er worden gedacht aan: *-**-VH-VERHARDING_KEI_GRES_VIERKANT_10/10-G *-**-VH-VERHARDING_KEI_BASALT_RECHTHOEKIG_14/20-G *-**-VH-VERHARDING_KEI_GRANIET_VIERKANT-G *-**-VH-VERHARDING_KEI_HARDSTEEN_RECHTHOEKIG-G *-**-VH-VERHARDING_KEI_PORFIER_RECHTHOEKIG-G

**Comment by ElisabethKloren** [comment]
Reactie Expertcommissie
vanuit Richard de Nier: Voor deze heb ik een betere oplossing. Een cobblestone is een trommelsteen. Een betonsteen die getrommeld is om hem ouder te laten lijken. Kunnen we dus eenvoudig hernoemen

**Comment by ElisabethKloren** [comment]
To Do
"Hernoemen arceringen
AVH-COBBLESTONE-SO naar AVH-TROMMELSTEEN-SO
AVH-COBBLESTONE-SOD naar AVH-TROMMELSTEEN-SOD

Hernoemen symbolen
SVH-COBBLESTONE-SO naar SVH-TROMMELSTEEN-SO
SVH-COBBLESTONE_KL-SO naar SVH-TROMMELSTEEN_KL-SO
V-SVH-COBBLESTONE-SO naar V-SVH-TROMMELSTEEN-SO
V-SVH-COBBLESTONE_KL-SO naar V-SVH-TROMMELSTEEN_KL-SO
ook symbolen wijzigen in database (d.m.v. Excel)
hernoemen object
OPENVERHARDING_COBBLESTONE naar OPENVERHARDING_TROMMELSTEEN (ID 2490)
aanpassen symboolnaam in kolom ""symbool"" en arceringnaam in kolom ""arcering"":
SVH:SVH-COBBLESTONE naar SVH:SVH-TROMMELSTEEN (d.m.v. Excel)
AVH:SVH-COBBLESTONE naar AVH:SVH-TROMMELSTEEN (d.m.v. Excel)"

**Comment by SanderNijhof** [comment]
Is de vertaling van 'cobblestone' trommelsteen of keisteen? kinderkopjes? plaveisel? 
Is Cobblestone niet een regulier gehanteerde benaming in Nederland?
Volgens mij zijn trommelsteen en Cobblestone niet hetzelfde.

**Comment by MvanderHulst** [comment]
Vaktaal mag in stand gehouden worden. m.i. niet aanpassen.

**Comment by NielsNederpel** [comment]
cobblestone is inderdaad geen trommelsteen. in mijn idee is een cobblestone een straatkei. cobblestone ken ik persoonlijk niet als regulier gehanteerde benaming, maar ik heb er ook geen problemen mee op zich. 
echter is e.e.a. nu genoeg gespecificeerd? moeten er zoals aangegeven niet meer verschillende soorten cobblestones/straatkeien worden aangegeven om onderscheid te kunnen maken? of valt dit onder "natuursteen"? voor natuursteen zijn wel meerdere symbolen in diverse verbanden beschikbaar

**Comment by MvanderHulst** [comment]
Cobblestones en natuursteen zijn twee verschillende materialen.

Cobblestones zijn kleine, meestal rechthoekige of vierkante stenen die vaak worden gebruikt voor bestrating. Ze kunnen gemaakt zijn van verschillende materialen, zoals beton, baksteen of natuursteen.
Ze hebben meestal een gelijkmatige vorm en zijn verkrijgbaar in verschillende maten, maar ze zijn doorgaans kleiner dan natuurstenen.
Cobblestones worden vaak gebruikt om wegen, trottoirs, opritten en binnenplaatsen te bestraten. Ze kunnen ook worden gerangschikt in verschillende patronen, zoals visgraat, wildverband of keperverband.
Vanwege hun uniforme vorm en relatieve gelijkmatigheid zijn cobblestones meestal gemakkelijker te leggen dan natuursteen, en ze kunnen een nette en georganiseerde uitstraling bieden.


Natuursteen verwijst naar stenen die rechtstreeks uit de natuur worden gewonnen, zoals graniet, marmer, kalksteen, leisteen en zandsteen. Ze worden niet kunstmatig vervaardigd en behouden vaak de natuurlijke eigenschappen en onregelmatige vormen.
Natuurstenen hebben meestal een meer organische en onregelmatige vorm, met unieke kleuren en texturen. Ze variëren in grootte en vorm, wat resulteert in een meer natuurlijke uitstraling.
Vanwege hun onregelmatige vormen en maten kan het leggen van natuurstenen uitdagender zijn en vereist het vakmanschap om ze in evenwichtige en esthetische patronen te plaatsen.
Natuursteen wordt vaak gebruikt in landschapsontwerpen, tuinpaden, en als decoratieve elementen in buitenruimtes vanwege hun natuurlijke schoonheid en duurzaamheid.

Over het algemeen hangt de keuze tussen cobblestones en natuursteen af van het gewenste uiterlijk, het beoogde gebruik en het budget van het bestratingsproject. Cobblestones bieden een meer uniforme uitstraling en zijn doorgaans budgetvriendelijker, terwijl natuurstenen een unieke, natuurlijke uitstraling hebben maar mogelijk duurder zijn en meer werk vereisen bij het leggen.

**Comment by ElisabethDeVries** [comment]
laagnaam en symboolnaam wijziging pas meenemen in 6.0

**Comment by SanderNijhof** [comment]
Is het ook een optie om dit niet te wijzigen? Dat heeft de minste impact. Ik zie vooral extra beheerlast en geen inhoudelijke verbetering. Omdat de naam cobblestone al jaren in de NLCS wordt gebruikt, bestaat bovendien het risico dat gebruikers lokaal alsnog een cobblestone-laag toevoegen, waardoor de uniformiteit juist afneemt.
Wat mij betreft is dit een voorstel dat we beter niet verder doorzetten.

**Comment by MvanderHulst** [comment]
Als engineer zou ik nooit 'Cobblestones' kiezen en maak ik een eigen laagnaam met 'kasseien' aan.
Gezien het een NLCS is zou ik dus alles vanuit nederlandse vakbenamingen benaderen.

ik heb nog nooit een stratenmaker een 'cobblestone' horen bestellen, maar zeker wel kasseien.

**Comment by SanderNijhof** [comment]
De vraag is voor mij niet of kasseien of cobblestone de betere benaming is. De vraag is of er voldoende noodzaak is om een bestaande NLCS-laagnaam te wijzigen. Die noodzaak is mij vooralsnog onvoldoende duidelijk, terwijl de wijziging wel impact heeft op bestaande implementaties.
