### ISSUE TITLE
Gebruikersvraag droge blusleiding

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#484]
Per mail ontvangen: Beste heer/mevrouw, In welke laag in NLCS teken ik de droge blusleiding?

**Comment by MvanderHulst** [comment]
Naar mijn beste eer en geweten komt een droge blusleiding niet voor in de openbare ruimte.
Een droge blusleiding zit over het algemeen inpandig in een gebouw verwerkt voor gebruik van de brandweer. De aansluiting voor de invoer zit ook in de gevel verwerkt.

Als er een situatie van een droge blusleiding in de openbare ruimte wordt bedoeld ben ik erg nieuwsgierig naar een voorbeeld van een dergelijke situatie om een passend advies/aanvulling te maken.

Wel is 'blusleiding' aanwezig in de hoofdgroep riolering, waarvan de brandweer gebruik kan maken. Deze blusleiding staat echter altijd vol water en wordt met een put in het straatwerk aangeboden of middels een speciale brandkraan.

**Comment by ElisabethKloren** [comment]
Dit antwoord gestuurd:

Dit antwoord kreeg ik van een van de inhoudelijke experts: 

Naar mijn beste eer en geweten komt een droge blusleiding niet voor in de openbare ruimte [red: de huidige scope van NLCS is openbare ruimte en infrastructuur, niet gebouwen].
Een droge blusleiding zit over het algemeen inpandig in een gebouw verwerkt voor gebruik van de brandweer. De aansluiting voor de invoer zit ook in de gevel verwerkt.
Als er een situatie van een droge blusleiding in de openbare ruimte wordt bedoeld ben ik erg nieuwsgierig naar een voorbeeld van een dergelijke situatie om een passend advies/aanvulling te maken.
Wel is 'blusleiding' aanwezig in de hoofdgroep riolering, waarvan de brandweer gebruik kan maken. Deze blusleiding staat echter altijd vol water en wordt met een put in het straatwerk aangeboden of middels een speciale brandkraan.
Daar zou ik zelf aan willen toevoegen: u kunt wel gebruik maken van de NLCS methode met een eigen aanvulling, een laagnaam in een hoofdgroep die naar uw mening het beste aansluit; OG (ondergrond) bevat al laagnamen voor gebouwen, daar kan het bijvoorbeeld worden toegevoegd.
