### ISSUE TITLE
pat bestand AVH-SBS_DIKFORMAAT_HALFST klopt niet deze arcering heeft de afmetingen van een waalformaat

### ISSUE THREAD

**Issue by DerkNouwensTPG** [nl-digigo/NLCS#486]
Hieronder een schermafdruk van de foute arcering

![image](https://github.com/user-attachments/assets/b0b97f2c-b762-4b1e-b982-a2beb78c84ea)

Hieronder een schermafdruk van de correcte arcering

![image](https://github.com/user-attachments/assets/e9a023fb-4633-4332-b109-63da87839c16)

Onderstaande in tekst weergegeven t.b.v. overnamen in patfile. Graag controleren een aanpassen.

*AVH-SBS_DIKFORMAAT_HALFST,dikformaathalfsteensverband
0.0,0,0,0,0.069
90.0,0.207,0,0,0.207,0.069,-0.069
90.0,0.1035,0.069,0,0.207,0.069,-0.069
0.0,0.1035,0.0345,0.0,0.1035,0.0,-0.1035,0.0,0.0,0.0
0.0,0.1035,0.1035,0.0,0.1035,0.0,-0.1035,0.0,0.0,0.0

**Comment by ElisabethKloren** [comment]
aangepast in database voor concept- release 5.1

**Comment by ElisabethDeVries** [comment]
[[Release note]] In hoofdgroep VH (VerHardingen) had de Arcering AVH-SBS_DIKFORMAAT_HALFST per abuis de visualisatie van waalformaat, dit is hersteld.
