### ISSUE TITLE
Ter besluit OG: pilot NLCS-NDW op basis van huidige invoer NDW

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#489]
De NDW verkeersborden dataset is nog niet gebaseerd op het toekomstige informatiemodel, daarom wordt voorgesteld een pilot te doen waarbij mutaties worden doorgegeven op basis van de huidige NDW dataset, met het huidige mechanisme dat beschikbaar is (csv sheet).

Daarbij wordt nog niet aan NLCS-leveranciers gevraagd om functionaliteit in te bouwen, maar wordt eerst gekeken welke open data beschikbaar is, en welke informatie door een wegontwerper / bouwpartij realistisch kan worden toegevoegd aan een NLCS model met verkeersborden. 
Aan de kant van het NDW zal worden onderzocht, wat de beoogde architectuur is voor de komende paar jaar, en wat een wegbeheerder nodig zou hebben qua functionaliteit om (a) de informatie van het ontwerp uit een NLCS model te kunnen gebruiken en dan (b) in een andere app (George? ) ontbrekende gegevens in te voeren; ook wordt nagedacht over de beoogde flow qua handelingen: ontwerpen, besluit nemen, bouwen; verkeersbesluiten publiceren; wegenbestand muteren; verkeersbordenbestand muteren. Daarbij is dan de vraag, wat op korte termijn gebouwd kan worden wat niet helemaal zonde van het budget is op lange termijn.  

Het informatiemodel vraagt om een heel ander ontwikkeltraject, waarbij aan de kant van NDW en de wegbeheerder moet worden voorbereid op fedratief datadelen en een heel andere vorm van data publiceren (linked data). Dit kan niet ook nog in de NLCS-pilot worden meegenomen.

**Comment by ElisabethKloren** [comment]
Dit besluit is in mondeling overleg op 4 oktober na de bijeenkomst met de werkgroep op 3 okt akkoord bevonden

**Comment by ElisabethDeVries** [comment]
[[Release note]] Tijdens de ontwikkeling van de verkeersbordenbibliotheek voor NLCS is onderzocht of het George dataportaal van het Nationaal Dataportaal Wegverkeer een bron kan zijn voor het inladen van bestaande verkeersborden in een NLCS-tekening, en of nieuwe borden uit het ontwerp of de revisietekening kunnen worden geüploaded naar het George dataportaal. Er is een praktische mapping gemaakt waarmee dit ingeregeld kan worden vanuit CAD-applicaties. Dit is als beschrijving opgenomen in [Uitwisselafspraken bij NLCS 5.2](https://nl-digigo.github.io/NLCS/representations/5-2/#ndw-nlcs-verkeersborden). Deze aanvulling op de standaard zorgt ervoor dat een wegbeheerder niet meer met de hand nieuwe verkeersborden hoeft in te voeren in het George dataportaal, maar dit geautomatiseerd kan doen. Indien mutaties in verkeersborden niet meer handmatig per bord in het GEORGE‑dataportaal hoeven te worden ingevoerd, maar automatisch worden afgeleid uit ontwerp‑ of beheergegevens (bijv. NLCS of IMBOR), kan het handmatige invoerwerk per bord met circa 5 tot 7 minuten worden gereduceerd. Bij enkele honderdduizenden bordmutaties per jaar betekent dit een potentiële besparing van tienduizenden uren, wat zich vertaalt in een jaarlijkse maatschappelijke kostenbesparing in de orde van enkele miljoenen euro’s.
