### ISSUE TITLE
#885	Veel arceringslagen ten behoeve van “Constructies” hebben de kleur 252.

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#49]
#885	Veel arceringslagen ten behoeve van “Constructies” hebben de kleur 252. Wij stellen de kleur 253 voor, aangezien er bijvoorbeeld in beton-doorsneden vaak wapening wordt afgebeeld (zwart). Deze wapening is véél duidelijker wanneer de betonarcering een tintje lichter is.

**Comment by MvanderHulst** [comment]
Betreft database aanpassing. geen actie voor mij nodig.

**Comment by ElisabethDeVries** [comment]
[[Release note]] De kleur van arceringen in hoofdgroep Betonconstructies is aangepast van kleur 252 naar kleur 253, omdat deze beter contrasteert met de kleur zwart waarin de wapening wordt weergegeven. Daarnaast is van BETONVORM_PREFAB de kl_t_v van 254 naar 253 gegaan, in lijn met BETONVORM_VSP_PREFAB

**Comment by ElisabethDeVries** [comment]
reopen voor herbeoordeling 5.2 release

**Comment by ElisabethDeVries** [comment]
> [[Release note]] De kleur van arceringen in hoofdgroep Betonconstructies is aangepast van kleur 252 naar kleur 253, omdat deze beter contrasteert met de kleur zwart waarin de wapening wordt weergegeven. Daarnaast is van BETONVORM_PREFAB de kl_t_v van 254 naar 253 gegaan, in lijn met BETONVORM_VSP_PREFAB

@MvanderHulst ik kon niet een issue terugvinden voor deze wijziging, weet jij waarom?
