### ISSUE TITLE
Gebruikersvraag instellen schalen

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#490]
Kreeg deze gebruikersvraag per mail, hoop dat één van de experts me helpt:

Ik zit toch even te stoeien in welke schalen ik de terrein tekening conform NLCS moet opzetten.
Ik heb in het menu vaninfracad de schaal 1:100 staan voor zowel het invoeren van geometrie, arcering, symbool, teksten en maatvoering.
Is dat juist of moet ik dat aanpassen aan de schaal van de layout waarop ik deze wil afdrukken?
![gebruikersvraagschalen](https://github.com/user-attachments/assets/6b611fc3-aefb-4512-8b9f-a42f1a78dff1)

**Comment by MvanderHulst** [comment]
Op basis van de gekozen schaal worden symbolen met de juiste grootte geplaatst, wanneer geen gebruik wordt gemaakt van 'annotatief' tekenen.
Als de schaal 'Annotatief' actief is, is de AutoCAD instelling leidend:
![image](https://github.com/user-attachments/assets/970b1c71-aaad-4288-86f8-51fd76d17164)

Mijn mening is dat InfraCAD altijd op annotatief kan staan en je dan alles in standaard AutoCAD kan regelen. Meest overzichtelijke manier van werken.

**Comment by ElisabethKloren** [comment]
Dank! Dit mail ik terug
