### ISSUE TITLE
Check Verkeersborden codering met wetten.overheid.nl

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#496]
Er is wellicht op basis van verkeersborden.nl een verkeerde codering gebruikt, check op wetten.overheid.nl op correcte naam

**Comment by ElisabethKloren** [comment]
Goed gezien! Dit is een vergissing, de N wordt niet herintroduceerd. Gaan we aanpassen

**Comment by DerkNouwensTPG** [comment]
Aanvullende vraag hoe gaan we om met samengestelde borden in de opbouw van de symbool naam?

Door het aantal op te nemen tekst blokjes past dit niet binnen de mogelijk aantal van subobjecten. Voor ons van belang omdat we dergelijke borden hebben opgenomen in onze bibliotheek.

![image](https://github.com/user-attachments/assets/72540f6b-0044-4d93-85c8-12b846a1be81)

Voorbeeld mogelijke vertaling (ons bestaande bord en een voorstel in lijn met gekozen opbouw):
![image](https://github.com/user-attachments/assets/fa6b0bc0-8bc5-4e69-a883-dd9d72a277ba)

![image](https://github.com/user-attachments/assets/d23ef622-a6ba-437a-8955-02ebb53be30c)

![image](https://github.com/user-attachments/assets/44872d59-f25f-48aa-9d42-705aa6f6795a)

Voorbeeld Plaswijckweg Gouda
![image](https://github.com/user-attachments/assets/c1695e94-1246-4cb2-a631-42dc19baee03)

**Comment by ElisabethKloren** [comment]
Goed punt, in de 5.1 concept versie staan nu zulk soort benamingen van symbolen (voorbeelden):

- SVW-VERKEERSTEKEN_BORD_J21_F_OB1004_A01_030-SO
- SVW-VERKEERSTEKEN_BORD_G05_ZH_015-SO
- SVW-VERKEERSTEKEN_BORD_E09_ZB_SLEEP-SO
- SVW-VERKEERSTEKEN_BORD_E01_ZH_TIJD-SO
- SVW-VERKEERSTEKEN_BORD_A04_050_F-SO

De benamingen volgens de RVV 1990 zijn zoveel mogelijk aangehouden; tot er een officiële lijst is van rvv-borden (in het Informatiemodel Verkeerstekens of elders, deze vraag ligt ter besluit bij het ministerie van IenW) zijn er verschillende commerciële en particuliere bronnen die eigen aanvullende coderingen maken.

**Comment by DerkNouwensTPG** [comment]
Helder!


Met vriendelijke groet,

Derk Nouwens
Consultant

The People Group | Driven by technology Created by people

Middelweg 2 | 5253 CA NIEUWKUIJK | Nederland

T +31(0)85 224 00 00<tel:+310852240000> M +31(0)6 54 93 72 54<tel:+310654937254>

https://www.thepeoplegroup.nl/e-mail-disclaimer/

________________________________
