### ISSUE TITLE
Hectometerpaal, hectometrering: AM, VW of beide?

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#499]
het symbool SVW-HECTOMETERPAAL is gekoppeld aan AL-HECTOMETRERING; volgens mij is de hectometrering van een alignement zoals bedoeld in AM niet hetzelfde als de fysieke keuze voor de plaatsing van de hectometerpaal; zou in VW het object "HECTOMETERPAAL" moeten worden toegevoegd, waar dit symbool aan wordt gekoppeld?

**Comment by ElisabethKloren** [comment]
ok, dus ik heb denk ik in  gesprek met iemand genoteerd dat hectometrering bij een as hoort > #474 

Nu blijkt dus dat hier de hectometerpaaltjes bedoeld worden? Dan zet ik dit dus gauw weer terug naar VW en stel voor de objectnaam te wijzigen

<> hectometreringen zijn ook een ding op tekeningen van spooralignementen bij ProRail in elk geval, maar dat zijn in een NLCS tekening misschien wel gewoon maatvoeringen oid

**Comment by MvanderHulst** [comment]
@ElisabethKloren de hoofdgroep AM is bedoeld voor 'assen en metrering' dit zijn ontwerptechnische zaken welke m.i. geen fysiek object representeren.
Een 'hectometrering' wordt fysiek zichtbaar gemaakt met een hectometerpaal.
Persoonlijk vindt ik dat dit paaltje een 'inrichtingselement is', maar met de huidige logica zou hij ook onder VW kunnen.

Doorspeculerend....
Waarom is een hectometerpaal een onderdeel van VW (of IE) als je mij vraagt.
maar een geleiderail die er naaststaat heeft wel een eigen hoofdgroep.
Vreemd verschil... maar dat is voor een volgende versie. :-)

**Comment by ElisabethDeVries** [comment]
[[Release note]] In hoofdgroep Verkeersmaatregelen Weg (VW) stond een object "HECTOMETRERING", welke thuis hoort in Assen en Metrering (sic.). Hier blijkt bedoeld te worden "HECTOMETERPAAL", het fysieke object dat de metrering weergeeft. De objectnaam is gewijzigd om verwarring hierover weg te nemen.

**Comment by ElisabethDeVries** [comment]
Reopen voor herbeoordeling in 5.2
