### ISSUE TITLE
#1703 Hoofdgroep ZZ, hoogtelabel, kantopsluting.

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#5]
Hoofdgroep ZZ, hoogtelabel, kantopsluting.
Vreemd subobject in de algemene bibliotheek.

PEIL zou eerder onder AL horen, niet in 'voor alle hoofdgroepen'.

**Comment by ElisabethKloren** [comment]
Reactie Expertcommissie: NN
HOOGTELABEL(_KANTOPSLUITING) zijn juist naar ZZ gegaan in 5.0
dit omdat ze eerst in AL stonden.
dan komen ze echter standaard op status X
probleem daarmee is dat je dan op laagniveau geen onderscheid tussen HOOGTELABEL bestaand en HOOGTELABEL nieuw kan maken. 
AL is dus zeker geen optie in mijn idee hiervoor.
dat zelfde idee heb ik bij PEIL.

MH
Het object HOOGTELABEL in ZZ is prima.
Enkel het subobject KANTOPSLUITING mag/zou moeten komen te vervallen.
Als je voor alle hoofdgroepen ‘HOOGTELABEL’ beschikbaar hebt, is dit voldoende onderscheid denk ik.
De aanvulling KANTOPSLUITING zie ik zelf de meerwaarde niet van, deze niet voor alle hoofdgroepen.
Wanneer iemand het aanvullende onderscheid wilt hebben, zijn veel meer smaken noodzakelijk, dit zal dan op hoofdgroep nieuw als eigen subobject aangemaakt worden door de gebruikers verwacht ik.

NN
dan komt dus het symbool. SZZ-HOOGTELABEL_KANTOPSLUITING wel op de laag *-**-HOOGTELABEL-S te staan?
want het symbool willen we niet kwijt verwacht ik
voorstel object naar hoofdgroep VH?

**Comment by SanderNijhof** [comment]
HOOGTELABEL en HOOGTELABEL_KANTOPSLUITNG zijn 2 verschillende symbolen, met elk 4 varianten voor de richting van de aanwijzing. Beide komen niet overeen met de voorbeelden in de FB. Zijn deze praktisch? Is het belangrijk voor de NLCS om deze symbolen voor te schrijven? Kan dit niet met text/multileader?

**Comment by MvanderHulst** [comment]
Mag m.i. vervallen. komt niet overeen met FB. Niels wilt ze houden. Mij op het even.
SUBOBJECT KANTOPSLUITING hoort echter niet onder hoofdgroep ZZ. die moet vervallen, enkel HOOGTELABEL in ZZ laten staan.
Specificatie naar KANTOPSLUITING eventueel in VH opnemen, of in eigen bibliotheek van rotterdam.

**Comment by SanderNijhof** [comment]
In de spirit van NLCS5, zou SUBOBJECT KANTOPSLUITING in de groep ZZ inderdaad moeten vervallen en zouden de symbolen HOOGTELABEL_KANTOPSLUITNG hernoemd moeten worden naar HOOGTELABEL_01, als zijnde een variant.

**Comment by ElisabethKloren** [comment]
Te besluiten in EC 20231109:
- PEIL opnemen in AL of laten staan in ZZ
- *.**-HOOGTELABEL_KANTOPSLUITING naar VH of laten staan in ZZ
- SUBOBJECT KANTOPSLUITING in de groep ZZ inderdaad moeten vervallen en zouden de symbolen HOOGTELABEL_KANTOPSLUITNG hernoemd moeten worden naar HOOGTELABEL_01, als zijnde een variant.

**Comment by ElisabethKloren** [comment]
EC 20231109:
Besluiten:
1. PEIL = punt in tekening Z-hoogte van een object; laten staan in ZZ, beter definiëren in documentatie
2. Symbool: HOOGTELABEL_KANTOPSLUITNG verplaatsen naar VH

**Comment by SanderNijhof** [comment]
Nabrander: Volgens de FB par 4.5 (.1, .8 en .11) behoren coördinaten, hoogtematen en peilmaten tot de maatvoeringen. Derhalve zou je kunnen verwachten dat die op een -M laag moeten komen. Dat komt niet overeen met hoe e.e.a. in de tabellen is opgenomen. Volgens de tabellen komen deze op lagen voor -G of -G/S
Moeten we de FB of de tabellen aanpassen?

**Comment by SanderNijhof** [comment]
en het symbool voor HOOGTELABEL_KANTOPSLUITING verwijderen uit de NLCS of te wijzigen naar HOOGTELABEL_VARIANT01 vind ik beide betere opties dan verhuizen naar hoofdgroep VH.

**Comment by MvanderHulst** [comment]
HOOGTELABEL moet in ZZ blijft.
Kantopsluiting mag er helemaal uit, zou ik een _01 variant van maken indien nodig.....

Het element -M is bedoeld voor maatvoeringsobjecten 'Dimensions'.
Coordinaten worden meestal als tekst of leader geplaatst en zijn dus 'Tekst' objecten
Peilmaken als tekst is een T element, als het 'block' wordt toegepast is het een S object.

DIMENSIONS staan specifiek op het M element.
Hoeven we volgens mij niet ingewikkelder te maken dan het is.

Het type 'entiteit' bepaald het element waar het op komt. Niet zozeer het 'Object'.

**Comment by ElisabethKloren** [comment]
Heb definitie van peil toegevoegd in http://127.0.0.1:5500/docs/requirementscadmodels/index.html#hoogtematen: Bij een punt in de tekening aangegeven hoogte ten opzichte van N.A.P. of een ander afgesproken peil. 

Daarbij uitleg toegevoegd: Peilmaten als tekst komen op een laag met element T, als het 'block' wordt toegepast op een laag met element S.

Openstaande actie: Symbool: HOOGTELABEL_KANTOPSLUITNG verplaatsen naar VH

**Comment by SanderNijhof** [comment]
> Openstaande actie: Symbool: HOOGTELABEL_KANTOPSLUITNG verplaatsen naar VH

Of HOOGTELABEL_KANTOPLSUITING wijzigen naar HOOGTELABEL_01 ? Zie eerder gemaakte opmerkingen in deze issue.

**Comment by MvanderHulst** [comment]
Graag aanpassen naar HOOGTELABEL_01 inderdaad. anders wordt het weer zo een losse flodder in de 'VH' hoofdgroep.
Hou het lekker algemeen.

**Comment by ElisabethKloren** [comment]
Sorry, jullie hebben gelijk: 

Openstaande actie: Symbool: HOOGTELABEL_KANTOPSLUITNG verplaatsen naar VH en hernoemen naar HOOGTELABEL_01

**Comment by SanderNijhof** [comment]
Nee niet(!) verplaatsen naar VH. Hoogtelabel in de groep ZZ laten staan, dan kan die in alle hoofdgroepen gebruikt worden, ook in VH. 
Wat mij betreft vervalt de laag HOOGELABEL_KANTOPSLUITING en wijzigt de naam van het symbool **HOOGTELABEL_KANTOPSLUITING** naar **HOOGTELABEL_VARIANT01**, om bij een hoofdgroep nog wel een alternatieve weergave van het symbool te kunnen kiezen voor wie dat wenst.

**Comment by MvanderHulst** [comment]
Concreet voorstel, namen de volgende symbolen herzien en aanpassen:
SZZ-HOOGTELABEL_01-SO
SZZ-HOOGTELABEL_02-SO
SZZ-HOOGTELABEL_03-SO
SZZ-HOOGTELABEL_04-SO
SZZ-HOOGTELABEL_KANTOPSLUITING_01-SO => SZZ-HOOGTELABEL_05-SO
SZZ-HOOGTELABEL_KANTOPSLUITING _02-SO => SZZ-HOOGTELABEL_06-SO
SZZ-HOOGTELABEL_KANTOPSLUITING _03-SO => SZZ-HOOGTELABEL_07-SO
SZZ-HOOGTELABEL_KANTOPSLUITING _04-SO => SZZ-HOOGTELABEL_08-SO

**Comment by SanderNijhof** [comment]
Waarom 'hoogtelabel_kantopsluiting' en niet 'hoogtelabel_variant' ?

**Comment by MvanderHulst** [comment]
@SanderNijhof 
Ik bedoel aan te geven dat 'HOOGTELABEL_KANTOPSLUITING wordt vervangen door een variant,
alleen variant 1 t/m 4 bestaan al. en zou dus 5 t/m 8 moeten worden.

**Comment by SanderNijhof** [comment]
Jaaaa, ik las het niet goed :-/
alternatief:
SZZ-HOOGTELABEL_KANTOPSLUITING_01-SO => SZZ-HOOGTELABEL_VARIANT_01-SO
SZZ-HOOGTELABEL_KANTOPSLUITING_02-SO => SZZ-HOOGTELABEL_VARIANT_02-SO
SZZ-HOOGTELABEL_KANTOPSLUITING_03-SO => SZZ-HOOGTELABEL_VARIANT_03-SO
SZZ-HOOGTELABEL_KANTOPSLUITING_04-SO => SZZ-HOOGTELABEL_VARIANT_04-SO

**Comment by MvanderHulst** [comment]
Ook prima en misschien nog wel netter.
Zijde het niet dat 'VARIANT' weer nergens anders in de standaard voorkomt?

Is er echt een noodzaak om een variant te hebben die geen omkadering heeft en een variant met omkadering?
Als de 'gesloten' variant geheel komt te vervallen vindt ik het nog de mooiste oplossing. ;-)

**Comment by SanderNijhof** [comment]
VARIANT wordt in de NLCS ook toegepast bij lijnstijlen, bijv. RI-DWA_VARIANT01-SO en VH-GELEIDEBAND_VARIANT01-SO, vandaar. Bij symbolen wordt 'VARIANT' inderdaad nergens toegepast. Zou logischer zijn om dat bij lijnstijlen dan ook niet te doen?

Noodzaak? Ik vind het sowieso vreemd om voor teksten een symbool te maken. Ik gebruik ze nooit.

**Comment by MvanderHulst** [comment]
Voorstel voor EC
één versie behouden, andere 4 laten vervallen?
of hernoemen naar VARIANT

**Comment by ElisabethKloren** [comment]
Voorstel voor 5.1: alle symbolen wel houden, wel hernoemen:
SZZ-HOOGTELABEL_01-SO
SZZ-HOOGTELABEL_02-SO
SZZ-HOOGTELABEL_03-SO
SZZ-HOOGTELABEL_04-SO
SZZ-HOOGTELABEL_KANTOPSLUITING_01-SO => SZZ-HOOGTELABEL_VARIANT_01-SO
SZZ-HOOGTELABEL_KANTOPSLUITING_02-SO => SZZ-HOOGTELABEL_VARIANT_02-SO
SZZ-HOOGTELABEL_KANTOPSLUITING_03-SO => SZZ-HOOGTELABEL_VARIANT_03-SO
SZZ-HOOGTELABEL_KANTOPSLUITING_04-SO => SZZ-HOOGTELABEL_VARIANT_04-SO

**Comment by ElisabethKloren** [comment]
![image](https://github.com/nl-digigo/NLCS/assets/48585720/38005093-8e63-4c7f-9bcc-3d7958eb1d44)

**Comment by SanderNijhof** [comment]
> als een gebruiker in een NLCS applicatie zoekt naar hoogtelabel, komt er een variant voor alle hoofdgroepen langs, waardoor er een reuzelijst ontstaat aan hoogtelabels.

Dit is software specifiek, zo ontworpen door de software leverancier.

> en de huidige symbolen met blokje eromheen kunnen niet eens goed gebruikt worden met hoogtes van meer dan 10 m

Dat zou evt. in de software/tooling opgelost kunnen worden door de cel op te rekken? Of het symbool standaard vergroten.

Maar waarom worden hiervoor symbolen gebruikt? Dit kan toch ook prima/beter met een multileader?

**Comment by MvanderHulst** [comment]
@SanderNijhof 

Precies dat. Ik kan mij niet voorstellen dat er 'iemand' is die deze blocks gebruikt.
Als een 'block' net niet lekker past, moet je ene nieuw block plaatsen met de andere rotatie... dat doet toch geen mens?
Volgens mij is een multileader of een gewone tekst de standaard toepassing.

Zodoende mogen ze m.i. helemaal vervallen.
Als ze wel moeten blijven, lijkt één versie mij voldoende.
De omkaderde versie zou zowiezo weg mogen.

**Comment by ElisabethDeVries** [comment]
[[Release note]] Alle symbolen voor hoogtelabel uit hoofdgroep ZZ worden verwijderd uit de standaard. Aanbeveling aan tekenaars is een losse tekst plaatsen in het dwarsprofiel. De pijlen staan in de meeste tekeningen in de weg. Dit maakt de standaard eenvoudiger.
