### ISSUE TITLE
#884	Er is geen arcering voor dikke tegels. (zowel 300x300 als 300x150 als 150x300).

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#50]
#884	Er is geen arcering voor dikke tegels. (zowel 300x300 als 300x150 als 150x300). Graag toevoegen aan de NLCS bibliotheek.

**Comment by MvanderHulst** [comment]
Hey symbool is een aanvulling met een solid-arcering.
Voor een vlak-arcering is de aanvulling van een vlakvulling dus noodzakelijk.
Vlakvulling heeft echter een presentatiedoel einde en geen technisch karakter. toepassing van vlakvulling hiervoor zou dan ook onlogisch zijn... Niet op te lossen in de bibliotheken. Andere tekenmethodiek zoeken voor de gebruiker.

**Comment by ElisabethKloren** [comment]
beter documenteren hoe gewerkt moet worden in de [eisen aan tekeningen en modellen[(https://nl-digigo.github.io/NLCS/requirementscadmodels/);

**Comment by MvanderHulst** [comment]
Deze vraag valt eigenlijk ook samen met issue: https://github.com/nl-digigo/NLCS/issues/312
De wens voor een arcering met een 'achtergrondkleur'. ;-)

**Comment by MvanderHulst** [comment]
Als de gebruiker vol-vlak arceringen wilt gebruiken past hij de arcering SVH-TEGEL toe met eventueel een vlakvulling SVH-TEGEL.
Hierdoor wordt de tegelarcering met een grijze achtergrond kleur gepresenteerd.
Onderstaand een voorbeeld van 'dun' versus 'dik'.
![image](https://github.com/nl-digigo/NLCS/assets/144665595/be3c9b43-181d-4206-b036-b90eeb395387)

**Comment by ElisabethKloren** [comment]
Voorgenomen wijziging: dit voorbeeld opnemen in [de algemene toelichting op de standaard: https://nl-digigo.github.io/NLCS/functionalspecification/](https://nl-digigo.github.io/NLCS/requirementscadmodels/)

**Comment by MvanderHulst** [comment]
@ElisabethKloren 
Dit staat tekstueel al beschreven onder:
![image](https://github.com/nl-digigo/NLCS/assets/144665595/62c18585-fd01-467c-a012-b1ece89d37bb)

**Comment by MvanderHulst** [comment]
Hierbij wat vriendelijkere voorbeelden:
![image](https://github.com/nl-digigo/NLCS/assets/144665595/638254e4-f887-4a65-ba1e-21253b9d3f6d)
![image](https://github.com/nl-digigo/NLCS/assets/144665595/26a0fc4b-b9ff-4e8c-b24e-f071ea0c88e8)

kijk maar wat beste voegt in de documentatie

**Comment by ElisabethKloren** [comment]
afbeelding toegevoegd in de documentatie

**Comment by ElisabethDeVries** [comment]
[[Release note]] Voor dikke tegels ontbreekt een aparte arcering. Oplossing is gevonden in documentatie en tekenmethodiek, niet in extra arceringen.
