### ISSUE TITLE
GELEIDECONSTRUCTIE_GELEIDERAIL_KOPPELING_SCHILDMUUR: foutje in BV, alle schildmuren zitten in RI?

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#500]
of is er een reden dat 1 schildmuur in BV zit > gekoppeld aan de symbolen SRI-SCHILDMUUR?

**Comment by MvanderHulst** [comment]
Denk een mappingsfoutje. verwijzingen tussen hoofdgroepen is sowiezo niet mogelijk.
kan denk ik ontkoppeld worden.

**Comment by MvanderHulst** [comment]
Ik denk het niet.
Ik zie geen relatie tussen een schildmuur en een geleiderail.

**Comment by ElisabethKloren** [comment]
ik pas het aan

**Comment by ElisabethDeVries** [comment]
[[Release note]] Het object GELEIDECONSTRUCTIE_GELEIDERAIL_KOPPELING_SCHILDMUUR is verwijderd uit hoofdgroep BV. Een schildmuur is een onderdeel van rioleringen en heeft geen relatie met geleiderail.

**Comment by ElisabethDeVries** [comment]
reopen voor beoordeling 5.2
