### ISSUE TITLE
AL - twee objecten hebben geen kleuren mee gekregen

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#502]
TEKENBLAD_KADER en
TEKENBLAD_KADER_CENTERMARKERING

hebben geen kleuren, lijndiktes meegekregen, terwijl die wel in de database staan, de rest van de objecten krijgt met die query wel kleuren mee

zag wel dat lijndikte werd opgegeven als 0.70,in de lijst met lijndiktes stond 0.7, daar heb ik een 0 aan toegevoegd

Was dat de oorzaak?

**Comment by ElisabethKloren** [comment]
yep, dat was de oorzaak. Case closed

**Comment by ElisabethDeVries** [comment]
[[Release note]] Zie #838
