### ISSUE TITLE
#883	De blocken voor straatbaksteen zijn door de puntjes behoorlijk onduidelijk

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#51]
#883	De blocken voor straatbaksteen zijn door de puntjes behoorlijk onduidelijk en vloeien dicht zeker bij dikformaat en waalformaat. En dan helemaal bij verwijderen en de “KL variant” van waalformaat hier loopt namelijk nog een extra lijn door het symbool. Het verband is sowieso niet meer uit het block te halen. Kan e.e.a. worden aangepast? Of kan er sowieso een extra attribute toegevoegd worden voor het aangeven van het verband aangezien dit niet altijd duidelijk uit het symbool kan worden gehaald. Of is het een idee om een generiek symbool te maken voor straatbaksteen (en dan ook voor BSS om het gelijk aan elkaar te houden) waaruit het verband kan worden gehaald (eventueel nog steeds met toevoeging van een attribuut voor verband zoals hierboven aangegeven) en dat het formaat altijd blijkt uit de toevoeging DF/WF/KF/(LF). Hier zou dan gekozen kunnen worden voor de blocken die nu gebruikt worden voor KF. Het verband is namelijk bij de blocken voor KF wel uit het block te halen. De blocknaam kan dan iets worden van SVH-STRAATBAKSTEEN_ELLEBOOG-SO, SVH-STRAATBAKSTEEN_KEPER-SO, SVH-STRAATBAKSTEEN_HALFST-SO etc. Het formaat volgt dan alleen nog uit de ingevulde attributen en dus niet meer uit de blocknaam. Of er kan zelf gekozen worden om een block te maken voor alleen het type materiaal (straatbakssteen) en dat naast het formaat ook het verband alleen duidelijk wordt gemaakt vanuit ingevulde attributen.

**Comment by MvanderHulst** [comment]
dit probleem kan ik helaas onderschrijven. Zal zijn ontstaan vanuit 'uniek verschijnen' gedachte. Echter zou de presentatie van de stenen gewoon de echte maatvoering mogen zijn. Als onderscheid nodig is, dit met een kleurvlak aanvullen. Tekenmethodiek is hier sterk bepalend in. De arceringen met de extra lijnen worden denk ik nooooit gebruikt door tekenaars?

**Comment by MvanderHulst** [comment]
Zover bij mij bekend is hier nog geen definitief ei over gelegd?
Volgens mij iet hier nog niet definitief een ei over gelegd.
Het dichtvloeien kan ik volledig onderschrijven en er moet dus iets mee gedaan worden.
Mogelijkheden die ik zie:
1.	Toestaan dat symbolen ook met een pendikte 0.18 mm in de nieuwe situatie mogen voorkomen. Hiermee worden de arceringen van de gehele hoofdgroep verhardingen aanzienlijk duidelijker en leesbaar. Daarmee kan de afmeting van de steen en het verband uit het symbool gehaald worden.
2.	De bolletjes volledig uit de symbolen halen. Hiermee worden alle SBS symbolen beter leesbaar. Onderscheid tussen SBS en BSS is echter wel slechter te zien.
3.	Introduceren van algemene symbolen:
SVH-BETONSTRAATSTENEN_ELLEBOOGVERBAND-SO
SVH-BETONSTRAATSTENEN_HALFSTEENSVERBAND-SO
SVH-BETONSTRAATSTENEN_KEPERVERBAND-SO
SVH-BETONSTRAATSTENEN_BLOKVERBAND-SO
SVH-STRAATBAKSTENEN_ELLEBOOGVERBAND-SO
SVH- STRAATBAKSTENEN _HALFSTEENSVERBAND-SO
SVH- STRAATBAKSTENEN _KEPERVERBAND-SO
SVH- STRAATBAKSTENEN _BLOKVERBAND-SO
De afmeting neem je vervolgens op als attribute. Bij de bestaande symbolen doen we dit ook al en is het eigenlijk dubbelop. Zowel in de naam van het blok ALS het attribuutveld.
Vereenvoudiging is daarbij een reëel alternatief.

**Comment by ElisabethKloren** [comment]
alle symbolen krijgen lijndiktes 0.25, maar bij patroonsymbolen is 0.18 handiger. Allen; de 0.25 wordt bij gebruik in de software toegekend aan het symbool. Dus moet de softwareleverancier iets extra's doen als er ook symbolen op 0.18 moeten komen. (lijndikte aangeven bij het symbool oid). Dan zou je dus bij alle blocks moeten aangeven of het een patroonsymbool is, zodat een andere lijndikte kan worden toegepast. 

Dit is de oplossing die veruit de voorkeur heeft, maar vraagt wel aanpassing in de software. is dit 5.1 of moet dit worden verplaatst naar latere release? Is wel een lang spelend praktisch probleem voor de tekenaars. 

Dus voorstel is bij symbolen een attribuut toevoegen in de database, als dat is ingevuld met waarde 0.18 moet je de afwijkende lijndikte gebruiken.

**Comment by MvanderHulst** [comment]
@ElisabethKloren 
Deze aanpassing vraagt inspanning voor de softwareleveranciers.
De concrete wens is:
Nieuwe symbolen krijgen standaard lijndikte 0.25
Om dit probleem op te lossen is voor de symbolen van verhardingen gewenst om deze ook voor nieuw op 0.18 te kunnen presenteren.
0.25 is nu hard-coded in de standaard. Dit zou onderdeel van de database moeten worden om het daar te kunnen regelen.

**Comment by MvanderHulst** [comment]
@ElisabethKloren gaat deze mee in 5.1?

**Comment by ElisabethKloren** [comment]
Beste Expertcommissie NLCS,

In de issues van 5.1 zitten een paar, die impact hebben op software implementatie of controle tooling. Dat zijn de issues waarvan ik graag zou willen, dat jullie die met extra aandacht reviewen. Ik weet dat de officiële reviewperiode van juni al voorbij is…. Maar denk dat het belangrijk is om voor deze meer tijd te geven, terwijl we al aan de slag zijn met de kleine verbeteringen. 

Ik zou jullie willen vragen om deze issues voor 1 september te reviewen en daarbij duidelijk aan te geven of het voorstel moet worden aangepast of uitgesteld naar een volgende release als deze te veel impact heeft.

**Comment by MvanderHulst** [comment]
@NielsNederpel jou oplossing herken ik zeker uit mijn HB verleden.
KEIFORMAAT presentatie gaf aan dat het betonstraatstenen waren.
DIKFORMAAT presentatie gaf aan dat het straatbakstenen waren.

Het verband was zichtbaar in het patroon, de kleur wat een attribute value.
Alle combinaties waren daarmee duidelijk en zichtbaar te maken, alleen soms kreeg je wat vreemde situaties bij werken waar het beide in zat, maar het klopte wel altijd. :-)

**Comment by ElisabethKloren** [comment]
aantekeningen van frank:

We hebben het hier over bepaalde uitzonderingen. Het is niet wenselijk om oplossingen voor uitzonderingen in software te gaan opnemen.

Oplossingsrichtingen: 
1.	Oplossingen; eigen overrule. Consequentie meldigen
2.	Kolom in de database; Consequenties aanpassen in de software >> redelijk impact 
3.	Symbolen volgen lijndikte van Geometrieën; consequenties voor presentatie in tekeningen (verwacht probleem voor objecten N- (bijvoorbeeld 0.5 dik..))
4.	NIET GOED BESPROKEN, voorstel van Paul: Tekstuele Aanpassing Formele Beschrijving 

Oplossingsrichting 4 >> Minste Impact en volgt huidige opbouw van bepaalde onderdelen uit de bibliotheek

Aanpassing
Paragraaf 3.5.6 Symbolen lid f. herschrijven

Huidig
“Een beperkt aantal symbolen heeft vaste kleuren, die onafhankelijk zijn van de lagen waarin ze worden geplaatst. Deze symbolen mogen worden geplaatst by object. (Voorbeelden zijn symbolen van verkeersborden)”

Onderbouwing:
Een voorbeeld van de inhoud van de huidige bibliotheek binnen definitie van symbolen (verkeersborden). 
Overrule voor:
-	Kleur
-	Lijndikte
![verkeersbordhardcodedsymbool](https://github.com/user-attachments/assets/0122a0ed-59ed-4cc2-bfb4-9c1222e59403)

Paul geeft ook aan bibliotheken te maken voor gebruikers waar ook lijntypes een afwijkende lijntype heeft en dus niet bylayer staat.
Dus voorstel: Afwijking voor inhoud van symbolen bibliotheek 

Voorstel
Een beperkt aantal symbolen heeft binnen de symbooldefinitie instellingen voor eigen kleuren, eigen lijnstijlen of eigen lijndiktes. Deze zijn onafhankelijk zijn van de lagen waarin ze worden geplaatst. Deze inhoud van symbolen mogen met de eigenschappen “by object” worden geplaatst. (Voorbeelden zijn onder andere symbolen van verkeersborden of aanduidingen van bestratingsmateriaal)

Acties / Controleren
Presentatie controleren voor verschillende schalen 1:200 en 1:500 >> Wie verantwoordelijk

**Comment by MvanderHulst** [comment]
Zoals besproken, maar nog even vastleggend:
Fundamenteel uitgangspunt voor NLCS, is het alles tekenen bij 'ByLayer'
Layerinstellingen voor -S element zijn geen onderdeel van de objectentabellen. Dit zou wel het geval moeten zijn, gezien alles over 1 kam scheren de lading onvoldoende dekt. **_Dit in het verlengde van de reden dat ook de linetype voor GD opgenomen gaat worden in de database._**

Dit het meest uniform te regelen door een extra kolom voor de lineweight van een -S element voor het object op te nemen in de database.

Object overrides in de symbolen zijn snelle kortetermijn oplossingen welke bij samenstellen van intergrale projecten weer andere problemen gaan opleveren.

Koppelen aan de lineweight van 'G' gaat conflicten opleveren voor bijvoorbeeld asfalt- en betonverhardingen lagen. Zeer aannemelijk is dat het op bepaalde fronten gaat wringen. Een 'snelle' oplossing voor een bij voorkeur te standaardiseren probleem.

Op de vraag...
_De experts zijn het niet eens over de urgentie van dit vraagstuk (om hoeveel tekeningen gaat het, om hoeveel handmatige aanpassingen gaat het?), dat er veel van de standaard wordt afgeweken, moet worden afgeweken nu wordt wel erkend._

...een inschatting op basis van de HB projecten:
In 2023 hebben wij 630 civiele projecten gedaan.
Van deze projecten bestaan 300 projecten uit meerdere faseringen. Voor het gemak rekenen we even met 2.

In 2023 zijn er dus minimaal in 930 bestanden voor 'nieuwe situatie' de lineweight van symbolen 'verhardingen' aangepast naar een dunnere pendikte.

Stel dat er 10 ingenieursbueaus zijn in Nederland, met dezelfde omvang als HB (40 CAD-tekenaars)...
Dan is het aannemelijk dat de handmatige aanpassing minimaal 10.000x per jaar wordt uitgevoerd voor een leesbare tekening.
Daarmee zit ik denk ik nog aan de voorzichtige kant.

**Comment by ElisabethKloren** [comment]
Mijn conclusie: de standaard zorgt ervoor, dat sommige symbolen niet goed leesbaar zijn, omdat het bij nieuwe objecten te dikke lijnen afdwingt. Dit leidt in de praktijk tot ERG VEEL handelingen in tekenwerk; waarbij het niet wenselijk is om dit hard coded in de symbolen op te lossen, omdat je dan in het geval van een ander soort tekening misschien een heleboel geplaatste symbolen moet gaan wijzigingen, je wilt dat de gebruiker de tekstdikte van de symbolen per laag kan aanpassen.

Voorstel voor versie 5.1: In de formele beschrijving wordt opgenomen, dat een N symbool ook dunnere lijnen mag hebben, als dit nodig is voor visualisatie. 
In de database worden een eigenschap toegevoegd BIJ HET SYMBOOL (dus niet bij de objecten, dat is inderdaad verwarrend) > waarbij deze standaard op N 25 staat, maar bij sommige symbolen op N 18. In 2025 kan dan door de leveranciers worden getest, geprobeerd of zijn dit bij plaatsing van het symbool standaard de lijndikte kunnen verminderen. 

In versie 6.0 kan dit dan als eis worden toegevoegd voor de nlcs-applicaties, dat symbolen de N-dikte krijgen van het toegevoegde attribuut. Dat geeft de ontwikkelaars meer tijd zonder potentieel gebruiksgemak tegen te gaan. 

Gevraagd van de experts: een lijstr met de symbolen, die nieuw altijd standaard dunner gezet worden, in de huidige situatie.

**Comment by MvanderHulst** [comment]
@ElisabethKloren conclusie is bijna juist.
In de database moet bij de OBJECTEN een extra kolom 'S-lineweight' worden opgenomen.
Dit kan niet op basis van de symbool definities.
Het is namelijk mogelijk om meerdere symbolen op 1 layer te plaatsen. De lineweight is eigenschap van de laagnaam.
Per symbool regelen is dus niet mogelijk, omdat het dan elkaar kan tegenspreken bij de laagnamen.
Object-laagnamen voor symbolen moeten dus gekoppeld worden aan een presentatiestyle.

**Comment by ElisabethKloren** [comment]
Dank voor je input, ik wil uiteraard niet dat het te complex wordt, dan wordt het toch een extra attribuut bij de objectentabellen

**Comment by ElisabethKloren** [comment]
EC 3 okt 2024: Akkoord met beschrijving in 5.1. Voor 6.0 onderzoeken of er een extra object moet worden geprogrammeerd, of een kolom erbij > dit moet worden uitgewerkt voor 6.0.

Ook onderzoeken of we voor de andere CAD elementen in de database willen publiceren wat de regel is.

**Comment by ElisabethDeVries** [comment]
[[Release note]] Aanpassing documentatie. Bij het overzicht representatie, bij symbolen: Status bestaand 0.18, overige statussen 0.25. Indien de symbolen door in elkaar overvloeiende lijnen niet meer goed leesbaar zijn, bijvoorbeeld bij bestratingssymbolen, mogen deze een pendikte kleiner krijgen

**Comment by ElisabethKloren** [comment]
issue #504 voor release 6.0
