### ISSUE TITLE
query objects levert zes-dubbele rijen op bij sommige IE objecten, zonder relaties naar arceringen/objecten

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#515]
Waarom? ik zie echt geen verschil tussen de regels

CONSTRUCTIEVE AFSCHEIDING_HEKWERK
CONSTRUCTIEVE AFSCHEIDING_HEKWERK
CONSTRUCTIEVE AFSCHEIDING_HEKWERK
CONSTRUCTIEVE AFSCHEIDING_HEKWERK
CONSTRUCTIEVE AFSCHEIDING_HEKWERK
CONSTRUCTIEVE AFSCHEIDING_HEKWERK
CONSTRUCTIEVE AFSCHEIDING_HEKWERK
CONSTRUCTIEVE AFSCHEIDING_HEKWERK

**Comment by gerritversteegh** [comment]
Er lijken dubbele URIs aangemaakt te zijn voor bepaalde lijntypes (e.g. IE-CONSTRUCTIEVE AFSCHEIDING-SO). Ik ga kijken waar dit vandaan komt

**Comment by gerritversteegh** [comment]
@ElisabethKloren Ik heb hier een overzicht gegenereerd van alle objecten/arceringen/symbolen/lijntypes waarvan meerdere URIs bestaan (filter de kolom numURI in [deze sheet](https://github.com/user-attachments/files/17519949/tableDownload.2.csv)). Ik heb niet alles bekeken maar het lijkt erop alsof sommige concepten onlangs zijn geimporteerd vanuit de nieuwe importsheets terwijl er oorspronkelijk ook al een concept voor was aangemaakt (bijv. WARMTENET_BRONPUT).
Daarnaast zag ik ook dat soms 2 concepten oorspronkelijk andere namen hadden maar nu zijn hernoemd naar dezelfde naam (bijv. IE-CONSTRUCTIEVE AFSCHEIDING-SO)

**Comment by ElisabethKloren** [comment]
@gerritversteegh twee objecten met dezelfde naam mogen toch? Die selecteer ik er weer uit (net gedaan bij warmte- en koudenet); maar dat geeft geen problemen in de publicatie want hebben verschillende URI's, toch?

lijntypes ga ik naar kijken, want die moeten uniek zijn qua naam.

**Comment by ElisabethKloren** [comment]
@gerritversteegh , mag een vervallen lijntype wel dezelfde naam hebben?

**Comment by gerritversteegh** [comment]
Concepten met dezelfde naam mag, maar het zal voor gebruikers onduidelijk zijn welk concept de juiste is in hun situatie. Mijn advies is om te kijken wat de overlap is tussen de concepten en deze eventueel samenvoegen/hernoemen, of één van beide concepten op Expired zetten en niet meenemen in de publicatie. 

Ik heb deze informatie uit de laatste test publicatie gehaald (http://hub.laces.tech/digitalbuildingdata/nlcs/test/nlcs-test6/versions/5-08). Ik ben er vanuit gegaan dat alleen de Current concepten zijn gepubliceerd maar dit is misschien niet het geval en dan het aantal dubbelingen misschien minder zijn dan in de sheet aangegeven.

**Comment by gerritversteegh** [comment]
> @gerritversteegh , mag een vervallen lijntype wel dezelfde naam hebben?

Ja dat mag, zolang de vervallen concepten niet worden gepubliceerd zal dit geen verwarring veroorzaken bij de gebruikers

**Comment by gerritversteegh** [comment]
De query om dubbelingen te vinden:

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sh: <http://www.w3.org/ns/shacl#>

# Check hoeveel URIs per naam (uniek voor hoofdgroep en topconcept)

SELECT DISTINCT ?name ?hoofdNames ?topNames (COUNT(DISTINCT ?uri) AS ?numUri) 
WHERE {  
  ?topconcepts a owl:Class .
  ?topconcepts skos:prefLabel ?topNames . 
  FILTER (?topNames IN ("NLCS-object", "Arcering", "Symbool", "Lijntype")) .
  ?hoofdgroepen rdfs:subClassOf ?topconcepts .
  ?hoofdgroepen skos:prefLabel ?hoofdNames .
  ?uri rdfs:subClassOf* ?hoofdgroepen .
  ?uri skos:prefLabel ?name .
  BIND ( IF(?uri = ?hoofdgroepen, IF(?name IN ("V-CONTINUOUS-SO", "CONTINUOUS", "NLCS_HIDDEN-SO"), ?uri, ?undefined), ?uri) AS ?NotHoofdgroep) .
  BIND ( IF(?uri = ?hoofdgroepen, IF(?name IN ("V-CONTINUOUS-SO", "CONTINUOUS", "NLCS_HIDDEN-SO"), ?undefined, ?hoofdNames), ?hoofdNames) AS ?hoofdgroep) .
  FILTER (?uri = ?NotHoofdgroep) .
}
  GROUP BY ?name ?hoofdNames ?topNames
```

**Comment by ElisabethKloren** [comment]
controles uitgevoerd, query gedocumenteerd

**Comment by ElisabethDeVries** [comment]
Deze issue kwam voort uit een foutje in de instellingen bij het publiceren van de testversie bij nlcs 5.1 en heeft geen impact op een actuele versie van de standaard
