### ISSUE TITLE
#882	Waarom zijn de SVH-symbolen voor BSS en straatbaksteen dikformaat

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#52]
#882	Waarom zijn de SVH-symbolen voor BSS en straatbaksteen dikformaat bij de kleine verhardingssymbolen met een grijze solid terwijl het “gewone” formaat block geen grijze solid heeft. En waarom zijn de SVH-symbolen voor BSS en straatbaksteen waalformaat bij de kleine verhardingssymbolen met extra lijnen door het block terwijl het “gewone” formaat block deze lijnen niet hebben. Maw waarom zijn de kleine verhardingssymbolen niet een ‘exacte’ kopie van het normale formaat verhardingssymbool maar dan in het klein? Graag e.e.a. gelijk maken.

**Comment by ElisabethKloren** [comment]
Reactie Expertcommissie
opmerking klopt.

**Comment by SanderNijhof** [comment]
Wat mij betreft moet er een analyse gemaakt worden van SVH en AVH cellen in de NLCS: welke ontbreken, welke zijn niet goed opgebouwd (vorm, inhoud). En voegen we de 'niet-KL' symbolen en de 'KL' symbolen samen tot 1 symbool. De KL symbolen worden toegepast als de 'niet-KL' symbolen te groot zijn. Waarom dan niet altijd de KL symbolen toepassen, of in ieder geval 1 variant maken die altijd toegepast kan worden?

**Comment by MvanderHulst** [comment]
De verhardingssymbolen zijn sowieso een drama om mee te werken. Hier kan ik een werkbaar voorstel van maken.

**Comment by SanderNijhof** [comment]
Hier idem dito: ontbrekende SVH en AVH toegevoegd en de vorm aangepast. Eigenlijk de AVH goed gemaakt en uit de AVH's de SVH's opgebouwd, zodat ze altijd overeenkomen en compleet zijn. Ook in NLCS5 zijn de AVH en SVH niet compleet, komen ze niet altijd met elkaar overeen en hebben ze niet de juiste schaal. (Uitgaande dat de conversie van Acad naar Microstation goed is gegaan).

**Comment by MvanderHulst** [comment]
Ik heb een analyse gedaan op alles symbolen van SVH: onderstaand de blocks welke in heb herzien:
![image](https://github.com/nl-digigo/NLCS/assets/144665595/91973505-f88c-4ff6-b778-3236703cdf3d)

**Comment by ElisabethDeVries** [comment]
[[Release note]] De symbolen voor SBS, BSS ROOSTER en GEOTEXTIEL zijn herzien zodat de klein formaat symbolen in visualisatie overeen komen met de groot formaat symbolen.

**Comment by SanderNijhof** [comment]
De _KL-varianten zijn voor mij niet langer verdedigbaar. Voor hetzelfde object hoort niet meer dan één symbool te bestaan. De _KL-varianten voegen geen functionaliteit toe, maar zorgen wel voor extra beheer- en implementatielast.

**Comment by MvanderHulst** [comment]
@SanderNijhof Wanneer een verhardingsvlak smaller is dan 1.20m, past het normale symbool niet meer en kan het kleine symbool worden toegepast. Ook voor 1:500 tekeningen kan het kleinsymbool beter tot zijn recht komen dan het reguliere symbool. Beide symbolen worden dus wel degelijk toepast in tekeningen.

Persoonlijk ben ik wel lui, en pas ik een 'CLIPPING' toe op het grote symbool om hem passen te krijgen.

Al met al kan ik geen bezwaar bedenken waarom het een enorme ramp zou moeten zijn als er kleinere en grotere symbolen voor de verhardingen (en groen) aanwezig zijn.

**Comment by SanderNijhof** [comment]
@MvanderHulst Ik begrijp dat een kleinere variant van het reguliere symbool beter leesbaar kan zijn, maar niet waarom daarvoor een tweede symbool voor hetzelfde object nodig is. Als het reguliere symbool niet voldoet, waarom passen we dat dan niet aan?

Ik zie namelijk wel bezwaren bij twee symbolen voor één object:

1. de standaard wordt minder eenduidig;
2. software moet meerdere presentaties van hetzelfde object ondersteunen;
3. gegevensuitwisseling en koppelingen met beheersystemen worden complexer;
4. binnen één tekening kunnen verschillende presentaties van hetzelfde object voorkomen.

Daarom zie ik meer voordelen in één symbool per object dan in de _KL-systematiek.

**Comment by MvanderHulst** [comment]
@SanderNijhof vanuit die logica snap ik het zeker, zodoende misbruik ik ook de CLIPPING in AutoCAD om het probleem op te lossen.
De vraag is denk ik dan ook... kan je in Microstation ook een soortgelijke truc toepassen, waarmee de grote symbolen ook leesbaar in kleine vlakken gemaakt kunnen worden?

Want de 'klein' symbolen anzich zijn ook niet altijd even duidelijk.

**Comment by SanderNijhof** [comment]
@MvanderHulst Als zowel het reguliere symbool als de _KL-variant niet altijd voldoen, zie ik dat eerder als een argument voor één beter symbool dan voor twee symbolen voor hetzelfde object. Die oplossing zou dan in de standaard zelf moeten zitten en niet afhankelijk moeten zijn van specifieke mogelijkheden van AutoCAD of Microstation.

**Comment by MvanderHulst** [comment]
@SanderNijhof 

voor 90% voldoet het standaard symbool, voor de overige 10% niet.

Ik zie echter geen andere oplossingen.

Dus... ik zie graag je voorstel. 😊

**Comment by SanderNijhof** [comment]
@MvanderHulst Ik zie wel een andere oplossing. Als het reguliere symbool in 90% van de gevallen voldoet, lijkt het mij logischer om die overige 10% op te lossen dan om voor 100% van de de objecten een extra _KL-variant aan de standaard toe te voegen.

Daarbij gaat het mij niet alleen om leesbaarheid. Twee symbolen voor hetzelfde object maken de standaard minder eenduidig, vergroten de complexiteit voor software, gegevensuitwisseling en koppelingen met beheersystemen, en kunnen ertoe leiden dat hetzelfde object binnen één tekening op verschillende manieren wordt weergegeven.

Bovendien geef je zelf aan dat ook de _KL-symbolen niet altijd duidelijk zijn. Dat zie ik eerder als een argument om te zoeken naar één beter symbool dat in **alle** situaties voldoet dan om twee verschillende symbolen voor hetzelfde object in stand te houden.
