### ISSUE TITLE
#881	Worden bijschriften t.a.v. te verwijderen situatie als zijnde bestaand weergegeven of wel met 1.8 en cursief?

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#53]
#881	Worden bijschriften t.a.v. te verwijderen situatie als zijnde bestaand weergegeven of wel met 1.8 en cursief? En verder: waarom staan de attributen bij bestaande/te verwijderen symbolen niet cursief aangegeven? Wordt dit niet gezien als bijschrift? Op zich zou het wel duidelijker onderscheid bieden tussen met name bestaand en nieuw En dan verder nog: De lineweight van de attributen in blocken hebben de eigenschap bylayer. Echter volgens formele omschrijving paragraaf 3.5.6 worden alle blocken in lagen gezet met een lineweight van 0.25 gezet. Moeten de teksten in symbolen niet voldoen aan de lineweight van teksten volgens paragraaf 4.6.2 van de formele beschrijving?

**Comment by ElisabethKloren** [comment]
To Do
verduidelijken in FB tabel op pagina 45 aanvullen

**Comment by SanderNijhof** [comment]
Conform tabel 4.6.3 op blz 45 FB kunnen bijschrijften in symbolen zowel 1.8mm als 2,5mm recht op zijn voor nieuw en zowel 1,8mm hoog rechtop als cursief voor bestaand. Dat is niet echt eenduidig. Dit lijkt mij het beste/makkelijkste op te lossen door dit door de NLCSTooling te laten regelen, dat bijschrijften 'bestaand' in alle gevallen cursief is.

**Comment by MvanderHulst** [comment]
Bekend probleem. Bij 'status' wisselen' zou ook een nieuw block met cursief symbool geplaatst moeten worden.
Ik vraag mij vooral af: waarom dit onderscheid? Volgens mij is er geen mens die kijkt naar schuine of rechte teksten, maar eerder of deze zwart of grijs zijn afgedrukt? Volgens mij is alles rechtop, met vrije tekstgrote prima werkbaar om je tekening uit te leggen. Op een bestaande situatie staan bestaande teksten, voor een nieuwe situatie presenteer je nieuwe teksten. Als je op een nieuwe situatie tekening ook bestaande teksten laat zien, maak je deze meestal toch wel grijs.

**Comment by MvanderHulst** [comment]
Zie eerdere voorstel. Is hier een klap op gegeven?

**Comment by MvanderHulst** [comment]
zie ook issue #108

**Comment by SanderNijhof** [comment]
Het verschil tussen BESTAAND en NIEUW in tekstgrootte en cursief is van belang vanuit het uitgangspunt dat alle tekst zwart afgedrukt wordt. Door BESTAAND grijs af te drukken wordt het onderscheid nog duidelijker.
@ElisabethKloren 
Optie 1 ben ik niet voor, lijkt me ook niet nodig. Ik/wij houd/en ons al jaren niet aan de vaste pendikte die cellen volgens de FB moeten hebben en passen voor status B en N dezelfde cellen toe met verschillende kleur/pendikten. 
Optie 2: de uitzondering is er al enigszins voor symbolen wat teksthoogte betreft. Ben er geen voorstanden van wat betreft leesbaarheid van de tekeningen. Optie 2 is zoals het al jaren in de NLCS werkt (toch?).
Optie 3: Voor mij is onderscheid tussen rechtop en cursief _HET_ onderscheid tussen BESTAAND en NIEUW. De kleur/grijstint is ter verduidelijking.
**Optie 4:** De software de presentatie van tekst laten regelen. De teksten die in de symbolen zijn opgenomen geven vooral aan welke inhoud de tekst moet hebben en waar de tekst t.o.v. het symbool moet komen te staan. De tekst moet inhoudelijk toch vaak aangepast worden door de NLCS-tooling en het lijkt mij een kleine kunst om daarbij ook wel/niet cursief in mee te nemen.

**Comment by MvanderHulst** [comment]
@SanderNijhof 
Het scenario van optie 4 heb ik beschouwd, maar is technisch niet mogelijk.
Dan val je terug op optie 1.

Binnen AutoCAD kan je maar één definitie van het block hebben.
In dit block staat de hoogte OF rechtop OF cursief.
Als het block van status N naar B verwisseld, zouden dit dus 2 blocks moeten zijn.
1 met het attribute normaal en 1 met het attribute cursief.

Hiermee sluit je aan op de standaard NLCS regel:
Symbolen hebben voor alle statussen dezelfde presentatie. Indien de presentatie van een status anders is heeft het block de status als aanvulling in de naam.
We moeten dus krijgen (bijvoorbeeld)

SAL-HOOGTELABEL-SO      rechtop tekst
B-SAL-HOOGTELABEL-SO  cursief tekst
V-SAL-HOOGTELABEL-SO cursief tekst met kruis.

Dan ben je consequent volgens de standaard.

Op dit moment is optie 2 wel hoe het nu in de standaard zit. Waarbij het inconsequent is ten opzichte van de rest.

Al vraag ik mij wel af hoeveel symbolen met hoogtes worden toegepast inplaats van gewoon 'teksten'.

**Comment by SanderNijhof** [comment]
> Binnen AutoCAD kan je maar één definitie van het block hebben.

Als dit niet (eenvoudig) te doen is in AutoCAD dan vervalt optie 4 inderdaad.

> Als het block van status N naar B verwisseld, zouden dit dus 2 blocks moeten zijn.
> 1 met het attribute normaal en 1 met het attribute cursief.

Ik zou dit als reden willen zien om deze blocks zoveel mogelijk te beperken en waar mogelijk text en multileaders toe te passen en voorstellen bij de gebruikers om die blocks uit de NLCS te schrappen.

> Al vraag ik mij wel af hoeveel symbolen met hoogtes worden toegepast in plaats van gewoon 'teksten'.

Vraag ik me ook af. Hetzelfde vraag ik me af bij blocks voor andere teksten zoals putnummers en b.o.b.'s, tenzij dit binnen AutoCAD niet anders kan.

**Comment by MvanderHulst** [comment]
Uit een snelle screening blijkt dat voor de 'hoogte' blocks al een B-symbool aanwezig is met de attribute als cursief:
Enkel bij het wisselen van de status gaat dit mis bij InfraCAD. @Han-Loermans 
![image](https://github.com/nl-digigo/NLCS/assets/144665595/bf204879-d3ae-4cec-b125-23b271f8457e)

Voor putdekselhoogte is het symbool niet aanwezig. Hiervoor zou ook een B-symbool moeten komen.
Voor SRI-BOB-SO ontbreekt deze ook
Voor SKL-WTB_HULP_BOB-SO ontbreekt deze ook.

Voor het plaatsen van bestaande teksten wordt nu niks met 'cursief' afgedwongen, tenzij je de juiste styling kiest.
Voor zaken als symbolen als 'putdekselhoogte' is de vraag vooral: wat is de definitie van een bestaand 'bijschrift'. Anders zouden ook de putnummers e.d. voor bestaand een cursief variant moeten hebben.
In de BGT zitten ook vele symbolen met een 'tekst' erin... geldt het daar dan ook voor?

VERVALLEN zou dezelfde presentatie als bestaand moeten hebben.
Formeel hebben alle vervallen symbolen een kruis. dus ook de hoogteblocks zouden een V-variant met een kruis moeten hebben.

Zoveel vragen.... en inconsequente toepassingen te bedenken..

**Comment by ElisabethKloren** [comment]
Wat mij betreft kiest de Expertcommissie dan tussen:
1. Een uitzondering maken voor de teksten in hoogtematen in blocks
2. De hoogtematen uit de blocks verwijderen, in de documentatie opnemen dat de gebruiker hier zelf een tekstlaag bij moet aanmaken. Eventueel kunnen we in de database een groepering maken van blocks waarbij je een tekst verwacht, dan kan je daarop iets automatiseren als daar behoefte aan is bij gebruikers van de software, maar dat hoeven we niet te verplichten bij versie 5.1

**Comment by MvanderHulst** [comment]
@ElisabethKloren de vraag gaat verder dan de hoogteblock.
Het is van toepassing voor ALLE symbolen met 'teksten' erin.

- Hoogtesymbolen laten vervallen en teksten verplichten maar voor hoogtemaatvoering het onderscheid duidelijk.
- Dat symbolen met 'bijschriften' altijd rechtop zijn is volgens mij ook prima. Aan de pendikte van het symbool is te zien of iets bestaand of nieuw is.

Dit zou voor de standaard betekenen:
- hoogteblocks laten vervallen en dit altijd met teksten doen cursief/rechtop.
- bijschriften in tekst cursief/recht volgens de standaard.
- symbolen altijd rechtop, de pendikte geeft aan of het bestaand of nieuw is.

Meest consequente oplossing.

**Comment by ElisabethKloren** [comment]
> @ElisabethKloren de vraag gaat verder dan de hoogteblock. Het is van toepassing voor ALLE symbolen met 'teksten' erin.
> 
> * Hoogtesymbolen laten vervallen en teksten verplichten maar voor hoogtemaatvoering het onderscheid duidelijk.
> * Dat symbolen met 'bijschriften' altijd rechtop zijn is volgens mij ook prima. Aan de pendikte van het symbool is te zien of iets bestaand of nieuw is.
> 
> Dit zou voor de standaard betekenen:
> 
> * hoogteblocks laten vervallen en dit altijd met teksten doen cursief/rechtop.
> * bijschriften in tekst cursief/recht volgens de standaard.
> * symbolen altijd rechtop, de pendikte geeft aan of het bestaand of nieuw is.
> 
> Meest consequente oplossing.

dan is dit de voorgenomen wijziging voor versie 5.1

**Comment by MvanderHulst** [comment]
Door het laten vervallen van de hogotesymbolen, en het werken met teksten en lijndiktes voor symbolen, is deze issue eenvoudig opgelost voor 5.1
