### ISSUE TITLE
#879	13. Ondanks dat de symbolen voor verwijzingen slechts aanbevolen symbolen zijn

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#54]
#879	13. Ondanks dat de symbolen voor verwijzingen slechts aanbevolen symbolen zijn en wij zelf een ander symbool kunnen/mogen gebruiken toch de volgende opmerking. Bij het verwijzen naar een detail op een situatietekening staat de omkadering in lineweight 0.35 in de kleur zwart. Op tekening lijkt dit niet altijd goed uit de verf te komen. Daarnaast is ook het symbool om de omkadering aan te wijzen erg lijvig en valt in drukke tekeningen niet altijd handig te plaatsen. Is het mogelijk om de omkadering aan te passen naar lineweight 0.60 in een kleur 252? Is het daarnaast mogelijk om het detail gewoon met een tekst evenwijdig boven/onder de omkadering te plaatsen in plaats van het symbool met de pijlpunt. Voorbeeld is gemaild naar Corné Helmons. In dit voorbeeld is de linestyle AL-Details aangehouden en niet de linestyle volgens de formelebeschrijving

**Comment by ElisabethKloren** [comment]
Reactie Expertcommissie
zie ook #878 hier moet sowieso een keuze gemaakt geworden daarna kan er voor #879 een keuze gemaakt worden

**Comment by SanderNijhof** [comment]
Een tekst plaatsen ipv een symbool is volgens de FB toegestaan. Lineweight 0,60mm niet. *-**-AL-TEKENBLAD_KADER-G is nu 0,70mm dik en *-**-AL-TEKENBLAD_DEELKADER-G 0,18mm. Groot verschil tussne KADER en DEELKADER: 0,18mm wijzigen naar 0,50mm of 0,35mm?

**Comment by MvanderHulst** [comment]
Voorstel: AL-VERWIJZING_DETAIL continuous maken met een lineweight van 0.50

**Comment by ElisabethDeVries** [comment]
[[Release note]] Zie issue #55

**Comment by ElisabethDeVries** [comment]
reopen voor acceptatie 5.2
