### ISSUE TITLE
#878	In de formele omschrijving staat bij 4.4.4 “verwijzing naar een detail” dat er gebruikt moet worden gemaakt van een rechthoek

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#55]
#878	In de formele omschrijving staat bij 4.4.4 “verwijzing naar een detail” dat er gebruikt moet worden gemaakt van een rechthoek, vierkant of rondje met lijntype “gemengde streeplijn” voor een omkadering van een situatie. Op het voorbeeld in de formele omschrijving lijkt nu een omkadering te worden gebruikt die lijkt op een “as” (linetype AM-AS?). Echter in de objectentabel bestaat de laag *-**-AL-VERWIJZING_DETAIL-G hierbij wordt het linetype AL-DETAILS aangeven. Dit linetype ziet er echter niet uit als een “as”. Om e.e.a. dus eenduidig te maken zal óf de objectentabel óf de formele omschrijving aangepast moeten worden.

**Comment by SanderNijhof** [comment]
Het verschil tussen de lijnstijlen AL-PROFIEL-SO en ZZ-CENTER-SO is (te) minimaal. De lijnstijl AL-DETAL-SO vind ik wel goed dat die afwijkt van de overige 3 verwijzingstypen, ook al is het onderscheid er ook al door de lijndikte 0,35m ipv 0.18mm.

**Comment by MvanderHulst** [comment]
Is het noodzakelijk dat een detailaanduiding een lijntype heeft? Persoonlijk zou ik deze lekker ‘dik’ Continuous aangeven. Voorstel: lijntype geheel laten vervallen.

**Comment by ElisabethDeVries** [comment]
[[Release note]] In hoofdgroep AL heeft VERWIJZING_AANZICHT een nieuwe lijnstijl gekregen: AL-AANZICHT-SO, met een lijndikte van 0.35 in plats van 0.18. De lijnstijl AL-PROFIEL-SO vervalt, omdat deze te weinig  verschilde van ZZ-CENTER-SO. De lijnstijl van VERWIJZING_DETAIL is CONTINUOUS geworden, omdat er geen reden is om een detail een andere lijnstijl te geven; bovendien is dit onderscheidbaar door de lijndikte van 0.35 mm in plaats van 0.18 mm. Daarmee is de lijnstijl AL-PROFIEL-SO vervallen. VERWIJZING_WIJZIGING heeft een eigen lijnstijl gekregen: AL-WIJZIGING-SO vervangt ZZ-CENTER-SO.

**Comment by ElisabethDeVries** [comment]
reopen voor beoordeling acceptatie 5.2

**Comment by MvanderHulst** [comment]
Ter onderbouwing de nieuwe lijntypes:
AL	AANZICHT		SO	"A,4,-.8,.8,-.8
AL	DOORSNEDE		SO	"A,5,-1,1,-1
AL	WIJZIGING		SO	"A,5,-1,1,-1
