### ISSUE TITLE
#877	Het symbool voor tegel 150x300 en 300x150 in zogenaamd “blokverband”

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#56]
#877	Het symbool voor tegel 150x300 en 300x150 in zogenaamd “blokverband” voor dikke als dunne tegels ontbreekt.

**Comment by ElisabethKloren** [comment]
"toevoegen symbolen:
SVH-TEGEL_150X300_DIK_BLOK_KL-SO
V-SVH-TEGEL_150X300_DIK_BLOK_KL-SO
SVH-TEGEL_150X300_DUN_BLOK_KL-SO
V-SVH-TEGEL_150X300_DUN_BLOK_KL-SO
SVH-TEGEL_150X300_DIK_BLOK-SO
V-SVH-TEGEL_150X300_DIK_BLOK-SO
SVH-TEGEL_150X300_DUN_BLOK-SO
V-SVH-TEGEL_150X300_DUN_BLOK-SO
ook symbolen toevoegen in database (d.m.v. Excel)"

**Comment by SanderNijhof** [comment]
300x150 én 150x300 heeft te maken met de ligging van de richting van het halfsteensverband. Maar dat is niet voor alle afmetingen consequent doorgevoerd. Er zijn wel mogelijkheden voor verbeteringen in de verhardingsymbolen en patterns. Wellicht deze inventariseren en dan een voorstel maken voor toe te voegen dan wel te verwijderen arceringen en symbolen.

**Comment by MvanderHulst** [comment]
Ik heb een uitgebreide analyse gemaakt op alle verhardingssymbolen.
Voorstel tot te verwijderen of aan te passen symbolen opgenomen.
DWG volgt door Elisabeth.

Aanvullende symbolen volgen..
![image](https://github.com/nl-digigo/NLCS/assets/144665595/1c9ebd69-b336-4a5b-a106-3488fc194a0c)

**Comment by ElisabethKloren** [comment]
@MvanderHulst  hier staat dehet bestand: https://github.com/nl-digigo/NLCS/blob/main/ontwikkeling/bijlagen_bij_issues/56/ALLE%20SVH%20SYMBOLEN.dwg

**Comment by MvanderHulst** [comment]
Onderstaand vanuit de DWG alle rood gemarkeerde gecorrigeerde symbolen::
![image](https://github.com/nl-digigo/NLCS/assets/144665595/f326b980-28a8-4186-861b-43d0d245b6f1)

SVH-TEGEL_150X300_DIK_ELLEBOOG-SO
SVH-TEGEL_150X300_DIK_ELLEBOOG_STIP-SO
SVH-TEGEL_150X300_DUN_ELLEBOOG-SO
SVH-TEGEL_150X300_DUN_ELLEBOOG_STIP-SO
SVH-TEGEL_300X150_DIK_LINT-SO
SVH-TEGEL_300X150_DIK_LINT_STIP-SO
SVH-TEGEL_300X150_DUN_LINT-SO
SVH-TEGEL_600X200_HALFST-SO
SVH-TEGEL_600X200_LINT-SO
V-SVH-TEGEL_150X300_DIK_ELLEBOOG-SO
V-SVH-TEGEL_150X300_DIK_ELLEBOOG_STIP-SO
V-SVH-TEGEL_150X300_DUN_ELLEBOOG-SO
V-SVH-TEGEL_150X300_DUN_ELLEBOOG_STIP-SO
V-SVH-TEGEL_300X150_DIK_LINT-SO
V-SVH-TEGEL_300X150_DIK_LINT_KL-SO
V-SVH-TEGEL_300X150_DIK_LINT_STIP-SO
V-SVH-TEGEL_300X150_DUN_LINT-SO
V-SVH-TEGEL_600X200_HALFST-SO
V-SVH-TEGEL_600X200_LINT-SO

**Comment by MvanderHulst** [comment]
Voorstel te vervallen symbolen:
dit zijn allemaal niets zeggende, off amper zichtbare symbolen waarvan in verwacht dat deze NOOIT gebruikt worden.
![image](https://github.com/nl-digigo/NLCS/assets/144665595/12b024eb-b714-4107-b0e5-9790fee7c9ef)

SVH-COBBLESTONE_KL-SO
SVH-COBBLESTONE-SO
SVH-FUNDERING_BIMS_KL-SO
SVH-FUNDERING_BIMS-SO
SVH-FUNDERING_EPS_KL-SO
SVH-FUNDERING_EPS-SO
SVH-FUNDERING_GRANULAAT_KL-SO
SVH-FUNDERING_GRANULAAT_MENG_02_KL-SO
SVH-FUNDERING_GRANULAAT_MENG_02-SO
SVH-FUNDERING_GRANULAAT_PUIN_KL-SO
SVH-FUNDERING_GRANULAAT_PUIN-SO
SVH-FUNDERING_GRANULAAT_SINTELS_KL-SO
SVH-FUNDERING_GRANULAAT_SINTELS-SO
SVH-FUNDERING_GRANULAAT-SO
SVH-FUNDERING_OVERIG_KL-SO
SVH-FUNDERING_OVERIG-SO
SVH-GESLOTEN_KL-SO
SVH-GESLOTEN-SO
SVH-GLAS_KL-SO
SVH-GLAS-SO
SVH-HALFVERHARDING_01-SO
SVH-HALFVERHARDING_GRIND_02_KL-SO
SVH-HALFVERHARDING_GRIND_02-SO
SVH-HOUTSNIPPERS_KL-SO
SVH-HOUTSNIPPERS-SO
SVH-HSTEEN_KL-SO
SVH-HSTEEN-SO
SVH-KALKZANDSTEEN_KL-SO
SVH-KALKZANDSTEEN-SO
SVH-METSELWERK_KL-SO
SVH-METSELWERK-SO
SVH-NATUURSTEEN_02_KL-SO
SVH-NATUURSTEEN_02-SO
SVH-SIERBESTRATING_02_KL-SO
SVH-SIERBESTRATING_02-SO
SVH-SIERTEGEL_KL-SO
SVH-SIERTEGEL-SO
SVH-SPECIAAL_01_KL-SO
SVH-SPECIAAL_01-SO
SVH-SPECIAAL_02_KL-SO
SVH-SPECIAAL_02-SO
SVH-SPECIAAL_OVERIG_01_KL-SO
SVH-SPECIAAL_OVERIG_01-SO
SVH-SPECIAAL_OVERIG_02_KL-SO
SVH-SPECIAAL_OVERIG_02-SO
SVH-SPECIAAL_OVERIG_KOPSHOUT_KL-SO
SVH-SPECIAAL_OVERIG_KOPSHOUT-SO
SVH-SPECIAAL_OVERIG_LANGSHOUT_KL-SO
SVH-SPECIAAL_OVERIG_LANGSHOUT-SO
SVH-SPECIAAL_OVERIG_TRANENPLAAT_01_KL-SO
SVH-SPECIAAL_OVERIG_TRANENPLAAT_01-SO
SVH-SPECIAAL_OVERIG_TRANENPLAAT_02_KL-SO
SVH-SPECIAAL_OVERIG_TRANENPLAAT_02-SO
V-SVH-COBBLESTONE_KL-SO
V-SVH-COBBLESTONE-SO
V-SVH-FUNDERING_BIMS_KL-SO
V-SVH-FUNDERING_BIMS-SO
V-SVH-FUNDERING_EPS_KL-SO
V-SVH-FUNDERING_EPS-SO
V-SVH-FUNDERING_GRANULAAT_KL-SO
V-SVH-FUNDERING_GRANULAAT_MENG_02_KL-SO
V-SVH-FUNDERING_GRANULAAT_MENG_02-SO
V-SVH-FUNDERING_GRANULAAT_PUIN_KL-SO
V-SVH-FUNDERING_GRANULAAT_PUIN-SO
V-SVH-FUNDERING_GRANULAAT_SINTELS_KL-SO
V-SVH-FUNDERING_GRANULAAT_SINTELS-SO
V-SVH-FUNDERING_GRANULAAT-SO
V-SVH-FUNDERING_OVERIG_KL-SO
V-SVH-FUNDERING_OVERIG-SO
V-SVH-GESLOTEN_KL-SO
V-SVH-GESLOTEN-SO
V-SVH-GLAS_KL-SO
V-SVH-GLAS-SO
V-SVH-HALFVERHARDING_01-SO
V-SVH-HALFVERHARDING_GRIND_02_KL-SO
V-SVH-HALFVERHARDING_GRIND_02-SO
V-SVH-HOUTSNIPPERS_KL-SO
V-SVH-HOUTSNIPPERS-SO
V-SVH-HSTEEN_KL-SO
V-SVH-HSTEEN-SO
V-SVH-KALKZANDSTEEN_KL-SO
V-SVH-KALKZANDSTEEN-SO
V-SVH-METSELWERK_KL-SO
V-SVH-METSELWERK-SO
V-SVH-NATUURSTEEN_02_KL-SO
V-SVH-NATUURSTEEN_02-SO
V-SVH-SIERBESTRATING_02_KL-SO
V-SVH-SIERBESTRATING_02-SO
V-SVH-SIERTEGEL_KL-SO
V-SVH-SIERTEGEL-SO
V-SVH-SPECIAAL_01_KL-SO
V-SVH-SPECIAAL_01-SO
V-SVH-SPECIAAL_02_KL-SO
V-SVH-SPECIAAL_02-SO
V-SVH-SPECIAAL_OVERIG_01_KL-SO
V-SVH-SPECIAAL_OVERIG_01-SO
V-SVH-SPECIAAL_OVERIG_02_KL-SO
V-SVH-SPECIAAL_OVERIG_02-SO
V-SVH-SPECIAAL_OVERIG_KOPSHOUT_KL-SO
V-SVH-SPECIAAL_OVERIG_KOPSHOUT-SO
V-SVH-SPECIAAL_OVERIG_LANGSHOUT_KL-SO
V-SVH-SPECIAAL_OVERIG_LANGSHOUT-SO
V-SVH-SPECIAAL_OVERIG_TRANENPLAAT_01_KL-SO
V-SVH-SPECIAAL_OVERIG_TRANENPLAAT_01-SO
V-SVH-SPECIAAL_OVERIG_TRANENPLAAT_02_KL-SO
V-SVH-SPECIAAL_OVERIG_TRANENPLAAT_02-SO

**Comment by MvanderHulst** [comment]
Voorstel voor alle te vervallen TEGEL symbolen.
Dit zijn all varianten met de 'stip' of 'strepen' erin.
Nnood hoeven toepassen en totaal overbodige noodzaak.
Alle standaard symbolen hebben al 2 attributes, waarin je alles kwijt kan.
![image](https://github.com/nl-digigo/NLCS/assets/144665595/04412316-9851-49a4-83c9-24381ddfe062)

SVH-TEGEL_150X300_DIK_ELLEBOOG_STIP_KL-SO
SVH-TEGEL_150X300_DIK_ELLEBOOG_STIP-SO
SVH-TEGEL_150X300_DUN_ELLEBOOG_STIP_KL-SO
SVH-TEGEL_150X300_DUN_ELLEBOOG_STIP-SO
SVH-TEGEL_300X150_DIK_ELLEBOOG_STIP_KL-SO
SVH-TEGEL_300X150_DIK_ELLEBOOG_STIP-SO
SVH-TEGEL_300X150_DIK_HALFST_STIP_KL-SO
SVH-TEGEL_300X150_DIK_HALFST_STIP-SO
SVH-TEGEL_300X150_DIK_LINT_STIP_KL-SO
SVH-TEGEL_300X150_DIK_LINT_STIP-SO
SVH-TEGEL_300X150_DUN_ELLEBOOG_STIP_KL-SO
SVH-TEGEL_300X150_DUN_ELLEBOOG_STIP-SO
SVH-TEGEL_300X150_DUN_HALFST_STIP_KL-SO
SVH-TEGEL_300X150_DUN_HALFST_STIP-SO
SVH-TEGEL_300X150_DUN_LINT_STIP_KL-SO
SVH-TEGEL_300X150_DUN_LINT_STIP-SO
SVH-TEGEL_300X300_DIK_BLOK_STIP_KL-SO
SVH-TEGEL_300X300_DIK_BLOK_STIP-SO
SVH-TEGEL_300X300_DIK_HALFST_STIP_KL-SO
SVH-TEGEL_300X300_DIK_HALFST_STIP-SO
SVH-TEGEL_300X300_DIK_LINT_STIP_KL-SO
SVH-TEGEL_300X300_DIK_LINT_STIP-SO
SVH-TEGEL_300X300_DUN_BLOK_STIP_KL-SO
SVH-TEGEL_300X300_DUN_BLOK_STIP-SO
SVH-TEGEL_300X300_DUN_HALFST_STIP_KL-SO
SVH-TEGEL_300X300_DUN_HALFST_STIP-SO
SVH-TEGEL_300X300_DUN_LINT_STIP_KL-SO
SVH-TEGEL_300X300_DUN_LINT_STIP-SO
SVH-TEGEL_400X400_HALFST_STIP_KL-SO
SVH-TEGEL_400X400_HALFST_STIP-SO
SVH-TEGEL_400X400_HALFST_STREEP_KL-SO
SVH-TEGEL_400X400_HALFST_STREEP-SO
SVH-TEGEL_400X400_LINT_STIP_KL-SO
SVH-TEGEL_400X400_LINT_STIP-SO
SVH-TEGEL_400X400_LINT_STREEP_KL-SO
SVH-TEGEL_400X400_LINT_STREEP-SO
SVH-TEGEL_600X600_HALFST_STIP-SO
SVH-TEGEL_600X600_LINT_STIP_KL-SO
SVH-TEGEL_600X600_LINT_STIP-SO
SVH-TEGEL_BLOK_STIP_01_KL-SO
SVH-TEGEL_BLOK_STIP_01-SO
SVH-TEGEL_BLOK_STIP_02_KL-SO
SVH-TEGEL_BLOK_STIP_02-SO
V-SVH-TEGEL_150X300_DIK_ELLEBOOG_STIP_KL-SO
V-SVH-TEGEL_150X300_DIK_ELLEBOOG_STIP-SO
V-SVH-TEGEL_150X300_DUN_ELLEBOOG_STIP_KL-SO
V-SVH-TEGEL_150X300_DUN_ELLEBOOG_STIP-SO
V-SVH-TEGEL_300X150_DIK_ELLEBOOG_STIP_KL-SO
V-SVH-TEGEL_300X150_DIK_ELLEBOOG_STIP-SO
V-SVH-TEGEL_300X150_DIK_HALFST_STIP_KL-SO
V-SVH-TEGEL_300X150_DIK_HALFST_STIP-SO
V-SVH-TEGEL_300X150_DIK_LINT_STIP_KL-SO
V-SVH-TEGEL_300X150_DIK_LINT_STIP-SO
V-SVH-TEGEL_300X150_DUN_ELLEBOOG_STIP_KL-SO
V-SVH-TEGEL_300X150_DUN_ELLEBOOG_STIP-SO
V-SVH-TEGEL_300X150_DUN_HALFST_STIP_KL-SO
V-SVH-TEGEL_300X150_DUN_HALFST_STIP-SO
V-SVH-TEGEL_300X150_DUN_LINT_STIP_KL-SO
V-SVH-TEGEL_300X150_DUN_LINT_STIP-SO
V-SVH-TEGEL_300X300_DIK_BLOK_STIP_KL-SO
V-SVH-TEGEL_300X300_DIK_BLOK_STIP-SO
V-SVH-TEGEL_300X300_DIK_HALFST_STIP_KL-SO
V-SVH-TEGEL_300X300_DIK_HALFST_STIP-SO
V-SVH-TEGEL_300X300_DIK_LINT_STIP_KL-SO
V-SVH-TEGEL_300X300_DIK_LINT_STIP-SO
V-SVH-TEGEL_300X300_DUN_BLOK_STIP_KL-SO
V-SVH-TEGEL_300X300_DUN_BLOK_STIP-SO
V-SVH-TEGEL_300X300_DUN_HALFST_STIP_KL-SO
V-SVH-TEGEL_300X300_DUN_HALFST_STIP-SO
V-SVH-TEGEL_300X300_DUN_LINT_STIP_KL-SO
V-SVH-TEGEL_300X300_DUN_LINT_STIP-SO
V-SVH-TEGEL_400X400_HALFST_STIP_KL-SO
V-SVH-TEGEL_400X400_HALFST_STIP-SO
V-SVH-TEGEL_400X400_HALFST_STREEP_KL-SO
V-SVH-TEGEL_400X400_HALFST_STREEP-SO
V-SVH-TEGEL_400X400_LINT_STIP_KL-SO
V-SVH-TEGEL_400X400_LINT_STIP-SO
V-SVH-TEGEL_400X400_LINT_STREEP_KL-SO
V-SVH-TEGEL_400X400_LINT_STREEP-SO
V-SVH-TEGEL_600X600_HALFST_STIP-SO
V-SVH-TEGEL_600X600_LINT_STIP_KL-SO
V-SVH-TEGEL_600X600_LINT_STIP-SO
V-SVH-TEGEL_BLOK_STIP_01_KL-SO
V-SVH-TEGEL_BLOK_STIP_01-SO
V-SVH-TEGEL_BLOK_STIP_02_KL-SO
V-SVH-TEGEL_BLOK_STIP_02-SO

**Comment by SanderNijhof** [comment]
En dan doe ik weer een oud voorstel: geen extra _KL-SO symbolen meer maar één goed symbool per object. Scheelt ook weer een heleboel symbolen. Waarom moet je een groot én een klein symbool hebben?

**Comment by MvanderHulst** [comment]
@SanderNijhof voor nu focus ik mij nog even op de 'huidige' symbolen. Om daar een flinke bezem doorheen te halen.
De kleine symbolen hoeven van mij ook niet, gezien die niet leesbaar zijn.
Ik pas dan liever een clipping toe op de grote symbolen indien nodig.

**Comment by MvanderHulst** [comment]
Volgende stap is de controle op noodzaak:
mijn referentiekader:
![image](https://github.com/nl-digigo/NLCS/assets/144665595/e7c5a2cc-58c2-4376-a917-9f27c47de4d7)

Voorstel te vervallen:
SVH-TEGEL_1000X1000_BLOK_KL-SO
SVH-TEGEL_1000X1000_BLOK-SO
SVH-TEGEL_1000X1000_HALFST_KL-SO
SVH-TEGEL_1000X1000_HALFST-SO
SVH-TEGEL_100X300_HALFST_KL-SO
SVH-TEGEL_100X300_HALFST-SO
SVH-TEGEL_100X300_LINT_KL-SO
SVH-TEGEL_100X300_LINT-SO
SVH-TEGEL_2000X2000_BLOK_KL-SO
SVH-TEGEL_2000X2000_BLOK-SO
SVH-TEGEL_2000X2000_HALFST_KL-SO
SVH-TEGEL_2000X2000_HALFST-SO
SVH-TEGEL_2000X2000_LINT_KL-SO
SVH-TEGEL_2000X2000_LINT-SO
SVH-TEGEL_200X300_HALFST_KL-SO
SVH-TEGEL_200X300_HALFST-SO
SVH-TEGEL_200X300_LINT_KL-SO
SVH-TEGEL_200X300_LINT-SO
SVH-TEGEL_200X600_HALFST_KL-SO
SVH-TEGEL_200X600_HALFST-SO
SVH-TEGEL_200X600_LINT_KL-SO
SVH-TEGEL_200X600_LINT-SO
SVH-TEGEL_300X200_HALFST_KL-SO
SVH-TEGEL_300X200_HALFST-SO
SVH-TEGEL_300X200_LINT_KL-SO
SVH-TEGEL_300X200_LINT-SO
SVH-TEGEL_600X200_HALFST_KL-SO
SVH-TEGEL_600X200_HALFST-SO
SVH-TEGEL_600X200_LINT_KL-SO
SVH-TEGEL_600X200_LINT-SO
SVH-TEGEL_600X600_BLOK_KL-SO
SVH-TEGEL_600X600_BLOK-SO
SVH-TEGEL_600X600_HALFST_KL-SO
SVH-TEGEL_600X600_HALFST_STIP_KL-SO
SVH-TEGEL_600X600_HALFST-SO
SVH-TEGEL_600X600_LINT_KL-SO
SVH-TEGEL_600X600_LINT-SO
V-SVH-TEGEL_1000X1000_BLOK_KL-SO
V-SVH-TEGEL_1000X1000_BLOK-SO
V-SVH-TEGEL_1000X1000_HALFST_KL-SO
V-SVH-TEGEL_1000X1000_HALFST-SO
V-SVH-TEGEL_100X300_HALFST_KL-SO
V-SVH-TEGEL_100X300_HALFST-SO
V-SVH-TEGEL_100X300_LINT_KL-SO
V-SVH-TEGEL_100X300_LINT-SO
V-SVH-TEGEL_2000X2000_BLOK_KL-SO
V-SVH-TEGEL_2000X2000_BLOK-SO
V-SVH-TEGEL_2000X2000_HALFST_KL-SO
V-SVH-TEGEL_2000X2000_HALFST-SO
V-SVH-TEGEL_2000X2000_LINT_KL-SO
V-SVH-TEGEL_2000X2000_LINT-SO
V-SVH-TEGEL_200X300_HALFST_KL-SO
V-SVH-TEGEL_200X300_HALFST-SO
V-SVH-TEGEL_200X300_LINT_KL-SO
V-SVH-TEGEL_200X300_LINT-SO
V-SVH-TEGEL_200X600_HALFST_KL-SO
V-SVH-TEGEL_200X600_HALFST-SO
V-SVH-TEGEL_200X600_LINT_KL-SO
V-SVH-TEGEL_200X600_LINT-SO
V-SVH-TEGEL_300X200_HALFST_KL-SO
V-SVH-TEGEL_300X200_HALFST-SO
V-SVH-TEGEL_300X200_LINT_KL-SO
V-SVH-TEGEL_300X200_LINT-SO
V-SVH-TEGEL_600X200_HALFST_KL-SO
V-SVH-TEGEL_600X200_HALFST-SO
V-SVH-TEGEL_600X200_LINT_KL-SO
V-SVH-TEGEL_600X200_LINT-SO
V-SVH-TEGEL_600X600_BLOK_KL-SO
V-SVH-TEGEL_600X600_BLOK-SO
V-SVH-TEGEL_600X600_HALFST_KL-SO
V-SVH-TEGEL_600X600_HALFST_STIP_KL-SO
V-SVH-TEGEL_600X600_HALFST-SO
V-SVH-TEGEL_600X600_LINT_KL-SO
V-SVH-TEGEL_600X600_LINT-SO

**Comment by MvanderHulst** [comment]
We zijn er bijna:
De restanten van de dubbele naamgevingen zijn:
![image](https://github.com/nl-digigo/NLCS/assets/144665595/0a856dfd-4d91-4c32-93d9-c95f518d3961)

De symbolen voor 'elleboogverband' zijn identieke symbolen en is verschil van verband en legrichting dus niet aan de orde.
Te vervallen:
V-SVH-TEGEL_150X300_DIK_ELLEBOOG_KL-SO
V-SVH-TEGEL_150X300_DIK_ELLEBOOG-SO
SVH-TEGEL_150X300_DIK_ELLEBOOG_KL-SO
SVH-TEGEL_150X300_DIK_ELLEBOOG-SO
SVH-TEGEL_150X300_DUN_ELLEBOOG-SO
SVH-TEGEL_150X300_DUN_ELLEBOOG_KL-SO
V-SVH-TEGEL_150X300_DUN_ELLEBOOG-SO
V-SVH-TEGEL_150X300_DUN_ELLEBOOG_KL-SO


Dan blijft over:
Waarbij van de onderste series het veschil in het verband zichtbaar is.
![image](https://github.com/nl-digigo/NLCS/assets/144665595/bb939836-f3fd-495f-b620-145064e3da4d)

**Comment by MvanderHulst** [comment]
Na alle acties is dit het voorstel voor de symbolen voor hoofdgroep VH.
https://github.com/nl-digigo/NLCS/blob/main/ontwikkeling/bijlagen_bij_issues/56/DEFINITIEFTOTAAL%20NIEUWE.dwg

waarin een behoorlijke opschoonactie is gedaan.

**Comment by MvanderHulst** [comment]
Niet te vergeten, de aanvullende symbolen waar de issue mee is begonnen:
![image](https://github.com/nl-digigo/NLCS/assets/144665595/83b87c45-bcdd-417f-aac9-400c9588af8f)

Aanvullingen::
SVH-TEGEL_300X150_DIK_BLOK_01-SO
SVH-TEGEL_300X150_DIK_BLOK_KL_01-SO
SVH-TEGEL_300X150_DIK_BLOK_KL-SO
SVH-TEGEL_300X150_DIK_BLOK-SO
SVH-TEGEL_300X150_DUN_BLOK_01-SO
SVH-TEGEL_300X150_DUN_BLOK_KL_01-SO
SVH-TEGEL_300X150_DUN_BLOK_KL-SO
SVH-TEGEL_300X150_DUN_BLOK-SO
V-SVH-TEGEL_300X150_DIK_BLOK_01-SO
V-SVH-TEGEL_300X150_DIK_BLOK_KL_01-SO
V-SVH-TEGEL_300X150_DIK_BLOK_KL-SO
V-SVH-TEGEL_300X150_DIK_BLOK-SO
V-SVH-TEGEL_300X150_DUN_BLOK_01-SO
V-SVH-TEGEL_300X150_DUN_BLOK_KL_01-SO
V-SVH-TEGEL_300X150_DUN_BLOK_KL-SO
V-SVH-TEGEL_300X150_DUN_BLOK-SO

**Comment by SanderNijhof** [comment]
Het zou mooi zijn als er voor elk object 1 duidelijk symbool is en niet een grote én kleine variant. Bijv. bij grote tegelformaten is in het KL-symbool het tegelpatroon niet herkenbaar en het KL-symbool niet duidelijk.

Jouw voorbeeld hierboven: zou het 1:500 symbool juist niet kleiner dan het 1:200 symbool moeten zijn, of maximaal even groot als het 1:200 symbool? Waarom is het 1:500 symbool groter dan het 1:200 symbool?

**Comment by SanderNijhof** [comment]
Aanvullend: in de symbolen staan de maten in cm. Conform NLCS zijn materiaalmaten in mm. Dus of de symbolen aanpassen of een uitzondering opnemen in de FB.

**Comment by MvanderHulst** [comment]
> Aanvullend: in de symbolen staan de maten in cm. Conform NLCS zijn materiaalmaten in mm. Dus of de symbolen aanpassen of een uitzondering opnemen in de FB.

Helemaal mee eens, deze opmerking heb ik ook al meerdere malen van mijn projectleiders gekregen.
Zou gewoon 300x300 moeten zijn bijvoorbeeld.

Persoonlijk vindt ik de standaard aanvullen 30x30 totaaal niet relevant.
Ik haal het dan meestal ook weg en verklaar het symbool in mijn legenda met de afmetingen.
Pas bij meerdere kleuren/afmetingen ga ik de attributes gebruiken voor verder specifieren.

**Comment by NielsNederpel** [comment]
> Jouw voorbeeld hierboven: zou het 1:500 symbool juist niet kleiner dan het 1:200 symbool moeten zijn, of maximaal even groot als het 1:200 symbool? Waarom is het 1:500 symbool groter dan het 1:200 symbool?

ik gaf al aan dat dit even 1:1 is aangegeven...had even snel een plaatje in model gemaakt....maar dan maar even "officieel"
maar gaat er dus om dat vaak de "normale"verhardingssymbolen bij 1:500 te groot zijn om binnen een v(l)ak te plaatsen....waardoor we dus eigenlijk alleen maar de -KL varianten gebruiken.

![image](https://github.com/nl-digigo/NLCS/assets/143591987/916846af-9f8b-47e0-abd8-c3a2b16a1fd4)

> Helemaal mee eens, deze opmerking heb ik ook al meerdere malen van mijn projectleiders gekregen.
Zou gewoon 300x300 moeten zijn bijvoorbeeld.
Persoonlijk vindt ik de standaard aanvullen 30x30 totaaal niet relevant.
Ik haal het dan meestal ook weg en verklaar het symbool in mijn legenda met de afmetingen.
Pas bij meerdere kleuren/afmetingen ga ik de attributes gebruiken voor verder specifieren.

klopt hier inderdaad ook...meestal niet in "tekening" en alleen in verklaring

**Comment by SanderNijhof** [comment]
Ik bedoelde of het niet zo zou moeten zijn:
![image](https://github.com/nl-digigo/NLCS/assets/143598041/9c6bdebb-776d-4214-9e1c-0a8d0dfa999e)
Dus dat het symbool 1:500 2,5x kleiner wordt.

**Comment by NielsNederpel** [comment]
nee dat is niet hoe e.e.a. hoort te werken....het zijn namelijk annotatieve symbolen... dus symbool moet net zo groot blijven op elke schaal, anders wordt het dus, zoals je al ziet in jou voorbeeld, te klein en is e.e.a. niet meer te onderscheiden.

**Comment by MvanderHulst** [comment]
In de MODEL is het 1:500 symbool juist 2,5x groter dan het 1:200 symbool.
In de LAyout wordt de verschaling van de viewport gedaan, waardoor ze op papier weer even groot weergegeven worden.

**Comment by SanderNijhof** [comment]
Dat is een persoonlijke keuze maar is nooit NLCS-standaard geweest en hoort dat ook niet te zijn.

**Comment by MvanderHulst** [comment]
> Dat is een persoonlijke keuze maar is nooit NLCS-standaard geweest en hoort dat ook niet te zijn.

Het beschreven gedrag is het Annotatieve gedrag van AutoCAD. oftewel -SO ;-)

**Comment by SanderNijhof** [comment]
> oftewel -SO ;-)

Expliciet benoemd in de NLCS-EC: -SO staat **niet** gelijk aan annotatief.

**Comment by NielsNederpel** [comment]
zo wordt dit echter wel aangeboden door de leveranciers en over -SO hebben we al een "controversieel" issue lopen...dus laten we dat even daar houden...
mijn vraag is nu meer
blijven we dan voor 5.1 nu in ieder geval zowel de kl als de niet -kl symbolen aanbieden? 
anders maak ik deze ook controversieel...tenzij er goede symbolen komen die zowel voor 1:200 als 1:500 gebruikt kunnen worden. en zoals aangegeven dan pleit ik juist voor de -kl versie. zoals aangegeven in mijn voorbeeld

**Comment by NielsNederpel** [comment]
#380

**Comment by MvanderHulst** [comment]
De 'grote' en 'kleine' symbolen mogen wat mij betreft gewoon blijven.
De weergave daarvan kan inderdaad wel wat beter. maar dat is weer een andere discussie. ;-)

In bovenstaande voorstel heb ik de bestaande bibliotheek even flink op de schop genomen, maar de huidige logica wel in stand gehouden.

**Comment by ElisabethDeVries** [comment]
[[Release note]] In de hoofdgroep VH zijn alle symbolen voor tegels doorgelicht op problemen met schaal, ontbrekende varianten KL (klein oppervlak, aanpassing symbool voor leesbaarheid). Ook zijn materiaalmaten in cm aangepast naar materiaalmaten in mm, dit is de standaard methode in NLCS.

**Comment by SanderNijhof** [comment]
Ik zie de _KL-systematiek eerder als een bron van complexiteit dan als een oplossing. De _KL-varianten zorgen ervoor dat één object met meerdere symbolen kan worden weergegeven. Dat maakt implementaties complexer en kan binnen één tekening tot verschillende presentaties van hetzelfde object leiden. Denk hierbij ook aan gegevensuitwisseling en koppelingen met beheersystemen.
Daarom zou ik eerder pleiten voor het uitfaseren van _KL-varianten dan voor het toevoegen van nieuwe.
