### ISSUE TITLE
#840	Linestyle RI-GWA-V lijkt niet op de linestyle RI-GWA.

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#57]
#840	Linestyle RI-GWA-V lijkt niet op de linestyle RI-GWA. Dit terwijl de linestyle RI-GWA_BETON_EI-V wel lijkt op RI-GWA. Waarom is er voor gekozen om het generieke linestyle niet te matchen? terwijl generiek HWA, GWA, SWA wel matcht. Daarnaast zijn er voor alle verschillende materialen onder 1 type stelsel verschillende linestylen. Dit is erg onrustig en door slechts de minimale afwijking tussen de linestylen is het “op papier” toch niet uit elkaar te houden. Is het wenselijk om voor alle verschillende materialen aparte linestylen te hebben?

**Comment by ElisabethKloren** [comment]
Reactie Expertcommissie
opmerking tbv lijnstyle GWA terecht overige opmerking niet meer van toepassing

**Comment by ElisabethKloren** [comment]
To Do
"aanpassen lijnstyle :
V-RI-GWA-SO => zodat deze gelijk wordt aan RI-GWA-SO maar dan met schrap (d.m.v. Excel)"

**Comment by MvanderHulst** [comment]
*V-RI-GWA-SO,332
A,3,[VERWIJDEREN2,NLCS,s=1],3,-1.8,1.75,-1.8,.875,[VERWIJDEREN2,NLCS,s=1],.875,-1.8,1.75,-1.8

![image](https://github.com/nl-digigo/NLCS/assets/144665595/578f997a-cb32-4613-b07c-6d0595e78a1d)

**Comment by ElisabethKloren** [comment]
lijnstijl aangepast in database
