### ISSUE TITLE
#839	Linestylen RI-DRAINAGE en RI-GWA lijken te veel op elkaar. Kan hier een ander linestyle voor bedacht worden?

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#58]
#839	Linestylen RI-DRAINAGE en RI-GWA lijken te veel op elkaar. Kan hier een ander linestyle voor bedacht worden?

**Comment by ElisabethKloren** [comment]
Reactie Expertcommissie
"opmerking is terecht: 
kunnen we hier het ""vervallen"" lijntype SWA voor gebruiken? Zie #1476"

**Comment by ElisabethKloren** [comment]
To Do
"Aanpassen lijnstyle:
RI-DRAINAGE-SO => definitie aanpassen (d.m.v. Excel)"

**Comment by MvanderHulst** [comment]
Niet eens met het voorstel, gezien er wel meer ‘gekke’ dingen inzitten.
Voorstel:
![image](https://github.com/nl-digigo/NLCS/assets/144665595/40aaf13d-c7e1-4fdb-93b7-bd1f127f0e8f)

Hiermee is 'vuilwater' altijd met een 'puntje' in het lijntype
en HWA / IT enkel met streepjes.

Dat is in de bestaande situatie totaal niet logisch, waarbij DWA 1 puntje heeft en ITR 2 puntjes.
Bijna gelijke presentatie met verschillende betekenissen.

**Comment by MvanderHulst** [comment]
zie ook #131

**Comment by ElisabethDeVries** [comment]
[[Release note]] De lijnstijlen van de rioleringsstelsels zijn herzien, zodat ze goed te onderscheiden zijn.
