### ISSUE TITLE
#1702 Meerdere ZZ linetypes hebben geen V- variant.

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#6]
Meerdere ZZ linetypes hebben geen V- variant.

**Comment by ElisabethKloren** [comment]
Reactie Expertcommissie:  mogelijk niet voor alle ZZ-lijnstylen, voorstel maken van welke objecten welke V-ZZ lijnstyle krijgen.

**Comment by ElisabethKloren** [comment]
Actie: lijnstyle maken en toepassen op

**Comment by MvanderHulst** [comment]
Hoofdgroep ZZ bevat op dit moment de volgende linetypes:
Standaard naaam:			Vervallen naam:			Opmerking
ZZ-AFBREEKLIJN-SO								Geen vervallen noodzakelijk?
ZZ-CENTER-SO									Linetype overbodig?
ZZ-DASHDOT-SO									Linetype overbodig?
ZZ-FASEGGRENS-SO								Plausibel
ZZ-HART-SO										Plausibel
ZZ-HIDDEN-SO									Geen vervallen noodzakelijk?
ZZ-ONDERZOEKSGRENS-SO							Plausibel
ZZ-PROJECTGRENS-SO		V-ZZ-PROJECTGRENS-SO	Vervallen linetype overbodig?
ZZ-STRAMIEN-SO									Plausibel
ZZ-SYSTEEMGRENS-SO		V-ZZ-SYSTEEMGRENS-SO	Vervallen linetype overbodig?
ZZ-WERKGRENS-SO		V-ZZ-WERKGRENS-SO		Vervallen linetype overbodig?

Vraag aan EC: zien we noodzaak voor uitbreiding of eerder opschoning?

**Comment by ElisabethKloren** [comment]
@MvanderHulst alleen het lijntype laten vervallen en vrijlaten, of bedoel je: in ZZ het hele object niet meer opnemen? bijvoorbeeld ZZ-DASHDOT-SO dus uit de objectentabel van zz verwijderen?

**Comment by MvanderHulst** [comment]
@ElisabethKloren alle objecten in de NLCS hebben een linetype, die overeenkomt met het OBJECT.
De toepassing van ZZ-HIDDEN-SO is logisch om een lijn gestippeld te maken.
De rest van de algemene 'AutoCAD' lijntypes zijn nergens voor nodig.
In de database wordt ZZ-DASHDOT-SO voor slechts 2 objecten toegepast, dit is in issue #416 

Korte antwoord:
Ja, lijntype ZZ-CENTER-SO en ZZ-DASHDOT-SO mag van mij volledig verdwijnen uit de NLCS.
Hiervoor is een voorstel voor een ander lijntype bij het betreffende OBJECT.

**Comment by ElisabethDeVries** [comment]
[[Release note]] Lijntypes ZZ-CENTER-SO en ZZ-DASHDOT-SO worden niet meer gebruikt. Indien een dergelijk lijntype nodig is, wordt een lijntypes aangemaakt bij het object.
