### ISSUE TITLE
#827	Er bestaan geen doorsnede symbolen voor 280/300x160 en 280/300x250 banden

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#61]
#827	Er bestaan geen doorsnede symbolen voor 280/300x160 en 280/300x250 banden

**Comment by ElisabethKloren** [comment]
Reactie Expertcommissie
opmerking is terecht:

**Comment by ElisabethKloren** [comment]
To Do
"symbolen toevoegen:
B-SVH-KANTOPSLUITING_TROTTOIRBAND_280 300X250-D
SVH-KANTOPSLUITING_TROTTOIRBAND_280 300X250-D
B-SVH-KANTOPSLUITING_TROTTOIRBAND_280 300X160-D
SVH-KANTOPSLUITING_TROTTOIRBAND_280 300X160-D
ook symbolen toevoegen in database (d.m.v. Excel)"

**Comment by MvanderHulst** [comment]
Bovenstaande maatvoeringen bestaan volgens mij niet. hoogtes zijn 150, 200, 240 en 300 mm
160 en 250 kan ik nergens vinden.

**Comment by MvanderHulst** [comment]
Zoals ook voorgesteld in issue #33 een 'ergens' ook verzocht door Sander.
alle doorsnedes kantopsluitingen mogen m.i. komen te vervallen.

**Comment by ElisabethKloren** [comment]
Afhandeling issue volgens #33

**Comment by MvanderHulst** [comment]
@ElisabethKloren 
Issue 33 gaat over de toepassing van spaties.

Voor deze issue is de vraag of we alle DOORSNEDE symbolen willen blijven aanbieden. Dit zijn er ook extreem veel.

**Comment by ElisabethKloren** [comment]
wat mij betreft houden we deze symbolen ,dat het er veel zijn is geen argument. Als deze maten niet te vinden zijn bij leveranciers zijn het wellicht oude maten die nog wel bestaand voorkomen. Mijn voorstel is ze op te nemen omdat deze gebruiker ze tegenkomt.

**Comment by ElisabethDeVries** [comment]
[[Release note]] In de hoofdgroep VH (VerHardingen) is voor alle kantopsluitingen ook een doorsnede-symbool toegevoegd waar deze ontbrak.
