### ISSUE TITLE
#821	"In de NLCS Database staat bijv. het Object KOLK op Geometrie en Symbool, maar de children verwijzen alleen naar Geometrie.

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#62]
#821	"In de NLCS Database staat bijv. het Object KOLK op Geometrie en Symbool, maar de children verwijzen alleen naar Geometrie.

Mijn inziens moeten hier ook Symbolen aan worden toegevoegd.

Na een quickscan heb ik momenteel het volgende gevonden, voor de XX moet je alle bestaande subobjecten lezen die verder onder het NLCS Object vallen.

Met betrekking tot de verharding geldt dit voor zowel patronen als symbolen en riool alleen de symbolen.

Het probleem is dus, dat je bijvoorbeeld voor Verharding wel arcering op de laag tbv ASFALT kunt plaatsen, maar geen ASFALT arcering op de laag ASFALT_ZOAB.  Hier geldt dat bepaalde arceringen dan ook niet op de daarvoor bestemde laag kunnen worden geplaatst (patroon FREESVAK op laag ASFALT_FREESVAK).

ARCERINGEN/ SYMBOLEN

VH   VERHARDING   FUNDERING                     XX
VH   VERHARDING   BETON                             XX
VH   VERHARDING   BEDRIJFSVLOERPLAAT   XX
VH   VERHARDING   ASFALT                           XX

SYMBOLEN

RI   GWA   KOLK  XX
RI   HWA   KOLK  XX
RI   ITR      KOLK  XX
RI   SWA   KOLK  XX"

**Comment by ElisabethKloren** [comment]
Reactie Expertcommissie
"opmerking is terecht: (althans op 5.0)
voorheen symbolen/arceringen op een niveau hoger, maar met 5.0 niet meer.

Bij de genoemde kolken symbolen is dit ook reeds aangepast in 5.0. 

Zijn dit de enige objecten waarbij dit nu nog niet goed in database zit?"

**Comment by ElisabethKloren** [comment]
To Do
"checken of hetgeen aangepast in FB (symbolen/arceringen worden op de laag geplaatst van het NLCS object dat met het symbool/arcering wordt weergegeven) doorgevoerd dient te worden in overige bibliotheken. zo ja deze aanpassen (m.b.v. Excel)

In ieder geval de volgende objecten de kolom tbv arceringen invullen (m.b.v. Excel) nav de melding 
FUNDERING_**
GESLOTENVERHARDING_BETON_**
GESLOTENVERHARDING_ASFALT

voor BEDRIJFSVLOERPLAAT geen arcering?

In ieder geval de volgende objecten de kolom tbv symbolen invullen (m.b.v. Excel)
FUNDERING_**
GESLOTENVERHARDING_BETON_**
GESLOTENVERHARDING_ASFALT

voor BEDRIJFSVLOERPLAAT geen symbool?"

**Comment by MvanderHulst** [comment]
Voor arceringen moet dezelfde tekst worden opgenomen in de FB als in #236 beschreven:

Per versie 5.0 is het toegestaan dat symbolen op een eigen laag komen te staan (4.1 logica), of eventueel een niveau hoger, mits het harmonicamodel dit toestaat.
Bijvoorbeeld: Symbool N-SVW-VERKEERSTEKEN_BORD_E01-SO, mag geplaatst worden op het OBJECT N-WE-VW-VERKEERSTEKEN_BORD_E01-S, maar ook op N-WE-VW-VERKEERSTEKEN_BORD-S
Bijvoorbeeld: Symbool N-SIE-WEG_ABRI-SO, mag geplaatst worden op het OBJECT N-WE-IE-WEGMEUBILAIR-S, maar ook op N-WE-IE-WEGMEUBILAIR_ABRI-S

De regel terugdraaien is m.i. absoluut geen optie.
Gebruikers hebben deze behoefte en noodzaak. Als het niet meer ‘mag’,  gaan ze het toch gewoon doen.

Uiitgangspunt is dat een symbool op alle OBJECT en SUBOBJECT niveau’s geplaatst mag worden, welke ook in de SYMBOOLNAAM voorkomen.
Bijvoorbeeld een symbool als:
SVH-KANTOPSLUITING_TROTTOIRBAND_130 150_GRIJS
Mag geplaats worden op de lagen:
*-**-VH-KANTOPSLUITING-S
*-**-VH-KANTOPSLUITING_TROTTOIRBAND-S
*-**-VH-KANTOPSLUITING_TROTTOIRBAND_130 150-S
*-**-VH-KANTOPSLUITING_TROTTOIRBAND_130 150_GRIJS-S

Zie bovenstaand.
Bijvoorbeeld een symbool als:
SGR-BOOM_FRUITBOOM
Mag geplaats worden op de lagen:
*-**-GR-BOOM-S
*-**-GR-BOOM_FRUITBOOM-S

**Comment by MvanderHulst** [comment]
Voor bedrijfsvloerplaat is geen arcering, maar wel een symbool in de bibliotheek aanwezig.

**Comment by NielsNederpel** [comment]
ik weet dat het plaatsen van symbolen op een eigen laag of niveau hoger, bij Netbeheer ook een rol speelde.
dat beide nu kan weet ik niet meer zeker of dit nu juist wél of níet een probleem was voor deze uitbreiding.

**Comment by ElisabethKloren** [comment]
De linked data publicatie geeft een relatie tussen object en symbool, die wordt overgeërfd. Daarmee kun je dus op een lager niveau het symbool terugvinden dat op een hoger niveau gekoppeld is.

Daarnaast is de discussie: moet er G/S in de bibliotheek staan om een symbool te mogen plaatsen? Het antwoord is nee, er staat S als er voor die laag een specifiek symbool aanwezig is in de database, je mag altijd je eigen symbool toevoegen volgens de regels van NLCS of dus het generiekere bovenliggende NLCS symbool gebruiken. Voor deze discussie bestaat issue #236 die is beslecht met het antwoord wat ik hier ook geef.

**Comment by ElisabethDeVries** [comment]
Deze vragen zijn voor de 5.2 release opgelost met deze antwoorden:

https://github.com/nl-digigo/NLCS/issues/817 Indien bij een NLCS-object symbolen of arceringen beschikbaar zijn, moeten deze door de ontwerper/tekenaar ook gevonden kunnen worden bij het bovenliggende object. In de NLCS-database (in linked data) wordt in dat geval zowel bij het object als bij het bovenliggende object een filter gegeven (aobject, sobject) voor het zoeken van symbolen of arceringen met dit filter in de naam. Voorbeeld: Bij BEPLANTING wordt als zoekterm SGR-BEPLANTING meegeleverd; bij BEPLANTING_BODEMBEDEKKERS dan de zoekterm SGR-BEPLANTING-BODEMBEDEKKER en bij BEPLANTING_BOSPLANTSOEN de zoekterm SGR-BEPLANTING_BOSPLANTSOEN. Indien er voor een onderliggend object géén eigen symbolen of arceringen aanwezig zijn, kan hier ook het bovenliggende symbool geplaatst worden en wordt deze zelfde zoekterm meegegeven, bijvoorbeeld de zoekterm “SRI-RIOOLPUT” wordt zowel bij RIOOLPUT als bij RIOOLPUT_BETON meegegeven. Dit was al het uitgangspunt bij NLCS versie 5.0, maar was nog niet consequent doorgevoerd in de NLCS-database. Dat is in versie 5.2 hersteld.

https://github.com/nl-digigo/NLCS/issues/775 De functie van de aanduiding "ELEMENT" is opgehelderd; deze informatie ondersteunt voor de implementatie in de software het zoeken naar arceringen dan wel symbolen. Indien de aanduiding S of A aanwezig is, moet ook een filter beschikbaar zijn (aobject, sobject) voor het zoeken van symbolen of arceringen met dit filter in de naam. Voor de gebruiker van de standaard betekent de aanduiding in ELEMENT geen verbod op het toevoegen van eigen arceringen of symbolen als deze niet beschikbaar zijn.
