### ISSUE TITLE
#585	"In de NLCS wordt aangegeven dat als decimaalteken de “punt” (.) wordt gebruikt. Dit is echter de Angelsaksische methode.

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#64]
#585	"In de NLCS wordt aangegeven dat als decimaalteken de “punt” (.) wordt gebruikt.
Dit is echter de Angelsaksische methode.
Verder wordt er aangegeven dat binnen de NLCS er zoveel mogelijk gekeken is naar NEN(-EN)-ISO normen.

https://taaladvies.net/taal/advies/vraag/1/10000000_10_000_000/

Volgens bovenstaande website is het echter binnen Nederland gebruikelijk om de “komma” (,) als decimaal teken te gebruiken. Volgens diezelfde website wordt van oudsher in Nederland gebruik gemaakt van een punt als scheidingsteken in getallen die uit meer dan vier cijfers bestaan. In geldbedragen (bijvoorbeeld bij wisselkoersen) worden cijfers achter de komma niet gegroepeerd.

De punt als scheidingsteken in getallen die uit meer dan vier cijfers bestaan wordt echter dan weer niet onderschreven door ISO-normen.
Er wordt aangegeven

In vakgebieden waarin veel belang wordt gehecht aan ISO-normen (bijvoorbeeld de techniek en de exacte wetenschappen), is het raadzaam de daarin gegeven richtlijn voor het scheiden van grote getallen (spaties, geen punten) te volgen.
Graag opheldering over het feit waarom er in een Nederlandse CAD standaard gekozen wordt voor de Angelsaksische methode en of we wel of niet de NEN volgen voor wat betreft het scheiden van getallen die uit meer dan vier cijfers bestaan te volgen, aangezien het in Nederland van oudsher juist wel met een punt wordt gedaan terwijl de NEN voorschrijft om het met spaties te doen."

**Comment by MvanderHulst** [comment]
Graag zou ik een toelichting schrijven, maar de achtergrond is mij onbekend.
Vanuit technisch tekenwerk ben ik niet anders gewend, ook omdat AutoCAD alles op deze methodiek doet.

Binnen AutoCAD moet je de decimalen ook met een punt invoeren.
Dit is ook het resultaat dat ik nu op het scherm zie. voor mij logisch... maar niet de achtergrond?

**Comment by ElisabethKloren** [comment]
@expertcommissie, waarom wijken we af?

**Comment by ElisabethKloren** [comment]
Reden van afwijking: de softwarepakketten die gebruikt worden gebruiken de Angelsaksische methode, daarom wijken we af van de standaard.

**Comment by NielsNederpel** [comment]
en het tweede punt? voor wat betreft de getallen uit meer dan 3 cijfers?
want doordat we nu "kiezen" om de punt als decimaal teken te gebruiken kan deze niet meer voor de scheiding van duizendtallen worden gebruikt. volgen we de iso? dan wordt het "spatie" en anders hebben we nog de opties "niks" of een komma.
1 234.56 (spatie)
1234.56 (niks)
1,234.56 (komma)

**Comment by NielsNederpel** [comment]
helemaal prima, als het maar beantwoord en daarme duidelijk is...

**Comment by MvanderHulst** [comment]
@ElisabethKloren mogen e.e.a. in documentatie opnemen? geen database actie nodig

**Comment by ElisabethKloren** [comment]
Heb nu dit in de documentatie gezet:

*  De punt (.) wordt gebruikt als decimaalteken. Onderbouwing: Dit wijkt af van ISO-normen, maar sluit aan op de CAD pakketten waarvoor deze standaard is gemaakt. 
*  Er wordt geen gebruik gemaakt van een scheidingsteken voor duizendtallen, ook weer in aansluiting op de gebruikte CAD-pakketten.
