### ISSUE TITLE
#508	"Hierbij wil ik jullie de symbolen voor de groep Verkeerskunde Vaarwegen doen toekomen

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#65]
#508	"Hierbij wil ik jullie de symbolen voor de groep Verkeerskunde Vaarwegen doen toekomen
Zodat dit opgenomen kan worden in de volgende versie van de NLCS
In het worddocument staan enkele gebuikte uitgangspunten
Scheepvaarttekens A t/m F en enkele Betonningboeien"

**Comment by MvanderHulst** [comment]
@ElisabethKloren waar vindt ik de bibliotheek die gecontroleerd moet worden?

**Comment by ElisabethKloren** [comment]
@NielsNederpel heb jij deze stukken ontvangen?

**Comment by NielsNederpel** [comment]
Ik moest ook weer even speuren...maar ik denk dat ik t gevonden heb!
Bedoelen jullie dit?
Ze stonden nog op de teams pagina...

Zo te zien moet er nog wel behoorlijk gesleuteld worden aan de symbolen. die zijn in ieder geval nog niet "schoon".
Er zit nog behoorlijk wat vervuiling in waar we voor 5.0 juist behoorlijk wat tijd in hebben gestoken (o.a. AEC objecten) om dit er uit te krijgen.

Ik kwam daarnaast nog wat zaken tegen waar Wouter Pronk mee bezig is geweest vooruitlopend op NLCS 5.0 aangaande dit onderwerp. Er zouden wat objecten verschuiven naar andere hoofdgroepen. Dit is echter maar deels doorgevoerd.
Ik kan geen reden vinden in de mail waarom dit slechts deels doorgevoerd is. Misschien dus ook even opnieuw tegen het licht houden?

[Uitgangspunten Scheepvaartborden.docx](https://github.com/user-attachments/files/15628594/Uitgangspunten.Scheepvaartborden.docx)

[NLCS-VV.zip](https://github.com/user-attachments/files/15628611/NLCS-VV.zip)

[NLCS-OBJECTEN-VV-4.2-5.0.xls](https://github.com/user-attachments/files/15630998/NLCS-OBJECTEN-VV-4.2-5.0.xls)

**Comment by ElisabethKloren** [comment]
Gezien de vraag van Niels om nog allerlei redactieslagen te doen en de beperkte tijd om dit door te voeren, kunnen we deze borden nog niet opnemen in 5.1. 

Tenzij één van de experts zich hier druk over maakt...

Voor mij moet het zover klaar zijn, dat ik de symbolen kan knippen en plakken in de juiste directory, en ik een lijst met symbolen kan importeren in de database (en aan welk object ze gekoppeld moeten wordne.

Tenzij het zo ver af komt in augustus (wat ik niet van jullie als vrijwilligerswerk verwacht), moet ik dit helaas in de ti9jd vooruitschuiven zodat we tijd en budget kunnen vrijmaken om dit op orde te brengen.

**Comment by MvanderHulst** [comment]
[SVV-borden.zip](https://github.com/user-attachments/files/16470406/SVV-borden.zip)
Bijgevoegd alle borden zonder de AEC objecten.

**Comment by ElisabethKloren** [comment]
wow, thanks

**Comment by ElisabethKloren** [comment]
wijzigingen doorgevoerd voor release 5.1

**Comment by ElisabethKloren** [comment]
Hoi Michel, ik heb ze opgenomen. Early birdy

**Comment by ElisabethDeVries** [comment]
[[Release note]] In de hoofdgroep VV zijn symbolen voor verkeerstekens voor de scheepvaart toegevoegd.
