### ISSUE TITLE
#454	"Het object stootband is als symbool terug te vinden bij SIE en bij SVH

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#67]
#454	"Het object stootband is als symbool terug te vinden bij SIE en bij SVH
In de groep VH staat  de stootband als object en als subobject van Kantopsluiting vermeld
Dit is verwarrend!
Voorstel
De symbolen van stootband onder SIE laten vervallen en onder VH-Kantopsluiting het subobject stootband te laten vervallen.
Object VH-Stootband handhaven en symbolen van SIE hieraan teoevoegen, wel graag namen/afmetingen controleren, wordt niet consequent toegepast"

**Comment by ElisabethKloren** [comment]
Actie	Reactie Expertcommissie	To Do
Aanpassen	"opmerking is (nogsteeds) terecht. Er is wel geschoven vanuit SIE naar SVH.
Echter zijn bij de symboolnamen van STOOTBANDEN de doorsnede symbolen nog wel als subobject van KANTOPSLUITING terwijl de gewone symbolen wel als object STOOTBAND staan, daarnaast is dit ook zo bij de objecten"

**Comment by MvanderHulst** [comment]
Alle leveranciers scharen de stootbanden onder 'kantopsluiting'.
Logisch en lekker laten staan.

**Comment by MvanderHulst** [comment]
De stootbanden bij hoofdgroep 'IE' kan ik nergens terug vinden.
![image](https://github.com/nl-digigo/NLCS/assets/144665595/298049e4-60c7-4c25-b254-547f961faf0d)

Bovenstaande symbolen moeten van naam worden veranderd.
B-SVH-STOOTBAND_150X200-D
B-SVH-STOOTBAND_200X200-D
B-SVH-STOOTBAND_250X250-D
B-SVH-STOOTBAND_300X300-D
B-SVH-STOOTBAND_100X250-D

Algemeen volgens eerdere issue.
Willen we deze blijven aanbieden? Bovenstaande maten kloppen niet allemaal meer. ;-)

**Comment by NielsNederpel** [comment]
klopt die bij SIE zijn juist verplaatst naar SVH
dat gaf Elisabeth ook al aan

> Aanpassen "opmerking is (nogsteeds) terecht. Er is wel **geschoven vanuit SIE naar SVH**.

gaat er nu alleen om dat de "niet -D" symbolen zonder KANTOPSLUITING in de blocknaam bestaan

**Comment by ElisabethDeVries** [comment]
[[Release note]] Het object STOOTBAND vervalt. In hoofdgroep VH (VerHardingen) bestond zowel een object STOOTBAND als KANTOPSLUITING_STOOTBAND. Het object STOOTBAND vervalt. De symbolen zijn herzien waarbij alle courante formaten zijn toegevoegd.

**Comment by MvanderHulst** [comment]
@ElisabethDeVries ik zie dat het niet helemaal goed is gedocumenteerd, maar volgens mij was de laatste conclusie dat we STOOTBAND juist als eigen object wilde laten bestaan, omdat alle kantopsluitingen 'meters' zijn, maar stootbanden stuks.
