### ISSUE TITLE
#454	"Grondkeringen Deze groep is naar mijn mening niet logisch opgebouwd.

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#68]
#454	"Grondkeringen Deze groep is naar mijn mening niet logisch opgebouwd.
Bij de groep VH wordt niet naar de functie van de verharding gekeken, maar naar de materialen.
Waarom is dit principe hier niet toegepast?
Je vind nu damwanden terug onder Beschoeiing, Bouwkuip, Keerwand en Kistdam.
Is het niet beter om de functies hier tussenuit te halen en de materialen als object te gebruiken ipv een subobject."

**Comment by ElisabethKloren** [comment]
Reactie Expertcommissie
opmerking is terecht

**Comment by ElisabethKloren** [comment]
To Do
decompositie nalopen en aanpassen (d.m.v. Excel)

**Comment by MvanderHulst** [comment]
[NLCS-OBJECTEN-GK-5.1 voorstel.xls](https://github.com/nl-digigo/NLCS/files/14959663/NLCS-OBJECTEN-GK-5.1.voorstel.xls)

Hierbij mijn voorstel van de aanpassing voor de hoofdggroep GK.
Uitgangspunt is dat de TYPE wanden worden beschreven en niet de functie van de wand.

Objecten worden dus terug gebracht naar:
BERLINERWAND
BESCHOEIING
COMBIWAND
DAMWAND
DIEPWAND
KADEMUUR
KEERWAND

met daaronder alle materialen.

KEERWAND is de 'wildcard' waar alle 'overige' zaken staan. Zoals betontegelementen, L-wanden en T-wanden.

**Comment by ElisabethKloren** [comment]
Aanvulling: een in een BESCHOEINING1, 2 en 3 en eveneens DAMWAND1, 2 en 3: deze zijn gemaakt zodat je op een tekening onderscheid kan maken tussen beschoeiingen of damwanden van verschillende hoogtes, met eigen lijntypes. Helaas leidt dit tot eigen laagnamen, zolang je niet een keuzelijst kan aanbieden voor te gebruiken lijntypes

**Comment by MvanderHulst** [comment]
Naast hoogtes, kom je in bestaande situaties ook beschoeiingen van verschillende materialen tegen, waarvan je op tekening duidelijk aan wilt kunnen geven wat-wat is.

**Comment by ElisabethDeVries** [comment]
Wegens het verkleinen van de sacope van 5.1 naar 5.2, heropen ik deze issue weer
