### ISSUE TITLE
#422	"Pagina 40-41, paragraaf 4.6.3. Wellicht extra duidelijk om hier op te nemen dat peilmaten/hoogtematen t.o.v. NAP altijd teksthoogte 1.8mm hebben: 

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#69]
#422	"Pagina 40-41, paragraaf 4.6.3. Wellicht extra duidelijk om hier op te nemen dat peilmaten/hoogtematen t.o.v. NAP altijd teksthoogte 1.8mm hebben: zowel bestaande hoogten als ontwerp hoogten conform par. 4.5.8.
Te meer omdat er staat NAP-aanduiding teksthoogte 3.5mm en polderpeil, zomerpeil, ect. een teksthoogte 2.5mm."

**Comment by ElisabethKloren** [comment]
To Do
FB aanpassen

**Comment by SanderNijhof** [comment]
Waarom hebben peilhoogten altijd een teksthoogte 1.8mm en volgt deze niet de rest van de standaard, nl bestaand 1.8mm cursief en nieuw 2.5mm rechtop?

**Comment by MvanderHulst** [comment]
Is volgens mij een fout in het artikel. De logica van sander is correct.
Veel tekst hoofdstukken zijn hierop aangepast, deze is denk ik gemist.

**Comment by MvanderHulst** [comment]
@ElisabethKloren betreft FB aanpassing, deze is voor jou. ;-)

**Comment by ElisabethKloren** [comment]
aangepast in [eisen aan tekeningen en modellen](https://nl-digigo.github.io/NLCS/requirementscadmodels/#maataanduidingen-van-cirkels-bogen-lengtemaat)

**Comment by SanderNijhof** [comment]
> Op basis van mijn eigen ervaringen is het voorstelschrijven van de lettergrootte op basis van de status onwenselijk en niet nodig. In ZEER veel gevallen is lettergrootte 2.5 mm simpelweg te groot. een hoogteplan 1:200 is hiermee niet eens knap uit te werken. Gebruikers gaan tóch vaak terug naar 1.8 mm ivm de leesbaarheid. Zodoende voorstel om dit gewoon vrij te geven.
> Tevens de verwijzing naar een vervallen NEN-Norm eruit gehaald.

Geld dit nog volgens de geldende NEN: "_Volgens de geldende NEN-norm moeten teksten op technische tekeningen een letterhoogte hebben van minimaal 1.8mm en maximaal 10.0mm. Daarnaast moet de lijndikte van de betreffende tekst 1/10 van de letterhoogte zijn._"

De Formele Beschrijving sluit daarop aan in par. 4.6.2:
Bij letterhoogte 1,8mm hoort lijndikte 0,18mm
Bij letterhoogte 2,5mm hoort lijndikte 0,25mm

Eigenlijk nooit onoverkomelijke problemen mee gehad. 
Onderscheid in bestaand/**nieuw** is niet alleen **in teksthoogte** maar ook **in lijndikte**: 1.8mm tekst wordt dunner afgedrukt dan 2.5mm tekst. Volgens mij wordt de lijndikte van de teksten bepaald in het TrueType NLCS-Font en niet door de in het CAD pakket gekozen lijndikte. Dus 1.8mm met lijndikte 0,25mm voor extra duidelijkheid is niet mogelijk.

Wat mij betreft wordt dit niet vrijgegeven en blijft teksthoogte 1.8mm toepassen voor bestaande objecten en teksthoogte 2.5mm toepassen voor nieuwe objecten de standaard, waarvan voor de leesbaarheid van de tekening afgeweken mag worden.

**Comment by ElisabethKloren** [comment]
terecht punt van Sander, bij andere issues bijvoorbeeld over maatvoering en aanpijling hebben we wel degelijk rekening gehouden met twee maten teksten met andere kleuren.

Ik haal te specifieke teksten over teksthoogte weg bij alle maatvoeringen, feitelijk heb je dit elders al gezegd
