### ISSUE TITLE
#1686  Het object RI-RWZI_DOCEERLEIDING moet RI-RWZI_DOSEERLEIDING zijn.

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#7]
Het object RI-RWZI_DOCEERLEIDING moet RI-RWZI_DOSEERLEIDING zijn.

**Comment by ElisabethKloren** [comment]
Actie: aanpassen in database

**Comment by MvanderHulst** [comment]
Aanpassen in database.

**Comment by ElisabethDeVries** [comment]
[[Release note]] Spelfout in object RI-RWZI_DOCEERLEIDING  verbeterd naar RI-RWZI_DOSEERLEIDING.

**Comment by ElisabethDeVries** [comment]
wegens hoge impact op bestaande individuele bibliotheken veranderen we geen laagnamen in de 5.2 tenzij een dringende reden. Met spelfouten kunnen de gebruikers wel leven tot versie 6.0
