### ISSUE TITLE
#422	Waarvoor dienen de lagen met de bewerking ‘-WERK’ ? Kan dat uitgelegd worden in de formele beschrijving?

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#71]
#422	Waarvoor dienen de lagen met de bewerking ‘-WERK’ ? Kan dat uitgelegd worden in de formele beschrijving?

**Comment by MvanderHulst** [comment]
Deze aanvulling heb ik ook nooit begrepen.
Mag van mij komen te vervallen. Deze staat volgens mij enkel in de hoofdgroep 'groenwerk'.
Waarbij de algemene lijn 'GRONDWERKLIJN' beschikbaar is.

Ook zijn er diverse arceringen met 'WERK' beschikbaar.

Logisch zou zijn om GRONDWERKLIJN aan te passen naar GRONDWERK.
Alle arceringen 'AGW-WERK_' aanpassen naar 'AGW_GRONDWERK'

Het bestaande object 'GROND' vervolgens aanpassen naar 'GRONDSOORTEN'
hierin staan dan alle daadwerkelijke arceringen van de grondsoorten.
In het huidige object GROND, staat echter de reguliere 'GROND' niet opgenomen.
Grond is een algemene noemer, maar GROND is vervolgens ook een soort, als in 'zwarte grond', wat weer iets anders is dan 'teelaarde'.
Tot slot moet in het hernoemde OBJECT 'GRONDSOORTEN' dus GROND als SUBOBJECT toegevoegd worden.

**Comment by ElisabethDeVries** [comment]
[[Release note]] De aanduiding "WERK" in de hoofgroep GW (GrondWerk) is aangepast naar GRONDWERK, zowel in de objectnamen als bij de arceringen. Het object GRONDWERKLIJN is aangepast naar GRONDWERK. Het object "GROND" is aangepast naar "GRONDSOORTEN" om verwarring te voorkomen met "GROND_GROND", waarmee gewone zwarte aarde wordt bedoeld (niet te verwarren met TEELAARDE).

**Comment by ElisabethDeVries** [comment]
Reopen voor 6.0

**Comment by MvanderHulst** [comment]
@ElisabethDeVries de aanpassing van WERK naar GRONDWERK zie ik niet overal doorgevoerd. als dit voor 6.0 bewaard, wordt dan ook voor de aanvullingen WERK benoemen i.p.v. GRONDWERK

**Comment by ElisabethDeVries** [comment]
> [@ElisabethDeVries](https://github.com/ElisabethDeVries) de aanpassing van WERK naar GRONDWERK zie ik niet overal doorgevoerd. als dit voor 6.0 bewaard, wordt dan ook voor de aanvullingen WERK benoemen i.p.v. GRONDWERK

in het 5.2 voorstel opgenomen
