### ISSUE TITLE
#398	De NLCS lagen om damwanden weer te geven zijn te summier, alleen linetype continuous.

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#72]
#398	De NLCS lagen om damwanden weer te geven zijn te summier, alleen linetype continuous. Kan hiervoor niet een complex linetype aangemaakt worden? De gemeente Rotterdam heeft goede alternatieven.

**Comment by ElisabethKloren** [comment]
Reactie Expertcommissie
opmerking is terecht

**Comment by ElisabethKloren** [comment]
To Do
"Lijnypen maken (eventueel op basis van aangeleverd bestand) en toevoegen aan database (d.m.v. Excel)
aangemaakte lijnstylen koppelen aan objecten (d.m.v. Excel)"

**Comment by MvanderHulst** [comment]
Ik heb hier nog wel een voorstel voor. Idem voor beschoeiingen.

**Comment by MvanderHulst** [comment]
Uit de oude HB-doos:
![image](https://github.com/nl-digigo/NLCS/assets/144665595/7bc598ea-4fca-4a55-b3b5-b00198b0676c)

ONDERSTAANDE LINETYPES ZIJN GEBASEERD OP EEN EIGEN SHAPEFILE,
INDIEN AKKOORD, MOETEN DEZE NOG NAGELOPEN WORDEN

*IE-BESCHOEIING_TYPE1,----0-----0----0-----0----0-----0--
A,2.50,[HBCIRKEL,HBSHAPES,s=1.00,x=-0.50,y=-0.50],2.50

*IE-BESCHOEIING_TYPE2,----[]-----[]----[]-----[]----[]---
A,1.90,[HBBOX,HBSHAPES,s=1.00],-1.20,1.90

*IE-BESCHOEIING_TYPE3,----[]-----[]----[]-----[]----[]---
A,1.75,[HBHBOX,HBSHAPES,s=1.00],-1.50,1.75

*IE-DAMWAND_TYPE1,----[   ]---[   ]---[   ]---[   ]---
A,1.00,[HBBLOK,HBSHAPES,s=1.00],-3.00,1.00

*IE-DAMWAND_TYPE2,----<>-------<>------<>-------<>------<>----
A,1.50,[HBRUIT,HBSHAPES,s=1.00],-2.00,1.50

*IE-PALENRIJ,-00000000000000000000-
A,0,[HBCIRKEL,HBSHAPES,s=1.00,y=0.50],-1.00

**Comment by ElisabethDeVries** [comment]
[[Release note]] Damwanden in hoofdgroep GK hebben in release 5.2 een eigen duidelijk onderscheidbaar lijntype gekregen in plaats van lijntype CONTINUOUS, de lijntypes voor beschoeiing en perkoenpalen zijn vernieuwd.

**Comment by ElisabethDeVries** [comment]
de objecten staan in GK in de nlcs 5.0, niet in IE
