### ISSUE TITLE
#E002	"lijntype komt dubbel voor: aansluitleiding

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#74]
#E002	"lijntype komt dubbel voor:

*RI-AANSLUITLEIDING-SO,349
A,2.5,-1.8

*RI-AANSLUITLEIDING-SO,381
A,4,-4,0,-4,0,-4

*V-RI-AANSLUITLEIDING-SO,350
A,1.25,[VERWIJDEREN2,NLCS.SHX,s=1],1.25,-1.8,2.5,-1.8

*V-RI-AANSLUITLEIDING-SO,382
A,2,[VERWIJDEREN2,NLCS.SHX,s=1],2,-4,0,-4,0,-4"

**Comment by ElisabethKloren** [comment]
Reactie Expertcommissie
lijntype 349 en 350 is in gebruik voor diverse objecten. 381 & 382 zijn niet in gebruik

**Comment by ElisabethKloren** [comment]
To Do
"lijntype: 381 en 382 laten vervallen
eventueel definitie van 349 en 350 wijzigen naar definitie van 381 en 382"

**Comment by MvanderHulst** [comment]
De ongebruikte lijntypes zijn zeer slechte lijntypes voor een aansluitleiding.
381 en 382 mogen van mij vervallen.

**Comment by ElisabethDeVries** [comment]
[[Release note]] Uit hoofdgroep RI (RIoleringen) zijn niet-gebruikte lijnstijlen verwijderd.
