### ISSUE TITLE
#E003	Maatvoering wijkt af bij de diverse softwareleveranciers en komt niet overeen met FB

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#75]
#E003	Maatvoering wijkt af bij de diverse softwareleveranciers en komt niet overeen met FB

**Comment by SanderNijhof** [comment]
Volgens mij ligt hier al een voorstel voor. Aanpassen in FB.

**Comment by MvanderHulst** [comment]
Zie ook issue #32

**Comment by ElisabethKloren** [comment]
ik sluit deze, wegens dubbel
