### ISSUE TITLE
#E004	het ontbreken van de Tekstgrootte in NLCS Maatvoerings layers. 

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#76]
#E004	het ontbreken van de Tekstgrootte in NLCS Maatvoerings layers. Geldt overigens ook voor de huidige NLCS. Voor teksten hebben we die mogelijkheid wel T18, T25 etc maar voor maatvoering ontbreekt deze M18, M25. Hierdoor kunnen we in AutoCAD ons niet houden aan de ByLayer uitgangspunt van de NLCS maar moeten we Object kleuren instellen in de Maatvoeringsstylen.

**Comment by SanderNijhof** [comment]
Volgens de uitgangspunten van de NLCS hebben maatvoeringen ongeacht de tekstgrootte allemaal kleur 7, conform de ZZ-objectentabel. Van verschillende kleuren voor maatvoeringen met teksthoogte T18 en T25 is geen sprake.

**Comment by KristiaanH** [comment]
Hier zit overlap/  moet gezien worden i.r.t.  item#1588. 
https://github.com/nl-digigo/NLCS/issues/25#issuecomment-1717003236
**SanderNijhof**
Ik weet niet beter dat de kleur van tekst wordt bepaald door de laag-eigenschappen. Dat doen we al sinds de 1e versie van de NLCS zo. In de FB staan de kleuren voor teksten gedefinieerd, maar ook dat deze in de laagnaam geregeld worden. Daartegen staat niet expliciet vermeld dat de kleur niet in de tekststijl geregeld mag worden. Verduidelijken in de FB.

Ik herken hier het probleem van de melder.
Doordat de tekstgrootte in een maatvoering de kleur bepaald, wordt deze met een text override ingeregeld. Dit betekent dat als een tekening als xref toegepast wordt (bijvoorbeeld bestaande maatvoeringen, of ontwerpmaatvoeringen onder revisietek) alles grijs wordt, behalve de tekstlabels van maten, die blijven zwart of kleur afhankelijk van de plotstyle. Wij konden hiermee dus niet voldoen aan de eisen die aan de opbouw van een rioolrevisie werden gesteld door gem. Rotterdam, zonder overal de tekstkleuren van maatvoeringen weer op bylayer terug te zetten (al dan niet met hulp van projectbieb instellingen/overrides)

Als we het uitgangspunt hanteren om de kleur van teksten altijd op bylayer niveau in te regelen, is er dus de -M18/25 laag nodig om dat onderscheid in kleur te kunnen maken. De volledige maatvoering inclusief belijning zal dan wel in rood weergegeven worden voor T18, maar dit is wel consequent met de omgang met attributes in andere symbolen.

**Comment by KristiaanH** [comment]
Afbeelding ter inllustratie dat de omgang tussen aanpijlingen en maatvoeringen inconsequent is doordat er voor maatvoeringen geen teksthoogte gespecificeerd wordt:

![image](https://github.com/nl-digigo/NLCS/assets/146870484/5f61016a-bb5f-4447-9733-a0fededed26f)

**Comment by SanderNijhof** [comment]
Wat zien we precies op de afbeelding @KristiaanH? 
Maatvoeringen komen op een -M laag, color 7 = wit
Aanpijlingen op een AANPIJLING-G laag, color 7 = wit
De textcolor zou 'ByLayer' moeten zijn, net als alle objecten in de NLCS.

**Comment by KristiaanH** [comment]
je ziet een kleur override op de tekst (kleur 10). Als je dit niet zou doen, worden dus zowel maatvoeringen in 1.8 als 2.5 in wit weergegeven. Dit is de implementatie van InfraCAD om rode teksten te kunnen visualiseren, omdat ze dit niet op laagniveau kunnen inregelen.
het gevolg hiervan is dat als deze tekening als een xref onder andere tekening hangt, ongeacht welke kleur je als XREF layer override toekent, de tekst 5.00 altijd in rood of zwart afgedrukt zal worden.

**Comment by SanderNijhof** [comment]
In Microstation is het zo ingesteld dat aanpijlingen en maatvoeringen bylayer zijn, dus geheel wit incl. text. Teksten bij aanpijlingen en maatvoeringen staan op een -M laag, dus gerheel wit. Altijd al zo gedaan.

**Comment by MvanderHulst** [comment]
bovenstaande probleem is ZEER bekend en moet opgelost worden.
Een aantal oplossingen hiervoor zijn:
- Presentatie van dimenions net als teksten behandelen, hiervoor moet het element M, worden aangepast naar M**, conform de huidige T** elementen. (Dit heeft mijn persoonlijke voorkeur). Iedere lettergrootte krijgt dan dus een eigen layer en dan kan alles dus ook 'ByLayer' geregeld worden.
- Dimensions worden niet als teksten behandeld. hierdoor krijgt het dus gewoon de kleur van de layer waarop deze is aangemaakt, hierdoor krijgt een maatvoering met lettergrootte 18 mm, een afwijkende presentatiekleur krijgt dan een 'tekst' 1.8 mm. Dit omdat volgens 3.5.9.tabel 1 aangeeft dat maatvoering een kleur 7 moet krijgen.

Of het één of het ander is een optie.
Huidige situatie is niet consequent en onlogisch.


Atrikel 5.1.4.j geeft aan:
De NLCS voorziet per HOOFDGROEP in aparte lagen voor het plaatsen van tekst, maatvoering en
‘hulpgeometrie’ als aanpijlingen, afbreeklijnen, hoogtelijnen, constructielijnen en stramienlijnen. De
betreffende standaard lagen zijn verzameld in een separate objectentabel, genaamd
VOORALLEHOOFDGROEPEN (code: ZZ). Deze standaard lagen volgen in de laagopbouw – indien
van toepassing – direct achter de HOOFDGROEP. Dat maakt het mogelijk om bijvoorbeeld alle tekst
of alle hulpgeometrie in een model in één keer ‘uit te schakelen’, wanneer die niet moet worden
meegeplot. Naar behoefte kunnen tekstlagen ook achter de (SUB-)OBJECTEN worden geplaatst
waarop ze betrekking hebben. Dit heeft niet de voorkeur, omdat dan zeer veel tekstlagen kunnen
ontstaan binnen één model, maar kan handig zijn wanneer tekst selectief moet worden geplot.

Volgens mij klopt dit ook niet, en is er voor teksten en maatvoering geen eigen lagen beschikbaar.
Dit is dan ook tegenstrijdig met 5.1.g

g. Tekst en bemating kunnen op elk niveau voorkomen (achter HOOFDGROEP, achter OBJECT, achter
SUBOBJECT enzovoort), maar staan default achter HOOFDGROEP (zie ook paragraaf 5.1.4).

het beschreven in 5.1.4.j, zie bovenstaand. is echter wel weer de logica die ik zou wensen.
Zie ook issue #42

**Comment by ElisabethKloren** [comment]
oplossing issue conform besluit in #42
