### ISSUE TITLE
#E005	SAM-ASPUNTNUMMER-SO bestaat uit een tag/attribute met een verkeerde tekststijl en een teksthoogte die niet conform de afspraken is.

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#77]
#E005	SAM-ASPUNTNUMMER-SO bestaat uit een tag/attribute met een verkeerde tekststijl en een teksthoogte die niet conform de afspraken is.

**Comment by ElisabethKloren** [comment]
Reactie Expertcommissie
style klopt, hoogte moet teksthoogte moet 2.5 zijn

**Comment by ElisabethKloren** [comment]
To Do
attribute aanpassen naar teksthoogte 2.5, ook aanleveren Excel tbv wijziging symbool in database

**Comment by SanderNijhof** [comment]
zonder te kijken, volgens mij zijn alle of de meeste teksthoogten in cellen 1.8mm? In de FB staat ook dat teksthoogte in cellen/blocks afwijkt. Zie FB 4.6.3 "_Indien symbolen voor bestaand en nieuw gelijk zijn wordt teksthoogte 1.8 gehanteerd_"

**Comment by MvanderHulst** [comment]
Bestaande symbool aangepast (verschil echter niet de zien op afbeelding.:
![image](https://github.com/nl-digigo/NLCS/assets/144665595/58f9cfcf-d384-47da-b99b-745b448611cd)

@SanderNijhof dit is weer zo een lekkere dubbeling.
![image](https://github.com/nl-digigo/NLCS/assets/144665595/02d8dbe3-4766-4471-85cf-b5c8de23b82b)

M.i. is 2.5 voor dit specifieke symbool akkoord.

**Comment by ElisabethDeVries** [comment]
[[Release note]] In hoofdgroep Assen en Metrering is het symbool SAM-ASPUNTNUMMER-SO aangepast van een teksthoogte 18 naar een teksthoogte 2.5

**Comment by ElisabethDeVries** [comment]
reopen voor acceptatie 5.2 release

**Comment by SanderNijhof** [comment]
vraag: waarom is SAM-ASPUNTNUMMER-SO een symbool? 
Het symbool bestaat alleen uit 1 tekstelement. 
Waarom moet van deze tekst een symbool gemaakt worden?

**Comment by MvanderHulst** [comment]
@SanderNijhof 
Ik denk om de (voor mij onbekende) reden dat er een symbool is voor een BOB maat en een materiaal in hoofdgroep Riolering.
Ook beide blocks met enkel een attribute, zonder verdere inhoud.

Lijkt een stukje NLCS historie te zijn.

**Comment by SanderNijhof** [comment]
> Lijkt een stukje NLCS historie te zijn.

Symbolen die uitsluitend uit een tekstattribuut bestaan en geen aantoonbare functie meer hebben binnen koppelingen, software of workflows, kunnen worden voorgedragen om te vervallen. Softwareleveranciers dienen aan te geven of er nog technische afhankelijkheden bestaan. Als die er niet zijn, zie ik geen reden om deze symbolen in de NLCS-bibliotheek te handhaven.

**Comment by MvanderHulst** [comment]
@SanderNijhof ben ik helemaal met je eens.
Persoonlijk pas ik deze ook niet toe, maar durf niks te zeggen over oorsprong en technische noodzaak...
