### ISSUE TITLE
#E006	"BGT mapping: -	Sommige symbolen zijn niet SO en dus niet schaalbaar:

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#78]
#E006	"BGT mapping: -	Sommige symbolen zijn niet SO en dus niet schaalbaar:
Dit betreffen de symbolen:
o	SGR >> BOOM > 01
o	SIE >> WEG > PARKEERMAATREGEL > PARKEERBEUGEL
o	SIE >> WEG > PICKNICKSET
o	SIE >> WEG > ZITBANK > MET > LEUNING
o	SVH >> BOOMKRANSBAND > 1200X1200"

**Comment by ElisabethKloren** [comment]
Reactie Expertcommissie
"Goed nagaan of het verschaalbare objecten zijn!
In de database staan een hele lijst met bomen maken we er 1 schaalbaar ?                                          SGR-BOOM_GBKN-SO toepassen? Is het handig dat hier een attribuut aanhangt?"

**Comment by MvanderHulst** [comment]
Hiervoor kan ik een goede dataset aanleveren. Heb ik voor ons intern helemaal herzien.

**Comment by MvanderHulst** [comment]
Zie ook issue #14 en #16 
alle BGT symbolen heb ik herzien.
Ten aanzien van bovenstaande symbolen:
o SGR >> BOOM > 01, AANGEPAST

o SIE >> WEG > PARKEERMAATREGEL > PARKEERBEUGEL, AANGEPAST
o SVH >> BOOMKRANSBAND > 1200X1200", AANGEPAST

Aanvullingen t.o.v. eerdere issue:

![image](https://github.com/nl-digigo/NLCS/assets/144665595/c9459b68-a961-4cd1-8337-ab3fb71ef5e7)
