### ISSUE TITLE
#E007	"""-	B-SAL-VERWIJZING_MATERIAALNUMMER-SO , wit vlakje met witte tekst?

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#79]
#E007	"""-	B-SAL-VERWIJZING_MATERIAALNUMMER-SO , wit vlakje met witte tekst?
-	SAL-AANKLEDING_AUTO1_BOVENAANZICHT is breder dan het voor- en achteraanzicht (±11cm verschil) en langer dan het zijaanzicht (ook ongeveer 11cm)
-	SAL-AANKLEDING_AUTO2_BOVENAANZICHT is breder dan het voor- en achteraanzicht (±6cm verschil) maar wel even lang als het zijaanzicht.
-	SAL-AANKLEDING_BUSJE1_BOVENAANZICHT is breder dan voor- en achteraanzicht (±10cm) en langer dan het zijaanzicht (±3cm).
-	Ook bij de fietsers wijken de bovenaanzichten qua afmetingen af van de zijaanzichten.
-	SAL-AANKLEDING_MOTOR_BOVENAANZICHT staat scheef (ongeveer 1°) en is ongeveer 5cm langer dan het zijaanzicht en ook de breedte komt niet overeen met het vooraanzicht.
-	Bij de rolstoelen is het vooraanzicht groter dan het zijaanzicht.
-	De afmetingen van de tractor zijn ook allemaal verschillend. De breedtes van voor- en achteraanzicht verschillen en het bovenaanzicht heeft weer een andere breedte.
-	De breedte van de tram is 2.18m, maar Nederlandse trams hebben een breedte tussen de 2.35m en de 2.65m. Nieuwe trams zijn bijna allemaal 2.65m (bron: Google).
-	De breedte van de trein is 2.43m. Nederlandse treinen zijn tussen de 2.84 en de 3.20m (bron: https://www.angelfire.com/ego/ist3/trein.html en Wikipedia:
 
-	Ook de aanzichten van de vrachtwagen corresponderen niet met elkaar.
-	De kaders zijn niet 1:1 getekend, maar 1:200. Is dat de bedoeling?
o	Is de extra breedte van het kader aan de linkerkant nog wel nodig? 
o	Is het nodig om al die extra letters en cijfers in de rand te vermelden? Onze meeste klanten gebruiken kaders die veel eenvoudiger zijn (snijrand, kaderrand, vouwlijntjes, niet meer). Ook die dikke hoekjes zien we nooit meer.
o	In SAL-AANKLEDING_BUSJE1_ACHTERAANZICHT-D komt tekststijl Romand voor. Deze is gebruikt voor de tekst op het busje. Misschien moet deze tekst geëxplodeerd/gedropped worden om te voorkomen dat deze tekststijl voorkomt in de tekening.
o	In SAL-AANKLEDING_VRACHTAUTO_ZIJAANZICHT_18.5-D staat een maatvoering met een tekststijl ‘Standard’, graag maatvoering verwijderen en de tekststijl ook.
o	In de schaalbalken is gebruik gemaakt van de tekststijl NLCS-ISO, dit zou NLCS-ISO-T25 moeten zijn.
o	In de maatvoeringstijl NLCS-M1000-T25-PIJL zit de tekststijl NLCS-T25_0, dat zou NLCS_ANNOTATIEF_T25 moeten zijn. Deze maatvoeringstijlen komen voor in de coördinaat-blocks.
"""

**Comment by MvanderHulst** [comment]
Presentatie van 'MATERIAALNUMMER' herzien, overeenkomstig met de wijzigingssymbolen van issue #45 
![image](https://github.com/nl-digigo/NLCS/assets/144665595/47c932c4-a921-4878-bee8-7a6c82b559f4)

Voor wat betreft de kaders:
De kader zijn 1:1 getekend, echter zijn dit -SO symbolen, waardoor deze verschaald worden (met InfraCAD). Als 1:200 actief is, wordt hij inderdaad kleiner, wat niet nodig is.
Door de juiste schaal actief te hebben, wordt het kader gewoon op de juiste schaal getekend.
- De extra breedte is nodig om tekeningen in ordners te kunnen stoppen, zonder dat er gaten in de tekening komen. Daarnaast is dit overeenkomstig met de geldende NEN-normen voor de sector. Dus Ja.
- De extra letters idem. komt uit de norm. Persoonlijk vindt ik de kaders erg 'kaal' als dit weg blijft. maar functioneel wordt het weinig gebruikt.
- De dikke hoekjes idem... heeft weinig toegevoegde waarde voor de tekening, maar komt uit de norm.
Wat mij betreft behoeven de kaders dus geen aanpassingen en dit bovenstaand een gebruikerswens/persoonlijke voorkeur.

Schaalbalk:
De teksten op NLCS-ISO is volgens de standaard gewoon toegestaan. als de lettergrootte maar klopt.
Geconstateerd heb ik wel dat de teksten in de schaalbalk '2.0' mm groot zijn. Dit is geen geldige waarde volgens de NLCS.
Dit zou aangepast moeten worden naar 1.8 of 2.5

WAS / WORDT
![image](https://github.com/nl-digigo/NLCS/assets/144665595/ba35752b-4047-4120-b981-e9c7ed418c2c)

Maatvoeringsstyles in coördinaatblocks:
De beschreven maatvoeringsstyle kan ik niet vinden/reproduceren met de coördinaatblocks. Verduidelijking is nodig waar zit precies zit om het op te lossen.
Mogelijk de oude XY-tool van een leverancier?

**Comment by MvanderHulst** [comment]
Tot slot de voertuigen:
De detailtekeningen van de voertuigen zijn behoorlijk specifiek om te maken en erg bewerkelijk.
Dat er een set in de NLCS zit lijkt mij prima, maat moet dit echt tot op de punten en cm kloppen?
Zoja, zou ik hier graag een seperate 'werkgroep' voor willen maken.
Er zullen ongetwijveld partijen zijn die hier mooie biebliotheken voor hebben (die kloppen).

**Comment by ElisabethDeVries** [comment]
[[Release note]] Verbetering van bestaande symbolen in de hoofdgroep AL: De presentatie van B-SAL-VERWIJZING_MATERIAALNUMMER-SO is aangepast, met grijze vlakvulling zoals ook toegepast bij de symbolen voor wijzigingen. De symbolen met schaalbalken aangepast omdat de lettergrootte afweek van de standaard maten uit de NLCS.

**Comment by ElisabethDeVries** [comment]
reopen voor acceptatie 5.2

**Comment by SanderNijhof** [comment]
> * o	In de schaalbalken is gebruik gemaakt van de tekststijl NLCS-ISO, dit zou NLCS-ISO-T25 moeten zijn.
>   o	In de maatvoeringstijl NLCS-M1000-T25-PIJL zit de tekststijl NLCS-T25_0, dat zou NLCS_ANNOTATIEF_T25 moeten zijn. Deze maatvoeringstijlen komen voor in de coördinaat-blocks.

NLCS-ISO is een geldig tekststijl, dit hoeft niet NLCS-ISO-T25 te zijn, zeker niet in symbolen, maar NLCS-ISO-T25 is wel een verbetering
Bij een maatvoeringstijl **NLCS-M1000-T25-PIJL** hoort een tekststijl **NLCS-ISO-M1000-T25**, niet NLCS_ANNOTATIEF_T25

**Comment by MvanderHulst** [comment]
@SanderNijhof in de schaalbalken heb ik inderdaad NLCS-ISO aangehouden met een juiste leterhoogte
De coördinatenblocks zijn komen te vervallen in de nieuwe versie, daarmee lijkt dit issue ook direct opgelost.
