### ISSUE TITLE
#1685	De ene keer wordt de aanduiding LOZELEIDING gebruikt en de andere keer LOZE LEIDING 

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#8]
De ene keer wordt de aanduiding LOZELEIDING gebruikt en de andere keer LOZE LEIDING kan dit overal hetzelfde worden? Dus alles met spatie of alles zonder spatie?

**Comment by ElisabethKloren** [comment]
Reactie expertcommissie: opmerking is terecht aanpassen. 
LOZELEIDING bij hoofdgroep RI
en LOZE LEIDING bij hoofdgroep KL
Zie ook #1554, #1547 en #1502

**Comment by ElisabethKloren** [comment]
Voorstel: alles aanpassen naar LOZE LEIDING

**Comment by ElisabethKloren** [comment]
Alles staat in versie 5.0 reeds op LOZELEIDING, daarmee kan deze ticket afgesloten worden.

**Comment by ElisabethDeVries** [comment]
Ik verplaats deze issue naar milestone gebruikersvragen, omdat het niet heeft geleid tot aanpassing van de standaard.
