### ISSUE TITLE
#E008	Onze filters hebben weer een fout gevonden, onder KL, Poller Kast.

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#80]
#E008	Onze filters hebben weer een fout gevonden, onder KL, Poller Kast. Normaal staan symbolen aangegeven met [Bib:Symbool-Naam], hier staat [Bib:Symbool:Naam]. Graag bevestiging van deze typo.

**Comment by MvanderHulst** [comment]
Wanneer ik de hele database kijken met de omgang voor 'pollers', dan lijkt de naam logisch gekozen?
Noodzaak van aanpassing is mij niet helemaal duidelijk.

Wel vraag ik mij af:
Wat doet een 'POLLER' (paal) in de hoofdgroep KL als OBJECT?
Zou dit niet ergens een SUBOBJECT van moeten zijn?

idem voor TELPUNT, is dat geen logischer subobject van MONITORING?

en WEESLEIDING, geen onderdeel van een THEMA als subobject?

**Comment by ElisabethKloren** [comment]
@MvanderHulst  Duidelijk voor mij is: symboolnaam poller wijzigen conform ingebrachte melding
POLLER opnemen in hoofdgroep IW Er is ook al een IW-VRI_Poller

TELPUNT opnemen als subobject van monitoring, maar: is er een verschil tussen monitoring_kabel en telpunt|_kabel? 
En zou de kast niet bij installaties wegen moeten staan, en alleen de kabel bij kabels en leidingen?

weesleiding - welke thema dan? bedoel je water-weesleiding enzovoorts? Graan uitwerken wat je bedoelt

**Comment by MvanderHulst** [comment]
@ElisabethKloren 
Volgens mij is een WEESLEIDING bijvoorbeeld een WATERLEIDING welke buiten bedrijf is?
Altijd is de afkomt bekend en hoort dus een OBJECT bij en is WEESLEIDING een SUBOBJECT.
Dit weet ik echter niet zeker. Is ook onderdeel van Netbeheer.

**Comment by ElisabethKloren** [comment]
voorgenomen zoals besproken bovenstaand, geen actie op de weesleiding in versie 5.1

**Comment by MvanderHulst** [comment]
Typo gecorrigeerd in voorstel. verplaatsing even gelaten voor wat het is, in afwachting van netbeheer. tzt in 1x goed doen.

**Comment by ElisabethDeVries** [comment]
reopen voor 6.0
