### ISSUE TITLE
#E010	"Status van symbooleigenschappen is niet juist in database voor 3740 en 3821

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#82]
#E010	"Status van symbooleigenschappen is niet juist in database voor 3740 en 3821; ""Nieuw"" aanpassen naar ""Vervallen""
symboolID 3740; Regel 12474: INSERT INTO `symbolen` VALUES('3740','19','','MANTELBUIS','','','','5.0','NIEUW','VERVALLEN!!!!');

SymboolID 3821; Regel 12555: INSERT INTO `symbolen` VALUES('3821','19','V','MANTELBUIS','','','','5.0','NIEUW','VERVALLEN!!!!');"

**Comment by MvanderHulst** [comment]
Betreft enkel een database aanpassing?

**Comment by MvanderHulst** [comment]
@ElisabethKloren kan je ophelderen wat hier bedoeld wordt? ik kan dit niet terugvinden

**Comment by ElisabethKloren** [comment]
Dit betrof een fout in de sql database, de mantelbuizen zijn op vervallen gezet, zie ook #87

**Comment by ElisabethDeVries** [comment]
dubbel met #87
