### ISSUE TITLE
#E011	NLCS objectID 517; lt_b en lt_n staan beide ingesteld op 685,

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#83]
#E011	NLCS objectID 517; lt_b en lt_n staan beide ingesteld op 685, lt_t en lt_v op 686. 685 niet aanwezig in de database en 686 betreft KG-RAMING is niet juist

**Comment by MvanderHulst** [comment]
Betreft database aanpassing.

**Comment by ElisabethKloren** [comment]
@MvanderHulst welke linetypes moet ik gebruiken?

**Comment by MvanderHulst** [comment]
Eigenschappen NIETBAGGERVAK mogen gelijk zijn aan BAGGERVAK.
Alles CONTINUOUS en de vervallen op V-CONTINUOUS-SO

**Comment by ElisabethDeVries** [comment]
[[Release note]] Het object NIET-BAGGERVAK in hoofdgroep GW had per abuis het lijntype van V-KG-RAMING in NLCS 5.0, in 5.2 is dit weer rechtgezet met lijntypes CONTINUOUS.
