### ISSUE TITLE
#E012	"De volgende lijntypes worden niet toegepast bij de NLCS objecten; 87 AL-WATERLIJN-SO   

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#84]
#E012	"De volgende lijntypes worden niet toegepast bij de NLCS objecten;
87 AL-WATERLIJN-SO                                                        
171 KG-GVVERKOOP-SO                                                        
172 V-KG-GVVERKOOP-SO                                                
325 RI-DRAINAGE_AANSLUITLEIDING-SO                        
326 V-RI-DRAINAGE_AANSLUITLEIDING-SO                
381 RI-AANSLUITLEIDING-SO                                        
382 V-RI-AANSLUITLEIDING-SO                                        
386 RI-SWA-SO                                                                
387 V-RI-SWA-SO                                                                
388 RI-SWA_AANSLUITLEIDING-SO
389 V-RI-SWA_AANSLUITLEIDING-SO
599 V-AL-WATERLIJN-SO"

**Comment by MvanderHulst** [comment]
87 AL-WATERLIJN-SO,
Lijnstyle is bedoeld voor ‘waterlijn in doorsnede’, wat een conflict geeft met de issue #18. Als dit verholpen is, moet dit lijntype toegekend worden alle alle WATERLIJNEN in GD presentatie. Aanvullend moet dit lijntype worden aangepast naar de hoofdgroep GW.
In hoofdgroep OB zou deze mogen komen te vervallen?
Hoofdgroep WH mag in zijn geheel weg?

171 KG-GVVERKOOP-SO
OBJECT GRONDVERWERKING_VERKOOP is nog wel aanwezig. Zou dus toegekend kunnen worden.

172 V-KG-GVVERKOOP-SO
OBJECT GRONDVERWERKING_VERKOOP is nog wel aanwezig. Zou dus toegekend kunnen worden.

325 RI-DRAINAGE_AANSLUITLEIDING-SO
OBJECT DRAINAGE_KOLKAANSLUITLEIDING en DRAINAGE_PERCEELAANSLUITLEIDING bestaand nog wel, lijntype dient toegekend te worden.
326 V-RI-DRAINAGE_AANSLUITLEIDING-SO
OBJECT DRAINAGE_KOLKAANSLUITLEIDING en DRAINAGE_PERCEELAANSLUITLEIDING bestaand nog wel, lijntype dient toegekend te worden.

381 RI-AANSLUITLEIDING-SO
Lijkt vervangen te zijn door alle ‘losse’ lijntypes voor diverse aansluitleidingen.
Kan eventueel benut worden voor de drainagepresentatie waar deze nog ontbreken?
382 V-RI-AANSLUITLEIDING-SO
Lijkt vervangen te zijn door alle ‘losse’ lijntypes voor diverse aansluitleidingen.
Kan eventueel benut worden voor de drainagepresentatie waar deze nog ontbreken?

386 RI-SWA-SO
Type stelsel bestaat niet meer en kan komen te vervallen.

387 V-RI-SWA-SO
Type stelsel bestaat niet meer en kan komen te vervallen.

388 RI-SWA_AANSLUITLEIDING-SO
Type stelsel bestaat niet meer en kan komen te vervallen.

389 V-RI-SWA_AANSLUITLEIDING-SO
Type stelsel bestaat niet meer en kan komen te vervallen.

599 V-AL-WATERLIJN-SO
Zie ook bovenstaand. Herschikken en behouden?

**Comment by ElisabethDeVries** [comment]
[[Release note]] In NLCS 5.0 kwamen lijnstijlen voor die niet aan objecten waren toegekend. Deze zijn verwijderd.

**Comment by ElisabethDeVries** [comment]
reopen voor heroverweging 5.2
