### ISSUE TITLE
#E013	"Lijntypes voor status vervallen niet ingesteld voor:

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#85]
#E013	"Lijntypes voor status vervallen niet ingesteld voor:
175 V-ZZ-PROJECTGRENS-SO                                        
177 V-ZZ-SYSTEEMGRENS-SO                                        
179 V-ZZ-WERKGRENS-SO
744 V-GR-HAAG-SO         >> Zou V-GR-HAAG1-SO moeten zijn
747 V-KL-BUNDEL-SO"

**Comment by MvanderHulst** [comment]
Zie ook #6 

Aanvullend zijn:
747 V-KL-BUNDEL-SO"
Deze staat wel in de LIN file.
Database nalopen op juiste toepassing.

744 V-GR-HAAG-SO >> Zou V-GR-HAAG1-SO moeten zijn

*V-GR-HAAG1-SO,744
A,3,[VERWIJDEREN2,NLCS.shx,s=1],3,[HAAG1,NLCS.shx,s=0.125],-2

**Comment by ElisabethDeVries** [comment]
DUBBEL MET #416 daarom even als backlog ingedeeld om aantal release notes voor 5.2 te beperken
