### ISSUE TITLE
#E014	Objecten dubbel: KNIKLIJN en TALUD; ObjectID's verwijderen: 4088, 4087, 4099 en 4100

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#86]
#E014	Objecten dubbel: KNIKLIJN en TALUD; ObjectID's verwijderen: 4088, 4087, 4099 en 4100

**Comment by MvanderHulst** [comment]
En tevens KNIKLIJN toevoegen aan 'GRONDWERKLIJN'

**Comment by MvanderHulst** [comment]
In het 5.1 voorstel zijn de regels vervallen wegens duplicaat.
Mogelijk klopt onderstaande theorie inderdaad dat er een aanvulling ontbreekt.
Er is echter geen enkele issue die deze behoefte aan lijkt te geven, dus moet dit dan aangevuld worden?

Algemeen vraag ik mij af of dit niet onder OG-thuis hoort, gezien WATERGANG en DIJK een functie zijn vanuit de BGT en je voor GRONDWERK vooral praat over aanvullen/ontgraven, dit ga je in een engineering niet per functie opdelen in een lagenstructuur.

**Comment by ElisabethKloren** [comment]
deze issue blijft gesloten, ik open een nieuwe issue om deze vraag te stellen voor een nieuwe versie van NLCS
