### ISSUE TITLE
#E015	"Symbool mantelbuis controleren; 'VERVALLEN' maar ook 'NIEUW' in combinatie met 'VERVALLEN!!!!'

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#87]
#E015	"Symbool mantelbuis controleren; 'VERVALLEN' maar ook 'NIEUW' in combinatie met 'VERVALLEN!!!!'
Regel 10840: INSERT INTO `symbolen` VALUES('2102','9','','MANTELBUIS','','','','5.0','VERVALLEN','');

Regel 12385: INSERT INTO `symbolen` VALUES('3651','9','V','MANTELBUIS','','','','5.0','VERVALLEN','');

Regel 12474: INSERT INTO `symbolen` VALUES('3740','19','','MANTELBUIS','','','','5.0','NIEUW','VERVALLEN!!!!');

Regel 12555: INSERT INTO `symbolen` VALUES('3821','19','V','MANTELBUIS','','','','5.0','NIEUW','VERVALLEN!!!!');"

**Comment by MvanderHulst** [comment]
Is dit een database actie?
Onduidelijk wat ik hiermee kan/moet.

**Comment by ElisabethKloren** [comment]
dus check op bestaan van deze symbolen in de database en in de symbolenbibliotheek

**Comment by MvanderHulst** [comment]
@ElisabethKloren 
Vanuit InfraCAD heb ik een match op MANTELBUIS met ID 2102
Dit is symbool SKL-MANTELBUIS van het OBJECT KL-MANTELBUIS-S

**Comment by ElisabethKloren** [comment]
SKL-MANTELBUIS met ID 2102 is vervallen in de 5.02 versie van de database
V-SKL-MANTELBUIS met ID 3651 is vervallen in de 5.02 versie van de database 

SOV-MANTELBUIS met ID 3740  is actueel in de 5.02 versie van de database 
V-SOV-MANTELBUIS met ID 3821  is actueel in de 5.02 versie van de database 

@MvanderHulst Als dit klopt met de symbolenbibliotheek die je maakt voor versie 5.1 kan deze issue afgesloten worden.

**Comment by MvanderHulst** [comment]
@ElisabethKloren 
SKL-MANTELBUIS met ID 2102 moet blijven bestaan.
Dit is een symbool gekoppeld aan OBJECT id 1215 (KL-MANTELBUIS)

SOV-MANTELBUIS als symbool bestaat niet (al zou die er wel moeten zijn)
V-SOV-MANTELBUIS als symbool bestaat niet (al zou die er wel moeten zijn)
Deze moeten dan gekoppeld zitten aan OBJECT id 913 (OV-MANTELBUIS)

**Comment by ElisabethKloren** [comment]
ok, dus V-SKL-Mantelbuis hoeft niet te bestaan?

De andere twee symbolen - graag maken, dan

**Comment by MvanderHulst** [comment]
Scherp.

V-SKL-Mantelbuis zou er ook moeten zijn. gezien alle symbolen een vervallen variant moeten hebben.
Ik ga de symbolen maken en aanleveren.

**Comment by MvanderHulst** [comment]
@ElisabethKloren
Ik heb wat nader onderzoek uitgevoerd.

Per 5.0 is het symbool voor de mantelbuis uit de NLCS verwijderd.
Dit omdat deze met een statische lengte niet toepasbaar is en dynamische blocks niet zijn toegestaan.

Zodoende is de toepassing van een lijn-element de enige logische methodiek.
Alle verwijzingen naar mantelbuizen symbolen zouden verwijderd moeten worden zodoende.

**Comment by ElisabethKloren** [comment]
@MvanderHulst check alle symbolen waar het woord mantelbuis in voorkomt verwijderen, dan 4x:

V-SKL-WTB_HULP_LINT_ANODE_MANTELBUIS-SO
SOV-MANTELBUIS
V-SOV-MANTELBUIS
SKL-WTB_HULP_LINT_ANODE_MANTELBUIS-SO

**Comment by ElisabethDeVries** [comment]
[[Release note]] Er worden geen symbolen meer opgenomen voor mantelbuizen, omdat deze als statische symbolen niet goed kunnen worden aangepast naar de lengte, en dynamische symbolen niet uitwisselbaar zijn tussen de CAD-pakketten. Daarom vervallen in de 5.2 release de volgende symbolen:
- In hoofdgroep KL (Kabels en Leidingen) de symbolen met filter SKL-WTB_HULP_LINT_ANODE_MANTELBUIS
- In hoofdgroep OV de symbolen met filter SOV-MANTELBUIS
