### ISSUE TITLE
#E016	Dubbele definitie in de NLCS.lin, RI-AANSLUITLEIDING-SO (349 en 381) & V-RI-AANSLUITLEIDING-SO

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#88]
#E016	Dubbele definitie in de NLCS.lin, RI-AANSLUITLEIDING-SO (349 en 381) & V-RI-AANSLUITLEIDING-SO (350 en 382). 381 en 382 hebben aantal op "0" staan

**Comment by MvanderHulst** [comment]
Dubbele definitie kan ik niet vinden in de .LIN file.
Voor gebruik, zie ook #84
