### ISSUE TITLE
#1684 Het object GW-WATERGANG_TALUD komt twee keer voor

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#9]
Het object GW-WATERGANG_TALUD komt twee keer voor in de NLCS-database. Eén keer op nr. 4089 en één keer op 4099. Welke is juist?

**Comment by ElisabethKloren** [comment]
Reactie Expertcommissie: opmerking is terecht. Object 4099 laten vervallen, e.e.a. geldt ook voor GW-WATERGANG_KNIKLIJN object 4100

**Comment by ElisabethKloren** [comment]
To do: op vervallen zetten in database, invloed op mapping?

**Comment by MvanderHulst** [comment]
Voor zover ik kan beoordelen geen impact op de mapping naar BGT.

**Comment by ElisabethDeVries** [comment]
[[Release note]] Objecten GW-WATERGANG_TALUD en GW-WATERGANG_KNIKLIJN kwamen dubbel voor in de database, de dubbeling is verwijderd.
