### ISSUE TITLE
#E018	Symbool N-SVH-KANTOPSLUITING_TROTTOIRBAND_130 250-D;

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#90]
#E018	Symbool N-SVH-KANTOPSLUITING_TROTTOIRBAND_130 250-D; uitzoeken bij welk type band deze hoort. Afmeting onderzijde is 250, bovenzijde 110/130 mm

**Comment by MvanderHulst** [comment]
Dit is een trottoirband 130/150x250 mm
Naam aanpassen naar 130 150x250
Algmeen voorstel is om deze symbolen te laten vervallen
Zie ook issue #61
