### ISSUE TITLE
#E019	"4 symbolen voor mapping BGT niet -SO; kan logisch zijn maar hoe dan om te gaan met rotatie van het object "

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#91]
#E019	"4 symbolen voor mapping BGT niet -SO; kan logisch zijn maar hoe dan om te gaan met rotatie van het object
"

**Comment by SanderNijhof** [comment]
Welke 4 symbolen worden hier bedoeld?

**Comment by MvanderHulst** [comment]
Zie ook issue #78 en #14 en #16 
Hiermee zijn alle problemen verholpen.
