### ISSUE TITLE
#E020	"op regel 144 van NLCS-OBJECTEN-OG-5.0.xls zit een bug.

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#92]
#E020	"op regel 144 van NLCS-OBJECTEN-OG-5.0.xls zit een bug.
kolom AJ,AK,AL,AM,AN,AO zijn gevuld met de waarde -1
"

**Comment by ElisabethKloren** [comment]
Reactie Expertcommissie	To Do
opmerking klopt.	"objectentabel regel 144 aanpassen en doorvoeren in database => 
kolom: AJ, AK, AL,AM = kleur 7
kolom: AN = kleur 253
kolom: AO = CONTINUOUS"

**Comment by MvanderHulst** [comment]
Reeds behandeld, aanpassing is bovenstaand vermeld.
