### ISSUE TITLE
#E021	"In de formele beschrijving lees ik het volgende op blz 60 (par 5.2.2.c) voor arceringen met een vervallen status:

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#93]
#E021	"In de formele beschrijving lees ik het volgende op blz 60 (par 5.2.2.c) voor arceringen met een vervallen status:
 
In principe bestaat een arcering van een OBJECT voor de STATUS V (Vervallen) uit de standaard arcering voor dat OBJECT, aangevuld met een streeparcering onder een hoek van 135 graden.
 
Hebben wij zulke arceringen in de database staan? Ik kan ze niet vinden."

**Comment by MvanderHulst** [comment]
Bij het consequent maken van alle soortgelijke hoofdstukken (wijziging van 4.2) is deze regel ten onrechte in de FB gekomen.
Artikel c. kan komen te vervallen.
Artikel d aanpassen naar 'c.

**Comment by ElisabethKloren** [comment]
done
