### ISSUE TITLE
#E022	"Wat betreft BEWERKINGEN: 

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#94]
#E022	"Wat betreft BEWERKINGEN: 

Deze teksten komen voor in de laagnamen:  _STELLEN, _TRAPSGEWIJSFREZEN en -VOLSCHUIMEN 

1.    Als _STELLEN een bewerking is dan zou dat -STELLEN moeten zijn, maar heeft STELLEN toevoegen als bewerking een meerwaarde? 

2.    Wel meerwaarde heeft _TRAPSGEWIJSFREZEN, dat moet dan -TRAPSGEWIJSFREZEN worden. 

3.    Het is “OP DE KOP” en “OPNIEUW STELLEN”, maar “OPHOOGTEBRENGEN”, consequenter zou dan zijn die te wijzigen naar “OP HOOGTE BRENGEN” 

4.    –VOLSCHUIMEN staat nu in de tabel als object i.p.v. bewerking. Zou dan bijvoorbeeld –TRANSPORTLEIDING-VOLSCHUIMEN kunnen worden om van – VOLSCHUIMEN een bewerking te maken. ‘Volschuimen’ lijkt me sowieso geen object. 

5.    AANVULLEN, ONTGRAVEN, FREZEN zijn ook bewerkingen toch? Maar nu niet als bewerking in de laagnamen opgenomen. 

  

Conflict laagnamen: 

In de tabel staat in de groep ZZ (voor alle hoofdgroepen) de laag *-**-***-HULPLIJN-G, kleur 7, lijnstijl CONTINUOUS. 

In de tabel staat ook *-**-OG-HULPLIJN-G, kleur 50, lijnstijl CONTINUOUS. 

En X-XX-AL-TEKENBLAD_HULPLIJN-G, kleur 7, lijnstijl CONTINUOUS. 

Kan *-**-OG-HULPLIJN-G dan uit de database i.v.m. dubbelop/conflict? 

  

Nader te bezien?: 

1.    Bijna alle lagen van hoofdgroep KW beginnen met KUNSTWERK op 3 na. Is dit bewust of mogen die 3 ook met KUNSTWERK beginnen.  

2.    Bij BV beginnen bijna alle lagen met GELEIDECONSTRUCTIE, waarom de laatste 6 niet? Een leuning of obstakelbeveiliger is geen geleideconstructie? 

3.    Lagen voor GROND en TEELAARDE komen voor in zowel GR als GW. Die conform voorstel Michel ook aanpassen?  

4.    Lagen met OVERIG handhaven? Bijv. OVERIG MATERIAAL. Zijn lagen met ‘OVERIG’ nodig? Zou een laag ‘MATERIAAL’ voldoen? 

5.    Is MEUBILAIR_WEGMEUBILAIR nodig of kan dit MEUBILAIR óf WEGMEUBILAIR worden?  "

**Comment by MvanderHulst** [comment]
BEWERKINGEN:
1 'STELLEN' kom ik als OBJECT, SUBOBJECT, of BEWERKING niet tegen in de database.
OPNIEUW STELLEN kom ik wel tegen als bewerking. Deze wordt met de streepjes op de juiste plek aangemaakt.

2. Deze wordt (in InfraCAD) op de juiste manier als bewerking aangemaakt.

3. Eens. Aanpassen naar BEWERKING: OP HOOGTE BRENGEN

4. VOLGESCHUIMD staat als 'SUBOBJECT' in de tabellen. VOLSCHUIMEN als BEWERKING. In relatie tot de netbehere discussie, is dus ook binnen riolering behoefte om VOLGESCHUIMD van een bestaand object aan te kunnen geven. Met alle nieuwe inzichten.... wordt BEWERKING aangepast naar BEWERKING/TOESTAND, waardoor VOLGESCHUIMD ook in dezelfde kolom komt te staan.... krijgen we hier een andere STATUS voor, volgens voorstel netbeheer, of blijft het een SUBOBJECT, wat niet logisch is, gezien het geen object is...

5.  Zie voorstel issue #71 

CONFLICT LAAGNAMEN:
1.  HULPLIJN komt voor in hoofdgroep ZZ, alle overige objecten mogen m.i. vervallen.
Dit betreft:
AL-TEKENBLAD_HULPLIJN
OG-HULPLIJN

Algemeen: de standaard kleur 'wit' voor hulplijnen is zeer ongelukkig en vallen samen met de standaard objecten.
Voorstel om een afwijkende kleur te kiezen die minder prominent aanwezig is. Bijvoorbeeld kleur 5 of 211.

NADER BEZIEN:
1. Korte termijn: alles aanvullen met KUNSTWERK, lange termijn: gehele hoofdgroep herzien. OBJECT kunstwerk laten vervallen en aanpassen naar daadwerkelijke kunstwerksoorten en vervolgens uitdiepen. is nu een vergaarbak.
2. Volledig nutteloze hoofdgroep. in zijin geheel onderbrengen onder 'IE'.
3. Zie voorstel issue #71 
4.  OVERIG is overal logisch toegepast, OVERIGMATERIAAL komt in alle Constructies hoofdgroepen terug. voor alsnog denk ik prima tot alle constructie hoofdgroepen in zijn geheel worden herzien.
5. onder MEUBLIAIR staat nu WATERMEUBILAIR en WEGMEUBLIAIR. het OBJECT Meubilair zou m.i. kunnen vervallen en het verschil maken tussen WEGMEUBILAIR en WATERMEUBILAIR. Onderscheid tussen 2 is voldoende, 3 is overbodig en tevens niet consequent. Is het onderscheid uberhaupt nodig en is MEUBILAIR niet voldoende?

**Comment by MvanderHulst** [comment]
Voor:
Volledig nutteloze hoofdgroep. in zijin geheel onderbrengen onder 'IE'.
een nieuwe issue aangemaakt voor een volgende versie.

voor:
OVERIG is overal logisch toegepast, OVERIGMATERIAAL komt in alle Constructies hoofdgroepen terug. voor alsnog denk ik prima tot alle constructie hoofdgroepen in zijn geheel worden herzien.
is reeds een andere issue aanwezig.

voor:
onder MEUBLIAIR staat nu WATERMEUBILAIR en WEGMEUBLIAIR. het OBJECT Meubilair zou m.i. kunnen vervallen en het verschil maken tussen WEGMEUBILAIR en WATERMEUBILAIR. Onderscheid tussen 2 is voldoende, 3 is overbodig en tevens niet consequent. Is het onderscheid uberhaupt nodig en is MEUBILAIR niet voldoende?
is ook een andere issue aanwezig.

overige zaken opgenomen in voorstel
