### ISSUE TITLE
BGT ondergrond

### ISSUE THREAD

**Issue by ElisabethKloren** [nl-digigo/NLCS#97]
“Graag zou ik iemand spreken over ondergronden welke wij uit InfraCad halen.
Volgens onze informatie zijn die sinds de overgang van NLCS v4.2 naar NLCS v5 veranderd.
Het kost ons nu heel veel tijd om de gedownloade ondergronden aan te passen naar onze standaard zoals wij die voorheen gebruikte.
Ik ben benieuwd of er mogelijkheden voor ons zijn om de ondergronden aangeleverd te krijgen zoals wij gewend waren.”

**Comment by ElisabethKloren** [comment]
Input leverancier: Uit de vraag kan ik herleiden dat het gaat om de verwerking van de BGT naar AutoCAD, waarbij InfraCAD Map wordt gebruikt. 
 
InfraCAD Map converteert de BGT data conform een mapping tabel naar NLCS. In versie 4.2 hebben we zelf een selectie gemaakt van objecten en kleuren om te mappen. Sinds versie 5.0 wordt de mapping van de BGT door het BIM Loket beheerd en passen wij deze ook toe, zoals dit door het BIM Loket wordt voorgeschreven. Het BIM Loket heeft voor andere objecten en kleuren gekozen dan wij voorheen hebben gedaan.
 
Voor de gebruiker is het vervelend dat de kleuren nu anders zijn geworden. Deze melding hebben we overigens vaker gekregen. Maar wij kunnen uiteraard de NLCS 5 niet aanpassen, en ook het beheer van de mapping tussen BGT en NLCS ligt niet bij ons.
 
Ik denk dat het beste aan de betreffende NLCS werkgroep (rondom mapping en degene die de kleuren enzo bepalen) gemeld kan worden dat gebruikers klagen over de gemaakte keuzes. Het is dan aan de werkgroep om te bepalen of dit in een toekomstige versie wordt aangepast. Het kan ook zijn dat men tegen die tijd intussen gewend is geraakt aan de nieuwe kleuren, waardoor een herstel naar oude kleuren weer onwenselijk is. Dit kan de betreffende werkgroep het beste bepalen.

**Comment by MvanderHulst** [comment]
Een aantal standaard kleuren zijn zeer onlogisch.
Deze kan ik aanleveren en zal veel gebruikers blijer maken denk ik.

**Comment by SanderNijhof** [comment]
Niet alleen de kleuren, ook de symbolen zijn byzonder. Wij passen ook andere symbolen en een 'bylevel override' met andere kleuren toe.

**Comment by MvanderHulst** [comment]
Mapping is vastgelegd in de NLCS, dus zouden geen verschillen tussen AutoCAD en Microstation in moeten zitten.

**Comment by MvanderHulst** [comment]
Wanneer ik een 'InfraCAD' map download maak. krijg ik onderstaande kleuren.
Daarop nog een paar aanpassingen gedaan voor 'OPENVERHARDING'

![image](https://github.com/nl-digigo/NLCS/assets/144665595/560daa18-bef3-48a9-b7c6-874772a84dde)
